2600hz/kazoo

- applications/ecallmgr/src/ecallmgr_fs_node.erl
back port of #3892 
(replacing old PRs #3838 for 4.0 and #3834 for master)
> [4.0] KAZOO-5259: use federate to reload acls/send command

- applications/acdc/src/acdc.hrl
- applications/acdc/src/acdc_agent_sup.erl
- applications/acdc/src/acdc_agents_sup.erl
- applications/acdc/src/acdc_maintenance.erl
- applications/acdc/src/acdc_queue_sup.erl
- applications/acdc/src/acdc_queue_worker_sup.erl
- applications/acdc/src/acdc_queue_workers_sup.erl
- applications/acdc/src/acdc_queues_sup.erl
master: https://github.com/2600hz/kazoo/pull/3895
reported at https://groups.google.com/forum/#!topic/2600hz-users/Wcjzq7ZGeSs
> qf-acdc_status-4oh: print to console when using acdc maintenance

- applications/crossbar/doc/phone_numbers.md
- core/kazoo_number_manager/src/carriers/knm_carriers.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/test/knm_carriers_find_test.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
- core/kazoo_number_manager/test/knm_port_request_test.erl
master: https://github.com/2600hz/kazoo/pull/3885
> HELP-30632_4oh: fix state picking on number creation

- applications/callflow/src/callflow_maintenance.erl
- applications/callflow/src/module/cf_move.erl
- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
master: https://github.com/2600hz/kazoo/pull/3905
> HELP-29745_4oh: logging improvements

- core/kazoo_auth/c_src/kz_auth_rsa_drv.c
> [4.0] add support for openssl 1.1

- applications/crossbar/src/cb_apps_util.erl
master: https://github.com/2600hz/kazoo/pull/3925
> HELP-30934_4oh: handle possibility of find an app more than once

- Makefile
- make/deps.mk
master: https://github.com/2600hz/kazoo/pull/3933
related issue: https://github.com/ninenines/erlang.mk/issues/709
> circle_4oh: pass circle CI builds again

- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- applications/ecallmgr/src/ecallmgr_originate.erl
- applications/ecallmgr/src/freeswitch.erl
Conflicts:
applications/ecallmgr/src/ecallmgr_originate.erl
> HELP-30966: treat an internal FS error as an execution error

- applications/crossbar/src/modules/cb_cdrs.erl
To handle the following case:
{'startkey', [OwnerId, CreatedTo]}
> Fix cb_cdrs get interactions for user

- core/kazoo_perf/src/kazoo_perf_maintenance.erl
- scripts/check-release-startup.sh
master: https://github.com/2600hz/kazoo/pull/3943
> qf-metrics_4oh: Graphite was tripping on non integer values (and a crash)

- applications/crossbar/doc/accounts.md
- applications/crossbar/doc/ref/accounts.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/src/cb_apps_util.erl
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_services.erl
- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules/cb_alerts.erl
- applications/crossbar/src/modules/cb_notifications.erl
- applications/crossbar/src/modules/cb_onboard.erl
- applications/notify/src/notify_new_account.erl
- applications/notify/src/notify_util.erl
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_customer_update.erl
- applications/teletype/src/templates/teletype_new_account.erl
- core/kazoo_documents/src/kzd_user.erl
- core/kazoo_services/src/services/kz_service_users.erl
* add an API to reset account's API key
* refactor the checks  to see user is account's admin
> KAZOO-5451: api for reset api key on put

- applications/teletype/src/templates/teletype_fax_inbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_inbound_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_to_email.erl
backport of #3960 
(only fixes for fax templates)
> [3.22] HELP-30998: fix timezone and pretty print number in fax templates

- applications/teletype/src/templates/teletype_fax_inbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_inbound_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_to_email.erl
> [4oh] HELP-30998: fix timezone and pretty print number in fax templates

- core/kazoo_services/src/kz_service_plans.erl
master: https://github.com/2600hz/kazoo/pull/3971
> pr-powerpbx_4oh: fix service plan not loading when no overrides present

- applications/crossbar/src/modules/cb_jobs_listener.erl
- applications/crossbar/src/modules/cb_resources.erl
Conflicts:
applications/crossbar/src/modules/cb_resources.erl
> HELP-31124: fix check type and add numbers as reserved

- applications/fax/src/fax.hrl
Update default pdf conversion command to read success or failure based on the exit code of the script
> Update default conversion command

- applications/crossbar/src/crossbar_maintenance.erl
- core/sup/src/sup.erl
- scripts/check-release-startup.sh
More reports coming in of first account creation failing. Better logging of errors from Crossbar helps; this PR will make sure Circle lets us know if it fails there too. Hopefully then we can analyze the logs to see what's going on and how to address this intermittent problem
> Ensure that when creating the first account, if it fails, so will CircleCI

- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/crossbar_freeswitch.erl
- applications/crossbar/src/crossbar_types.hrl
- applications/crossbar/src/modules/cb_auth.erl
- applications/crossbar/src/modules/cb_configs.erl
- applications/crossbar/src/modules/cb_media.erl
- applications/crossbar/src/modules/cb_notifications.erl
- applications/crossbar/src/modules/cb_port_requests.erl
- applications/crossbar/src/modules/cb_presence.erl
- applications/crossbar/src/modules/cb_security.erl
- applications/crossbar/src/modules/cb_signup.erl
- applications/crossbar/src/modules/cb_system_configs.erl
- applications/crossbar/src/modules/cb_token_restrictions.erl
- applications/crossbar/src/modules/cb_whitelabel.erl
Not sure why I missed them but fixes calls to `crossbar_doc:delete/2` in other modules.
> Low hanging type fixes

- applications/stepswitch/src/stepswitch_inbound.erl
- applications/stepswitch/src/stepswitch_local_extension.erl
- applications/stepswitch/src/stepswitch_outbound.erl
- applications/stepswitch/src/stepswitch_resources.erl
Conflicts:
applications/stepswitch/src/stepswitch_resources.erl
> KAZOO-5602: added resource-type to ccvs

- applications/stepswitch/src/stepswitch_resources.erl
Related to https://github.com/2600hz/kazoo-configs-freeswitch/pull/3
> no need to filter as from_list already does it

- core/kazoo_data/src/kz_datamgr.erl
4.1 (& master) version: https://github.com/2600hz/kazoo/pull/3106
> save_docs_loop: backport of #3106

- applications/crossbar/src/modules/cb_vmboxes.erl
> [4.1] fix typo and check for attachment

- applications/crossbar/src/modules/cb_vmboxes.erl
backport of #4025 (master) and #4026 (4.1)
> [4ohr] fix typo and check for attachment

- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/modules/cb_tasks.erl
> Task naming 4 2

- applications/crossbar/src/modules_v2/cb_devices_v2.erl
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_release_number_test.erl
4.0: https://github.com/2600hz/kazoo/pull/4020
4.1: https://github.com/2600hz/kazoo/pull/4024
> KAZOO-5626_master: fix MDN deletion on device deletion

- applications/teletype/src/teletype_tests.erl
- applications/teletype/src/templates/teletype_service_added.erl
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/kazoo_apps/src/kapps_notify_publisher.erl
- core/kazoo_documents/src/kz_custom_sip_headers.erl
- core/kazoo_documents/src/kz_device.erl
- core/kazoo_stdlib/include/kz_types.hrl
- core/kazoo_stdlib/src/props.erl
Adjusted after running `./scripts/dialyze-changed.bash  core/kazoo_stdlib/ebin/ core/kazoo/ebin/kz_util.beam applications/teletype/ebin/ core/kazoo_documents/ebin/ core/kazoo/ebin/kz_doc.beam  core/kazoo_amqp/ebin/kz_amqp_worker.beam core/kazoo_amqp/ebin/gen_listener.beam`
> Dialyzer adjustments

- applications/crossbar/src/modules/cb_configs.erl
- core/kazoo_config/src/kapps_account_config.erl
- core/kazoo_config/src/kapps_config.erl
- core/kazoo_config/src/kapps_config_util.erl
- core/kazoo_config/src/kazoo_config.hrl
- core/kazoo_config/src/kazoo_config_init.erl
- core/kazoo_config/src/kz_config.erl
- core/kazoo_config/test/fixture/a_master_account.json
- core/kazoo_config/test/fixture/customized_parent_account.json
- core/kazoo_config/test/fixture/customized_sub_subaccount.json
- core/kazoo_config/test/fixture/test_cat_reseller.json
- core/kazoo_config/test/fixture/test_cat_subaccount_1.json
- core/kazoo_config/test/fixture/test_cat_subaccount_2.json
- core/kazoo_config/test/fixture/test_cat_system.json
- core/kazoo_config/test/kapps_account_config_test.erl
- core/kazoo_documents/src/kz_account.erl
> [4.1] get merge result of account, it's parents and system config

- core/sup/Makefile
master: https://github.com/2600hz/kazoo/pull/4050
> qf-makesup_4one: fix clean command of sup's Makefile

- applications/acdc/src/acdc_stats.hrl
- applications/call_inspector/src/ci_datastore.erl
- applications/callflow/src/module/cf_call_forward.erl
- applications/callflow/src/module/cf_directory.erl
- applications/callflow/src/module/cf_dynamic_cid.erl
- applications/callflow/src/module/cf_menu.erl
- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/src/modules/cb_clicktocall.erl
- applications/crossbar/src/modules/provisioner_contact_list.erl
- applications/dth/src/dth_listener.erl
- applications/ecallmgr/src/ecallmgr_call_control.erl
- applications/omnipresence/src/omnipresence.hrl
- applications/omnipresence/src/omnipresence_listener.erl
- applications/omnipresence/src/omnipresence_shared_listener.erl
- core/amqp_cron/src/amqp_cron.erl
- core/amqp_leader/src/amqp_leader_proc.erl
- core/gcm/src/gcm.erl
- core/kazoo_amqp/include/kz_amqp.hrl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_amqp/src/kz_amqp_connections.erl
- core/kazoo_amqp/src/kz_amqp_history.erl
- core/kazoo_ast/src/cf_data_usage.erl
- core/kazoo_media/include/kz_media.hrl
- core/kazoo_media/src/kz_media_util.erl
- make/kz.mk
Unfortunately the compile flag cannot be enforced as just importing xmerl records makes compilation fail...
> Type most records

- core/kazoo_number_manager/doc/README.md
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
4.1: https://github.com/2600hz/kazoo/pull/4046
> HELP-31537_master: ensure_adminonly_features_are_reachable

- applications/crossbar/doc/auth.md
- applications/crossbar/doc/ref/auth.md
- applications/crossbar/doc/voicemail.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_auth.erl
- applications/crossbar/src/modules/cb_ledgers.erl
- applications/crossbar/src/modules/cb_media.erl
- applications/crossbar/src/modules/cb_security.erl
- core/kazoo_auth/doc/oauth.md
- core/kazoo_auth/src/kazoo_auth_maintenance.erl
- core/kazoo_auth/src/kz_auth_identity.erl
- core/kazoo_auth/src/kz_auth_jwt.erl
- core/kazoo_auth/src/kz_auth_keys.erl
- core/kazoo_auth/src/kz_auth_util.erl
> [4.1] KAZOO-5449: reset api for private key, identity secrets and get public key

- applications/registrar/Makefile
- core/kazoo_auth/Makefile
Needed to add the CC and LDFLAGS for the solaris platform to be able to build.
> Update registrar and kazoo_auth Makefiles for solaris platform

- applications/crossbar/src/crossbar_auth.erl
> [4.1] fix method config path

- applications/crossbar/src/modules/cb_callflows.erl
- applications/crossbar/src/modules/cb_modules_util.erl
- core/kazoo_number_manager/src/converters/knm_converter_regex.erl
- core/kazoo_number_manager/src/converters/knm_converters.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
master: https://github.com/2600hz/kazoo/pull/4069
> KAZOO-5639_4one: move MDN check on write instead of read, to allow reads

- applications/crossbar/src/modules/cb_callflows.erl
- core/kazoo_number_manager/src/converters/knm_converter_regex.erl
- core/kazoo_number_manager/src/converters/knm_converters.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
4.1: https://github.com/2600hz/kazoo/pull/4070
> KAZOO-5639_4oh: move MDN check on write instead of read, to allow reads

- core/kazoo_number_manager/include/knm_phone_number.hrl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/providers/knm_force_outbound.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_number_manager/test/knm_force_outbound_tests.erl
- core/kazoo_number_manager/test/knm_port_request_test.erl
- core/kazoo_stdlib/test/props_test.erl
4.1: https://github.com/2600hz/kazoo/pull/4074
No 4.0 version.
> KAZOO-5642_master: add force_outbound feature provider

- applications/registrar/src/reg_authn_req.erl
- applications/registrar/src/reg_route_req.erl
- applications/registrar/src/registrar_maintenance.erl
- applications/trunkstore/src/ts_callflow.erl
- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_apps/src/kapps_util.erl
[4.0] HELP-31826 (#4085)
* HELP-31826: better logging of CCVs for debugging
* add flush for getby cache
* move lookup by ip to route_req handler
* HELP-31826: normalize checking if things are enabled
* HELP-31826: functions to help figure out what's being checked
* HELP-31826: ensure account id is present
* HELP-31826: finer return type, formatting
* spel much gud
> HELP-31826: forward port from 4.0

- core/kazoo_stdlib/src/kz_json.erl
- core/kazoo_stdlib/test/kz_json_test.erl
fixes the error found by PropEr
Found in https://travis-ci.org/2600hz/kazoo/jobs/267396238
don't conflict with proper
> backport of kz_json_fix

- applications/acdc/doc/architecture.md
- applications/acdc/src/acdc_agent_fsm.erl
- applications/acdc/src/acdc_queue_fsm.erl
> Fix acdc under OTP 20 using gen_statem

- applications/crossbar/doc/notifications.md
- applications/crossbar/doc/ref/notifications.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/doc/maintenance.md
- applications/teletype/src/teletype_maintenance.erl
- applications/teletype/src/templates/teletype_customer_update.erl
Also fix `customer_update` notifications return message and update crossbar notifications documentation.
backport of #4095
> [4.1] Add notifications API and SUP command to delete/reset to system

- applications/crossbar/doc/notifications.md
- applications/crossbar/doc/ref/notifications.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/doc/maintenance.md
- applications/teletype/src/teletype_maintenance.erl
- applications/teletype/src/templates/teletype_customer_update.erl
Also fix `customer_update` notifications return message and update crossbar notifications documentation.
> [master] Add notifications API and SUP command to delete/reset to system

- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules/notification_util.erl
> [master] flush registrar and fs_xml when enable/disable an account or a device

- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules/notification_util.erl
> [4.0] flush registrar and fs_xml when enable/disable an account or a device

- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules/notification_util.erl
> [4.1] flush registrar and fs_xml when enable/disable an account or a device

- core/kazoo_data/src/kzs_doc.erl
- core/kazoo_stdlib/src/props.erl
- core/kazoo_stdlib/test/props_test.erl
added property testing as well
> remove key unpacking

- applications/callflow/doc/privacy.md
- applications/callflow/doc/ref/privacy.md
- applications/crossbar/doc/about.md
- doc/mkdocs/mkdocs.yml
- scripts/generate-doc-schemas.sh
- scripts/reconcile_docs_to_index.bash
Also error the build if a new doc is missing from the index
> Update privacy callflow docs

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.conference.config_req.json
- core/kazoo/Makefile
- core/kazoo/include/kz_api_literals.hrl
- core/kazoo_amqp/include/kz_amqp.hrl
- core/kazoo_amqp/include/kz_api.hrl
- core/kazoo_amqp/src/amqp_util.erl
- core/kazoo_amqp/src/api/kapi_conference.erl
- core/kazoo_amqp/src/api/kz_api.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_amqp/src/kz_amqp_channel.erl
- core/kazoo_amqp/src/kz_amqp_history.erl
- core/kazoo_amqp/src/kz_amqp_sup.erl
- core/kazoo_amqp/src/kz_amqp_worker.erl
- core/kazoo_amqp/src/listener_types.hrl
- core/kazoo_amqp/src/listener_utils.erl
- core/kazoo_stdlib/include/kz_types.hrl
- allow consumer channel to prevent calls to kz_amqp_assignments
- allow multiple pools for kz_amqp_workers
- allow auto_ack in gen_listener
- optimize finding the client handles for delivering the payload
> KAZOO-5659 amqp optimizations

- applications/ecallmgr/src/ecallmgr_call_control.erl
> KAZOO-5646 prevent handle replaced crash

- applications/tasks/priv/list_task_modules.py
- applications/tasks/src/kz_tasks_scheduler.erl
- applications/tasks/src/modules/kt_compactor_worker.erl
- core/kazoo_config/src/kapps_config.erl
- core/kazoo_couch/src/kazoo_couch.erl
- core/kazoo_couch/src/kz_couch_db.erl
- core/kazoo_couch/src/kz_couch_util.erl
- core/kazoo_couch/src/kz_couch_view.erl
- core/kazoo_data/src/kz_datamgr.erl
- core/kazoo_data/src/kzs_util.erl
- make/deps.mk
Fix various problem in `kt_compactor`.
**Note:** `couchbeam` needs to patch to have `Content-type` header when doing `view_cleanup` otherwise BigCouch is returning an error
4.1: #4113
> [master] Resurrect kt compactor

- applications/callflow/src/module/cf_park.erl
- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.callflow.park.json
> fix parking attended timer & cleanup

- core/kazoo_globals/src/kz_nodes.erl
kamailio script does not support converting with long int
> handle kamailio timestamp - 4.1

- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/listener_federator.erl
because of new arity handling in gen_listener
> fix federator listener

- core/kazoo_globals/src/kz_nodes.erl
kamailio script does not support converting with long int
> handle kamailio timestamp

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/account_config.crossbar.auth.json
- applications/crossbar/priv/couchdb/schemas/system_config.crossbar.auth.json
- applications/crossbar/src/crossbar_auth.erl
> [4.1] log successful login for cb_user_auth only

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/account_config.crossbar.auth.json
- applications/crossbar/priv/couchdb/schemas/system_config.crossbar.auth.json
- applications/crossbar/src/crossbar_auth.erl
> [master] log successful login for cb_user_auth only

- doc/announcements.md
Was reading through the announcements md and found a couple quick spelling errors
> Some quick spelling and grammar fixes

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.crossbar.json
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar.hrl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_cdrs.erl
* calculating page_size correctly
* loop over databases until requested page_size is exhausted or database is exhausted.
* reverse the order of databases to query
> [master] KAZOO-5625: fix cdrs pagination

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.crossbar.json
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar.hrl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_cdrs.erl
* calculating page_size correctly
* loop over databases until requested page_size is exhausted or database is exhausted.
* reverse the order of databases to query
master: #4186
> [4.1] KAZOO-5625: fix cdrs pagination

- core/kazoo_endpoint/src/kz_endpoint.erl
master https://github.com/2600hz/kazoo/pull/4188
> fix endpoint call recording merging "any" - 4.1

- doc/mkdocs/commercial.md
- doc/mkdocs/commercial.yml
Comments are left for collaboration purposes--manually went through and kept what had content, removed what didn't, marked what was incomplete or a missing doc in an otherwise okay section.
> First pass of a commercial doc yml

- applications/fax/src/fax_worker.erl
- applications/notify/src/notify_fax_inbound_to_email.erl
- applications/notify/src/notify_fax_outbound_to_email.erl
- applications/teletype/src/teletype_bindings.erl
- applications/teletype/src/teletype_fax_util.erl
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_fax_inbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_inbound_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_smtp_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_to_email.erl
- applications/teletype/src/templates/teletype_voicemail_full.erl
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/kazoo_amqp/src/api/kapi_notifications.erl
- core/kazoo_apps/src/kapps_notify_publisher.erl
* Don't send fax notifications to reseller if could not find owner email address
* fix issue with finding account_db (found during debugging fax notification)
4.1: #4212
> [master] don't send fax to reseller, fix user email lookup

- core/kazoo_amqp/src/gen_listener.erl
Conflicts:
core/kazoo_amqp/src/gen_listener.erl
> master: log crashes in handle_event for gen_listener

- circle.yml
- scripts/.org/README.org
- scripts/README.md
- scripts/check-unstaged.bash
Let's other build processes that use kazoo as a base repo to check for changes in the kazoo repo.
> Check unstaged in script

- .gitignore
- applications/blackhole/src/blackhole_tracking.erl
- applications/doodle/src/doodle_exe.erl
- applications/ecallmgr/src/ecallmgr_fs_msg.erl
- core/kazoo_auth/src/kz_auth_jwt.erl
- core/kazoo_endpoint/src/kz_privacy.erl
- core/kazoo_globals/src/kz_nodes.erl
- core/kazoo_speech/src/kazoo_asr_util.erl
lager invalid format fix, added .idea folder for intellij ide into gitignore, please let me know if idea should be removed
> Invalid log format

- applications/crossbar/doc/ref/storage.md
- applications/crossbar/doc/storage.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/storage.attachment.aws.json
> change s3 doc host to vhost

- core/kazoo_amqp/src/gen_listener.erl
Conflicts:
core/kazoo_amqp/src/gen_listener.erl
> master: don't crash when we get a gen_listener event callback crash

- applications/fax/src/fax_worker.erl
> [master] fix fax_worker crash

- applications/fax/src/fax_worker.erl
> [4.2] fix fax_worker crash

- applications/crossbar/doc/ref/service_plans.md
- applications/crossbar/doc/service_plans.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/service_plans.json
- core/kazoo_apps/src/kapps_notify_publisher.erl
> [4.2] manual recurring must be array, fix publisher log typo

- applications/registrar/priv/couchdb/credentials.json
Feels like if device disabled, ip auth should be disabled too...
> disabled device still provides ip auth

- applications/webhooks/src/webhooks_init.erl
- applications/webhooks/src/webhooks_maint_listener.erl
- applications/webhooks/src/webhooks_maintenance.erl
- applications/webhooks/src/webhooks_shared_listener.erl
- core/kazoo_amqp/src/listener_types.hrl
Remove loop when refreshing views that refreshes views.
> Webhooks Loop

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.qubicle_session.create_session.json
- applications/crossbar/priv/couchdb/schemas/kapi.qubicle_session.delete_session.json
- applications/crossbar/priv/couchdb/schemas/kapi.qubicle_session.join_queue.json
- applications/crossbar/priv/couchdb/schemas/system_config.qubicle.json
- applications/crossbar/src/crossbar_types.hrl
- core/kazoo_call/src/kapps_call.erl
- core/kazoo_globals/src/kz_global.erl
- scripts/check-dialyzer.escript
A few updates as I worked through qube's circleci
> Qube updates

- core/kazoo_documents/src/kzd_rate.erl
> [4.1] Rate direction fixes

- applications/crossbar/doc/resources.md
Documentation of Collections endpoints were in the middle of a group of endpoints on jobs. Put collections to the end of the doc.
> Reorder Resources doc for Collections & Jobs

- applications/callflow/doc/dead_air.md
- applications/callflow/doc/ref/route_to_cid.md
- applications/callflow/doc/route_to_cid.md
- applications/callflow/priv/couchdb/views/attributes.json
- applications/callflow/src/module/cf_dead_air.erl
- applications/callflow/src/module/cf_route_to_cid.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.route_to_cid.json
- doc/mkdocs/mkdocs.yml
- scripts/check-spelling.bash
- scripts/misspellings.txt
Refactoring PR #4265 with some improvements.
@onnet Let me know your thoughts on this version, if you have any questions or comments :)
> Route to caller id

- applications/crossbar/doc/access_lists.md
Tried to make the doc more clear and logical
> Fixed API URLs and changed an order in access_lists.md

- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.smtp_client.json
- applications/teletype/src/teletype_util.erl
- core/kazoo_apps/src/kapps_notify_publisher.erl
> [master] callid for smtp_log, timeout for send_smtp

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.presence.update.json
- core/kazoo_amqp/src/api/kapi_presence.hrl
- core/kazoo_call/src/kapps_call_command.erl
requires https://github.com/2600hz/kazoo-configs-kamailio/pull/35
> fix presence update

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.presence.update.json
- core/kazoo_amqp/src/api/kapi_presence.hrl
- core/kazoo_call/src/kapps_call_command.erl
master https://github.com/2600hz/kazoo/pull/4305
> fix presence update - 4.1

- applications/stepswitch/Makefile
- applications/stepswitch/src/stepswitch.hrl
- applications/stepswitch/src/stepswitch_resources.erl
- applications/stepswitch/test/fixtures/offnet_req/global.json
- applications/stepswitch/test/fixtures/resources/global.json
- applications/stepswitch/test/stepswitch_resources_test.erl
- doc/mkdocs/mkdocs.yml
Test function to ensure `sip_invite_parameters/2` is working correctly
> Invite Parameters Test

- core/kazoo_ast/src/kapi_schemas.erl
- core/kazoo_ast/src/kapps_config_usage.erl
Store kapi modules according to applications' preferences
> Kapi json app prefs

- applications/webhooks/src/webhooks_channel_util.erl
- applications/webhooks/test/webhooks_channel_util_test.erl
Include a flag for internal legs in the base call event as well.
> Log filtered hooks

- applications/ananke/src/tasks/ananke_vm_callback.erl
- applications/callflow/src/cf_util.erl
- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/src/modules/cb_modules_util.erl
- applications/crossbar/src/modules/cb_vmboxes.erl
- core/kazoo_media/src/kz_media_util.erl
- core/kazoo_modb/priv/couchdb/views/mailbox_messages.json
- core/kazoo_voicemail/src/kvm_message.erl
- core/kazoo_voicemail/src/kvm_messages.erl
- core/kazoo_voicemail/src/kvm_util.erl
- core/kazoo_voicemail/src/kz_voicemail.hrl
> [master] KAZOO-5736: properly handling retention for voicemail operations

- applications/crossbar/src/modules/cb_cdrs.erl
> [master] KAZOO-5698: return media_server on cdrs/interaction

- applications/crossbar/src/modules/cb_cdrs.erl
> [4.1] KAZOO-5698: return media_server on cdrs/interaction

- core/kazoo/src/kazoo_maintenance.erl
- core/kazoo_amqp/src/kazoo_amqp_maintenance.erl
- core/kazoo_stdlib/src/kz_term.erl
helpful when pressed to relieve memory pressue
> gc amqp pool workers and report the results

- applications/teletype/src/teletype_farms_sup.erl
- applications/teletype/src/teletype_maintenance.erl
- applications/teletype/src/teletype_renderer.erl
- applications/teletype/test/teletype_publish_tests.erl
- core/kazoo_caches/src/kz_cache.erl
- core/kazoo_caches/src/kz_caches.hrl
- core/kazoo_caches/test/kz_cache_pqc.erl
- core/kazoo_caches/test/kz_cache_tests.erl
- core/kazoo_config/test/kapps_account_config_test.erl
- core/kazoo_data/src/kazoo_data_link_sup.erl
- core/kazoo_data/src/kazoo_data_sup.erl
- core/kazoo_stdlib/src/kz_time.erl
Specifically looking at `wait_for_key_local` issues reported from a client.
> Tests for kz_cache

- applications/crossbar/src/crossbar_util.erl
- core/kazoo_endpoint/src/kz_endpoint.erl
> [master] KAZOO-5575: do not handle disabled/deleted endpoints

- applications/crossbar/src/modules/cb_ledgers.erl
- core/kazoo_ledgers/src/kazoo_ledger.erl
> KAZOO-5777: support ledgers without an amount

- core/kazoo_stdlib/include/kz_log.hrl
Conflicts:
core/kazoo_stdlib/include/kz_log.hrl
> clean up logs a bit

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.reorder.json
- applications/ecallmgr/src/ecallmgr_fs_xml.erl
- applications/reorder/src/reorder_route_req.erl
- core/kazoo_apps/src/kz_hooks_util.erl
- core/kazoo_config/src/kapps_config.erl
KAZOO-5782: updated schema
KAZOO-5782: addressing CI issues
KAZOO-5782: make apis
KAZOO-5782: remove check
KAZOO-5782: formatting
> KAZOO-5782: added transfer and bridge actions to reorder (#4395)

- core/kazoo/src/kz_util.erl
- core/kazoo_amqp/src/api/kz_api.erl
> Fix md master

- applications/ecallmgr/src/ecallmgr_events.erl
- applications/ecallmgr/src/ecallmgr_fs_recordings.erl
* HELP-33420 fix recording events duplication
* fix default for Force-Publish-Event-State
> HELP-33420 fix recording events duplication (#4398)

- applications/callflow/doc/device.md
- applications/callflow/doc/ref/device.md
- applications/callflow/src/module/cf_device.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.device.json
fixes changed behaviour in https://github.com/2600hz/kazoo/commit/c0c16cbf42efcb393bbe114b4432c9e06e0bc3b9
> add dial strategy for cf_device

- core/kazoo_config/src/kapps_config.erl
- core/kazoo_config/test/kapps_config_migrate_test.erl
- core/kazoo_fixturedb/priv/dbs/system_config/docs/kapps_controller.json
- core/kazoo_fixturedb/priv/dbs/system_config/docs/whapps_controller.json
tests for whapps_controller to kapps_controller
> migrate system_config doc to another named doc

- applications/ecallmgr/src/ecallmgr_maintenance.erl
Before fix:
```
+--------------------------------+-------------------+---------------+-------+------------------+----------------------------------+
| Name                           | CIDR               | List          | Type  | Authorizing Type | ID                               |
+================================+===================+===============+=======+==================+==================================+
| kamailio1                      | 172.31.1.100/32    | authoritative | allow | system_config    |                                  |
+--------------------------------+-------------------+---------------+-------+------------------+----------------------------------+
```
After fix:
```
+--------------------------------+--------------------+---------------+-------+------------------+ …
```
> Fix ecallmgr_maintenance sbc_acls alignment

- Makefile
- core/kazoo_media/src/kz_media_file.erl
- core/kazoo_media/src/kz_media_store_proxy.erl
- core/kazoo_media/src/kz_media_util.erl
- make/kz.mk
- scripts/check-dialyzer.escript
Also addresses some issues when dialyzing from an app (vs the project vs CI).
Refactors the proxy handler to have more useful logging as well (around errors mostly).
> Fix proxy for recordings

- applications/callflow/doc/dynamic_cid.md
- applications/callflow/src/module/cf_cidlistmatch.erl
- applications/callflow/src/module/cf_dynamic_cid.erl
- applications/callflow/src/module/cf_lookupcidname.erl
- applications/crossbar/priv/couchdb/account/lists.json
- applications/crossbar/src/modules_v2/cb_lists_v2.erl
master: https://github.com/2600hz/kazoo/pull/4507
> [4.1] HELP-34270: using list entries for both list/lists dynamic_cid actions

- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_number_manager/src/knm_numbers.erl
> [4.1] KAZOO-5801: add a maintenance command to sync numbers from account db to number dbs

- applications/callflow/src/module/cf_voicemail.erl
- core/kazoo_documents/src/kzd_voicemail_box.erl
Added feature to disable the playback of the voicemail envelope ("received on ....") when listening to voicemail
> Master pr disable voicemail envelope playback

- applications/crossbar/src/modules/cb_notifications.erl
The request was crashing before, with no useful information as to why.
> Handle case where teletype template exists on account but not system

- applications/crossbar/doc/ref/vmboxes.md
- applications/crossbar/doc/voicemail.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/vmboxes.json
Conflicts:
applications/crossbar/doc/ref/vmboxes.md
applications/crossbar/doc/voicemail.md
> Added swagger dock for skip_envelope

- applications/crossbar/priv/couchdb/account/account.json
- applications/crossbar/priv/couchdb/account/callflows.json
- applications/crossbar/priv/couchdb/account/click2call.json
- applications/crossbar/priv/couchdb/account/conferences.json
- applications/crossbar/priv/couchdb/account/directories.json
- applications/crossbar/priv/couchdb/account/lists.json
- applications/crossbar/priv/couchdb/account/media.json
- applications/crossbar/priv/couchdb/account/menus.json
- applications/crossbar/priv/couchdb/account/numbers.json
- applications/crossbar/priv/couchdb/account/provisioner_templates.json
- applications/crossbar/priv/couchdb/account/servers.json
- applications/crossbar/priv/couchdb/account/temporal_rules.json
- applications/crossbar/priv/couchdb/account/temporal_rules_sets.json
- applications/crossbar/priv/couchdb/account/users.json
- applications/crossbar/priv/couchdb/account/vmboxes.json
- applications/crossbar/priv/couchdb/views/ts_accounts.json
- applications/crossbar/priv/couchdb/views/ts_users.json
Just a maintenance PR, removing the unused filters from the view.
> remove unused filters object

- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
> [master] KAZOO-5801: remove _rev to avoid conflict during creating new docs

- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
> [4.1] KAZOO-5801: remove _rev to avoid conflict during creating new docs

- core/kazoo_documents/test/kzd_callflow_test.erl
- core/kazoo_schemas/src/kz_json_schema.erl
- core/kazoo_schemas/test/fixtures/schemav3_sub_defaults_array.json
- core/kazoo_schemas/test/kz_json_schema_test.erl
- make/deps.mk
- scripts/README.md
- scripts/check-whitespace.sh
jesse was fixed for using the applied defaults after properties/items andalso json_path fix for integer as part of the path to access items in arrays ([foo, 0, bar] ) 
added tests for array access/validation
> use defaults from jesse

- Makefile
- applications/callflow/src/cf_util.erl
- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/src/ecallmgr_call_control.erl
- core/kazoo_amqp/src/api/kapi_dialplan.erl
- core/kazoo_documents/src/kzd_item_plan.erl
- core/kazoo_media/src/kz_media_tts_cache.erl
- make/kz.mk
update var name
fix spec
remove using special freeswitch apps for playback
add to phony target
> handle looping of media in ecallmgr instead of freeswitch

- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/doc/media.md
- applications/crossbar/doc/ref/media.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/media.json
- applications/crossbar/src/modules/cb_media.erl
> [4.1] HELP-34868: enforce media_source when recording in cf_voicemail

- applications/crossbar/src/modules/cb_search.erl
> [master] KAZOO-5829: normalize the value to search with

- applications/crossbar/src/modules/cb_search.erl
> [4.1] KAZOO-5829: normalize the value to search with

- core/kazoo_number_manager/src/carriers/knm_simwood.erl
Otherwise it returns empty list
> knm_simwood_update

- applications/crossbar/src/modules/provisioner_v5.erl
Also handle the case when we have to set combo/feature keys to null.
master: #4598
> [4.1] KAZOO-5837: set label from user doc on provisioner_v5

- applications/stepswitch/src/stepswitch_inbound.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_port_request.erl
> [master] HELP-34892: transition legacy port_in to in_service

- applications/stepswitch/src/stepswitch_inbound.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_port_request.erl
> [4.1] HELP-34892: transition legacy port_in to in_service

- applications/crossbar/doc/ref/resources.md
- applications/crossbar/doc/resources.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/resources.json
- applications/stepswitch/src/stepswitch_resources.erl
- core/kazoo_documents/src/kzd_resources.erl
- core/kazoo_documents/src/kzd_resources.erl.src
- core/kazoo_schemas/test/fixtures/schemav3_sub_defaults_array.json
> PROD-154: fix missing default resource when using dynamic flags

- .gitignore
- Makefile
* remove a dir when cleaning deps
* make sure we have the latest deps
* download from commit sha
* checkout to known sha, fmt project helper
* use the SHA luke
> Formatter (#4627) - 4.1

- applications/jonny5/src/j5_authz_req.erl
- applications/jonny5/src/j5_channel_destroy.erl
> fix jonny5 authz crash - 4.2

- applications/crossbar/src/modules/cb_ips.erl
> fix permission in ips management - 4.2

- core/kazoo_documents/Makefile
> [4.2] fix compilation for macos

- Makefile
- make/kz.mk
- rel/ci.relx.config.script
- rel/dev.relx.config.script
- rel/dist.relx.config
- rel/dist.relx.config.script
- rel/dist.sys.config
- rel/dist.vm.args
- rel/relx.config.script
- scripts/next_version
After testing on 4.2 this should be back-ported to 4.1 as well.
> ci-relx: support the packaging system

- Makefile
- make/kz.mk
- rel/ci.relx.config.script
- rel/dev.relx.config.script
- rel/dist.relx.config
- rel/dist.relx.config.script
- rel/dist.sys.config
- rel/dist.vm.args
- rel/relx.config.script
- scripts/next_version
> ci-relx: support the packaging system - 4.2

- applications/crossbar/src/modules/cb_media.erl
> [master] don't call is_tts_changed on PUT

- core/kazoo_globals/src/kz_nodes.erl
- core/kazoo_stdlib/src/kz_json.erl
Found during client issue investigation.
> Logging updates for version mismatches and missing files

- applications/callflow/src/cf_route_req.erl
- applications/ecallmgr/src/ecallmgr_fs_conferences.erl
> 4.2: if no account id is found, try using the call-id to get it

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.provisioner.json
- applications/crossbar/src/modules/provisioner_v5.erl
- applications/crossbar/src/modules/provisioner_v5.hrl
Also add vtech combo keys association object
> [4.1] set correct type and line combo keys for brands

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.provisioner.json
- applications/crossbar/src/modules/provisioner_v5.erl
- applications/crossbar/src/modules/provisioner_v5.hrl
Also add vtech combo keys association object
> [4.2] set correct type and line combo keys for brands

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.provisioner.json
- applications/crossbar/src/modules/provisioner_v5.erl
- applications/crossbar/src/modules/provisioner_v5.hrl
Also add vtech combo keys association object
4.2: #4688 
4.1: #4687
> [master] set correct type and line combo keys for brands

- core/kazoo_data/src/kzs_cache.erl
DON'T MERGE, needs proper fetch from configuration
> avoid catch in get_first_defined

- applications/crossbar/src/modules/cb_vmboxes.erl
> [master] HELP-35998: use listing_by_timestamp to get all account's vm messages

- applications/ecallmgr/src/ecallmgr_call_control.erl
- applications/ecallmgr/src/ecallmgr_util.erl
> [master] lets crash on baduuid and advance the queue

- applications/hotornot/src/hon_util.erl
- applications/hotornot/test/hon_util_test.erl
- core/kazoo_documents/src/kzd_rates.erl
> KAZOO-5867: missed type conversion

- applications/hotornot/src/hon_util.erl
- applications/hotornot/test/hon_util_test.erl
- core/kazoo_documents/src/kzd_rates.erl
> KAZOO-5867-4.2: missed type conversion

- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/api_util.erl
- applications/crossbar/src/crossbar_view.erl
- applications/crossbar/src/modules/cb_cdrs.erl
- rel/dev.sys.config
4.2: #4732 
Also adding lager file backend for debug logs (from #4731)
> [master] HELP-36065: don't repeat CDRs headers in csv

- applications/crossbar/src/modules/cb_conferences.erl
> [master] KAZOO-5861: user portal conference fix

- rel/dev.relx.config
- rel/dev.sys.config
lager debug log file for master: #4733
> include erts for dev release

- applications/callflow/src/module/cf_park.erl
observed that when a db operation takes longer than expected saving
the slot, the channel_destroy will be waiting for the cf_park when it
goes into b_answer. However, because the code ignored the return of
b_answer, the cf_park process would end up blocking in b_prompt. This
is because the ecallmgr_call_control process was gone and would not
respond with an error (and obviously the channel_destroy wasn't coming
again).
Another issue to address is kapps_call_command:wait_for_noop/X uses
'infinity' for its timeout when receiving events. Should make it big
but not forever.
> handle when channel goes down while answering

- applications/callflow/src/module/cf_park.erl
observed that when a db operation takes longer than expected saving
the slot, the channel_destroy will be waiting for the cf_park when it
goes into b_answer. However, because the code ignored the return of
b_answer, the cf_park process would end up blocking in b_prompt. This
is because the ecallmgr_call_control process was gone and would not
respond with an error (and obviously the channel_destroy wasn't coming
again).
Another issue to address is kapps_call_command:wait_for_noop/X uses
'infinity' for its timeout when receiving events. Should make it big
but not forever.
> [4.2] handle when channel goes down while answering

- applications/callflow/src/module/cf_voicemail.erl
> [master] HELP-36123: set temp greeting to null to remove

- applications/crossbar/doc/ref/service_plans.md
- applications/crossbar/doc/service_plans.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/service_plan_editable_fields.json
- applications/crossbar/src/modules/cb_service_plans.erl
> [master] KAZOO-5879: list service plan editable quantifiers via service_plans api

- applications/crossbar/src/modules/cb_search.erl
> [master] HELP-36125: use high value for end_key in cb_search

- applications/cdr/src/cdr_channel_destroy.erl
- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/api_util.erl
- applications/crossbar/src/crossbar_view.erl
- applications/crossbar/src/modules/cb_cdrs.erl
> [master] HELP-36124: handle crash in cb_cdrs to avoid returning view results

- applications/crossbar/src/modules/cb_rates.erl
- applications/ecallmgr/src/ecallmgr_fs_authz.erl
- applications/tasks/src/modules/kt_rates.erl
- core/kazoo_documents/src/kzd_rates.erl
- core/kazoo_proper/src/kazoo_proper_maintenance.erl
- core/kazoo_proper/src/pqc_cb_rates.erl
- make/deps.mk
the proper tests actually would have caught this but unfortunately we
don't have a place to run them. My thought is to put them in CircleCI
during the running of the release. I'll add that to master though.
> [4.2] fix confusion with dollars/units and update tests

- applications/hotornot/src/hon_rater.erl
- core/kazoo_documents/src/kzd_rates.erl
> [master] rate cost and rate surcharge are in unit

- applications/crossbar/priv/couchdb/account/users.json
- applications/crossbar/src/modules_v2/cb_users_v2.erl
Also:
- Differentiate between non_unique and system_error errors when checking hotdesk.id uniqueness
> KAZOO-5856: Add uniqueness check for hotdesk.id in user docs

- applications/crossbar/src/modules/cb_search.erl
> [master] workaround for search issue for bigcouch

- applications/crossbar/src/modules/cb_transactions.erl
- core/kazoo_ledgers/src/kz_ledger.erl
> [4.2] HELP-36339: add default description to debit transaction

- applications/crossbar/src/modules/cb_transactions.erl
- core/kazoo_ledgers/src/kz_ledger.erl
> [master] HELP-36339: add default description to debit transaction

- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
> [4.2] give more time for fix/sync account numbers

- core/kazoo_amqp/src/api/kapi_notifications.erl
- core/kazoo_data/src/kzs_doc.erl
- core/kazoo_modb/src/kazoo_modb.erl
> [master] docid + notifications get db + set dest db

- applications/tasks/src/modules/kt_compactor.erl
- applications/tasks/src/modules/kt_compactor_worker.erl
- core/kazoo_couch/src/kz_couch_db.erl
- core/kazoo_couch/src/kz_couch_util.erl
- core/kazoo_couch/src/kz_couch_view.erl
Mostly cleaning up making sure the account id is properly encoded for compaction, and fixes view_cleanup to use API port instead of admin port.
> Compaction fixes

- applications/crossbar/src/modules/cb_service_plans.erl
> [master] allow list service plan editable field without account id in path

- applications/crossbar/src/modules/cb_vmboxes.erl
> [4.2] revert to default filter to remove all msgs if no filter is given

- applications/crossbar/src/modules/cb_vmboxes.erl
- core/kazoo_voicemail/src/kvm_messages.erl
- core/kazoo_voicemail/src/kvm_util.erl
4.2: https://github.com/2600hz/kazoo/pull/4825
> [master] HELP-36621: fix filter message

- core/kazoo_endpoint/src/kz_endpoint.erl
Use the 'loopback' `Invite-Format` for call-forwarded devices.
> HELP-36935-4.2: Call fwd devices

- applications/tasks/src/modules/kt_rates.erl
Update rate if it exists already
> Rate import 4.2

- applications/ecallmgr/src/ecallmgr_call_command.erl
If a play command specified no terminators allowed, previously that would be set on the channel but nothing would change the process registry entry (mutable state - bad! :) ). This changes things to cache the empty list so that subsequent terminator lists are respected.
> HELP-36974-4.2: cache when no terminators are used

- applications/ecallmgr/src/ecallmgr_call_command.erl
If a play command specified no terminators allowed, previously that would be set on the channel but nothing would change the process registry entry (mutable state - bad! :) ). This changes things to cache the empty list so that subsequent terminator lists are respected.
> HELP-36974: cache when no terminators are used

- core/kazoo_endpoint/src/kz_endpoint.erl
master: https://github.com/2600hz/kazoo/pull/4846
> [4.2] KAZOO-5893: do not set Alert-Info on forward

- core/kazoo_endpoint/src/kz_endpoint.erl
4.2: https://github.com/2600hz/kazoo/pull/4847
> [master] KAZOO-5893: do not set Alert-Info on forward

- applications/crossbar/src/api_util.erl
- core/kazoo_documents/src/kz_attachment.erl
master: https://github.com/2600hz/kazoo/pull/4856
> [4.2] crossbar: handle file content multipart headers

- applications/crossbar/src/api_util.erl
- core/kazoo_documents/src/kz_attachment.erl
4.2: https://github.com/2600hz/kazoo/pull/4857
> [master] crossbar: handle file content multipart headers

- applications/callflow/src/cf_exe.erl
- applications/callflow/src/cf_util.erl
- applications/callflow/src/module/cf_branch_bnumber.erl
- applications/callflow/src/module/cf_call_forward.erl
- applications/callflow/src/module/cf_dynamic_cid.erl
- applications/callflow/src/module/cf_intercom.erl
- applications/callflow/src/module/cf_park.erl
- applications/callflow/src/module/cf_play.erl
- applications/callflow/src/module/cf_privacy.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
- core/kazoo_number_manager/src/converters/knm_converter_regex.erl
- core/kazoo_number_manager/src/converters/knm_converters.erl
- core/kazoo_number_manager/test/knm_converters_test.erl
master: https://github.com/2600hz/kazoo/pull/4861
> [4.2] HELP-37136: normalize capture group in cf_privacy

- applications/callflow/src/cf_exe.erl
- applications/callflow/src/cf_util.erl
- applications/callflow/src/module/cf_branch_bnumber.erl
- applications/callflow/src/module/cf_call_forward.erl
- applications/callflow/src/module/cf_dynamic_cid.erl
- applications/callflow/src/module/cf_intercom.erl
- applications/callflow/src/module/cf_park.erl
- applications/callflow/src/module/cf_play.erl
- applications/callflow/src/module/cf_privacy.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
- core/kazoo_number_manager/src/converters/knm_converter_regex.erl
- core/kazoo_number_manager/src/converters/knm_converters.erl
- core/kazoo_number_manager/test/knm_converters_tests.erl
4.2: https://github.com/2600hz/kazoo/pull/4867
> [master] HELP-37136: normalize capture group in cf_privacy

- applications/callflow/src/module/cf_prepend_cid.erl
> KAZOO-5873: Delete key instead of setting it as undefined when using prepend_cid's reset action

- applications/crossbar/src/modules/cb_user_auth.erl
master: https://github.com/2600hz/kazoo/pull/4876
> [4.2] some cleanup

- applications/crossbar/src/modules/cb_user_auth.erl
4.2: https://github.com/2600hz/kazoo/pull/4877
> [master] some cleanup

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.fax.status.json
- applications/crossbar/priv/couchdb/schemas/system_config.fax.json
- applications/fax/src/fax.hrl
- applications/fax/src/fax_jobs.erl
- applications/fax/src/fax_request.erl
- applications/fax/src/fax_worker.erl
- applications/fax/src/fax_worker_sup.erl
- core/kazoo_amqp/src/api/kapi_fax.erl
master: https://github.com/2600hz/kazoo/pull/4878
> [4.2] HELP-37175: fixed email2fax sticking when multiple faxes sent to same destination

- core/kazoo_config/src/kapps_config_doc.erl
4.2: https://github.com/2600hz/kazoo/pull/4864
> [master] build default using system_config_document_schema

- applications/crossbar/src/modules/cb_ledgers.erl
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_couch/src/kz_couch.hrl
- core/kazoo_couch/src/kz_couch_util.erl
- core/kazoo_couch/src/kz_couch_view.erl
- core/kazoo_ledgers/src/kz_ledgers.erl
- core/kazoo_modb/priv/couchdb/views/ledgers.json
- make/deps.mk
Also KAZOO-5191
master: https://github.com/2600hz/kazoo/pull/4910
> [4.2] HELP-37319: handle couchbeam socket closed unexpectedly

- scripts/eunit_run.escript
master: https://github.com/2600hz/kazoo/pull/4946
> [4.2] ensure cover dir is created + halt eunit_run on error

- scripts/eunit_run.escript
4.2: https://github.com/2600hz/kazoo/pull/4947
> [master] ensure cover dir is created + halt eunit_run on error

- applications/callflow/src/module/cf_dynamic_cid.erl
4.2: https://github.com/2600hz/kazoo/pull/4917
> [master] HELP-37496: don't let dynamic cid down if capture group is empty

- applications/crossbar/src/crossbar_maintenance.erl
- core/kazoo_apps/src/kapps_controller.erl
- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_data/src/kzs_db.erl
master: https://github.com/2600hz/kazoo/pull/4949
> [4.2] log error when updating views, add some edoc for system startup

- Makefile
- applications/crossbar/src/modules/cb_modules_util.erl
Cleaned up a few dialyzer complaints too.
> Token costs can be a integer or JSON object

- applications/fax/src/fax.hrl
- applications/fax/src/fax_request.erl
- applications/fax/src/fax_util.erl
> [4.1] KAZOO-5870: fixed fax attachments from inbound fax getting saved over and over and over

- applications/doodle/src/doodle_inbound_listener.erl
- applications/doodle/src/doodle_maintenance.erl
- applications/stepswitch/src/stepswitch_sms.erl
- core/kazoo_amqp/src/api/kapi_sms.erl
- core/kazoo_call/src/kapps_sms_command.erl
Removes dependency cycle between kazoo_amqp and kapps_config
> Moves all outbound AMQP SMS publishing to kapps_sms_command

- core/kazoo_apps/src/kapps_util.erl
- core/kazoo_apps/src/kazoo_apps.app.src
- core/kazoo_config/src/kapps_account_config.erl
- core/kazoo_endpoint/src/kz_attributes.erl
- core/kazoo_speech/src/kazoo_tts.erl
- core/kazoo_translator/src/convertors/kzt_twiml.erl
move local function out of kazoo_apps
> remove kapps_call from kapps_account_config

- applications/crossbar/src/modules/cb_ledgers.erl
- core/kazoo_ledgers/src/kz_ledgers.erl
- core/kazoo_modb/priv/couchdb/views/ledgers.json
4.2: https://github.com/2600hz/kazoo/pull/4971
> [master] KAZOO-5927: use reduce to calculate usage charges

- applications/crossbar/src/modules/cb_ledgers.erl
- core/kazoo_ledgers/src/kz_ledgers.erl
- core/kazoo_modb/priv/couchdb/views/ledgers.json
master: https://github.com/2600hz/kazoo/pull/4970
> [4.2] KAZOO-5927: use reduce to calculate usage charges

- applications/crossbar/src/api_util.erl
- core/kazoo_csv/src/kz_csv.erl
4.2: https://github.com/2600hz/kazoo/pull/4975
> [master] KAZOO-5933: don't create the header for CSV in each chunk

- applications/crossbar/src/api_util.erl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_recordings.erl
add helper functions and fix location spelling
> KAZOO-5934-4.2: set the content-type when loading a recording's attachment

- .circleci/config.yml
- .gitignore
- applications/callflow/src/cf_listener.erl
- applications/crossbar/src/api_util.erl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/crossbar_maintenance.erl
- applications/crossbar/src/modules/cb_ips.erl
- applications/crossbar/src/modules/cb_recordings.erl
- applications/teletype/src/teletype_util.erl
- core/kazoo_apps/src/kapps_controller.erl
- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_documents/src/kzd_call_recordings.erl
- core/kazoo_proper/Makefile
- core/kazoo_proper/doc/README.md
- core/kazoo_proper/src/kazoo_proper.hrl
- core/kazoo_proper/src/pqc_cb_api.erl
- core/kazoo_proper/src/pqc_cb_recordings.erl
- rel/ci.sys.config
Also adds basic testing to the API (PropEr testing to come)
> KAZOO-5934: fix response content-type when tunneled accept header is used

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.vitelity.json
- core/kazoo_number_manager/src/carriers/knm_vitelity.erl
Addes use_stepswitch_cnam to should_lookup_cnam/0
Adds changes requested by @icehess and @lazedo. Thanks guys for your help!
> KAZOO-5938 (patch to master)

- applications/crossbar/doc/connectivity.md
- applications/crossbar/doc/ref/connectivity.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/connectivity.json
- applications/trunkstore/src/ts_from_onnet.erl
Options available in the code weren't reflected in the schema.
> Update connectivity schema to reflect what's in the code

- applications/crossbar/src/api_util.erl
Handling uploading big file properly in Crossbar.
4.2: https://github.com/2600hz/kazoo/pull/5021
> [master] KAZOO-5943: read next body content properly in crossbar

- applications/crossbar/priv/couchdb/account/services.json
- applications/crossbar/priv/service_plan_editable_fields.json
- applications/crossbar/src/crossbar_services.erl
- applications/crossbar/src/modules/cb_conferences.erl
- applications/crossbar/src/modules/cb_faxboxes.erl
- applications/crossbar/src/modules/cb_vmboxes.erl
- core/kazoo_services/src/services/kz_service_conferences.erl
- core/kazoo_services/src/services/kz_service_faxes.erl
- core/kazoo_services/src/services/kz_service_voicemails.erl
There is no master variant as it will be included in KAZOO-5564.
> HELP-37990: added optional quantifiers for faxbox, vmbox and conference

- applications/conference/src/conf_discovery_req.erl
- applications/conference/src/conf_participant.erl
- applications/conference/src/conf_pronounced_name.erl
- applications/pivot/src/pivot_call.erl
- core/kazoo/src/kz_util.erl
- core/kazoo_call/src/kapps_conference.erl
- core/kazoo_data/src/kzs_attachments.erl
- core/kazoo_translator/src/converters/kzt_twiml.erl
- core/kazoo_translator/src/converters/kzt_twiml_dial.erl
- core/kazoo_translator/src/kzt_receiver.erl
> [master] Fix dialing conferences via XML

- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_data/src/kz_datamgr.erl
- core/kazoo_translator/src/converters/kzt_twiml.erl
- core/kazoo_translator/src/converters/kzt_twiml_util.erl
- core/kazoo_translator/src/kzt_receiver.erl
Empty finishOnKey means no DTMF cancel of the gather
> [master] Twiml gather finishonkey

- core/kazoo/src/kz_network_utils.erl
> [4.1] KAZOO-5948: avoid crash when cidr is invalid

- applications/callflow/doc/ref/transfer.md
- applications/callflow/doc/transfer.md
- applications/callflow/src/module/cf_intercept.erl
- applications/callflow/src/module/cf_transfer.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.transfer.json
- core/kazoo_amqp/src/api/kapi_dialplan.hrl
- core/kazoo_ast/src/cf_data_usage.erl
- doc/mkdocs/mkdocs.yml
Could make this chain-able in a "callflow" metaflow
> Transfer callflow

- applications/stepswitch/src/stepswitch_bridge.erl
- applications/stepswitch/src/stepswitch_request_sup.erl
- applications/stepswitch/src/stepswitch_resources.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/listener_types.hrl
- core/kazoo_documents/src/kz_call_event.erl
More specific type usage, accessor module usage, cleanup functions
> Refactor stepswitch a bit 

- applications/crossbar/src/modules/provisioner_util.erl
When new MAC was 'undefined', the logic in do_full_provision/2 that deletes the _old_ MAC from the provisioner was not being executed.
> PISTON-552: remove old MAC from provisioner even if new one is undefined

- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/crossbar_view.erl
- applications/crossbar/src/modules/cb_notifications.erl
btw have you notice we have 35 notifications and they're filling the whole configured sandbox page size (25)?
>  do not paginate when getting available templates

- applications/teletype/priv/templates/service_added.html
- applications/teletype/priv/templates/service_added.text
- applications/teletype/test/rendered-templates/service_added.html
- applications/teletype/test/rendered-templates/service_added.text
> fix some grammar issues for service_added

- applications/acdc/src/acdc_agent_fsm.erl
Conflicts:
applications/acdc/src/acdc_agent_fsm.erl
> PISTON-618: move timeouts/gproc sends to info - resolve infinite loops

- Makefile
- core/kazoo_services/src/kz_services_item.erl
- core/kazoo_services/src/kz_services_items.erl
- doc/engineering/make.md
- scripts/check-dialyzer.escript
A lighter version of `dialyze-hard` that just dialyzes the changed files in one go (but doesn't pull in the unknown modules like in `hard`).
> Dialyze changed files all at once

- applications/teletype/priv/templates/service_added.html
- applications/teletype/priv/templates/topup.html
- applications/teletype/priv/templates/topup.text
- applications/teletype/priv/templates/transaction.html
- applications/teletype/priv/templates/transaction.text
- applications/teletype/priv/templates/transaction_failed.html
- applications/teletype/priv/templates/transaction_failed.text
- applications/teletype/test/rendered-templates/service_added.html
I don't know, do not use Outlook, Gmail I think? Use Mail.app? Everything seems fine, ErlyDTL rendered it okay, mimemail encode it correctly, gen_smtp_client send it correctly, Gmail or outlook or whatever received it correctly, but they can't doing their job of showing it properly.
Mail.app (on iOS and Mac) just render it just as what it should be.
> dollars problem

- core/kazoo_documents/src/kzd_accounts.erl
* needed to fetch tree for a deleted account
> allow kzd_accounts to access soft deleted accounts - 4.2

- applications/crossbar/priv/couchdb/schemas/faxbox.json
- core/kazoo_schemas/src/kz_json_schema_extensions.erl
- core/kazoo_schemas/test/fixtures/schema_regexp.json
- core/kazoo_schemas/test/kz_json_schema_tests.erl
- core/kazoo_stdlib/src/kz_json.erl
> add kazoo-regexp extension to json schema

- applications/tasks/src/knm_number_crawler.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
master: https://github.com/2600hz/kazoo/pull/5186
> [4.2] HELP-39737: update modified timestamp for aging

- applications/crossbar/src/crossbar_init.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
4.3 pr: https://github.com/2600hz/kazoo/pull/5210
> [master] Fix crash in copy numbers, increase timeout in crossbar

- applications/crossbar/src/crossbar_init.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
master pr: https://github.com/2600hz/kazoo/pull/5209
> [4.3] Fix crash in copy numbers, increase timeout in crossbar

- core/kazoo_data/src/kz_datamgr.erl
- doc/engineering/couch_views.md
- doc/mkdocs/mkdocs.yml
Document the metadata needed in design docs to have them properly registered with kz_datamgr.
> Doc view registering

- core/kazoo_couch/src/kz_couch_util.erl
(cherry picked from commit bc7734d085b9d55618d5fa57275e2180a2d44ea5)
> couch errors can be sent in text/html by haproxy - 4.3

- applications/blackhole/src/bh_events.erl
- applications/blackhole/src/blackhole_listener.erl
- applications/blackhole/src/blackhole_socket_handler.erl
> rework blackhole subscriptions -4.2

- applications/crossbar/src/modules/cb_notifications.erl
- core/kazoo_documents/src/kz_notification.erl
- core/kazoo_templates/src/kz_template.erl
4.3: https://github.com/2600hz/kazoo/pull/5242
> [master] check if template exists to update

- applications/crossbar/src/modules/cb_notifications.erl
master: https://github.com/2600hz/kazoo/pull/5241
> [4.3] check if template exists to update

- core/kazoo_amqp/src/kz_amqp_sup.erl
- core/kazoo_amqp/src/kz_amqp_worker.erl
also handles ordering issue when receiving multiple replies
> publisher confirms - 4.3

- applications/callflow/src/module/cf_directory.erl
- core/kazoo_call/src/kapps_call_command.erl
4.3: https://github.com/2600hz/kazoo/pull/5263
> [master] HELP-40391: fix passing terminators instead of lang in cf_directory

- applications/callflow/src/module/cf_voicemail.erl
> [4.3] HELP-40510: vm message_menu: play invalid entry upon invalid option selection 

- applications/teletype/Makefile
- applications/teletype/src/teletype.hrl
- applications/teletype/src/teletype_app.erl
- applications/teletype/src/teletype_bindings.erl
- applications/teletype/src/teletype_farms_sup.erl
- applications/teletype/src/teletype_maintenance.erl
- applications/teletype/src/teletype_port_utils.erl
- applications/teletype/src/teletype_sup.erl
- applications/teletype/src/teletype_tests.erl
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_customer_update.erl
- applications/teletype/src/templates/teletype_low_balance.erl
- applications/teletype/src/templates/teletype_system_alert.erl
- applications/teletype/src/templates/teletype_template_skel.erl
- applications/teletype/test/teletype_render_tests.erl
- core/kazoo_apps/src/kapps_config.erl
- core/kazoo_web/src/kz_http.erl
> Help operators avoid adding duplicates

- applications/ecallmgr/src/ecallmgr_fs_bridge.erl
- core/kazoo_stdlib/test/kz_json_tests.erl
Confirm-related vars are in endpoint CCVs.
> Fix confirm in ccvs

- applications/crossbar/src/modules_v2/cb_devices_v2.erl
When a device is dry-run'd with a 402 accept charges, the
'maybe_add_mobile_mdn/1' call would still add the number to the
account. On the subsequent PUT to accept charges, since the number now
exists, the PUT will fail and the device will not be created.
Instead, we check that the save was successful (since 402 is an
'error') before handling the new device. This is more in line with how
it used to work when crossbar_services:maybe_dry_run/2 took a callback
function if not dry-running.
> [4.3] Handle new device only on successful save

- applications/ecallmgr/src/ecallmgr_fs_authn.erl
> mod_kazoo 1.5+ can send uuid in fetch requests - 4.3

- applications/tasks/src/modules/kt_cleanup.erl
- core/kazoo_data/src/kzs_db.erl
- core/kazoo_documents/src/kzd_accounts.erl
- core/kazoo_number_manager/doc/carrier_types.md
- core/kazoo_number_manager/src/carriers/knm_managed.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_stdlib/src/kz_term.erl
- make/deps.mk
Mostly updating PropEr to 1.3 (and the newer repo location) and some tickies and dialyzer updates.
> Updates related to cpaas

- core/kazoo_data/src/kzs_db.erl
> publish created fix - 4.3

- Makefile
- core/kazoo_amqp/src/kz_amqp_worker.erl
> fix handle_payload return - 4.3

- applications/crossbar/src/modules/provisioner_util.erl
- applications/crossbar/src/modules_v2/cb_devices_v2.erl
> KAZOO-6009: refactor provisioner functions to support MAC normalization

- applications/braintree/src/braintree_maintenance.erl
- applications/braintree/src/integration/cb_braintree.erl
- applications/braintree/src/sdk/braintree_card.erl
- applications/braintree/src/sdk/braintree_customer.erl
- applications/braintree/src/sdk/braintree_util.erl
- core/kazoo_documents/src/kzd_services.erl
- core/kazoo_services/src/kz_services.erl
- core/kazoo_services/src/modules/kz_services_payment_tokens.erl
> [4.3] SSSU-62: stores payment information in Kazoo services 

- applications/crossbar/doc/ref/devices.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/devices.combo_key.json
- applications/crossbar/priv/couchdb/schemas/devices.json
- applications/crossbar/src/modules/provisioner_v5.erl
> [4.3] SSSU-68: add ability to set a custom label for BLF keys

- applications/jonny5/src/j5_limits.erl
- core/kazoo_documents/src/kzd_service_plan.erl
- core/kazoo_services/src/kz_services_plan.erl
- core/kazoo_services/src/kz_services_plans.erl
- core/kazoo_services/src/kz_services_quantities.erl
- core/kazoo_services/src/modules/kz_services_limits.erl
> [4.3] SSSU-50: tie limits to service plan for user-based accounts

- applications/crossbar/src/cb_apps_util.erl
- applications/hotornot/src/hon_util.erl
- core/kazoo_services/src/kazoo_services.app.src
- core/kazoo_services/src/kz_services.erl
- core/kazoo_services/src/modules/kz_services_applications.erl
- core/kazoo_services/src/modules/kz_services_ratedecks.erl
> [4.3] Split services modules

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.jonny5.json
- applications/crossbar/src/crossbar_services.erl
- applications/crossbar/src/modules/cb_services.erl
- applications/jonny5/src/j5_flat_rate.erl
- applications/teletype/src/templates/teletype_service_added.erl
- core/kazoo_number_manager/src/knm_errors.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_services/src/kz_services.erl
- core/kazoo_services/src/kz_services_invoice.erl
- core/kazoo_services/src/kz_services_invoices.erl
- core/kazoo_services/src/kz_services_item.erl
- core/kazoo_services/src/kz_services_items.erl
- core/kazoo_services/src/kz_services_plans.erl
- core/kazoo_stdlib/src/kz_currency.erl
> [4.3] SSSU-20: the good, the bad, the ugly standing

- applications/crossbar/doc/ref/storage.md
- applications/crossbar/doc/storage.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/storage.attachment.dropbox.json
- applications/crossbar/priv/couchdb/schemas/storage.attachment.google_drive.json
- applications/crossbar/priv/couchdb/schemas/storage.attachment.onedrive.json
- core/kazoo_schemas/src/kz_json_schema_extensions.erl
> catch more errors validating oauth doc_id - 4.3

- applications/callflow/src/cf_route_req.erl
the case where freeswitch emitted the channel_destroy before accepting the dialplan
> KAZOO-6016 protect from undefined Fetch-ID

- applications/callflow/src/cf_route_req.erl
the case where freeswitch emitted the channel_destroy before accepting the dialplan
> KAZOO-6016 protect from undefined Fetch-ID - 4.3

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.ecallmgr.json
- applications/ecallmgr/src/ecallmgr_util.erl
…registered. (#5314)
doc updates
add config property to schema
Delete .gitmodules
make apis and whitespace
add missing specs
> HELP-34627:Add global config to failover only when all devices unregistered  [4.3]

- make/deps.mk
> Revert "Upgrade to Cowboy 2.6.1"

- applications/crossbar/src/modules/cb_alerts.erl
- applications/crossbar/test/cb_alerts_tests.erl
- core/kazoo_documents/src/kzd_accounts.erl
- core/kazoo_number_manager/src/knm_port_request.erl
for when:
- [SSSU-40] Balance is below threshold
- [SSSU-41] Default payment tokens check
- [SSSU-42] Port request's last comment has waiting_for_reply property set to true
- [SSSU-43] Port request's state is scheduled or rejected
- [SSSU-61] Create unit tests for notification triggers
> [SSSU-21] Add notification triggers

- core/kazoo_services/src/kz_services.erl
master: https://github.com/2600hz/kazoo/pull/5392
> [4.3] avoid conflict when deleting service doc

- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules_v2/cb_users_v2.erl
- applications/teletype/src/templates/teletype_new_account.erl
master: https://github.com/2600hz/kazoo/pull/5364
> [4.3] SSSU-71: send no emails on creation

- .gitignore
- Makefile
- core/kazoo_documents/src/kzd_accounts.erl
- core/kazoo_media/src/kz_media_util.erl
- make/ci.mk
When making changes it can be nice to check that the config.yml is still valid.
> Validate CI config

- applications/callflow/src/module/cf_set_variables.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.dialplan.set.json
- applications/ecallmgr/src/ecallmgr_call_command.erl
- core/kazoo_amqp/src/api/kapi_dialplan.hrl
- core/kazoo_call/src/kapps_call.erl
- core/kazoo_call/src/kapps_call_command.erl
Allow CCVs and CAVs to be exported
> PISTON-652: add Export-All option for kapps_call_command:set

- core/kazoo_services/src/modules/kz_services_payment_tokens.erl
> [4.3] KAZOO-6028: flip it and reverse it

- core/kazoo_services/src/kz_services.erl
master: https://github.com/2600hz/kazoo/pull/5417
> [4.3] log delinquency in dollars

- applications/callflow/doc/device.md
- applications/callflow/doc/ref/device.md
- applications/callflow/doc/ref/user.md
- applications/callflow/doc/user.md
- applications/callflow/src/module/cf_device.erl
- applications/callflow/src/module/cf_user.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.device.json
- applications/crossbar/priv/couchdb/schemas/callflows.user.json
> [4.3] KAZOO-6027: support custom_sip_headers on device/user actions

- applications/callflow/doc/device.md
- applications/callflow/doc/ref/device.md
- applications/callflow/doc/ref/user.md
- applications/callflow/doc/user.md
- applications/callflow/src/module/cf_device.erl
- applications/callflow/src/module/cf_user.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.device.json
- applications/crossbar/priv/couchdb/schemas/callflows.user.json
> [4.2] KAZOO-6027: support custom_sip_headers on device/user actions

- core/kazoo_documents/src/kzd_box_message.erl
> HELP-40835: include more expected fields in message metadata

- applications/ecallmgr/src/ecallmgr_fs_authz.erl
- applications/jonny5/src/j5_authz_req.erl
- applications/jonny5/src/j5_channel_destroy.erl
4.3: https://github.com/2600hz/kazoo/pull/5433
> [master] KAZOO-6024: determine reseller id properly for authz request by number

- applications/ecallmgr/src/ecallmgr_fs_authz.erl
- applications/jonny5/src/j5_authz_req.erl
- applications/jonny5/src/j5_channel_destroy.erl
master: https://github.com/2600hz/kazoo/pull/5434
> [4.3] KAZOO-6024: determine reseller id properly for authz request by number

- applications/crossbar/src/modules/cb_alerts.erl
> KAZOO-6032: handle an empty list of comments

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.services.json
- core/kazoo_services/include/kazoo_services.hrl
- core/kazoo_services/src/kz_services.erl
> KAZOO-6031: add system_config parameter to enforce good_standing

- applications/trunkstore/src/ts.hrl
- applications/trunkstore/src/ts_callflow.erl
- applications/trunkstore/src/ts_from_offnet.erl
- applications/trunkstore/src/ts_from_onnet.erl
- applications/trunkstore/src/ts_offnet_sup.erl
- applications/trunkstore/src/ts_onnet_sup.erl
- applications/trunkstore/src/ts_util.erl
- core/kazoo_amqp/src/api/kapi_route.erl
- core/kazoo_apps/src/kapps_config.erl
- core/kazoo_couch/src/kz_couch.hrl
- Handle timeout on views more gracefully
- Improve types and naming
> Cleanup of some trunkstore code

- applications/teletype/src/teletype_port_utils.erl
master: https://github.com/2600hz/kazoo/pull/5446
> [4.3] check port support email first

- applications/braintree/src/braintree_maintenance.erl
> [4.3] add braintree token for undeleted accounts with plans only

- core/kazoo_services/src/kz_services.erl
> [4.3] change format to support float

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.ledgers.json
- core/kazoo_ledgers/src/kz_ledgers.erl
> Kazoo 6039 4.3

- applications/callflow/src/module/cf_resources.erl
- applications/crossbar/doc/ref/accounts.md
- applications/crossbar/doc/ref/devices.md
- applications/crossbar/doc/ref/users.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/caller_id.json
- applications/crossbar/priv/couchdb/schemas/kapi.dialplan.bridge.json
- applications/crossbar/priv/couchdb/schemas/kapi.offnet_resource.req.json
- applications/crossbar/priv/couchdb/schemas/kapi.resource.eavesdrop_req.json
- applications/crossbar/priv/couchdb/schemas/kapi.resource.originate_req.json
- applications/crossbar/priv/couchdb/schemas/kapi.sms.message.json
- applications/ecallmgr/src/ecallmgr_fs_xml.erl
- applications/ecallmgr/src/ecallmgr_originate.erl
- applications/stepswitch/src/stepswitch_bridge.erl
- core/kazoo_amqp/include/kapi_offnet_resource.hrl
- core/kazoo_amqp/src/api/kapi_dialplan.hrl
- core/kazoo_amqp/src/api/kapi_offnet_resource.erl
- core/kazoo_documents/src/kzd_caller_id.erl
- core/kazoo_documents/src/kzd_caller_id.erl.src
- core/kazoo_endpoint/src/kz_endpoint.erl
- doc/announcements.md
> Kazoo 6040 4.3

- applications/teletype/priv/templates/port_request_admin.html
- applications/teletype/priv/templates/port_request_admin.text
- applications/teletype/src/teletype_port_utils.erl
- applications/teletype/src/templates/teletype_port_cancel.erl
- applications/teletype/src/templates/teletype_port_comment.erl
- applications/teletype/src/templates/teletype_port_pending.erl
- applications/teletype/src/templates/teletype_port_rejected.erl
- applications/teletype/src/templates/teletype_port_request.erl
- applications/teletype/src/templates/teletype_port_request_admin.erl
- applications/teletype/src/templates/teletype_port_scheduled.erl
- applications/teletype/src/templates/teletype_port_unconfirmed.erl
- applications/teletype/src/templates/teletype_ported.erl
- core/kazoo_documents/src/kzd_port_requests.erl
~~DON'T MERGE THIS YET!~~
master: https://github.com/2600hz/kazoo/pull/5471
~~DON'T MERGE THIS YET!~~
Meeeeergggee it
> [4.3] send to port authority and submitter in two passes, fix fields

- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/src/teletype_util.erl
master: https://github.com/2600hz/kazoo/pull/5477
> [4.3] check only data for preview, remove private comment if not superduper

- applications/crossbar/src/api_util.erl
- applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
Most of this is pulled from cb_phone_numbers_v2
> PISTON-660: set_accepting_charges to handle dry_run in v1 phone_numbers

- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/priv/templates/port_comment.html
- applications/teletype/priv/templates/port_comment.text
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_port_cancel.erl
- applications/teletype/src/templates/teletype_port_comment.erl
- applications/teletype/src/templates/teletype_port_rejected.erl
- applications/teletype/src/templates/teletype_port_request.erl
- applications/teletype/src/templates/teletype_port_request_admin.erl
master: https://github.com/2600hz/kazoo/pull/5486
> [4.3] fix port comment author, don't expose port authority emails

- applications/crossbar/src/modules/cb_cdrs.erl
- core/kazoo_modb/priv/couchdb/views/cdrs.json
master: https://github.com/2600hz/kazoo/pull/5491
> [4.3] HELP-42125: add cdrs doc id to view keys to avoid pagination problem

- core/kazoo_ledgers/src/kz_ledger.erl
> KAZOO-6046: return negative amounts for debits

- applications/crossbar/doc/storage.md
- applications/crossbar/src/modules/cb_storage.erl
- core/kazoo_attachments/src/kz_att_onedrive.erl
- core/kazoo_attachments/src/kz_att_s3.erl
- core/kazoo_data/priv/defaults/system.json
- core/kazoo_data/src/kazoo_data_bootstrap.erl
- core/kazoo_data/src/kzs_plan.erl
- core/kazoo_proper/src/pqc_cb_api.erl
- core/kazoo_proper/src/pqc_cb_storage.erl
- make/deps.mk
* validates attachment handlers once
* probes system attachment handlers
* changes caching of dataplans to avoid concurrency load
> system storage api update

- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/priv/preview_data/port_request.json
- applications/teletype/src/teletype_port_utils.erl
- applications/teletype/src/templates/teletype_port_cancel.erl
- applications/teletype/src/templates/teletype_port_comment.erl
- applications/teletype/src/templates/teletype_port_rejected.erl
- applications/teletype/src/templates/teletype_port_request.erl
- applications/teletype/src/templates/teletype_port_request_admin.erl
> [4.3] KAZOO-6048: port preview notification is happy now

- applications/teletype/src/templates/teletype_new_account.erl
Properly set To email address for new account notification. If the email type is admins make sure it always send to the reseller account admins.
> [master] HELP-42138: properly set to email address for new account

- applications/teletype/src/templates/teletype_new_account.erl
> [4.3] HELP-42138: properly set to email address for new account

- applications/crossbar/doc/ips.md
- applications/crossbar/doc/ref/ips.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/ip.json
- applications/crossbar/priv/couchdb/schemas/ips.json
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/modules/cb_ips.erl
- core/kazoo_documents/src/kzd_ip.erl
- core/kazoo_documents/src/kzd_ip.erl.src
- core/kazoo_documents/src/kzd_ips.erl.src
- core/kazoo_ips/src/kz_ip.erl
- core/kazoo_schemas/src/kz_json_schema.erl
> KAZOO-6051: fix ips assignments - 4.3

- applications/crossbar/src/modules/cb_call_inspector.erl
master: https://github.com/2600hz/kazoo/pull/5522
> [4.3] update cdrs view options for call inspector according to #5491

- applications/crossbar/src/api_util.erl
master: https://github.com/2600hz/kazoo/pull/5533
> [4.3] don't log json response, it breaks log and shell

- applications/teletype/src/templates/teletype_port_cancel.erl
- applications/teletype/src/templates/teletype_port_comment.erl
- applications/teletype/src/templates/teletype_port_rejected.erl
- applications/teletype/src/templates/teletype_port_request.erl
- applications/teletype/src/templates/teletype_port_request_admin.erl
fix issue when trying to get Emails as jobj instead of props.
> [master] never ending teletype issues

- applications/teletype/src/templates/teletype_port_cancel.erl
- applications/teletype/src/templates/teletype_port_comment.erl
- applications/teletype/src/templates/teletype_port_rejected.erl
- applications/teletype/src/templates/teletype_port_request.erl
- applications/teletype/src/templates/teletype_port_request_admin.erl
master: https://github.com/2600hz/kazoo/pull/5536
> [4.3] never ending teletype issues

- core/kazoo_data/src/kz_datamgr.erl
master: https://github.com/2600hz/kazoo/pull/5539
> [4.3] replace whole doc when revising from filesystem

- core/kazoo_amqp/src/api/kapi_notifications.erl
master: https://github.com/2600hz/kazoo/pull/5541
> [4.3] don't required optional payment-token

- applications/crossbar/src/modules/provisioner_v5.erl
master: https://github.com/2600hz/kazoo/pull/5562
> [4.3] fix combo key line

- core/kazoo_proper/src/pqc_cb_port_requests.erl
pull requests https://github.com/2600hz/kazoo/pull/5578 has this fix.
> [master-only] qf: fix port_requests test, crash if tests are failed

- applications/crossbar/src/modules_v2/cb_devices_v2.erl
Master counterpart: #5576
KAZOO-6038: Fixes according to ci checks
KAZOO-6038: Add changes according to PR comments
KAZOO-6038: Add change to fix ci checks
formatting
> KAZOO-6038: Fix cb_devices_v2.erl to allow mobile devices modification

- core/kazoo_documents/src/kzd_item_plan.erl
- core/kazoo_services/src/kz_services_item.erl
> [4.3] KAZOO-6045: more intuitive parameter names

- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- applications/ecallmgr/src/fs_event_filters.hrl
Backporting https://github.com/2600hz/kazoo/pull/5545
> PISTON-688: add callee/caller ID to ecallmgr_fs_channel - 4.3

- core/kazoo_data/src/kzs_plan.erl
reworked to start and cache connection maps in plan cache_object on initial load
> 4.3 - HELP-43211 Missing Commit Fix

- core/kazoo_provisioner/src/provisioner_v5.erl
Conflicts:
core/kazoo_provisioner/src/provisioner_v5.erl
> [master] QF: support video codecs in provisioner_v5

- applications/registrar/src/reg_authn_req.erl
Depends on https://github.com/2600hz/kazoo-configs-kamailio/pull/97 to work.
> HELP-41363: Add HotDesk-Current-ID CCV when device is hotdesked

- applications/tasks/src/kz_tasks_trigger.erl
- applications/tasks/src/modules/kt_compaction_reporter.erl
- applications/tasks/src/modules/kt_compactor.erl
- applications/tasks/src/modules/kt_compactor.hrl
- applications/tasks/src/modules/kt_compactor_worker.erl
- applications/tasks/src/tasks_bindings.erl
- applications/tasks/src/tasks_maintenance.erl
- applications/tasks/src/tasks_sup.erl
- applications/tasks/test/kt_compactor_tests.erl
- core/kazoo_modb/priv/couchdb/views/compaction_jobs.json
- core/kazoo_tasks/src/kz_tasks.erl
> Several improments for compactions jobs

- core/kazoo_proper/src/pqc_cb_cdrs.erl
When the previous month has 31 days (like March), the default date
range calculated for CDR lookups will miss the previous month's CDRs
if their time is set to too early in the day.
This change sets the time for the current month's CDRs to midnight and
the previous month's CDRs to one second before midnight.
I'm sure a leap year will hose all this at some point too!
> fix time set on CDRs to ensure they show up

- applications/crossbar/src/modules/cb_ledgers.erl
4.3: https://github.com/2600hz/kazoo/pull/5634
> KAZOO-6073: [master] final sum for ledgers summary

- applications/crossbar/src/modules/cb_port_requests.erl
master: https://github.com/2600hz/kazoo/pull/5639
> PORT-4: [4.3] fix set and check private comments

- core/kazoo_attachments/src/kz_att_util.erl
> format_url : handle case where path has trailing /

- applications/ecallmgr/src/ecallmgr_util.erl
Also refactoring use failover if all devices unregister part
master: https://github.com/2600hz/kazoo/pull/5675
> HELP-43124: [4.3] don't reverse bridge strings again when failover option is set

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.epmd.json
- core/kazoo_apps/src/kazoo_apps_app.erl
- core/kazoo_apps/src/kazoo_apps_sup.erl
- core/kazoo_apps/src/kz_epmd.erl
* if epmd goes down, try to reconnect
> Check that an EMPD registration exists

- core/kazoo_services/src/kz_services_quantities.erl
> [4.3] KAZOO-6090: if the quantities cannot be fetched do not proceed

- core/kazoo_services/src/kz_services.erl
> [4.3] KAZOO-6089: allow the delete to proceed if missing

- core/kazoo_services/src/kz_services_item.erl
> [4.3] KAZOO-6087: calculate both discounts during creation

- core/kazoo_number_manager/src/knm_port_request.erl
4.3: https://github.com/2600hz/kazoo/pull/5716
> PORT-24: [master] let any account in hierarchy to create their sub-account port

- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/kazoo_amqp_maintenance.erl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_caches/src/kz_cache_listener.erl
- core/kazoo_globals/src/kz_nodes.erl
> AMQP Updates from #5215 now that history is removed

- rel/kazoo
* allow per node vm.args/sys.config
* remove code path as its not needed
> Kazoo script

- applications/crossbar/src/modules/cb_alerts.erl
- applications/crossbar/test/cb_alerts_tests.erl
> [4.3] KAZOO-6088: skip payment token alerts if there are no service plans

- core/kazoo/include/kz_api_literals.hrl
- core/kazoo_amqp/include/kz_amqp.hrl
- core/kazoo_amqp/include/kz_api.hrl
- core/kazoo_amqp/src/api/kapi.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/kz_amqp_util.erl
- core/kazoo_amqp/src/listener_federator.erl
- core/kazoo_amqp/src/listener_utils.erl
this allows a gen_listener to serve several processes
> allow delivering a message to a pid

- applications/fax/src/fax_global_shared_listener.erl
- applications/fax/src/fax_shared_listener.erl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_amqp/src/listener_federator.erl
- core/kazoo_caches/src/kz_cache_listener.erl
- core/kazoo_media/src/kz_media_map.erl
- core/kazoo_number_manager/src/knm_search.erl
* tell processes with sticky channels about down brokers
* handle gen_listener casts
> [4.3] tell processes with sticky channels about down brokers

- scripts/check-dialyzer.escript
4.3: https://github.com/2600hz/kazoo/pull/5761
> [master] removing dialyzer race_conditions, it causing oom in cricleci

- applications/braintree/src/braintree_sdk.hrl
- applications/braintree/src/integration/cb_braintree.erl
- applications/braintree/src/sdk/braintree_card.erl
> [4.3] KAZOO-6098: verify only when adding a new card

- applications/crossbar/src/crossbar_services.erl
- applications/crossbar/src/modules/cb_user_auth.erl
- core/kazoo_services/src/kz_services.erl
- core/kazoo_services/src/kz_services_invoices.erl
- core/kazoo_services/src/kz_services_plans.erl
> [4.3] Kazoo 6099 4.3

- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/api_util.erl
- applications/crossbar/src/cb_apps_util.erl
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_types.hrl
- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_auth.erl
- applications/crossbar/src/modules/cb_cdrs.erl
- applications/crossbar/src/modules/cb_media.erl
- applications/crossbar/src/modules/cb_port_requests.erl
- applications/crossbar/src/modules/cb_rates.erl
- applications/crossbar/src/modules/cb_services.erl
- applications/crossbar/src/modules/cb_tasks.erl
- applications/crossbar/src/modules/cb_whitelabel.erl
- applications/hotornot/test/hon_trie_lru_pqc.erl
- core/kazoo_stdlib/src/kz_term.erl
> Address content type changes

- applications/crossbar/src/modules/cb_notifications.erl
- applications/crossbar/src/modules/cb_port_requests.erl
- applications/teletype/src/teletype_port_utils.erl
- core/kazoo_documents/src/kzd_comment.erl
4.3: https://github.com/2600hz/kazoo/pull/5706
> PORT-23: [master] check old key for setting is_private first

- core/kazoo_documents/src/kzd_activation_item.erl
- core/kazoo_documents/src/kzd_item_plan.erl
- core/kazoo_services/src/kz_services_invoice.erl
- core/kazoo_services/src/kz_services_invoices.erl
- core/kazoo_services/src/kz_services_item.erl
- core/kazoo_services/src/kz_services_items.erl
> [4.3] KAZOO-6099: simplify annotate to fix last object removal quantity bug

- applications/braintree/src/integration/cb_braintree.erl
- applications/braintree/src/sdk/braintree_address.erl
- applications/braintree/src/sdk/braintree_card.erl
- applications/braintree/src/sdk/braintree_util.erl
- core/kazoo_services/src/modules/kz_services_payment_tokens.erl
master: https://github.com/2600hz/kazoo/pull/5766
> [4.3] fix deleting a single cc payment token

- applications/jonny5/src/j5_authz_req.erl
- applications/jonny5/src/j5_channels.erl
- applications/jonny5/src/j5_hard_limit.erl
- applications/jonny5/src/j5_limits.erl
- core/kazoo_documents/src/kzd_limits.erl
- doc/reference/routing.md
Having an office did and call-center did within one account, would like to make sure not all allowed sessions are eaten by call center ...
> limit inbound calls per did

- applications/crossbar/doc/devices.md
- applications/crossbar/doc/ref/devices.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/devices.json
- core/kazoo_documents/src/kzd_devices.erl.src
master: https://github.com/2600hz/kazoo/pull/5838
> [4.3] fix improper devices.hotdesk schema

- applications/callflow/src/module/cf_directory.erl
- applications/callflow/src/module/cf_directory.hrl
- applications/callflow/test/cf_directory_tests.erl
Mostly adding testing to ensure sort/filter is working as expected
> KAZOO-6108: check order of users after sort/filter

- doc/engineering/installing-on-mac.md
- doc/installation.md
- Add a few more brew modules required for Mojave.
- Add a link to mac build md file from the main installation guide.
> update majove osx build instruction

- core/kazoo_apps/priv/couchdb/account/users.json
> [master] format users view json file

- applications/tasks/src/modules/kt_modb_creation.erl
If the tasks app is started on or after the MODB creation date, the
next month's MODBs won't be created (or may be partially created if
tasks was restarted after MODB creation had begun).
Check if the tasks app is starting up between configured creation date
and the end of the month and start a MODB creation task if so.
> On init, check if modb creation should start

- applications/tasks/src/modules/kt_modb_creation.erl
If the tasks app is started on or after the MODB creation date, the
next month's MODBs won't be created (or may be partially created if
tasks was restarted after MODB creation had begun).
Check if the tasks app is starting up between configured creation date
and the end of the month and start a MODB creation task if so.
> [4.3] On init, check if modb creation should start

- applications/crossbar/src/cb_apps_util.erl
- applications/crossbar/src/crossbar_util.erl
> [4.3] KAZOO-6113: add exception for master account and refactor

- applications/doodle/src/doodle.hrl
- applications/doodle/src/doodle_inbound_listener_sup.erl
(cherry picked from commit 94bd87df0260663611059a0c0adfaded3d2ba8b4)
> get doodle default connection from runtime - 4.3

- applications/tasks/src/kz_tasks_trigger.erl
- applications/tasks/src/modules/kt_compactor.erl
And:
- Use proper variable names
> Export function to handle auto compaction triggers (#5881)

- core/kazoo_apps/src/kz_epmd.erl
- doc/installation.md
-More information about FQDN requirement to start dev release shell
-Print out Host during epmd registration
> update install doc with more epmd registration info

- applications/callflow/src/module/cf_voicemail.erl
Reference commit f37d9f9b7ee0c8f69f92def1d94b0f91be9790ee
handle dialyzer complaints from #5910
> callflow: Code cleanup of cf_voicemail callback cleanup

- applications/crossbar/test/provisioner_v5_tests.erl
- core/kazoo_call/src/kzc_recording.erl
Start a timer to limit recording time; stop kzc_recording process if
the timer expires
Start a timer for RECORD_STOP when recv CHANNEL_DESTROY; stop
kzc_recording if the timer expires
> [4.3] Timers for kzc_recording processes to make sure they terminate

- applications/crossbar/src/cb_apps_util.erl
- applications/crossbar/test/provisioner_v5_tests.erl
> [4.3] HELP-45578: dont override the blacklist and improved logging

- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/api_util.erl
There is already a more expansive fix on master.
> [4.3] fix send_file CTA and make file removal optional

- applications/crossbar/src/modules/cb_services.erl
- core/kazoo_modb/priv/couchdb/views/services.json
- core/kazoo_services/src/kz_services_plan.erl
master: https://github.com/2600hz/kazoo/pull/5962
> [4.3] service changes summary per account followup

- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/modules/cb_comments.erl
- applications/crossbar/src/modules/cb_port_requests.erl
- applications/crossbar/src/modules/phonebook.erl
- core/kazoo_documents/src/kzd_port_requests.erl
- core/kazoo_number_manager/src/knm_port_request.erl
> SPHBK-12: [4.3] rejecting port if port submission is failed due to an external service

- applications/blackhole/src/blackhole_init.erl
- applications/conference/src/conf_discovery_req.erl
- applications/crossbar/src/crossbar_init.erl
- applications/ecallmgr/src/call_control/ecallmgr_call_control_listener.erl
- applications/ecallmgr/src/ecallmgr_app.erl
- applications/ecallmgr/src/event_stream/ecallmgr_fs_event_stream.erl
- applications/fax/src/fax_init.erl
- applications/media_mgr/src/media_proxy.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_amqp/src/kz_amqp_channel.erl
- core/kazoo_amqp/src/kz_amqp_connection.erl
- core/kazoo_amqp/src/kz_amqp_connections.erl
- core/kazoo_amqp/src/kz_amqp_util.erl
- core/kazoo_amqp/src/listener_federator.erl
- core/kazoo_amqp/test/kz_amqp_test.erl
- core/kazoo_bindings/src/kazoo_bindings.erl
- core/kazoo_globals/src/kz_nodes.erl
- core/kazoo_proper/src/pqc_httpd.erl
major change to handle assignments async
> Amqp updates

- applications/conference/src/conf_discovery_req.erl
- applications/ecallmgr/src/ecallmgr_app.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_amqp/src/kz_amqp_channel.erl
- core/kazoo_amqp/src/kz_amqp_connection.erl
- core/kazoo_amqp/src/kz_amqp_connections.erl
- core/kazoo_amqp/src/kz_amqp_util.erl
- core/kazoo_amqp/src/listener_federator.erl
- core/kazoo_amqp/test/kz_amqp_test.erl
- core/kazoo_globals/src/kz_nodes.erl
async in assignments
reconnect issues
ranch warnings
> backport of amqp-updates

- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/kz_amqp_connection.erl
- core/kazoo_amqp/src/kz_amqp_util.erl
- core/kazoo_globals/src/kz_nodes.erl
> declare exchanges on reconnect - 4.3

- core/kazoo_provisioner/src/provisioner_v5.erl
4.3: https://github.com/2600hz/kazoo/pull/6000
> [master] setting account to 1 for htek

- applications/callflow/src/module/cf_directory.erl
Sort users consistently in the multiple failure and retry scenarios.
> [master] sort user in tts directory consistently

- applications/callflow/src/module/cf_directory.erl
sort user in tts directory consistently
> [4.3] sort user in directory consistently

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.call.event.json
- applications/crossbar/priv/couchdb/schemas/kapi.dialplan.error.json
- applications/crossbar/priv/couchdb/schemas/kapi.resource.originate_resp.json
- applications/crossbar/priv/couchdb/schemas/kapi.resource.originate_started.json
- applications/ecallmgr/Makefile
- applications/ecallmgr/priv/mod_kazoo/definitions/Custom-Channel-Vars.xml
- applications/ecallmgr/priv/mod_kazoo/events/CHANNEL_EXECUTE_COMPLETE.xml
- applications/ecallmgr/src/call_cmd/ecallmgr_fs_bridge.erl
- applications/ecallmgr/src/call_cmd/ecallmgr_fs_command.erl
- applications/ecallmgr/src/call_control/ecallmgr_call_control.erl
- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_fs_xml.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- applications/ecallmgr/src/fs_dist.erl
- applications/ecallmgr/src/node/ecallmgr_fs_node.erl
- applications/ecallmgr/src/node/ecallmgr_fs_node_command.erl
- applications/ecallmgr/src/node/ecallmgr_fs_nodes.erl
- applications/ecallmgr/src/node/ecallmgr_fs_pinger.erl
- applications/jonny5/src/j5_util.erl
- core/kazoo_amqp/include/kz_amqp.hrl
- core/kazoo_amqp/include/kz_api.hrl
- core/kazoo_amqp/src/api/kapi_call.hrl
- core/kazoo_amqp/src/api/kapi_dialplan.erl
- core/kazoo_amqp/src/api/kapi_dialplan.hrl
- core/kazoo_amqp/src/api/kz_api.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_apps/src/kz_amqp_worker.erl
- core/kazoo_events/src/kz_hooks_listener.erl
* sends back error with error & channel/call state
* simplifies queue forward handling from 3 places to 1
* other missing fixes
* remove dead code
> Call control fixes & enhancements

- applications/callflow/doc/cf_branch_variable.md
- applications/callflow/doc/dynamic_cid.md
- applications/callflow/doc/missed_call_alert.md
- applications/callflow/doc/park.md
- applications/callflow/doc/prepend_cid.md
- applications/callflow/doc/ref/prepend_cid.md
- applications/callflow/doc/resources.md
- applications/crossbar/doc/auth.md
- applications/crossbar/doc/conference.md
- applications/crossbar/doc/ips.md
- applications/crossbar/doc/ledgers.md
- applications/crossbar/doc/multi_factor.md
- applications/crossbar/doc/notifications.md
- applications/crossbar/doc/pivot.md
- applications/crossbar/doc/search.md
- applications/crossbar/doc/security.md
- applications/crossbar/doc/user_authentication.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.prepend_cid.json
- applications/crossbar/priv/couchdb/schemas/list_entries.json
- applications/crossbar/priv/couchdb/schemas/system_config.callflow.dynamic_cid.json
- applications/crossbar/priv/oas3/oas3-schemas.yml
- applications/tasks/doc/compaction.md
- core/kazoo_documents/src/kzd_list_entries.erl
- core/kazoo_documents/src/kzd_list_entries.erl.src
Closes #6037 in favor of a broader update (thanks mentax007 for the
heads-up!)
> Update schema tables to reflect newer format

- make/deps.mk
amqp_dist handling of pid exit could bring node down
> update reference to amqp_dist

- applications/callflow/doc/group_pickup_feature.md
- applications/callflow/doc/ref/group_pickup_feature.md
- applications/callflow/src/module/cf_group_pickup_feature.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.group_pickup_feature.json
1. Add type is required for group_pickup_feature's callflow json
2. Change b_play to b_prompt
> [4.3] add type required for group_pickup_feature

- applications/callflow/doc/group_pickup_feature.md
- applications/callflow/doc/ref/group_pickup_feature.md
- applications/callflow/src/module/cf_group_pickup_feature.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.group_pickup_feature.json
- applications/crossbar/priv/oas3/oas3-schemas.yml
- core/kazoo_ast/src/cf_data_usage.erl
- core/kazoo_ast/src/kapi_schemas.erl
1. Add type is required for group_pickup_feature's callflow json
2. Change b_play to b_prompt
> [master] add type required for group_pickup_feature

- applications/crossbar/src/modules/cb_services.erl
Adds an optional parameter to the services available API which when true will include the full plan in the listing.
{{api_server}}/accounts/{{account_id}}/services/available?details=true
Master PR #6085
> KCRO-1 [4.3]: support a request parameter details on the available service plans

- applications/ecallmgr/src/ecallmgr_util.erl
- applications/ecallmgr/test/ecallmgr_config_tests.erl
- applications/ecallmgr/test/ecallmgr_util_tests.erl
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/docs/14b279cdaef7d55cff7235ba2a5010e9.json
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/docs/239d0734328f7043629d425ce7d93a4d.json
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/docs/2fee5aa5a89193f63822d09019dca1d7.json
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/docs/7145b996f7ee0d40b314114a9869b7fe.json
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/docs/account0000000000000000000010722.json
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/docs/e192d667e3abd732d802353b70c26248.json
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/view-index.csv
- core/kazoo_fixturedb/priv/dbs/account%2Fac%2Fco%2Funt0000000000000000000010722/views/attributes+owned-31995bc39d925bdbeb336ca10e9daa00.json
Build failover endpoint if endpoint is unregistered and failover is
present on the endpoint's bridge_endpoint record.
> HELP-10722: clarify when to build failover

- applications/callflow/src/module/cf_park.erl
* when parker answers the call and then hangs
the parked channel is not hangup
> wait for bridge after ringback parker

- applications/crossbar/doc/devices.md
- applications/crossbar/doc/ref/devices.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/devices.json
- applications/crossbar/priv/oas3/oas3-schemas.yml
Increase number of allowed digits in call forwarding to support international destinations better
> Increase number of allowed digits in call forwarding

- applications/ecallmgr/priv/mod_kazoo/events/spandsp-rxfaxresult.xml
- applications/ecallmgr/priv/mod_kazoo/events/spandsp-txfaxresult.xml
- applications/ecallmgr/src/call_control/ecallmgr_call_control.erl
- applications/ecallmgr/src/call_control/ecallmgr_call_control_listener_sup.erl
- applications/ecallmgr/src/ecallmgr_originate.erl
- applications/ecallmgr/src/node/ecallmgr_fs_node_command.erl
- applications/fax/src/fax_worker.erl
- applications/stepswitch/src/stepswitch_local_extension.erl
- applications/stepswitch/src/stepswitch_outbound.erl
* initialize consumer channel in call control
* fix logging in fax worker
> initialize consumer channel in call control

- applications/acdc/src/acdc_agent_stats.erl
Empty list of agent status stats is a valid response and should not be treated like an error (nor lead to HTTP 500s when making status API reqs)
> PISTON-949: respond positively for empty agents status payloads

- applications/ecallmgr/src/ecallmgr_fs_xml.erl
- core/kazoo/src/kz_util.erl
- core/kazoo/test/kz_util_tests.erl
- core/kazoo_ast/src/cb_api_endpoints.erl
- core/kazoo_csv/src/kz_csv.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_perf/src/kazoo_perf_maintenance.erl
- core/kazoo_stdlib/src/kz_term.erl
- core/kazoo_stdlib/test/kz_term_tests.erl
- core/sup/src/sup.erl
- scripts/kz_diaspora.bash
Start the remove the need for kz_util. Original PR was huge; breaking it up into smaller increments for easier review and merge.
> Move iolist_join to kz_term

- core/kazoo/src/kz_util.erl
- core/kazoo/test/kz_util_tests.erl
- core/kazoo_number_manager/src/knm_number_options.erl
- core/kazoo_stdlib/test/props_tests.erl
- scripts/kz_diaspora.bash
DRY change to a better implementation.
> move kz_util:uniq calls to props:unqiue

- core/kazoo_endpoint/src/kz_endpoint.erl
New funs flush only the node's local cache
> PISTON-955: add kz_endpoint:flush_account_local & flush_local

- applications/tasks/src/knm_number_crawler.erl
- core/kazoo_number_manager/doc/maintenance.md
- core/kazoo_number_manager/doc/ref/maintenance.md
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
* fix `kazoo_number_manager_maintenance:fix_apps_*` functions
* add commands to operate on a list of numbers
> [master] knm maintenance fixes

- applications/pusher/src/pusher_listener.erl
* decode registration parameters
> [4.3] url decode push parameters

- core/kazoo_services/src/kz_services.erl
> [4.3] expand summary to include other service sections

- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- applications/ecallmgr/src/freeswitch.erl
- core/kazoo_amqp/src/kz_amqp_util.erl
- core/kazoo_auth/src/kz_auth.erl
- make/kz.mk
Add some additional targets for the per-app Makefiles
> Per app targets

- applications/crossbar/src/modules/cb_apps_link.erl
- applications/crossbar/src/modules/cb_apps_store.erl
- applications/crossbar/src/modules/cb_clicktocall.erl
- applications/crossbar/src/modules/cb_ips.erl
- applications/crossbar/src/modules/cb_media.erl
- applications/crossbar/src/modules/cb_presence.erl
- applications/crossbar/src/modules/cb_rates.erl
- applications/crossbar/src/modules/cb_resources.erl
- applications/crossbar/src/modules/cb_schemas.erl
- applications/crossbar/src/modules/cb_user_auth.erl
- applications/crossbar/src/modules/cb_webhooks.erl
- applications/crossbar/src/modules/cb_whitelabel.erl
* to authenticate/authorize by module we need to export the proper arities
> add missing authenticate/authorize methods

- applications/tasks/src/kt_number_crawler.erl
- applications/tasks/src/kt_port_request_crawler.erl
- applications/tasks/src/modules/kt_compactor.erl
- applications/tasks/src/tasks.hrl
- applications/tasks/src/tasks_bindings.erl
- applications/tasks/src/tasks_sup.erl
* rename `knm_` task modules to `kt_`
* fix `include_lib` issue with `tasks_modules` in `tasks.hrl`
> some cleanup in tasks app

- applications/crossbar/src/modules/cb_notifications.erl
> [4.3] PISTON-979: fix migrating templates from system into accounts

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.sms.inbound.json
- applications/crossbar/priv/couchdb/schemas/kapi.sms.message.json
- applications/crossbar/priv/couchdb/schemas/kapi.sms.message_endpoint_headers.json
- applications/crossbar/priv/couchdb/schemas/kapi.sms.outbound.json
- core/kazoo_amqp/src/api/kapi_sms.erl
> kapi_sms on-net/off-net renamed to onnet/offnet

- applications/crossbar/src/api_util.erl
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_bindings.erl
allows modules to handle different types of payloads
> crossbar extensions

- core/sup/priv/sup
- rel/kazoo
make this work
`sup mymod myfun myarg "this is a binary" 'this is "also" a "binary"'`
> preserve the way args are passed to sup

- core/kazoo_stdlib/src/kz_term.erl
- core/kazoo_stdlib/test/kz_term_tests.erl
Old version: kz_term_tests:to_hex_str in 5.742178s
New version: kz_term_tests:to_hex_bin in 0.471149s
> Improve to_hex/1 performance

- core/kazoo_speech/src/asr_flat_rate.erl
- core/kazoo_speech/src/asr_request.erl
* If not service plan definition or rate is 0 skip ledger debit
* Fix case condition where errors weren't returning an asr_request
> [KZOO-33] - 4.3

- core/kazoo_speech/src/asr_flat_rate.erl
- core/kazoo_speech/src/asr_request.erl
* If not service plan definition or rate is 0 skip ledger debit
* Fix case condition where errors weren't returning an asr_request
> [KZOO-33] - master

- core/kazoo_stdlib/src/kz_json.erl
- core/kazoo_stdlib/test/kz_json_tests.erl
- deleting a key from an object
```
{ {"b" : {"b1" : 1, "b2": 2}
,{"z": {"z1": 1, "z2": 2}
}
deleting key z.z1 or z.z2 would move "z" to top (before "b")
```
- flatten_deep {"a" : {"b": [{"c1": 1, "c2": 2}]}}
```
flatten {[{["a","b"], [{"c1": 1, "c2": 2}]}]}
flatten_deep {[{["a","b", 1, "c1"], 1}
,["a","b", 1, "c2"], 2}
}]}
```
- diff_deep 
```
A1 = {"a" : {"b": [{"c1": 1, "c2": 2}]}}
A2 = {"a" : {"b": [{"c1": 1, "c2": 2, "c3": 3}]}}
diff(A2, A1) => {"a":{"b":[{"c1":1,"c2":2,"c3":3}]}}
diff_deep(A2, A1) => {"a":{"b":[{"c3":3}]}}
```
> preserve json KV order when deleting and deep versions of flatten, expand, diff

- applications/crossbar/src/modules/cb_alerts.erl
When deciding to how to show port alerts for reseller account, we should check and use **authenticated** account ID (as it was describ in the comments).
> [master] HELP-13256: show correct port alerts based on authenticated account id

- applications/teletype/priv/templates/voicemail_to_email.html
- applications/teletype/priv/templates/voicemail_to_email.text
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
master https://github.com/2600hz/kazoo/pull/6338
> HELP-13212: Exclude attachments from being included if present

- .gitignore
- Makefile
See https://github.com/erlang-ls/erlang_ls#customization for options
> Generate an Erlang LS config file

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.telemetry.json
- applications/crossbar/priv/couchdb/schemas/system_config.telemetry.waveguide.json
- applications/crossbar/priv/oas3/oas3-schemas.yml
- applications/ecallmgr/src/ecallmgr_app.erl
- applications/ecallmgr/src/node/ecallmgr_fs_node.erl
- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_apps/src/kazoo_apps.app.src
- core/kazoo_proper/src/pqc_cb_cdrs.erl
- core/kazoo_telemetry/LICENSE
- core/kazoo_telemetry/Makefile
- core/kazoo_telemetry/doc/README.md
- core/kazoo_telemetry/include/kazoo_telemetry.hrl
- core/kazoo_telemetry/include/waveguide.hrl
- core/kazoo_telemetry/src/extractors/kztm_database_extractor.erl
- core/kazoo_telemetry/src/extractors/kztm_nodes_extractor.erl
- core/kazoo_telemetry/src/extractors/kztm_services_extractor.erl
- core/kazoo_telemetry/src/gen_extractor.erl
- core/kazoo_telemetry/src/gen_reducer.erl
- core/kazoo_telemetry/src/kazoo_telemetry.app.src
- core/kazoo_telemetry/src/kazoo_telemetry_app.erl
- core/kazoo_telemetry/src/kazoo_telemetry_leader.erl
- core/kazoo_telemetry/src/kazoo_telemetry_sup.erl
- core/kazoo_telemetry/src/reducers/waveguide_reducer.erl
- core/kazoo_telemetry/src/responders/waveguide_responder.erl
- core/kazoo_telemetry/src/wg_httpc.erl
- core/kazoo_telemetry/src/wg_util.erl
- doc/announcements.md
- doc/mkdocs/mkdocs.yml
Adding telemetry capabilities, see the`doc/announcements.md` for details.
> [PROD-157] - Master

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.telemetry.json
- applications/crossbar/priv/couchdb/schemas/system_config.telemetry.waveguide.json
- applications/ecallmgr/src/ecallmgr_app.erl
- applications/ecallmgr/src/ecallmgr_fs_node.erl
- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_apps/src/kazoo_apps.app.src
- core/kazoo_globals/src/kz_nodes.erl
- core/kazoo_telemetry/.deps.rules
- core/kazoo_telemetry/.test.deps
- core/kazoo_telemetry/LICENSE
- core/kazoo_telemetry/Makefile
- core/kazoo_telemetry/doc/README.md
- core/kazoo_telemetry/include/kazoo_telemetry.hrl
- core/kazoo_telemetry/include/waveguide.hrl
- core/kazoo_telemetry/src/extractors/kztm_database_extractor.erl
- core/kazoo_telemetry/src/extractors/kztm_nodes_extractor.erl
- core/kazoo_telemetry/src/extractors/kztm_services_extractor.erl
- core/kazoo_telemetry/src/gen_extractor.erl
- core/kazoo_telemetry/src/gen_reducer.erl
- core/kazoo_telemetry/src/kazoo_telemetry.app.src
- core/kazoo_telemetry/src/kazoo_telemetry_app.erl
- core/kazoo_telemetry/src/kazoo_telemetry_leader.erl
- core/kazoo_telemetry/src/kazoo_telemetry_sup.erl
- core/kazoo_telemetry/src/reducers/waveguide_reducer.erl
- core/kazoo_telemetry/src/responders/waveguide_responder.erl
- core/kazoo_telemetry/src/wg_httpc.erl
- core/kazoo_telemetry/src/wg_util.erl
- doc/announcements.md
Adding telemetry capabilities, see the`doc/announcements.md` for details.
> [PROD-157] - 4.3

- applications/callflow/src/cf_util.erl
This makes it possible for a vmbox's `operator_number` to match callflow pattern regexes
> PISTON-1003: cf_util:get_operator_callflow now uses cf_flow:lookup

- applications/crossbar/doc/ref/vmboxes.md
- applications/crossbar/doc/voicemail.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/vmboxes.json
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/kazoo_documents/src/kzd_vmboxes.erl
- core/kazoo_documents/src/kzd_vmboxes.erl.src
Missing change for https://github.com/2600hz/kazoo/pull/6339
> [4.3] HELP-13212: Document vmboxes.include_message_on_notify field

- applications/crossbar/doc/ref/vmboxes.md
- applications/crossbar/doc/voicemail.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/vmboxes.json
- applications/crossbar/priv/oas3/oas3-schemas.yml
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/kazoo_documents/src/kzd_vmboxes.erl
- core/kazoo_documents/src/kzd_vmboxes.erl.src
Missing change for https://github.com/2600hz/kazoo/pull/6338
> HELP-13212: Document vmboxes.include_message_on_notify field

- applications/crossbar/src/crossbar.hrl
- applications/crossbar/src/crossbar_doc.erl
- core/kazoo_bindings/test/kazoo_bindings_tests.erl
- core/kazoo_number_manager/src/converters/knm_converter_regex.erl
- core/kazoo_stdlib/include/kazoo_dbg.hrl
- doc/engineering/testing.md
See doc/engineering/testing.md for usage and example
> [4.3] HELP-13697: add dbg macros for easier tracing

- core/kazoo_bindings/test/kazoo_bindings_tests.erl
- core/kazoo_numbers/src/converters/knm_converter_regex.erl
- core/kazoo_stdlib/include/kazoo_dbg.hrl
- doc/engineering/testing.md
See doc/engineering/testing.md for usage and example
> HELP-13697: add dbg macros for easier tracing

- applications/crossbar/doc/user_authentication.md
Corrections for markdown, changed string for MD5, changed requirements
Added SHA example
> Syntax Corrections

- applications/ecallmgr/src/ecallmgr_util.erl
[4.3](https://github.com/2600hz/kazoo/pull/6409)
> fix hold media path in get_fs_key_and_value

- applications/fax/src/fax_smtp.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_apps/src/kapps_util.erl
- core/kazoo_stdlib/src/kz_process.erl
* allows creation of smaller app releases
> core apps can depend on siblings except kazoo_apps

- applications/ecallmgr/src/ecallmgr_fs_event_stream.erl
- applications/ecallmgr/src/ecallmgr_fs_event_stream_sup.erl
- applications/ecallmgr/src/freeswitch.erl
* requires kazoo-freeswitch >= 4.3.15
> simplified bindings - 4.3

- applications/crossbar/priv/api/swagger.json
- core/kazoo_stdlib/src/kz_time.erl
- make/deps.mk
4.3 version was merged as an emergency fix
> accept binary or string for Timezone

- core/kazoo_apps/doc/kapps_config_maintenance.md
- core/kazoo_apps/doc/ref/kapps_config_maintenance.md
- core/kazoo_apps/src/kapps_config.erl
- core/kazoo_apps/src/kapps_config_maintenance.erl
- core/kazoo_data/doc/ref/maintenance.md
- core/kazoo_data/src/kazoo_data_maintenance.erl
- doc/mkdocs/mkdocs.yml
Optional _pp suffix if you want the returned term pretty-printed.
> Add maintenance module for kapps_config interactions

- core/kazoo_call/src/kapps_conference.erl
> lower case the conference language - 4.3

- applications/crossbar/doc/ledgers.md
Added a note explaining the intended purpose of the source.id field
> Adding some info to the ledgers documentation

- applications/ecallmgr/src/ecallmgr_fs_conferences.erl
* if the conference is initiated directly
in freeswitch, we need to assign a node
so that conference events are emitted
> determine conference-control-node - 4.3

- applications/stepswitch/src/stepswitch_resources.erl
* these were already allowed in the schema but were not sent
> add gateway ccvs - 4.3

- applications/stepswitch/src/stepswitch_resources.erl
* these were already allowed in the schema but were not sent
> add gateway ccvs

- applications/ecallmgr/src/ecallmgr_fs_acls.erl
- core/kazoo_stdlib/src/kz_network_utils.erl
allow the cidr to be a dns name instead of IPs
> resolve system-acls IPs - 4.3

- applications/ecallmgr/src/ecallmgr_fs_acls.erl
- core/kazoo_stdlib/src/kz_network_utils.erl
allow the cidr to be a dns name instead of IPs
> resolve system-acls IPs

- core/kazoo_stdlib/src/kz_json.erl
since we're not using decode/2 (`application/json`)
take it and change it to options that can be passed
to decoder
> allow json decode options

- core/kazoo_csv/src/kz_csv.erl
🤦 
Fixing spelling mistakes from previous pr. Sorry!
> Fixed spelling

- applications/crossbar/doc/webhooks.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.milliwatt.json
- applications/crossbar/priv/oas3/oas3-schemas.yml
- applications/jonny5/src/j5_authz_req.erl
- applications/milliwatt/doc/README.md
- applications/milliwatt/src/milliwatt.hrl
- applications/milliwatt/src/milliwatt_echo.erl
- applications/milliwatt/src/milliwatt_listener.erl
- applications/milliwatt/src/milliwatt_route_req.erl
- applications/milliwatt/src/milliwatt_tone.erl
- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_apps/src/kapps_notify_publisher.erl
- core/kazoo_ast/src/kapps_config_usage.erl
- core/kazoo_proper/src/pqc_j5_channels.erl
Cleanup module usage, update schema and docs for getting started with
Milliwatt.
> Refresh Milliwatt a bit

- scripts/validate-js.py
Adding 1 to `replace` function so the we add name to the first occurrence
function.
> fix adding name function name during view validation

- Makefile
- make/apps.mk
- make/more_apps.mk.default
- scripts/tags.escript
Bootstrap more_apps.mk with kazoo_proper and kazoo_ast so CI-related targets work as well
> generate tags only if kazoo_ast is found

- core/kazoo_number_manager/src/carriers/knm_didww.erl
- core/kazoo_number_manager/src/carriers/knm_flowroute.erl
- core/kazoo_number_manager/src/carriers/knm_inteliquent.erl
- core/kazoo_number_manager/src/carriers/knm_it_vocal.erl
- core/kazoo_number_manager/src/carriers/knm_level3.erl
- core/kazoo_number_manager/src/carriers/knm_o1.erl
- core/kazoo_number_manager/src/carriers/knm_peerless.erl
- core/kazoo_number_manager/src/carriers/knm_thinq.erl
- core/kazoo_number_manager/src/carriers/knm_verizon.erl
- core/kazoo_number_manager/src/carriers/knm_windstream.erl
- core/kazoo_number_manager/src/carriers/knm_ziron.erl
Master https://github.com/2600hz/kazoo-core/pull/1
> [4.3] HELP-14474: Mimic knm_other:disconnect_number/1 on placeholder carrier modules

- .circleci/config.yml
- Makefile
- make/ci.mk
- make/fmt.mk
- make/kz.mk
- scripts/README.md
- scripts/check-changed.bash
- scripts/check-git-status.bash
- scripts/check-unstaged.bash
- build plt via target not filename
- calculate changed files
- diff against base branch
- detect repos' base branches
- init with root repo's .base_branch
- use calculated changes
- use $CHANGED to check for unstaged
- check all repos for changes/status
> More breakening-related updates

- .gitignore
- make/apps.mk
* update `.gitignore` in all repos
* add `.base_branch`
> update gitignore and some other fixes

- applications/teletype/src/teletype_util.erl
Per SMTP spec bare line feed (LF) are forbidden and
CRLF should be used instead. Some SMTP relays and server in both ends
are nice enough to correct bad line ending, but some don't.
Like in one case relay server is Office 365 and receiving end is AOL.com.
Office 365 stopped correcting line endings and AOL is not fixing it either.
This cause the email to bounce back with Non-Delivery Report (NDR) message.
From [here](https://www.drupal.org/forum/support/post-installation/2017-06-05/office-365-blocks-emails-with-bare-line-feeds-how-to-fix):
When bare line feed characters are included in a message, the SMTP protocol
chunking feature is required to transmit the message between email servers.
Chunking uses the SMTP protocol BDAT command, but the recipient's email
server (in our case AOL) …
> HELP-14590: replacing LF with CRLF before sending emails

- applications/teletype/src/templates/teletype_fax_outbound_smtp_error_to_email.erl
- applications/teletype/src/templates/teletype_missed_call.erl
- applications/teletype/src/templates/teletype_port_request_admin.erl
- applications/teletype/src/templates/teletype_service_added.erl
- applications/teletype/src/templates/teletype_system_alert.erl
- applications/teletype/src/templates/teletype_voicemail_deleted.erl
Master: https://github.com/2600hz/kazoo-teletype/pull/8
> Update teletype available macros list

- applications/callflow/src/module/cf_voicemail.erl
Before this change the process would crash with reason `function clause`.
Master: https://github.com/2600hz/kazoo-callflow/pull/7
> HELP-15581: Log when not config menu option was selected after 3 tries

- applications/callflow/src/cf_route_win.erl
Do not normalize number if there is no dialplan or number is not from capture group when callflow wins the call.
Normalizing twice may result the number to be classified differently so call won't be restricted.
> [4.3] SUPP-22: do not normalize number if there is no dialplan or capture group

- applications/crossbar/src/modules/cb_accounts.erl
It is not clear what is the difference between `/accounts/:id/parents` and
`/accounts/:id/tree`. But the are doing same thing in different ways.
As it turns out `load_parents` is loading all result of `accounts/listing_by_id`
and then uses `kz_json:find_value/3` to grab the parent's account info.
But it is constantly failing in a specific server. I can't reproduce the exact
problem in any environment that I test it.
For example it should return:
```json
[{"id":"{ACCOUNT_1}","name":"{ACCOUNT1_NAME}"},{"id":"{ACCOUNT_2}","name":"{ACCOUNT2_NAME}"}]
```
But it returns instead:
```json
[{"id":"{ACCOUNT_1}","name":"{ACCOUNT1_NAME}"},{}]
```
Since those `/tree` and `/parents` seems returning same thing
and `/tree` implementation is way more efficient and stable than `/parents`
I change it to use …
> [4.3] SUPP-16: load_parents sets an empty object for account

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/doc/ref/phone_numbers.md
- applications/crossbar/doc/ref/resources.md
- applications/crossbar/doc/resources.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/kapi.notifications.emergency_bridge.json
- applications/crossbar/priv/couchdb/schemas/phone_numbers.json
- applications/crossbar/priv/couchdb/schemas/resources.json
- applications/crossbar/src/modules/cb_notifications.erl
- applications/stepswitch/doc/emergency.md
- applications/stepswitch/doc/rules.md
- applications/stepswitch/src/stepswitch_bridge.erl
- applications/stepswitch/src/stepswitch_resources.erl
- applications/teletype/doc/README.md
- applications/teletype/priv/templates/emergency_bridge.html
- applications/teletype/priv/templates/emergency_bridge.text
- applications/teletype/src/templates/teletype_emergency_bridge.erl
- applications/teletype/test/teletype_render_tests.erl
- core/kazoo_amqp/src/api/kapi_dialplan.erl
- core/kazoo_amqp/src/api/kapi_notifications.erl
- core/kazoo_amqp/src/api/kz_api.erl
- core/kazoo_apps/src/kz_amqp_worker.erl
- core/kazoo_call/src/kz_call_response.erl
- core/kazoo_documents/src/kzd_phone_numbers.erl
- core/kazoo_documents/src/kzd_phone_numbers.erl.src
- core/kazoo_documents/src/kzd_resources.erl
- core/kazoo_documents/src/kzd_resources.erl.src
- core/kazoo_number_manager/src/providers/knm_dash_e911.erl
- core/kazoo_number_manager/src/providers/knm_vitelity_e911.erl
- doc/mkdocs/mkdocs.yml
Main PR with more information can be found here https://github.com/2600hz/kazoo/pull/6443
> KZOO-46: Back port emergency calls email notification

- core/kazoo_attachments/src/kz_att_ftp.erl
- core/kazoo_schemas/src/kz_json_schema_extensions.erl
added ftps url support.
e.g. ftps://username:password@domain:port
username, password and port being compulsory for ftps support.
> [4.3] ftps support

- core/kazoo_stdlib/src/kz_json.erl
Dialyzer hard highlighted this issue
Kazoo 5 PR - https://github.com/2600hz/kazoo-core/pull/113
> Fix incorrect spec for kz_json:filter/3

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.speech.ibm.json
- core/kazoo_speech/src/asr/kazoo_asr_ibm.erl
https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-output#smart_formatting
Smart formatting remove hesitation as well as formats text more elegantly.
> [4.3] KZOO-103: add smart formatting to remove hesitations

- applications/stepswitch/src/stepswitch_bridge.erl
When e911 call is made from number different than number which has e911 active, make sure to resolve proper address and info. Also make sure to not try to send emails for e911 calls made using local carrier as we only care about numbers which have e911 activated and have email address setup for that.
> [4.3] KZOO-96: Resolve emergency email num resolve correct caller id number to get proper address

- core/kazoo_documents/src/kzd_module_utils.erl
Kazoo 5.x pr https://github.com/2600hz/kazoo-core/pull/211
> PISTON-1086:Fixed incorrectly formatted kazoo_document validation system error responses

- applications/crossbar/src/cb_context.erl
- core/kazoo_proper/src/pqc_cb_users.erl
Test creating a document with ID on the request data.
> [4.3] FORUM-11759: Check for ID on req data

- applications/acdc/src/acdc_agent_listener.erl
- applications/acdc/src/acdc_recordings_map_srv.erl
- applications/acdc/src/acdc_recordings_sup.erl
- applications/acdc/src/acdc_sup.erl
- prevent multiple overlapping recordings if caller re-enters a queue
> [4.3] PISTON-221: only record in ACDc once per call

- doc/appexchange/intro.md
- doc/mkdocs/commercial.yml
... plus a couple tiny changes to the mkdocs yml
> removed excess docs and added redirect to new marketplace portal

- doc/mkdocs/commercial.md
- doc/mkdocs/commercial.yml
and also addressing a couple broken nav items by giving them explicit titles
> commercial.md landing page links updated to use relative paths
