- applications/crossbar/Makefile
- applications/crossbar/src/crossbar_types.hrl
- applications/crossbar/src/modules/cb_modules_util.erl
- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/src/teletype.hrl
- applications/teletype/src/templates/teletype_voicemail_full.erl
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/kazoo_documents-1.0.0/src/kz_notification.erl
Cleans up migrating notification templates from master account to sub account when overriding templates.
> Kazoo 3211

- applications/callflow/src/module/cf_pivot.erl
- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- core/kazoo_translator-1.0.0/Makefile
- core/kazoo_translator-1.0.0/src/convertors/kzt_twiml.erl
- core/kazoo_translator-1.0.0/src/convertors/kzt_twiml_dial.erl
- core/kazoo_translator-1.0.0/src/convertors/kzt_twiml_say.erl
- core/kazoo_translator-1.0.0/src/convertors/kzt_twiml_util.erl
- core/kazoo_translator-1.0.0/src/kazoo_translator_app.erl
- core/kazoo_translator-1.0.0/src/kzt_receiver.erl
- core/kazoo_translator-1.0.0/src/kzt_util.erl
- core/whistle-1.0.0/include/wh_api.hrl
- core/whistle-1.0.0/include/wh_types.hrl
- core/whistle-1.0.0/src/props.erl
- core/whistle-1.0.0/src/wh_api.erl
- core/whistle_amqp-1.0.0/src/wh_amqp_worker.erl
twiml handling updates for dial/tts
> Kazoo 2809

- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/priv/couchdb/account/vmboxes.json
- applications/crossbar/priv/couchdb/schemas/notifications.json
- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_notifications.erl
- applications/fax/src/fax_request.erl
- applications/teletype/Makefile
- applications/teletype/src/teletype.hrl
- applications/teletype/src/teletype_renderer.erl
- applications/teletype/src/teletype_shared_listener.erl
- applications/teletype/src/teletype_tests.erl
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_fax_inbound_to_email.erl
- applications/teletype/src/templates/teletype_fax_util.erl
- applications/teletype/src/templates/teletype_template_skel.erl
- applications/teletype/src/templates/teletype_voicemail_full.erl
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/kazoo_bindings-1.0.0/src/kazoo_bindings.erl
- core/whistle-1.0.0/src/api/wapi_notifications.erl
- core/whistle_config-1.0.0/src/whapps_config.erl
- core/whistle_couch-1.0.0/src/couch_compactor_fsm.erl
- core/whistle_couch-1.0.0/src/couch_util.erl
- core/whistle_couch-1.0.0/src/wh_couch_connections.erl
- core/whistle_couch-1.0.0/src/wh_doc.erl
- deps/erlydtl-0.9.4/Makefile
> Kazoo 3089

- applications/registrar/Makefile
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/Makefile
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/Makefile.old
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/README
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/c_src/eiconv_nif.c
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/rebar.config
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/src/eiconv.app.src
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/src/eiconv.erl
- deps/eiconv-644fb5e7bd6640fbd073f4d28957914ea979aea0/src/iconv.erl
- deps/lager_syslog-1.2.2/Makefile
> Kazoo 3228

- applications/crossbar/src/crossbar_maintenance.erl
> Kazoo 3001

- applications/fax/src/fax_maintenance.erl
- core/whistle-1.0.0/src/props.erl
- core/whistle_couch-1.0.0/src/couch_util.erl
please backport to 3.16 and  later
> KAZOO-3301 override_existing_document in copy_doc/move_doc

- applications/callflow/src/cf_endpoint.erl
preparing cf_endpoint for failover push endpoints.
> KAZOO-3302 pusher

- core/whistle_number_manager-1.0.0/src/carriers/wnm_simwood.erl
Hi
Module searches for UK numbers, allocates/deallocates single number.
Regards,
Kirill
> KAZOO-3306 - simwood.com carrier module

- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/modules/cb_search.erl
- core/whistle-1.0.0/src/wh_json.erl
- core/whistle-1.0.0/src/wh_json.hrl
1) fix pagination for 3 part key. 
2) handle authorization
> KAZOO-3314

- core/whistle_number_manager-1.0.0/src/wnm_number.erl
> Revert "Kazoo 3251"

- applications/ecallmgr/src/ecallmgr_fs_event_stream.erl
do not impact a call on another server with the same Call-ID
Drop the CHANNEL_DESTROY message before it kills the working server
(when the message comes from the non-working server).
> KAZOO-3283: make so that channels that are destroyed on one media server

- applications/callflow/src/module/cf_menu.erl
- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_apps_store.erl
- applications/crossbar/src/modules/cb_faxes.erl
- applications/crossbar/src/modules/cb_global_provisioner_templates.erl
- applications/crossbar/src/modules/cb_local_provisioner_templates.erl
- applications/crossbar/src/modules/cb_media.erl
- applications/crossbar/src/modules/cb_notifications.erl
- applications/crossbar/src/modules/cb_port_requests.erl
- applications/crossbar/src/modules/cb_templates.erl
- applications/crossbar/src/modules/cb_vmboxes.erl
- applications/crossbar/src/modules/cb_whitelabel.erl
- applications/fax/src/fax_maintenance.erl
- applications/fax/src/fax_worker.erl
- applications/notify/src/notify_fax_util.erl
- applications/notify/src/notify_port_request.erl
- applications/notify/src/notify_voicemail_to_email.erl
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/whistle_apps-1.0.0/src/whapps_maintenance.erl
- core/whistle_couch-1.0.0/src/couch_util.erl
- core/whistle_couch-1.0.0/src/wh_doc.erl
- core/whistle_media-1.0.0/src/wh_media_doc.erl
- core/whistle_media-1.0.0/src/wh_media_file.erl
- core/whistle_media-1.0.0/src/wh_media_file_cache.erl
- core/whistle_media-1.0.0/src/whistle_media_maintenance.erl
- core/whistle_number_manager-1.0.0/src/wh_number_manager.erl
- core/whistle_number_manager-1.0.0/src/wh_port_request.erl
standardize on wh_doc:attachment* functions
> attachment-cleanup: remove refs to _attachments

- core/whistle_services-1.0.0/src/wh_services.erl
Add a check in wh_services:calculate_transactions_charge_fold/2
that discards a transaction charging for $0
> KAZOO-3354: Don't require payment when charges are zero

- applications/ecallmgr/src/ecallmgr_fs_channels.erl
handle query_user_channels for call-park by looking into destination with empty leg.
> KAZOO-3308 query call-park

- applications/callflow/Makefile
- applications/callflow/src/callflow.hrl
- applications/callflow/src/wapi_callflow.erl
- applications/crossbar/doc/webhooks.md
- applications/crossbar/priv/couchdb/account/webhooks.json
- applications/crossbar/priv/couchdb/schemas/webhooks.json
- applications/crossbar/priv/couchdb/views/webhooks.json
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_cdrs.erl
- applications/crossbar/src/modules/cb_webhooks.erl
- applications/webhooks/Makefile
- applications/webhooks/doc/maintenance.md
- applications/webhooks/src/webhooks.hrl
- applications/webhooks/src/webhooks_listener.erl
- applications/webhooks/src/webhooks_maintenance.erl
- applications/webhooks/src/webhooks_sup.erl
- applications/webhooks/src/webhooks_util.erl
- core/kazoo_modb-1.0.0/priv/couchdb/views/webhooks.json
- core/whistle-1.0.0/src/wh_cache.erl
- core/whistle-1.0.0/src/wh_json.erl
- core/whistle-1.0.0/src/wh_json.hrl
Adds more ops tools, auto-disable failing hooks, better pagination support, and PATCH.
> Kazoo 2570: webhooks for all!

- applications/omnipresence/src/omnip_dialog.erl
- applications/omnipresence/src/omnip_message_summary.erl
- applications/omnipresence/src/omnip_presence.erl
- applications/omnipresence/src/omnip_util.erl
> KAZOO-3383 bad uri issue in omnipresence

- applications/jonny5/src/j5_allotments.erl
You must use "endkey" for correct filtering data.
Example.
Allotments table have this data:
{"id":"1","key":["class_a",1000],"value":9},
{"id":"2","key":["class_a",1001],"value":18},
{"id":"3","key":["class_b",1010],"value":25},
{"id":"3","key":["class_b",1015],"value":385},
{"id":"4","key":["class_a",1030],"value":113},
{"id":"5","key":["class_a",1031],"value":7},
{"id":"6","key":["class_b",1050],"value":39}
using only startkey=["class_a",1020]  return: 
{"id":"4","key":["class_a",1030],"value":113},
{"id":"5","key":["class_a",1031],"value":7},
{"id":"6","key":["class_b",1050],"value":39}
using startkey=["class_a",1020]  and endkey=["class_a",1070] return
{"id":"4","key":["class_a",1030],"value":113},
{"id":"5","key":["class_a",1031],"value":7}
> Fix: Filtering consumed allotmens may return wrong data

- applications/crossbar/priv/couchdb/account/access_lists.json
If this method is not good enough, can you suggest something?
> Siplabs kazoo 3355

- applications/doodle/doc/configuration.md
- applications/doodle/src/doodle.hrl
- applications/doodle/src/doodle_inbound_listener.erl
- applications/doodle/src/doodle_inbound_listener_sup.erl
- applications/doodle/src/doodle_sup.erl
created supervisor multiple inbound connections
> KAZOO-3407 support multiple connection for doodle listener

- applications/crossbar/priv/couchdb/views/rates.json
Hi
Added prefix and description fields in order rates list looks a bit more informative
Regards,
> KAZOO-3417: Update rates.json

- applications/omnipresence/src/omnip_dialog.erl
- applications/omnipresence/src/omnip_presence.erl
- applications/omnipresence/src/omnip_subscriptions.erl
- applications/omnipresence/src/omnipresence.hrl
- applications/omnipresence/src/wapi_omnipresence.erl
- core/whistle-1.0.0/include/wh_types.hrl
KAZOO-3416 add kazoo-id to dialog target uri
KAZOO-3416 add helper function set_presence_state in omnip_presence
> KAZOO-3416 update only relevant information on subscriptions

- applications/crossbar/src/modules/provisioner_v5.erl
When timezone & realm are set on an account don't also push these fields
to the devices belonging to the account.
Provisioner handles hierarchical fetches itself.
> KAZOO-3364: do not bypass provisioner's data hierarchy

- applications/crossbar/src/crossbar_maintenance.erl
Changes this
```
0 wef monster-modules # sup crossbar_maintenance init_apps /var/www/html/monster-modules/provisioner 'http://localhost:8000/v2'
trying to init app from /var/www/html/monster-modules/provisioner/.git
failed to incorporate app because there was no app.json in /var/www/html/monster-modules/provisioner/.git/metadata
trying to init app from /var/www/html/monster-modules/provisioner/README.md
failed to find metadata in /var/www/html/monster-modules/provisioner/README.md: {badmatch,
{error,
enotdir}}
trying to init app from /var/www/html/monster-modules/provisioner/metadata
saved app provisioner as doc 291ca86a02016dd7f3fca857478c1979
saved Provisioning_app.png to 291ca86a02016dd7f3fca857478c1979
trying to init app from /var/www/html/monster-modules/provisioner/app.js
failed to …
```
> Do not fail on simple path cases when using init_apps/2 in maintenance

- applications/crossbar/src/modules_v1/cb_devices_v1.erl
- applications/crossbar/src/modules_v2/cb_devices_v2.erl
> KAZOO-3386: call the right util module

- applications/crossbar/priv/couchdb/schemas/provisioner_v5.json
- applications/crossbar/src/modules/provisioner_util.erl
- applications/crossbar/src/modules/provisioner_v5.erl
* Fix provisioner_v5 schema validation (now data actually validates)
* Upadte provisioner_v5 API to follow the new provisioner's
* A lot of smaller stuff
> KAZOO-3367: properly handle and send updated user data to provisioner

- applications/callflow/src/cf_exe.erl
Does not add extra flow to Flows the way branching does.
> Functionality of dynamically updating the callflow, like branching.

- applications/crossbar/src/modules/cb_port_requests.erl
> refactor code handling number validation error

- applications/crossbar/src/modules/cb_faxes.erl
- applications/crossbar/src/modules/cb_modules_util.erl
- applications/fax/src/fax_smtp.erl
- applications/fax/src/fax_util.erl
- core/kazoo_modb-1.0.0/priv/couchdb/views/faxes.json
log smtp errors
create system_alert
create crossbar faxes/smtplog handler
moved get_incoming_view_options to cb_modules_utl:range_modb_view_options
> KAZOO-3487 fax smtp

- applications/callflow/src/module/cf_record_call.erl
- applications/ecallmgr/Makefile
- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_call_events.erl
- core/kazoo_documents-1.0.0/Makefile
- core/kazoo_documents-1.0.0/include/kazoo_documents.hrl
- core/kazoo_documents-1.0.0/src/kz_documents.hrl
- core/kazoo_documents-1.0.0/src/kzd_freeswitch.erl
- core/whistle_apps-1.0.0/src/whapps_call_command.erl
- core/whistle_media-1.0.0/src/wh_media_recording.erl
Start timers in gen_listener when starting recording.
> Kazoo 3423

- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/src/teletype_shared_listener.erl
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_cnam_request.erl
- applications/teletype/src/templates/teletype_deregister.erl
- applications/teletype/src/templates/teletype_fax_inbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_inbound_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_to_email.erl
- applications/teletype/src/templates/teletype_low_balance.erl
- applications/teletype/src/templates/teletype_new_account.erl
- applications/teletype/src/templates/teletype_new_user.erl
- applications/teletype/src/templates/teletype_password_recovery.erl
- applications/teletype/src/templates/teletype_port_cancel.erl
- applications/teletype/src/templates/teletype_port_comment.erl
- applications/teletype/src/templates/teletype_port_pending.erl
- applications/teletype/src/templates/teletype_port_request.erl
- applications/teletype/src/templates/teletype_port_scheduled.erl
- applications/teletype/src/templates/teletype_ported.erl
- applications/teletype/src/templates/teletype_system_alert.erl
- applications/teletype/src/templates/teletype_template_skel.erl
- applications/teletype/src/templates/teletype_topup.erl
- applications/teletype/src/templates/teletype_transaction.erl
- applications/teletype/src/templates/teletype_voicemail_full.erl
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
> KAZOO-3490: only send template preview when enabled

- core/kazoo_modb-1.0.0/src/kazoo_modb.erl
- core/kazoo_modb-1.0.0/src/kazoo_modb_maintenance.erl
- core/whistle_couch-1.0.0/src/couch_util.erl
- core/whistle_couch-1.0.0/src/whistle_couch_maintenance.erl
Found this branch during cleanup, seems like a good idea ;)
> Kazoo 2617

- applications/callflow/src/cf_attributes.erl
- applications/cccp/src/cccp_util.erl
- applications/crossbar/src/api_util.erl
- applications/crossbar/src/modules/cb_port_requests.erl
- applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- applications/stepswitch/src/stepswitch_bridge.erl
- applications/stepswitch/src/stepswitch_sms.erl
- applications/trunkstore/Makefile
- applications/trunkstore/src/ts.hrl
- applications/trunkstore/src/ts_util.erl
- core/whistle_number_manager-1.0.0/include/wh_number_manager.hrl
- core/whistle_number_manager-1.0.0/src/carriers/wnm_other.erl
- core/whistle_number_manager-1.0.0/src/providers/wnm_dash_e911.erl
- core/whistle_number_manager-1.0.0/src/providers/wnm_vitelity_e911.erl
- core/whistle_number_manager-1.0.0/src/wh_number_fix.erl
- core/whistle_number_manager-1.0.0/src/wnm_number.erl
- core/whistle_number_manager-1.0.0/src/wnm_util.erl
- core/whistle_services-1.0.0/src/services/wh_service_phone_numbers.erl
> Kazoo 3438

- applications/callflow/src/cf_shared_listener.erl
- applications/crossbar/doc/devices.md
- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/api_util.erl
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/modules/provisioner_v5.erl
- applications/crossbar/src/modules_v2/cb_devices_v2.erl
- applications/ecallmgr/src/ecallmgr_fs_notify.erl
- core/kazoo_documents-1.0.0/src/kz_device.erl
- core/whistle-1.0.0/src/api/wapi_presence.erl
- core/whistle-1.0.0/src/api/wapi_switch.erl
Sends check_sync AMQP payload when device is updated in provisioner.
Exposes API at `/devices/{DEVICE_ID}/sync` to send the check_sync via Crossbar.
> Kazoo 3514 and Kazoo 3515

- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules/cb_connectivity.erl
- applications/crossbar/src/modules/cb_faxes.erl
- applications/crossbar/src/modules/cb_ip_auth.erl
- applications/crossbar/src/modules/cb_media.erl
- applications/crossbar/src/modules/cb_pivot.erl
- applications/crossbar/src/modules/cb_queues.erl
- applications/crossbar/src/modules/cb_service_plans.erl
- applications/crossbar/src/modules/cb_whitelabel.erl
KAZOO-3550 do not force 'include_docs' when there is a normalize function
> KAZOO-3550 do not force 'include_docs' 

- applications/callflow/src/cf_endpoint.erl
- applications/crossbar/priv/couchdb/schemas/sms.json
- applications/doodle/priv/couchdb/reschedule.json
- applications/doodle/src/doodle.erl
- applications/doodle/src/doodle.hrl
- applications/doodle/src/doodle_inbound_listener.erl
- applications/doodle/src/doodle_inbound_listener_sup.erl
- applications/doodle/src/doodle_maintenance.erl
- applications/doodle/src/doodle_util.erl
- applications/doodle/src/module/cf_sms_device.erl
- applications/doodle/src/module/cf_sms_user.erl
- applications/stepswitch/src/stepswitch.hrl
- applications/stepswitch/src/stepswitch_resources.erl
- applications/stepswitch/src/stepswitch_sms.erl
- core/kazoo_modb-1.0.0/priv/couchdb/views/sms.json
- core/whistle-1.0.0/include/wh_amqp.hrl
- core/whistle-1.0.0/src/api/wapi_sms.erl
- core/whistle-1.0.0/src/gen_listener.erl
- core/whistle_amqp-1.0.0/src/amqp_util.erl
- core/whistle_amqp-1.0.0/src/wh_amqp_assignments.erl
- core/whistle_amqp-1.0.0/src/wh_amqp_channel.erl
- core/whistle_amqp-1.0.0/src/wh_amqp_connections.erl
- core/whistle_amqp-1.0.0/src/wh_amqp_sup.erl
- core/whistle_amqp-1.0.0/src/wh_amqp_worker.erl
- core/whistle_apps-1.0.0/src/whapps_sms_command.erl
- core/whistle_apps-1.0.0/src/whapps_sms_command.hrl
amqp failover for on-net devices , amqp server ack, fixes
> KAZOO-3560

- applications/callflow/src/module/cf_menu.erl
With this patch we can create menus like:
"Press 1 for ...
Press 2 for ...
**Or wait to connect with operator**"
> Allow to use <<"timeout">> as menu item

- applications/fax/src/fax_smtp.erl
KAZOO-3590 return permanent error
> KAZOO-3591 log no attachments

- Makefile
- scripts/check-xref.escript
Adds a filtering capability, and fancier output.
> Enhance xref

- .travis.yml
- Makefile
- applications/crossbar/test/cb_ubiquiti_util_test.erl
- core/kazoo_bindings-1.0.0/test/kazoo_bindings_test.erl
- core/kazoo_token_buckets-1.0.0/test/kz_token_bucket_pqc.erl
- core/whistle-1.0.0/test/wh_json_test.erl
- core/whistle-1.0.0/test/wh_util_test.erl
- core/whistle_number_manager-1.0.0/test/wnm_util_test.erl
- scripts/check-xref.escript
**Depends on #1001**
Before merging we need to sort out these last errors:
```
Xref: undefined_function_calls
blackhole_sup:start_link,,,,,,,,,,,,,,,,,,,,/0                calls undefined                         cowboy:start_http/4
crossbar:maybe_start_plaintext,,,,,,,,,/1                calls undefined                         cowboy:start_http/4
crossbar:start_ssl,,,,,,,,,,,,,,,,,,,,,/1                calls undefined                         cowboy:start_https/4
ecallmgr_fs_conferen:send_conference_event,,,,,,,,,/3                calls undefined                wapi_conference:publish_conference_event/2
fax:start_link,,,,,,,,,,,,,,,,,,,,/0                calls undefined                         cowboy:start_http/4
gcm_api:retry_after_from,,,,,,,,,,,,,,/1                calls undefined …
```
> Xref travis

- applications/teletype/src/templates/teletype_fax_inbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_outbound_error_to_email.erl
- applications/teletype/src/templates/teletype_fax_util.erl
don't assume there is a doc
no need for owner doc
don't assume there is a attachment
error macros used in default template
> teletype fixes for fax errors

- applications/stepswitch/src/stepswitch_resources.erl
- core/whistle_number_manager-1.0.0/src/wnm_util.erl
allow classifiers by account/reseller/global
> use customized regex from carriers app

- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_connectivity.erl
- applications/crossbar/src/modules_v2/cb_devices_v2.erl
- applications/crossbar/test/crossbar_util_test.erl
- applications/teletype/src/templates/teletype_low_balance.erl
- applications/teletype/src/templates/teletype_topup.erl
Flushes XML config as well as caches on update/delete to trunkstore docs
> Kazoo 3577

- applications/crossbar/doc/transactions.md
- applications/crossbar/src/modules/cb_braintree.erl
- applications/crossbar/src/modules/cb_transactions.erl
- applications/teletype/src/templates/teletype_low_balance.erl
- applications/teletype/src/templates/teletype_topup.erl
- core/whistle_transactions-1.0.0/src/wht_util.erl
As a User, I'd like to be able to lower per-minute credit amount (ie. from $10 to $5), so that I can manage sub accounts per-minute credit balances.
> Kazoo 3572

- applications/callflow/src/cf_task.erl
- applications/callflow/src/cf_util.erl
- applications/callflow/src/module/cf_voicemail.erl
- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_system_alert.erl
- core/whistle-1.0.0/src/api/wapi_dialplan.hrl
- core/whistle_apps-1.0.0/src/whapps_call_command.erl
- core/whistle_services-1.0.0/src/wh_services.erl
also some improvements in teletype system template and html smtp encoding
> KAZOO-3324 voicemail slow response

- core/whistle_media-1.0.0/src/wh_media_recording.erl
wh_media_recording shutdowns after sending record_start command.
> Record dont store to third_party

- applications/acdc/src/acdc_agent_fsm.erl
- applications/callflow/src/cf_endpoint.erl
- applications/spyvsspy/src/spyvsspy_handlers.erl
if accepted, please backport to 3.20
> KAZOO-3662 ACDC

- core/whistle_config-1.0.0/src/whapps_config.erl
- core/whistle_couch-1.0.0/src/couch_util.erl
format more errors in couch_util
> KAZOO-3551: add some more logging to whapps_config

- applications/stepswitch/doc/rules.md
Spent an hour trying to understand why cid_rules don't work... :)))
> small typo fix

- applications/stepswitch/src/stepswitch_listener.erl
- core/whistle_couch-1.0.0/src/couch_util.erl
publish fields to wapi_conf
removed changed_handler in stepswitch
> HELP - document type not published to wapi_conf

- applications/trunkstore/src/trunkstore_sup.erl
This problem like in https://github.com/2600hz/kazoo/pull/1059
> Incorrect bindings

- .gitignore
- .travis.yml
- Makefile
- doc/engineering/dialyzer.md
- scripts/check-dialyzer.escript
**Merge only when #1053 #1057 are.**
> Travis dialyzer

- applications/ecallmgr/src/ecallmgr_fs_node.erl
- core/whistle-1.0.0/src/wh_nodes.erl
also fixes the media servers printing
> KAZOO-3851 add interface info for media servers in wh_nodes

- scripts/check-dialyzer.escript
> KAZOO-3854: do not Dialyze test files

- applications/ecallmgr/src/ecallmgr_registrar.erl
- core/whistle-1.0.0/include/wh_amqp.hrl
- core/whistle-1.0.0/src/api/wapi_registration.erl
- core/whistle-1.0.0/src/wh_nodes.erl
- core/whistle_amqp-1.0.0/src/amqp_util.erl
- core/whistle_amqp-1.0.0/src/wh_amqp_worker.erl
registrar wapi changes so we can move it.
> KAZOO-3925

- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_faxes.erl
fixes issue in `cb_context:should_paginate/1`
> Kazoo 3781: paginate smtp logs

- applications/cccp/src/cccp.hrl
- applications/cccp/src/cccp_util.erl
- applications/crossbar/src/modules/cb_cccps.erl
- core/whistle-1.0.0/include/wh_databases.hrl
- core/whistle_apps-1.0.0/src/whapps_maintenance.erl
Implemented the 'cccps' database migration (bug fix).
> KAZOO-3941: Migration doesn't work for cccps database.

- applications/ecallmgr/src/ecallmgr_util.erl
As discussed this approach is just masking the real issue.  The root cause will be addressed by KAZOO-3957 (and the current workaround via KAZOO-3945).
> KAZOO-3778: remove depricated function

- applications/crossbar/priv/couchdb/views/resources.json
- applications/sysconf/src/sysconf_gateways.erl
Fixed variables names used in FS-gateways.
Added "register_extension" to gateway.
> Fix gateway registration

- applications/crossbar/priv/couchdb/views/port_requests.json
- applications/crossbar/src/modules/cb_port_requests.erl
- core/whistle_apps-1.0.0/src/whapps_maintenance.erl
- core/whistle_number_manager-1.0.0/src/wh_port_request.erl
@k-anderson please review; will backport to 3.21 if acceptable
> Kazoo 3810 - listing by descendants

- applications/callflow/doc/ring_group.md
- applications/callflow/src/module/cf_ring_group.erl
- applications/callflow/test/cf_ring_group_test.erl
- applications/crossbar/priv/couchdb/schemas/callflows.ring_group.json
This strategy to order endpoints by weight.
> KAZOO-3943: added "weighted_random" strategy to cf_ring_group

- applications/ecallmgr/src/ecallmgr_registrar.erl
and added the federate flag back to reg_success
> KAZOO-4034: fix querying between ecallmgr nodes for registrations

- applications/crossbar/src/modules/cb_notifications.erl
- applications/crossbar/src/modules/cb_port_requests.erl
- applications/crossbar/src/modules/cb_simple_authz.erl
- applications/teletype/priv/couchdb/views/notifications.json
- applications/teletype/src/teletype_shared_listener.erl
- applications/teletype/src/templates/teletype_port_rejected.erl
- core/whistle-1.0.0/src/api/wapi_notifications.erl
- core/whistle_apps-1.0.0/src/whapps_maintenance.erl
- core/whistle_couch-1.0.0/src/couch_mgr.erl
and fixed the listing of templates
> KAZOO-4037: added the rejected notification, removed the deletion

- applications/callflow/src/module/cf_ring_group.erl
Closing this = PR #1200th closed! :)
> Fix Dialyzer warning in cf_ring_group.erl

- applications/jonny5/src/j5_authz_req.erl
- applications/stepswitch/src/stepswitch_inbound.erl
PR https://github.com/2600hz/kazoo/pull/1211 broke inbound.
> KAZOO-1243: j5_authz_req is not passing device Options on rate requests

- applications/crossbar/doc/allotments.md
- applications/crossbar/priv/couchdb/schemas/allotments.json
- applications/crossbar/src/modules/cb_allotments.erl
- applications/crossbar/src/modules/cb_modules_util.erl
Show current allotments configuration.
Update allotments configuration (only reseller/admin).
Show consumed allotments in current cycle.
> Crossbar module for allotments

- applications/pivot/src/pivot_call.erl
> Pivot sends pivot_failed if returned data cannot be translated

- applications/crossbar/src/modules/cb_conferences.erl
Moved actions into POST to conference/id
Changed conference_participants to list comp
#1249 against master
> Added participants/kick/mute/unmute to cb_conferences

- core/whistle-1.0.0/src/wh_util.erl
- core/whistle_number_manager-1.0.0/include/wh_number_manager.hrl
- core/whistle_number_manager-1.0.0/src/wh_number_manager.erl
- core/whistle_number_manager-1.0.0/src/wnm.hrl
- core/whistle_number_manager-1.0.0/src/wnm_number.erl
- core/whistle_number_manager-1.0.0/src/wnm_number_crawler.erl
KAZOO-4105 The number manger crawler does not appear to be crawling
KAZOO-4106 number crawler operates on chunks of documents
> KAZOO-4107 Numbers that are 're-discovered' are not updated in the number database

- applications/crossbar/src/modules/cb_vmboxes.erl
https://github.com/2600hz/kazoo/issues/1307
> KAZOO-4215: cb_vmboxes.erl typo

- applications/callflow/src/cf_endpoint.erl
- applications/crossbar/priv/couchdb/schemas/devices.json
Move maybe_exclude_from_queues function calls to vars
#1248 against master
> Added feature for excluding device from a queue

- applications/crossbar/Makefile
- applications/crossbar/doc/token_restrictions.md
- applications/crossbar/src/crossbar_types.hrl
- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_token_restrictions.erl
- applications/crossbar/test/cb_token_restrictions_test.erl
- applications/crossbar/test/cb_token_restrictions_test.hrl
- core/kazoo_bindings-1.0.0/src/kazoo_bindings.erl
Unit tests hopefully covering the options available in token restriction rules.
> Token restrictions tests

- applications/callflow/src/module/cf_hotdesk.erl
- applications/crossbar/doc/devices.md
- applications/crossbar/priv/couchdb/account/devices.json
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/crossbar_freeswitch.erl
- applications/crossbar/src/modules_v1/cb_devices_v1.erl
- applications/crossbar/src/modules_v2/cb_devices_v2.erl
List devices, both owned_by and hotdesked into, by user.
> Kazoo 4236

- applications/crossbar/priv/couchdb/account/lists.json
- applications/crossbar/src/modules_v1/cb_lists_v1.erl
- applications/crossbar/src/modules_v2/cb_lists_v2.erl
Also removed dependency of `fetch_reduce` option.
> KAZOO-4255: lists v1 compatibility

- applications/crossbar/doc/limits.md
- applications/crossbar/priv/couchdb/schemas/acls.json
- applications/ecallmgr/src/ecallmgr_fs_authn.erl
- applications/ecallmgr/src/ecallmgr_fs_authz.erl
- applications/hotornot/src/hon_rater.erl
- applications/hotornot/src/hon_util.erl
- applications/jonny5/src/j5_allotments.erl
- applications/jonny5/src/j5_authz_req.erl
- applications/jonny5/src/j5_flat_rate.erl
- applications/jonny5/src/j5_hard_limit.erl
- applications/jonny5/src/j5_limits.erl
- applications/jonny5/src/j5_per_minute.erl
- applications/jonny5/src/jonny5_maintenance.erl
- applications/registrar/src/reg_authn_req.erl
- core/whistle_number_manager-1.0.0/src/carriers/wnm_bandwidth.erl
- core/whistle_number_manager-1.0.0/src/providers/wnm_dash_e911.erl
- core/whistle_services-1.0.0/src/wh_service_sync.erl
- core/whistle_services-1.0.0/src/whistle_services_maintenance.erl
- doc/reference/routing.md
KazooCon '15 presentation source material, plus some code cleanup
> Rating and limits preso

- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/test/ecallmgr_call_command_test.erl
> Tones refactor

- applications/acdc/src/acdc_agent_fsm.erl
- applications/acdc/src/acdc_stats.erl
- applications/acdc/src/acdc_stats.hrl
- applications/acdc/src/wapi_acdc_stats.erl
> Track whether agent or member hung up queue call

- applications/milliwatt/src/milliwatt_tone.erl
trust that they will be converted to proper representation down the line.
> 3.21-milliwatt-fix: get a list of frequencies

- .gitignore
- .travis.yml
> KAZOO-4277: make Travis fail when unstaged changes exist

- applications/webhooks/doc/maintenance.md
- applications/webhooks/src/webhooks_disabler.erl
- applications/webhooks/src/webhooks_listener.erl
- applications/webhooks/src/webhooks_maintenance.erl
- applications/webhooks/src/webhooks_util.erl
- core/kazoo_documents-1.0.0/src/kzd_webhook.erl
- core/whistle-1.0.0/src/wh_cache.erl
- core/whistle-1.0.0/src/wh_json.erl
- core/whistle-1.0.0/test/wh_json_test.erl
- core/whistle_couch-1.0.0/src/wh_doc.erl
Fixes webhook re-enable when failure tracking hasn't flushed yet.
> Kazoo 4279 - Fix for HELP-19316

- applications/notify/src/notify_voicemail_to_email.erl
Check first response for 'ok' or 'error' for whether to tell response
queue the result of vm->email send
> KAZOO-4319: iterate and create email tuples

- core/whistle_media-1.0.0/src/wh_media_recording.erl
CHANNEL_REPLACED + small corrections
> KAZOO-4309: recording on call forward

- core/whistle_amqp-1.0.0/src/wh_amqp_connection.erl
allow timeout to grow larger for remote brokers vs local brokers
> KAZOO-4293: distinguish local vs remote when reconnecting

- core/whistle-1.0.0/src/wh_cache.erl
- core/whistle_apps-1.0.0/src/whapps_util.erl
> KAZOO-4278: fix database auto cache

- applications/ecallmgr/src/ecallmgr.erl
- core/whistle-1.0.0/src/wh_nodes.erl
- core/whistle_apps-1.0.0/src/whistle_apps.app.src
- core/whistle_apps-1.0.0/src/whistle_apps.erl
- core/whistle_config-1.0.0/src/wh_config.erl
- core/whistle_config-1.0.0/src/whapps_config.erl
- core/whistle_config-1.0.0/src/whistle_config.erl
- core/whistle_config-1.0.0/src/whistle_config.hrl
- core/whistle_config-1.0.0/src/whistle_config_app.erl
- core/whistle_config-1.0.0/src/whistle_config_sup.erl
provide zone configuration based on ini file
> KAZOO-4425 whistle_config changes

- core/whistle_couch-1.0.0/src/couch_mgr.erl
- core/whistle_couch-1.0.0/src/wh_couch.hrl
- core/whistle_couch-1.0.0/src/wh_couch_connections.erl
supporting connections other than local
> KAZOO-4456 allow tagged couch connections

- applications/ecallmgr/src/ecallmgr_fs_route.erl
- applications/ecallmgr/src/ecallmgr_fs_xml.erl
Reopen of https://github.com/2600hz/kazoo/pull/1510
> KAZOO-4470: Run start_dtmf in case of "101 telephone-event" absence.

- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/src/ecallmgr_call_events.erl
- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- applications/ecallmgr/src/ecallmgr_fs_event_stream.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- core/kazoo_documents-1.0.0/src/kzd_freeswitch.erl
- core/whistle-1.0.0/src/props.erl
needs backport to 3.22 to fix blf issue
> KAZOO-4477 handle freeswitch logical direction

- applications/omnipresence/src/omnip_dialog_amqp.erl
> HELP-20240 log target-call-id

- applications/omnipresence/src/omnip_dialog_amqp.erl
some UAs send the pickup to local instead of remote
> BLF add the fastpickup to local

- applications/callflow/src/module/cf_callflow.erl
> HELP-20384 remove aggressive channel check

- applications/crossbar/doc/accounts.md
- applications/crossbar/doc/api_authentication.md
Updated the API docs to include the api_key endpoint for obtaining the API key from a kazoo account.
> Update api key docs

- applications/callflow/src/callflow.hrl
- applications/callflow/src/cf_endpoint.erl
- applications/callflow/src/cf_event_handler_sup.erl
- applications/callflow/src/cf_exe.erl
- applications/callflow/src/cf_route_win.erl
- applications/callflow/src/cf_util.erl
- applications/callflow/src/module/cf_record_call.erl
- applications/callflow/src/module/cf_resources.erl
- applications/cdr/src/cdr_channel_destroy.erl
- applications/crossbar/src/modules/cb_clicktocall.erl
- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_call_events.erl
- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- applications/ecallmgr/src/ecallmgr_fs_route.erl
- applications/ecallmgr/src/ecallmgr_fs_xml.erl
- applications/ecallmgr/src/ecallmgr_originate.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- applications/stepswitch/src/stepswitch_bridge.erl
- core/kazoo_documents-1.0.0/src/kz_call_event.erl
- core/kazoo_modb-1.0.0/priv/couchdb/views/recordings.json
- core/whistle-1.0.0/src/api/wapi_call.erl
- core/whistle-1.0.0/src/api/wapi_registration.erl
- core/whistle-1.0.0/src/wh_nodes.erl
- core/whistle_apps-1.0.0/src/whapps_call_command.erl
- core/whistle_media-1.0.0/Makefile
- core/whistle_media-1.0.0/src/wh_media_recording.erl
also makes some tweaks / optimization to loopback channels
also resolves KAZOO-4408
> KAZOO-4389 refactor recording

- applications/crossbar/src/crossbar_doc.erl
Ex: 
{SERVER}/accounts/{ACCOUNT_ID}/devices?filter_name=[ "name1", "name2"]
@k-anderson
> KAZOO-4505: Add the ability to use list in filter

- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_fs_command.erl
- applications/ecallmgr/src/ecallmgr_fs_route.erl
- applications/ecallmgr/src/ecallmgr_fs_xml.erl
- applications/ecallmgr/src/ecallmgr_util.erl
Refactor FS command module and remove custom sip headers from channel
> KAZOO-4467: remove ecallmgr CCV duplicates in AMQP messages

- ANNOUNCEMENTS.md
- core/whistle-1.0.0/src/wh_json.erl
- core/whistle-1.0.0/src/wh_util.erl
- core/whistle_number_manager-1.0.0/src/carriers/wnm_bandwidth.erl
Needs testing (@k-anderson knows the actual login:pwd info)
> KAZOO-4231: tollfree number search

- applications/webhooks/src/webhooks_util.erl
> Add AccountId to debug on non-200 responses

- applications/callflow/src/callflow.hrl
- applications/callflow/src/cf_route_req.erl
- applications/callflow/src/cf_route_win.erl
> KAZOO-4521 apply restrictions to transfers without changing

- .travis.yml
> CI-for-3.22: dialyze files changed wrt. 3.22, not master

- applications/omnipresence/src/omnip_message_summary_amqp.erl
- applications/omnipresence/src/omnip_message_summary_sip.erl
- applications/omnipresence/src/omnip_subscriptions.erl
- applications/omnipresence/src/omnipresence.hrl
- applications/omnipresence/src/omnipresence_maintenance.erl
reset_subscription (user@realm or user realm)
resets the subscription and notifies every subscriber
reset_subscriber (user@realm or user realm)
gets all subscriptions of user@realm
calls reset_subscription
> KAZOO-4526 add reset functions to omnipresence_maintenance

- applications/acdc/src/acdc_agent_fsm.erl
- applications/acdc/src/acdc_agent_listener.erl
fixed acdc bugs which were causing unexpected behaviour and crashes
> Fixed some ACDC Bugs which were making it unusable

- core/whistle_config-1.0.0/src/wh_config.erl
- core/whistle_config-1.0.0/src/whapps_config.erl
- core/whistle_config-1.0.0/src/whistle_config.erl
- Add SUP commands to reload/set/unset app environment variables through `wh_config`
- Add SUP command to `whapps_config` to lock db writes on `whapps_config` doc
> SUP commands for reload/set/unset app env

- applications/crossbar/src/crossbar_services.erl
- applications/crossbar/src/crossbar_util.erl
- core/kazoo_documents/src/kzd_audit_log.erl
- core/whistle_services/doc/lifecycle.md
- core/whistle_services/src/services/wh_service_devices.erl
- core/whistle_services/src/wh_services.erl
- core/whistle_services/src/whistle_services.hrl
- core/whistle_services/src/whistle_services_sup.erl
@k-anderson unless you find issues, of course.
> KAZOO-244: more service plan processing

- applications/trunkstore/src/ts_from_offnet.erl
updated specs/types and var naming a bit too
> ts_refer: added authz id and type to ccvs for endpoint

- core/whistle_couch-1.0.0/src/couch_util.erl
This will need to be pick'd into master :)
> publish doc changes by db classification

- applications/trunkstore/src/ts_from_offnet.erl
- core/whistle-1.0.0/src/listener_utils.erl
This will need to be pick'd into master :)
> KAZOO-4545: handle lookup errors to clean up logs

- core/kazoo_token_buckets-1.0.0/src/kz_buckets.erl
This will need to be pick'd into 3.22 and master :)
> KAZOO-4548: handle when the bucket is shutting down

- core/whistle-1.0.0/src/gen_listener.erl
- core/whistle-1.0.0/src/wh_cache.erl
Same commits as 3.21 but for 3.22
> Cache perf 3.22

- core/whistle-1.0.0/src/gen_listener.erl
- core/whistle-1.0.0/src/wh_cache.erl
Easy commits to add to wh_cache
> Cache perf for 3.21

- core/whistle/src/gen_listener.erl
* https://travis-ci.org/2600hz/kazoo/builds/110238268
* https://travis-ci.org/2600hz/kazoo/builds/110031397
> #quickfix: un-break master after cache_perf changes

- applications/crossbar/doc/notifications.md
- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/src/teletype_shared_listener.erl
- applications/teletype/src/teletype_templates.erl
- applications/teletype/src/templates/teletype_customer_update.erl
- core/kazoo_documents/src/kzd_user.erl
- core/whistle/src/api/wapi_notifications.erl
Discussion could be seen over here: https://groups.google.com/forum/?fromgroups#!topic/2600hz-dev/iMj0oa5V5kA
> KAZOO-4539: Customers update over teletype

- applications/callflow/src/cf_endpoint.erl
- applications/callflow/src/module/cf_resources.erl
- core/kazoo_documents-1.0.0/src/kz_device.erl
> KAZOO-4220: set custom-sip-headers on outbound legs

- core/whistle_media-1.0.0/src/wh_media_map.erl
convert MediaId to PromptId for removing entries
Use Db as it is consistently found, then format for account id in handlers
> HELP-20785: flush media map helper

- applications/callflow/src/module/cf_voicemail.erl
- core/kazoo_couch/src/kz_couch_attachments.erl
- core/kazoo_couch/src/kz_couch_util.erl
- core/kazoo_data/src/kz_datamgr.erl
- core/kazoo_data/src/kzs_attachments.erl
- core/kazoo_data/src/kzs_plan.erl
- core/whistle_media/src/wh_media_file.erl
- core/whistle_media/src/wh_media_store_proxy.erl
- core/whistle_media/src/wh_media_url.erl
- core/whistle_media/src/whistle_media.hrl
- make/deps.mk
minor fixes & media_proxy refactoring
> KAZOO-4562 Part II

- make/deps.mk
> Add reloader to dep for scripts/dev-start-apps.sh

- applications/crossbar/src/modules/cb_webhooks.erl
https://github.com/2600hz/kazoo/compare/73406159a471...2edae9f2fdd3
> quick-fix: revert nasty change due to 🍒-picking

- applications/callflow/src/cf_route_req.erl
- applications/stepswitch/src/stepswitch_inbound.erl
- applications/trunkstore/src/ts_route_req.erl
- core/whistle-1.0.0/src/api/wapi_route.erl
log fetch-id in cf_route_req and stepswitch_inbound to try to determine causes for no_route_to_destination.
> HELP-21287 log fetch-id

- applications/fax/src/fax_util.erl
> fix extension_to_content_type return

- applications/callflow/src/cf_route_req.erl
- applications/stepswitch/src/stepswitch_inbound.erl
- applications/trunkstore/src/ts_route_req.erl
- core/whistle/src/api/wapi_route.erl
> HELP-21287

- core/whistle/src/wh_json.erl
> decode to {} and log input when failing hard

- ANNOUNCEMENTS.md
- applications/crossbar/doc/accounts.md
- applications/crossbar/src/modules/cb_accounts.erl
> patch-9: list siblings only by admin or if it is for child account

- applications/fax/src/fax_worker.erl
> KAZOO-4594: set number of pages to zero on crash

- applications/crossbar/doc/recordings.md
- applications/crossbar/doc/ref/recordings.md
- applications/crossbar/priv/couchdb/swagger/swagger.json
- applications/crossbar/src/modules/cb_recordings.erl
- core/kazoo_modb/priv/couchdb/views/recordings.json
- core/whistle_media/src/wh_media_recording.erl
> KAZOO-3214 crossbar api to access recordings

- applications/crossbar/doc/ref/user_auth.md
- applications/crossbar/doc/user_authentication.md
- applications/crossbar/priv/couchdb/swagger/swagger.json
- applications/crossbar/src/modules/cb_user_auth.erl
@jamesaimonetti I updated this by hand, couldn't find your documentation-generating tools (agreed, only looked in /scripts)
But seeing your doc changes I believe the variable names in the crossbar module are useful.
Though I am really interested in your doc tools. Where did I miss them?
> KAZOO-4646: fix documentation for GET user_auth

- core/kazoo_number_manager/src/knm_phone_number.erl
As recomended @fenollp in #1747
> Fix knm_phone_number:delete/1

- core/kazoo_number_manager/src/carriers/knm_bandwidth.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
> knm-buy: fix knm_number:buy

- applications/ecallmgr/src/ecallmgr_fs_command.erl
> use mod_kazoo commands

- core/whistle/include/wh_types.hrl
- core/whistle/src/wh_util.erl
- core/whistle/test/wh_util_test.erl
…forshadowing the addition of format-related types (such as account_id())
> KAZOO-4612: spec/doc/test wh_util:format_account_* 

- core/whistle/src/wh_json.erl
Cherry pick of https://github.com/2600hz/kazoo/pull/1709
This was missed by https://github.com/2600hz/kazoo/pull/1668
However, I was able to successfully wh_json:decode the JSON string
logged in the ticket.
> KAZOO-4603: handle uncaught exception when decoding JSON

- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- applications/konami/src/module/konami_audio_level.erl
- core/whistle/src/api/wapi_dialplan.erl
- core/whistle/src/api/wapi_dialplan.hrl
- core/whistle_apps/src/whapps_call_command.erl
The basic groundwork for audio levels, mute, unmute in konami and standalone commands. If you accept it I will add more docs and channels HTTP API.
> Basic audio levels modification support

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
@icehess What is that `_read_only` field in `3.22` for? @jamesaimonetti ?
> knm-REST-POST: fix POST phone_number/DID

- applications/crossbar/src/cb_context.erl
- core/whistle/src/wh_json_schema.erl
optionally tries to convert to numbers
> Crossbar schema validation

- applications/crossbar/doc/phone_numbers.md
- core/kazoo_number_manager/src/knm_phone_number.erl
Fixes for the docs are coming. Please merge other PRs before! @lazedo
> Knm leak fix

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/knm_numbers.erl
This PR needs 
1. https://github.com/2600hz/kazoo/pull/1824
1. https://github.com/2600hz/kazoo/pull/1822 which will probably mean a rebase
> Knm collections

- core/kazoo_number_manager/src/carriers/knm_carriers.erl
forward port of https://github.com/2600hz/kazoo/pull/1852
> fwdport_1852: allow disconnecting numbers from unknown carriers

- core/kazoo_number_manager/doc/knm_bandwidth2.md
- core/kazoo_number_manager/priv/fixtures/bandwidth2_buy_a_number.xml
- core/kazoo_number_manager/priv/fixtures/bandwidth2_find_by_npa.xml
- core/kazoo_number_manager/priv/fixtures/bandwidth2_find_tollfree.xml
- core/kazoo_number_manager/src/carriers/knm_bandwidth.erl
- core/kazoo_number_manager/src/carriers/knm_bandwidth2.erl
- core/kazoo_number_manager/src/carriers/knm_other.erl
- core/kazoo_number_manager/src/carriers/knm_simwood.erl
- core/kazoo_number_manager/src/carriers/knm_vitelity.erl
- core/kazoo_number_manager/src/carriers/knm_voip_innovations.erl
- core/kazoo_number_manager/src/knm_errors.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_bandwidth2_test.erl
- core/kazoo_number_manager/test/knm_voip_innovations_test.erl
- core/kazoo_web/src/kz_http.erl
why is Dialyzer complaining here?
> Knm bandwidth2

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_web/src/kz_http.erl
- core/kazoo_web/src/kz_http_util.erl
Somehow talking to phonebook from master was slower than from 3.22.
I made the requests somehow at the same time (and 3.22 is inside a VM…), same shitty wifi half the Earth away from the phonebook server… may be nothing!
> Knm locality

- core/braintree/src/braintree_address.erl
fixed address bug https://2600hz.atlassian.net/browse/KAZOO-4722
> KAZOO-4722 Braintree addresses bug fix

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/priv/couchdb/account/phone_numbers.json
- core/kazoo_number_manager/src/carriers/knm_local.erl
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/providers/knm_cnam_notifier.erl
- core/kazoo_number_manager/src/providers/knm_vitelity_cnam.erl
> Knm features  4.0

- applications/crossbar/doc/blacklists.md
Changed spelling from "Main Blacklis" to "Main Blacklist"
> Corrected Spelling

- core/kazoo_services/src/kz_services.erl
replaced maybe_follow_billling_id with maybe_follow_billing_id
> billing typo

- .travis.yml
- applications/trunkstore/priv/couchdb/lookupipauth.json
- scripts/validate-js.sh
Heuristic: looks for JS code in values of JSON files (strings starting with `"function"`).
@lazedo do you think this heuristic misses some JS? Is there JS code in our trunk that doesn't start with `"function"`?
> Validate js

- applications/crossbar/priv/couchdb/views/port_requests.json
> KAZOO-4368: Don't return unconfirmed port requests (3.21)

- applications/crossbar/priv/couchdb/views/port_requests.json
> KAZOO-4368: Don't return unconfirmed port requests (3.22)

- applications/crossbar/src/modules/cb_resources.erl
> cb_resources: on changing send reload_gateways

- applications/crossbar/doc/ledgers.md
- applications/crossbar/doc/ref/ledgers.md
- applications/crossbar/priv/couchdb/schemas/ledgers.json
- applications/crossbar/priv/couchdb/swagger/swagger.json
- applications/crossbar/src/api_util.erl
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar.hrl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules/cb_ledgers.erl
- applications/crossbar/src/modules/cb_modules_util.erl
- applications/jonny5/src/j5_per_minute.erl
- applications/jonny5/src/j5_request.erl
- core/kazoo_data/src/kz_data.hrl
- core/kazoo_data/src/kz_datamgr.erl
- core/kazoo_data/src/kzs_db.erl
- core/kazoo_ledgers/include/kazoo_ledger.hrl
- core/kazoo_ledgers/src/kazoo_ledger.erl
- core/kazoo_ledgers/src/kz_ledger.erl
- core/kazoo_ledgers/src/kz_ledgers.erl
- core/kazoo_ledgers/src/kzl.hrl
- core/kazoo_modb/priv/couchdb/views/ledgers.json
- core/kazoo_modb/priv/couchdb/views/transactions.json
- core/kazoo_transactions/src/kz_transaction.erl
> KAZOO-4511 Ledgers API

- applications/jonny5/src/j5_per_minute.erl
- applications/jonny5/src/j5_request.erl
https://github.com/2600hz/kazoo/pull/1919 continued
> KAZOO-4718: additional fields for per_minute_call doc

- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/doc/ref/vmboxes.md
- applications/crossbar/doc/voicemail.md
- applications/crossbar/priv/couchdb/schemas/callflows.voicemail.json
- applications/crossbar/priv/couchdb/swagger/swagger.json
- applications/crossbar/src/modules_v1/cb_vmboxes_v1.erl
- applications/crossbar/src/modules_v2/cb_vmboxes_v2.erl
- core/kazoo_documents/src/kzd_box_message.erl
- core/kazoo_voicemail/src/kz_vm_message.erl
* better implementation for move/update operation voicemail messages
* adds missing callflow voicemail element schema
* adds bulk delete/update in vmboxes crossbar module
> KAZOO-4736: add bulk update/delete in vmboxes crossbar module

- Makefile
create symlinks instead of copying files to _rel
> build: new Makefile target build-dev-release

- core/kazoo_apps/src/kazoo_apps.hrl
> remove duplicated include

- applications/acdc/src/acdc_agent_util.erl
- applications/crossbar/src/modules/cb_agents.erl
Added new query element in acdc queue status which will return full agent status
GET /agents/ID/status?full
> added new agent status query element

- applications/ecallmgr/src/ecallmgr_fs_authz.erl
- applications/jonny5/src/j5_channels.erl
- applications/jonny5/src/j5_per_minute.erl
- applications/jonny5/src/j5_request.erl
Please consider to add rounded billing seconds and rate description to per-minute-voip ledger doc.
> per-minute-voip ledgers doc: an attempt to add Rate-Description field. 

- applications/ecallmgr/src/ecallmgr_util.erl
As a developer, I would like to provide a Shoutcast URL for the MOH via API, so I can stream media during On Hold
> KAZOO-4062 Support of shout URL for media

- applications/hotornot/src/hon_util.erl
- applications/hotornot/test/hon_util_test.erl
> KAZOO-4620: strip non-numeric characters before lookup

- applications/callflow/doc/cf_dynamic_cid.md
- applications/callflow/src/module/cf_dynamic_cid.erl
> KAZOO-4506: update number to cf_capture_group in cf_dynamic_cid

- applications/callflow/src/module/cf_intercom.erl
- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_fs_command.erl
> KAZOO-4779 simple backport

- applications/crossbar/src/crossbar_maintenance.erl
> REFACTOR: reduce redundand typing

- applications/notify/src/notify.hrl
- applications/notify/src/notify_listener.erl
- applications/teletype/src/teletype.hrl
- applications/teletype/src/teletype_shared_listener.erl
- core/kazoo/include/kz_config.hrl
- core/kazoo_config/src/kapps_config.erl
- core/kazoo_config/src/kz_config.erl
federate notifications bindings for notify and teletype if
federate option is specified for notify application in system_config document.
> KAZOO-4794 federate notifications

- rel/sys.config
* make console logging with module and line numbers
* make it feet on screen
> refactor: reformat sys.config

- applications/callflow/doc/cf_dynamic_cid.md
- applications/callflow/src/module/cf_dynamic_cid.erl
> KAZOO-4506_4.0: update number to cf_capture_group in cf_dynamic_cid for 4.0

- applications/callflow/doc/cf_dynamic_cid.md
- applications/callflow/src/module/cf_dynamic_cid.erl
> KAZOO-4506_master: update number to cf_capture_group in cf_dynamic_cid for master

- core/kazoo_services/src/kz_services.erl
Store cascade_quantities to services json document.
> KAZOO-4669 cascade_quantities in services modb

- applications/conference/src/conf_participant.erl
- applications/ecallmgr/src/ecallmgr_fs_conference.erl
- core/kazoo/src/api/kapi_conference.erl
- core/kazoo_amqp/src/amqp_util.erl
* generate amqp participant events 'add-member' and 'del-member'
* send these events to queue conference.event.$conf_id.$call_id
* synchronize participant state on these events
> KAZOO-4462 participant events

- applications/crossbar/priv/couchdb/schemas/resource_selector.rules.json
- applications/crossbar/priv/couchdb/schemas/resource_selectors.json
- applications/crossbar/priv/couchdb/views/resource_selectors.json
- applications/crossbar/src/crossbar.hrl
- applications/crossbar/src/modules/cb_resource_selectors.erl
- applications/stepswitch/doc/resource_selectors.md
- applications/stepswitch/src/kz_srs_util.erl
- applications/stepswitch/src/resource_selectors/kz_srs_filter_list.erl
- applications/stepswitch/src/resource_selectors/kz_srs_filter_prefix.erl
- applications/stepswitch/src/resource_selectors/kz_srs_filter_regex.erl
- applications/stepswitch/src/resource_selectors/kz_srs_get_resources.erl
- applications/stepswitch/src/resource_selectors/kz_srs_null.erl
- applications/stepswitch/src/resource_selectors/kz_srs_order.erl
- applications/stepswitch/src/stepswitch.hrl
- applications/stepswitch/src/stepswitch_outbound.erl
- applications/stepswitch/src/stepswitch_resource_selectors.erl
- applications/stepswitch/src/stepswitch_resource_selectors.hrl
- applications/stepswitch/src/stepswitch_resources.erl
- applications/stepswitch/src/stepswitch_util.erl
- core/kazoo/include/kapi_conf.hrl
- core/kazoo/include/kz_databases.hrl
- core/kazoo/include/kz_types.hrl
- core/kazoo/src/api/kapi_conf.erl
- core/kazoo/src/kz_util.erl
- core/kazoo_data/src/kz_data.hrl
- core/kazoo_data/src/kzs_plan.erl
- core/kazoo_data/src/kzs_util.erl
> KAZOO-4804: new version of resource selectors

- applications/crossbar/src/modules_v1/cb_vmboxes_v1.erl
- applications/crossbar/src/modules_v2/cb_vmboxes_v2.erl
- core/kazoo_voicemail/src/kz_vm_message.erl
type checking for older messages
maybe_load_vmboxes recursion
> fix some vm issues found during testing

- core/whistle_number_manager-1.0.0/src/carriers/wnm_bandwidth2.erl
also changes the way that we return number for search and after processing
> KAZOO-4858 use correct xpath for order

- applications/crossbar/src/crossbar_util.erl
There were two bugs in update_descendants_tree.
- The recursive call passed ToTree instead of Tree
- Descendants were assumed to be children, but could be any level of descendant
> Fix incorrect movement of descendants

- doc/announcements.md
ejson was deprecated with jiffy
> added deprication of ejson

- core/sup/Makefile
- core/sup/rebar.config
- core/sup/src/sup.erl
- make/kz.mk
@fenollp we should also try to work with overlays in relx to copy the output core/sup/sup to _rel/kazoo/bin
> sup escriptize

- applications/crossbar/src/modules/cb_presence.erl
> use send_file instead of to_binary

- make/kz.mk
To allow sync compile modules.
> Make include_lib and include interchangable

- core/braintree/src/braintree_addon.erl
- core/braintree/src/braintree_address.erl
- core/braintree/src/braintree_card.erl
- core/braintree/src/braintree_customer.erl
- core/braintree/src/braintree_discount.erl
- core/braintree/src/braintree_subscription.erl
- core/braintree/src/braintree_transaction.erl
Found with
```shell
git grep -InE '\-import'
```
> no-import: remove -import attributes

- .gitignore
- applications/registrar/Makefile
- core/kazoo/Makefile
- make/kz.mk
it depends on ninenines/erlang.mk#572 (for issue with building deps that have C code on OS X)
> make build system posix compatible

- core/kazoo_apps/src/kapps_util.erl
we are checking encoded/encoded and unencoded/unencoded
this adds encoded/unencoded unencoded/encoded encoded/raw unencoded/raw
> fix is_matched_account_mod

- applications/callflow/src/cf_util.erl
- applications/crossbar/src/crossbar.hrl
- applications/crossbar/src/modules/cb_modules_util.erl
- applications/ecallmgr/src/ecallmgr_fs_notify.erl
- applications/ecallmgr/src/ecallmgr_registrar.erl
- core/kazoo/src/api/kapi_presence.erl
adds unsolicited mwi binding
fixes counts for vmboxes from crossbar
binds ecallmgr notify to unsolicited mwi
updates the send unsolicited mwi updates
fixes registrar age response
> KAZOO-4879 optimize mwi

- core/braintree/src/braintree_customer.erl
This pr will make sure that every address associated with old cards is deleted properly as well as if the old address is being used by the new card it will not delete it.
> Billing pr

- applications/crossbar/src/crossbar_maintenance.erl
allows serving multiple api uris
> allow init_apps without url

- core/kazoo_services/src/kazoo_services.hrl
- core/kazoo_services/src/kz_services.erl
Only found filesystem queries of src/ in kazoo_services. Maybe I missed some others?
Note: include...src/... do not count: I am looking for runtime queries.
Note: ebin/ and priv/ are fine, they are in the released applications.
@k-anderson ?
> KAZOO-4856

- applications/crossbar/src/crossbar_maintenance.erl
- scripts/check-release-startup.sh
When checking that release starts, also check that creating a master account works.
Wink @k-anderson 
Also wink KAZOO-4866
> Ci test release

- applications/crossbar/src/modules/cb_callflows.erl
- applications/crossbar/src/modules/cb_faxes.erl
- applications/fax/src/fax_jobs.erl
- applications/fax/src/fax_smtp.erl
- applications/fax/src/fax_util.erl
- core/kazoo_number_manager/src/carriers/knm_managed.erl
. knm_managed not activating number
. cb_callflows reconciling non-numbers, (create account, acquire number, go to "Main Number")
. faxes not initializing pvt_modified
. fax smtp, possible switch of MAIL/RCPTTO
. fax_jobs lower limit not handling null
> sandbox fixes

- core/kazoo_modb/src/kazoo_modb.erl
> KAZOO-4842: migrate wh_ to kz_ while updating system_configs/modb routines for 4.0

- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_options.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_services.erl
- core/kazoo_number_manager/src/knm_tasks.erl
Disable writes to services document for KNM tasks.
@k-anderson Needs testing big job/slow machine to be sure
> Qf nm tasks

- core/kazoo_endpoint/src/kz_endpoint.erl
Add Authorizing-Type field alongside with Authorizing-ID when calling
endpoint.
> KAZOO-4901: add auth type to ccv

- core/kazoo_endpoint/src/kz_attributes.erl
there is no view kz_attributes
> bugfix: kz_attributes/owner -> attributes/owner

- applications/crossbar/priv/couchdb/schemas/tasks.json
This gives 5x and maybe more (theoretically a quadratic improvement)
> qf-tasks: great speedup when creating tasks by relaxing requirements

- applications/callflow/src/cf_route_win.erl
- applications/crossbar/doc/callflows.md
- applications/crossbar/doc/clicktocall.md
- applications/crossbar/doc/devices.md
- applications/crossbar/doc/directories.md
- applications/crossbar/doc/ref/conferences.md
- applications/crossbar/doc/ref/devices.md
- applications/crossbar/doc/ref/directories.md
- applications/crossbar/priv/couchdb/schemas/directories.json
- applications/crossbar/priv/couchdb/swagger/swagger.json
- applications/crossbar/src/modules/cb_directories.erl
- applications/crossbar/src/modules_v2/cb_devices_v2.erl
- applications/crossbar/src/modules_v2/cb_users_v2.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- core/kazoo_documents/src/kzd_user.erl
- core/kazoo_endpoint/src/kz_endpoint.erl
refactor fold to own named function
fix function call, specs
formatting
> KAZOO-4886: add PATCH support to devices

- applications/cccp/doc/index.md
- applications/cccp/doc/usage.md
- applications/cccp/src/cccp.hrl
- applications/cccp/src/cccp_callback_listener.erl
- applications/cccp/src/cccp_handlers.erl
- applications/cccp/src/cccp_platform_listener.erl
- applications/cccp/src/cccp_util.erl
- applications/crossbar/priv/couchdb/account/cccps.json
- applications/crossbar/priv/couchdb/schemas/cccps.json
- applications/crossbar/priv/couchdb/views/cccps.json
- applications/crossbar/src/modules/cb_cccps.erl
Unfortunately I wasn't able to divide these changes into several steps, 'cause it evolved in time and interconnected. Tested on my single node 4.0 (master).
> cccp update for 4.0

- applications/callflow/src/cf_util.erl
- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/src/crossbar_maintenance.erl
- applications/doodle/src/doodle_util.erl
- core/kazoo_data/src/kz_datamgr.erl
- core/kazoo_number_manager/src/knm_port_request.erl
- core/kazoo_transactions/src/wht_util.erl
Places to use this were found using
```shell
git grep -InE 'ok.+\[\].+error'
```
> get_result: introduce kz_datamgr:get_result/3

- applications/crossbar/src/cb_apps_util.erl
- applications/crossbar/src/crossbar_maintenance.erl
- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_apps_store.erl
- core/kazoo_documents/src/kzd_app.erl
- core/kazoo_services/src/services/kz_service_ui_apps.erl
also formatting, some refactor into LCs & less funs.
> More uses of kzd_app

- applications/crossbar/src/modules/cb_port_requests.erl
> Kazoo 4912 2

- applications/teletype/src/teletype_util.erl
- core/kazoo_services/src/kz_services.erl
lighter weight is_reseller check
> KAZOO-4943: avoid loops

- core/kazoo_number_manager/src/knm_port_request.erl
Completion of #2340 and #2343.
> KAZOO-4914: transition ported in numbers to in_service

- applications/pivot/src/pivot_call.erl
- core/kazoo_translator/src/convertors/kzt_kazoo.erl
- core/kazoo_translator/src/convertors/kzt_twiml.erl
- core/kazoo_translator/src/kzt.hrl
- core/kazoo_translator/src/kzt_translator.erl
- core/kazoo_translator/src/kzt_util.erl
- core/kazoo_web/src/kz_http.erl
fix types/specs related to pivot/kazoo_translator
> KAZOO-4701: increment interator when redirecting

- core/kazoo_number_manager/src/knm_number_options.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
> some more input checking for KNM

- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_tasks.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
> KNM: do state picking logic from inside knm_number

- applications/crossbar/doc/tasks.md
- applications/crossbar/src/modules/cb_tasks.erl
- core/kazoo_tasks/doc/maintenance.md
- core/kazoo_tasks/priv/couchdb/views/tasks.json
- core/kazoo_tasks/src/kazoo_tasks_maintenance.erl
- core/kazoo_tasks/src/kz_tasks.erl
- core/kazoo_tasks/src/kz_tasks.hrl
> KAZOO-4952: read & return file_name if provided

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/knm_maintenance.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_tasks.erl
Note: delete is only available through Tasks UI & knm_number:delete.
Should I:
1. Add a maintenance function?
1. Add a DELETE API (though phone_numbers' already calls knm_number:release)
> KAZOO-3866

- applications/cccp/doc/usage.md
- applications/cccp/src/cccp_callback_listener.erl
- applications/cccp/src/cccp_util.erl
... makes possible connect participant to the conference over API without creating callflow for this conference
> cccp autodial direct to conference

- applications/crossbar/doc/channels.md
- applications/crossbar/src/modules/cb_channels.erl
- applications/konami/src/module/konami_intercept.erl
- core/kazoo/src/api/kapi_metaflow.erl
This combination of `quickcall` and `call pickup` for `cb_channels`.
For now its only call to one device, `user` target will be added later.
> cb_channels: Call to target device and intercept given UUID to it, after answer.

- core/kazoo_number_manager/src/knm_maintenance.erl
- core/kazoo_number_manager/src/knm_number.erl
(CI: 2 Dialyzer warnings already fixed in master)
> KAZOO-4975: fix KNM number Fix button

- applications/ananke/src/tasks/ananke_vm_callback.erl
- applications/callflow/src/cf_util.erl
- applications/callflow/src/module/cf_voicemail.erl
- applications/crossbar/doc/voicemail.md
- applications/crossbar/src/modules/cb_modules_util.erl
- applications/crossbar/src/modules_v1/cb_vmboxes_v1.erl
- applications/crossbar/src/modules_v2/cb_vmboxes_v2.erl
- applications/notify/src/notify_voicemail_to_email.erl
- applications/teletype/src/teletype_tests.erl
- applications/teletype/src/templates/teletype_voicemail_to_email.erl
- core/kazoo_documents/src/kzd_box_message.erl
- core/kazoo_voicemail/doc/index.md
- core/kazoo_voicemail/src/kvm_maintenance.erl
- core/kazoo_voicemail/src/kvm_message.erl
- core/kazoo_voicemail/src/kvm_messages.erl
- core/kazoo_voicemail/src/kvm_util.erl
- core/kazoo_voicemail/src/kz_voicemail.hrl
include tickets KAZOO-4954 KAZOO-4965
> KAZOO-4954 KAZOO-4965 & Various VM improvements

- applications/crossbar/priv/api/swagger.json
- core/kazoo_ast/src/cb_api_endpoints.erl
Re-add changes that disappeared from https://github.com/2600hz/kazoo/pull/2446
> Qf swagger

- applications/callflow/src/cf_route_req.erl
- applications/crossbar/doc/faxes.md
- applications/crossbar/doc/ref/faxes.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/faxes.json
- applications/crossbar/src/modules/cb_faxes.erl
- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- applications/ecallmgr/src/ecallmgr_fs_node_command.erl
- applications/webhooks/src/webhooks_shared_listener.erl
- core/kazoo/include/kz_api.hrl
- core/kazoo/include/kz_types.hrl
- core/kazoo/src/kz_api.erl
- core/kazoo_apps/src/kapps_call.erl
- core/kazoo_apps/src/kapps_call_command.erl
- core/kazoo_documents/src/kzd_fax.erl
also adds unrelated updates in separate commit
> KAZOO-5018 schema fixes & some defaults

- applications/blackhole/src/blackhole_socket_callback.erl
> bh unsubscribe misses account_id

- applications/crossbar/priv/couchdb/account/devices.json
Port of https://github.com/2600hz/kazoo/pull/2490 to 3.22
> KAZOO-4662_3.22: return device username as part of crossbar view

- applications/conference/src/conf_discovery_req.erl
- check entered conference number not to be an empty string, play error message otherwise
> KAZOO-5041 enforce entered conf-number not empty

- applications/crossbar/src/modules/cb_service_plans.erl
Instead of validating their existance in DB.
> KAZOO-4495 check plans to delete to be assigned

- scripts/code_checks.bash
Make code checks really better (again)
> qf-codechecks: skip files that do not exist

- applications/crossbar/src/modules/cb_service_plans.erl
- core/kazoo_services/doc/.org/bookkeepers.org
- core/kazoo_services/doc/bookkeepers.md
- core/kazoo_services/src/bookkeepers/kz_bookkeeper_http.erl
- core/kazoo_services/src/kz_service_sync.erl
This is mostly a RFC at the moment. Once agreed upon, implementation can move forward from this "spec". Let's discuss on the next standup
> kz_bookkeeper_http: generic bookkeeper interface

- scripts/check-xref.escript
Also adds checking for `undefined_functions`
> qf-xref: rewrite to prepare for per-app xref-ing

- applications/blackhole/src/bh_context.erl
- applications/blackhole/src/bh_events.erl
- applications/blackhole/src/blackhole.hrl
- applications/blackhole/src/blackhole_app.erl
- applications/blackhole/src/blackhole_bindings.erl
- applications/blackhole/src/blackhole_data_emitter.erl
- applications/blackhole/src/blackhole_listener.erl
- applications/blackhole/src/blackhole_socket_callback.erl
- applications/blackhole/src/blackhole_socket_handler.erl
- applications/blackhole/src/blackhole_sup.erl
- applications/blackhole/src/blackhole_tracking.erl
- applications/blackhole/src/blackhole_util.erl
- applications/blackhole/src/modules/bh_call.erl
- applications/blackhole/src/modules/bh_conference.erl
- applications/blackhole/src/modules/bh_fax.erl
- applications/blackhole/src/modules/bh_object.erl
- applications/blackhole/src/modules/bh_skel.erl
- applications/blackhole/src/modules/bh_token_auth.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.blackhole.json
- core/kazoo_bindings/src/kazoo_bindings.erl
- core/kazoo_bindings/src/kazoo_bindings_rt.erl
> blackhole refactor

- applications/ecallmgr/src/ecallmgr.hrl
- applications/ecallmgr/src/ecallmgr_call_control.erl
- applications/ecallmgr/src/ecallmgr_fs_authz.erl
- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- core/whistle-1.0.0/include/wh_api.hrl
Include channel-authorized (and ccvs in general) on dialplan errors
> HELP-24822-3.22

- applications/crossbar/src/modules/cb_onboard.erl
- applications/pivot/src/pivot_call.erl
- applications/trunkstore/src/trunkstore_maintenance.erl
- applications/trunkstore/src/ts_from_offnet.erl
- core/apns/include/apns.hrl
- core/apns/src/apns.erl
- core/braintree/src/braintree_request.erl
- core/gcm/src/gcm.erl
- core/gcm/src/gcm_api.erl
- core/kazoo/src/kz_perf_transform.erl
- core/kazoo_amqp/include/kz_amqp.hrl
- core/kazoo_amqp/include/kz_api.hrl
- core/kazoo_amqp/src/api/kapi_conference.erl
- core/kazoo_amqp/src/api/kapi_metaflow.erl
- core/kazoo_amqp/src/api/kapi_money.erl
- core/kazoo_amqp/src/api/kapi_presence.erl
- core/kazoo_amqp/src/api/kz_api.erl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_attachments/src/aws/kz_aws.erl
- core/kazoo_caches/test/kz_cache_pqc.erl
- core/kazoo_call/src/kapps_call.erl
- core/kazoo_config/src/kz_config.erl
- core/sup/src/sup.erl
Remove usage of the proplists module in favor of props
> No proplists

- applications/blackhole/src/bh_context.erl
- applications/callflow/src/cf_route_win.erl
- applications/camper/src/camper_onnet_handler.erl
- applications/cccp/src/cccp_callback_listener.erl
- applications/cccp/src/cccp_util.erl
- applications/conference/src/conf_config_req.erl
- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_init.erl
- applications/crossbar/src/crossbar_maintenance.erl
- applications/ecallmgr/src/ecallmgr_fs_channel.erl
- applications/notify/src/notify_first_occurrence.erl
- applications/notify/src/notify_port_request.erl
- applications/omnipresence/src/omnip_dialog_amqp.erl
- applications/teletype/src/templates/teletype_first_occurrence.erl
- applications/webhooks/src/webhooks_util.erl
- core/kazoo/src/kz_util.erl
- core/kazoo_call/src/kapps_call_command.erl
- scripts/.org/README.org
- scripts/README.md
- scripts/check-app-registered.sh
- scripts/conn-to-apps.sh
- scripts/conn-to-ecallmgr.sh
- scripts/dialyze-usage.bash
Removes usage of proplists in favor of props, documents scripts, and updates some Dialyzer complaints
> Props, scripts, and specs

- core/kazoo_couch/src/kazoo_couch.erl
Everything works fine while saving multiple docs
> Fixed a Typo

- applications/crossbar/src/modules/cb_system_configs.erl
> qf-sysc: fix up typo

- applications/crossbar/src/cb_pager.erl
- applications/crossbar/src/crossbar_filter.erl
- applications/crossbar/src/crossbar_view.erl
- applications/crossbar/src/modules/cb_notifications.erl
- core/kazoo_modb/src/kazoo_modb_view.erl
- applied to cb_notifications as example
> KAZOO-5039 modb pagination

- core/kazoo/src/kz_json_schema.erl
- make/deps.mk
also changes jesse dep to 1.4.2 which handles better the error list
> return error for schema errors instead of throw

- applications/crossbar/doc/ref/webhooks.md
- applications/crossbar/doc/webhooks.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/webhooks.json
- applications/webhooks/src/modules/webhooks_channel_answer.erl
- applications/webhooks/src/modules/webhooks_channel_bridge.erl
- applications/webhooks/src/modules/webhooks_channel_create.erl
- applications/webhooks/src/modules/webhooks_channel_destroy.erl
- applications/webhooks/src/modules/webhooks_object.erl
- applications/webhooks/src/modules/webhooks_parking.erl
- applications/webhooks/src/webhooks.hrl
- applications/webhooks/src/webhooks_channel_util.erl
- applications/webhooks/src/webhooks_shared_listener.erl
- applications/webhooks/src/webhooks_util.erl
- core/kazoo_documents/src/kzd_webhook.erl
also adds parent account hooks processing.
> KAZOO-5102 removes federation from webhooks

- core/kazoo_auth/src/kazoo_auth_maintenance.erl
- core/kazoo_auth/src/kz_auth.erl
- core/kazoo_auth/src/kz_auth_profile.erl
and util to flush local caches
> profile claim mapping

- applications/crossbar/src/modules/cb_vmboxes.erl
- core/kazoo_voicemail/src/kvm_message.erl
- core/kazoo_voicemail/src/kvm_messages.erl
- core/kazoo_voicemail/src/kvm_util.erl
> kvm-retention: only allow to fetch mesasges prior to retention

- applications/milliwatt/src/milliwatt_listener.erl
> bugfix: make milliwatt listen to each call request

- core/kazoo_voicemail/src/kvm_message.erl
- core/kazoo_voicemail/src/kvm_util.erl
if not found just do not check the retention policy
> qf-kvm_retention: search for timestamp in the doc or metadata

- core/kazoo_web/src/kz_http.erl
> KAZOO-5117: convert body to binary to make sure content_lenght sets correctly

- applications/webhooks/src/modules/webhooks_object.erl
- applications/webhooks/src/webhooks_listener.erl
- applications/webhooks/src/webhooks_shared_listener.erl
also simplifies subscribing to object events
> KAZOO-5126: filter action and type in object custom data

- applications/crossbar/doc/basics.md
Sorry just thought about this now
> Updated pretty printing docs

- applications/crossbar/doc/recordings.md
- applications/crossbar/src/modules/cb_recordings.erl
I'll leave it to the guys at https://github.com/2600hz/kazoo/pull/2705 to actually fix the bug ;)
> 5120: update docs

- .travis.yml
- core/kazoo_token_buckets/test/kz_token_bucket_pqc.erl
Should I remove that module now that we have kazoo_auth?
> qf-proper: reactivate PropEr tests but kz_token_buckekts_pqc

- applications/crossbar/src/modules/cb_notifications.erl
- applications/teletype/src/teletype_util.erl
- core/kazoo_templates/src/kazoo_template.hrl
and some fixes for kazoo_templates
> KAZOO-5090: find address properly from data and template

- applications/tasks/src/kz_account_crawler.erl
- core/kazoo_services/src/bookkeepers/kz_bookkeeper_braintree.erl
- core/kazoo_services/src/bookkeepers/kz_bookkeeper_http.erl
- core/kazoo_services/src/bookkeepers/kz_bookkeeper_local.erl
- core/kazoo_services/src/kz_service_sync.erl
- core/kazoo_services/src/kz_services.erl
- core/kazoo_transactions/src/kazoo_transactions_maintenance.erl
- core/kazoo_transactions/src/kz_topup.erl
> KAZOO-5137: execute auto top up transaction immediately

- applications/crossbar/src/crossbar_auth.erl
Using `system_config/crossbar/token_auth_expiry` for calculating expiration date.
token_auth_expiry = 0 means no expiration ("exp" claim removed).
> Add "exp" claim to JWT

- applications/ecallmgr/src/ecallmgr_fs_authz.erl
- applications/hotornot/src/hon_rater.erl
- core/kazoo_amqp/src/api/kapi_rate.erl
Would like to be able to apply rates based on gateway, call sent to.
> KAZOO-5124: optionally filter rates by resource id

- core/kazoo_auth/src/kz_auth_identity.erl
adds check expiration based on configured values from claim/profile
> KAZOO-5171 new check expiration

- core/kazoo_voicemail/src/migrate/kvm_migrate_crawler.erl
processing the same account which is currently under process by another
worker
> fix crashes due to bad workers searching & enhance worker queue by not

- applications/conference/src/conf_config_req.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.call_command.json
- applications/crossbar/priv/couchdb/schemas/system_config.conferences.json
- applications/crossbar/priv/couchdb/schemas/system_config.crossbar.freeswitch.json
- applications/crossbar/priv/couchdb/schemas/system_config.crossbar.ubiquiti.json
- applications/crossbar/priv/couchdb/schemas/system_config.ecallmgr.json
- applications/crossbar/priv/couchdb/schemas/system_config.jonny5.json
- applications/crossbar/priv/couchdb/schemas/system_config.notify.json
- applications/crossbar/priv/couchdb/schemas/system_config.token_buckets.json
- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- core/kazoo_ast/src/fs_prop_usage.erl
- core/kazoo_ast/src/kapps_config_usage.erl
- core/kazoo_ast/src/kz_ast_util.erl
Note: i left the kapps_config_usage changed code commented as there may be a better solution not in the scope of this PR.
> KAZOO-5179 properly build outcall list

- core/kazoo_couch/src/kazoo_couch.erl
- core/kazoo_couch/src/kz_couch_db.erl
- core/kazoo_data/src/kz_datamgr.erl
not suitable for large databases
> qf-import import database

- core/kazoo/include/kz_types.hrl
- core/kazoo_amqp/src/api/kapi_nodes.erl
- core/kazoo_globals/src/kazoo_globals_sup.erl
- core/kazoo_globals/src/kz_global.erl
- core/kazoo_globals/src/kz_globals.erl
- core/kazoo_globals/src/kz_nodes.erl
also adds stats to kz_nodes output
> fix globals scope

- applications/crossbar/doc/basics.md
> Fix filename missing .md extension

- applications/crossbar/doc/ref/accounts.md
- applications/crossbar/doc/ref/callflows.md
- applications/crossbar/doc/ref/connectivity.md
- applications/crossbar/doc/ref/devices.md
- applications/crossbar/doc/ref/metaflows.md
- applications/crossbar/doc/ref/port_requests.md
- applications/crossbar/doc/ref/service_plans.md
- applications/crossbar/doc/ref/storage.md
- applications/crossbar/doc/ref/token_restrictions.md
- applications/crossbar/doc/ref/users.md
- applications/crossbar/doc/ref/vmboxes.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/metaflow.audio_level.json
- core/kazoo_ast/src/cb_api_endpoints.erl
Auto-generate schema tables referenced by the main doc's schema. 
This is a first pass to see if this is a viable thing to do. If acceptable, I'll incorporate the changes into the doc/ versions.
> Follow $ref in docs

- applications/callflow/src/module/cf_disa.erl
- applications/callflow/src/module/cf_prepend_cid.erl
- core/kazoo_endpoint/src/kz_attributes.erl
Reverted on request from lazedo
> Revert "keep the origrinal caller id in disa & add some log lines"

- applications/crossbar/doc/ref/callflows.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.action.json
- applications/crossbar/priv/couchdb/schemas/callflows.json
- core/kazoo_documents/src/kzd_callflow.erl
- core/kazoo_json/src/kz_json_schema.erl
move action schema to its own schema doc
use callflows.action schema
export types for use
add test clause
update ref doc and swagger
> add action callflow schema

- applications/crossbar/priv/couchdb/account/phone_numbers.json
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/include/knm_phone_number.hrl
> HELP-26792: fill up features_available fields

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/carriers/knm_bandwidth.erl
- core/kazoo_number_manager/src/carriers/knm_bandwidth2.erl
- core/kazoo_number_manager/src/carriers/knm_carriers.erl
- core/kazoo_number_manager/src/carriers/knm_inum.erl
- core/kazoo_number_manager/src/carriers/knm_local.erl
- core/kazoo_number_manager/src/carriers/knm_managed.erl
- core/kazoo_number_manager/src/carriers/knm_mdn.erl
- core/kazoo_number_manager/src/carriers/knm_other.erl
- core/kazoo_number_manager/src/carriers/knm_reserved.erl
- core/kazoo_number_manager/src/carriers/knm_reserved_reseller.erl
- core/kazoo_number_manager/src/carriers/knm_simwood.erl
- core/kazoo_number_manager/src/carriers/knm_telnyx.erl
- core/kazoo_number_manager/src/carriers/knm_vitelity.erl
- core/kazoo_number_manager/src/carriers/knm_voip_innovations.erl
- core/kazoo_number_manager/src/knm_gen_carrier.erl
- core/kazoo_number_manager/test/knm_carriers_find_test.erl
Also sets ground for future addition of multiple carriers checking.
> qf-check: more stable carriers check API

- applications/callflow/src/module/cf_prepend_cid.erl
- core/kazoo_endpoint/src/kz_attributes.erl
The new behavior cause the internal number prepend which is wrong. rewriting module to previous behavior which is storing prefixes in `prepen_cid_*` call variable.
To prevent setting prefix multiple times, in `kz_attributes` setting prefix to the unmodified caller ids.
> change prepend behavior back with set to current/original concept

- core/kazoo_number_manager/priv/fixtures/old_vsn_2_out.json
- core/kazoo_number_manager/src/carriers/knm_carriers.erl
- core/kazoo_number_manager/test/knm_carriers_find_test.erl
- core/kazoo_number_manager/test/knm_phone_number_test.erl
Follow up of: https://github.com/2600hz/kazoo/pull/2986
fourdotoh version: https://github.com/2600hz/kazoo/pull/3005
> HELP-26693: better try-catch on is_number_billable call

- Makefile
- circle.yml
- doc/engineering/dialyzer.md
- doc/engineering/releases.md
- doc/installation.md
- doc/kazoocon/pivot2014.md
- doc/mkdocs/mkdocs.yml
- doc/reference/caller_id_formatting.md
- doc/reference/routing.md
- scripts/validate_mkdocs.py
Checks the mkdocs.yml for errors and fails the build if found
> Docs target

- core/kazoo_number_manager/src/knm_errors.erl
- core/kazoo_number_manager/src/providers/knm_dash_e911.erl
https://github.com/2600hz/kazoo/pull/3011
> KAZOO-5247: properly encode knm_errors:invalid/2

- applications/stepswitch/src/stepswitch_bridge.erl
> HELP-27113: update endpoint cid when emergency

- applications/crossbar/src/crossbar_services.erl
> HELP-27132: construct phone number correctly to avoid crashes during

- core/kazoo_number_manager/src/carriers/knm_carriers.erl
cherry pick of https://github.com/2600hz/kazoo/pull/3032
> KAZOO-5254_4oh: use defaults when reseller id is undefined

- applications/crossbar/src/crossbar_services.erl
> [4.0] HELP-27132: construct phone number correctly to avoid crashes during

- circle.yml
Replaces https://github.com/2600hz/kazoo/pull/3063
> copy_2017: only check copyrights on master

- applications/callflow/doc/prepend_cid.md
- applications/crossbar/doc/phone_numbers.md
- core/kazoo_json/src/kz_json.erl
- core/kazoo_json/test/kz_json_test.erl
- core/kazoo_number_manager/src/providers/knm_dash_e911.erl
- core/kazoo_number_manager/src/providers/knm_failover.erl
- core/kazoo_number_manager/src/providers/knm_port_notifier.erl
- core/kazoo_number_manager/src/providers/knm_prepend.erl
- core/kazoo_number_manager/src/providers/knm_telnyx_e911.erl
- core/kazoo_number_manager/src/providers/knm_vitelity_e911.erl
> qf-knm-4oh: remove kz_json:are_identical

- core/kazoo_number_manager/src/knm_errors.erl
- core/kazoo_number_manager/src/knm_services.erl
Master version of https://github.com/2600hz/kazoo/pull/3061
> knm_service_restriction_error: fix knm_service_restriction_error

- applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
- core/kazoo_number_manager/src/carriers/knm_vitelity.erl
cc https://github.com/2600hz/kazoo/pull/3100
> HELP-27139_master: fix searching numbers with v1 & ordering with Vitelity

- applications/fax/src/fax_cloud.erl
- applications/fax/src/fax_worker.erl
- core/kazoo_apps/src/kapps_speech.erl
Changing HTTP response headers to lower case because they're lower case on httpc.
(backport of #3102)
> [4.0] httpc response headers are lower case

- applications/crossbar/src/modules/cb_modules_util.erl
- applications/ecallmgr/src/ecallmgr_originate.erl
Forcefully set caller-id if specified.
> KAZOO-5118: forcefully set caller-id on transfered calls if specified

- applications/crossbar/src/cb_apps_util.erl
If the account does not have a service plan with apps defined then it lists all apps of the reseller, unless the reseller doesn't have apps defined in which case it list all system apps.
If the service plan defines the available apps then it gets the list from the service plan, regardless of the published state.
> NOTE: currently there is no logic for checking the `published` status, and **NONE** of the Monster apps have `published` set in their `metadata/app.json` file!
backport of #3110
> [master] HELP-26987: check service plan for ui_apps recursively to top reseller

- applications/crossbar/src/cb_context.erl
cc https://github.com/2600hz/kazoo/pull/3124
> KAZOO-5279_4oh: coercion for JSON booleans, as 3.22 used to support that

- applications/crossbar/src/modules/cb_modules_util.erl
- applications/ecallmgr/src/ecallmgr_originate.erl
Forcefully set caller-id on transferred calls if specified.
> KAZOO-5118 4oh: forcefully set caller-id on transfered calls if specified

- applications/callflow/doc/cf_dynamic_cid.md
- applications/callflow/src/module/cf_dynamic_cid.erl
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.dynamic_cid.json
Add missing documentation for `static` mode for #3055
> document cf_dynamic_cid static action

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.tasks.json
- applications/tasks/src/knm_number_crawler.erl
- core/kazoo_number_manager/src/carriers/knm_mdn.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_release_number_test.erl
cc https://github.com/2600hz/kazoo/pull/3123
> KAZOO-5277_4oh: number state deleted incurs immediate hard deletion

- applications/crossbar/src/modules_v2/cb_devices_v2.erl
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_number_options.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_search.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
- core/kazoo_number_manager/test/knm_move_number_test.erl
create number in func `add_mobile_mdn` in cb_devices
> KAZOO-5278: create the number when adding a mobile device

- applications/crossbar/src/modules_v2/cb_devices_v2.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_number_manager/test/knm_number_test.erl
cc https://github.com/2600hz/kazoo/pull/3132
> KAZOO-5288_4oh

- applications/crossbar/doc/ref/users.md
- applications/crossbar/doc/users.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/users.json
cc https://github.com/2600hz/kazoo/pull/3105
> qf-users_schema: document users.password schema property

- applications/fax/src/fax_worker.erl
- core/kazoo_web/src/kz_http.erl
cc https://github.com/2600hz/kazoo/pull/3141
cc https://github.com/2600hz/kazoo/pull/3139
> HELP-27667 4oh

- applications/fax/src/fax_worker.erl
- core/kazoo_web/src/kz_http.erl
cc https://github.com/2600hz/kazoo/pull/3140
> HELP-27667: continuation of #3102

- applications/crossbar/src/modules_v2/cb_devices_v2.erl
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/knm_number_options.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_number_test.erl
- core/kazoo_number_manager/test/knm_release_number_test.erl
cc https://github.com/2600hz/kazoo/pull/3133
cc https://github.com/2600hz/kazoo/pull/3132
> KAZOO-5288_4oh_2nd: part 2 of #3133

- core/kazoo_number_manager/src/knm_telnyx_util.erl
- core/kazoo_number_manager/src/providers/knm_cnam_notifier.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_number_manager/src/providers/knm_telnyx_cnam.erl
- core/kazoo_number_manager/src/providers/knm_vitelity_cnam.erl
- core/kazoo_number_manager/test/knm_telnyx_test.erl
cc https://github.com/2600hz/kazoo/pull/3160
> KAZOO-5298: fix disabling CNAM feature

- .gitignore
- Makefile
- applications/blackhole/doc/README.md
- applications/callflow/doc/record_call.md
- applications/fax/doc/dns.md
- circle.yml
- doc/engineering/dialyzer.md
- doc/kazoocon/pivot2016.md
- doc/mkdocs/mkdocs.yml
- scripts/setup_docs.bash
Updates to the mkdocs index, as well as makefile targets for building the docs site locally
> Dev site index

- core/kazoo_config/src/kapps_account_config.erl
In `kapps_account_config:get_global` if `AccountId` is `undefined` or somehow is invalid, instead of crashing, returning the system wide config value.
For example in `kz_privacy` module for getting account's default config or system wide, don't fail if account id is not known.
> If AccountId is undefined or invalid, get system wide config instead

- applications/crossbar/src/modules/cb_tasks.erl
- applications/tasks/src/kz_task_worker.erl
- applications/tasks/src/kz_tasks_scheduler.erl
- applications/tasks/src/tasks_maintenance.erl
- core/kazoo_tasks/include/tasks.hrl
cc https://github.com/2600hz/kazoo/pull/3167
> HELP-27718_4oh: retry 3 times tasks output.csv uploads

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
cc https://github.com/2600hz/kazoo/pull/3173
cc https://circleci.com/gh/2600hz/kazoo/4491?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> qf-master: merge me @jamesaimonetti

- core/kazoo_data/src/kz_data.hrl
- core/kazoo_data/src/kz_datamgr.erl
- core/kazoo_data/src/kzs_db.erl
- core/kazoo_data/src/kzs_publish.erl
datamgr caching of db_exists requires it
explicit fails db_exists for 'other' dbs
> publish database create/delete

- core/kazoo_number_manager/src/carriers/knm_vitelity.erl
- core/kazoo_number_manager/src/knm_vitelity.hrl
Upgrades https://github.com/2600hz/kazoo/pull/3174
> KAZOO-5303: fix Vitelity response handling

- core/kazoo_number_manager/src/carriers/knm_vitelity.erl
- core/kazoo_number_manager/src/knm_vitelity.hrl
cc https://github.com/2600hz/kazoo/pull/3180
> KAZOO-5303_4oh: fix Vitelity response handling

- core/kazoo_number_manager/src/providers/knm_dash_e911.erl
cc https://github.com/2600hz/kazoo/pull/3206
> KAZOO-5312: fix encoding of error for dash e911

- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
cc https://github.com/2600hz/kazoo/pull/3204
> KAZOO-5313: port-in numbers must not have features & have state port_in

- applications/crossbar/src/modules_v2/cb_devices_v2.erl
> [master] no need to dry_run mdn

- core/kazoo_modb-1.0.0/src/kazoo_modb.erl
cc https://github.com/2600hz/kazoo/pull/3188
> HELP-27022_3.22: ensure views exist on MoDb creation

- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_signup.erl
- core/kazoo_data/src/kz_datamgr.erl
Important part: maybe_adapt_multilines
fixes port_request handling on master after https://github.com/2600hz/kazoo/pull/3204
> Revise from file

- applications/trunkstore/src/ts_from_onnet.erl
> fix clause

- core/kazoo_number_manager/src/knm_phone_number.erl
cc https://github.com/2600hz/kazoo/pull/3252
> HELP-27694: log more when updating number properties

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/doc/ref/phone_numbers.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/phone_numbers.json
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/include/knm_phone_number.hrl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_number_manager/src/providers/knm_rename_carrier.erl
- core/kazoo_number_manager/test/knm_telnyx_test.erl
cc https://github.com/2600hz/kazoo/pull/3247
> KAZOO-5290_4oh: temporary number feature to rename a number's carrier

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
- core/kazoo_config/src/kapps_config.erl
- core/kazoo_number_manager/doc/knm_bandwidth2.md
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_port_request.erl
cc https://github.com/2600hz/kazoo/pull/3267
> KAZOO-5345_4oh: fix port_in module name

- core/kazoo_number_manager/src/providers/knm_vitelity_cnam.erl
- core/kazoo_number_manager/src/providers/knm_vitelity_e911.erl
cc https://github.com/2600hz/kazoo/pull/3262
> KAZOO-5344_4oh: Fix - Vitelity CNAM and e911 API response handling

- core/kazoo_voicemail/src/kvm_message.erl
- core/kazoo_voicemail/src/kvm_messages.erl
- core/kazoo_voicemail/src/kvm_util.erl
> [4.0] handle properly copy/move from old modb to current modb (#3243)

- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_search.erl
- core/kazoo_number_manager/test/knm_bandwidth2_test.erl
- core/kazoo_number_manager/test/knm_phone_number_test.erl
- core/kazoo_number_manager/test/knm_telnyx_test.erl
- core/kazoo_number_manager/test/knm_voip_innovations_test.erl
cc https://github.com/2600hz/kazoo/pull/3263
> KAZOO-5341_4oh: fix KNM's is_dirty

- core/kazoo_config/src/kapps_config.erl
master: https://github.com/2600hz/kazoo/pull/3274
> KAZOO-5347_4oh: ensure dst gets written properly

- Makefile
- doc/.org/installation.org
- doc/installation.md
- doc/mkdocs/mkdocs.yml
The intent is to get Kazoo cloned and built on a local machine.
> Install guide cleanup

- core/kazoo_documents/src/kz_account.erl
4.0: https://github.com/2600hz/kazoo/pull/3292
> HELP-28155: do not cache failures of kz_account:fetch/1,2

- applications/tasks/src/kz_task_worker.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
- core/kazoo_number_manager/test/knm_phone_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3300
> KAZOO-5355: KNM fix set_created

- applications/crossbar/src/modules_v2/cb_limits_v2.erl
I would like to suggest to leak allow_postpay and max_postpay_amount fields
> KAZOO-5342: leak_max_postpay

- core/kazoo_endpoint/doc/formatters.md
- doc/mkdocs/mkdocs.yml
fixes link and adds to mkdocs index
> Fix formatter doc

- core/kazoo_config/src/kapps_account_config.erl
- core/kazoo_config/src/kapps_config.erl
- core/kazoo_config/src/kapps_config_util.erl
- core/kazoo_json/src/kz_json.erl
- core/kazoo_json/src/kz_json_schema.erl
- core/kazoo_json/test/kz_json_schema_test.erl
merged config for account (account/reseller/system/system_default)
> Merged config document for account with system defaults.

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.json
- applications/crossbar/priv/couchdb/schemas/callflows.page_group.json
* set uniqueItems for numbers
* page group
* update swagger
> Cf schema fix (#3309) - 4.0

- core/kazoo_number_manager/src/knm_port_request.erl
This only impacts current master (latest commit to master at this time: 21f8842e310c3c53ab44bd4758ed01887d72fecc)
> KAZOO-5365: fix handling port requests transition results

- applications/crossbar/src/crossbar_maintenance.erl
- applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
- applications/fax/src/fax_smtp.erl
- core/kazoo_number_manager/src/carriers/knm_carriers.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_search.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3288
> HELP-27694_4oh: exactly mimic v2 behavior

- make/deps.mk
- scripts/cover.escript
master: https://github.com/2600hz/kazoo/pull/3353
> qf-coveralls: upgrade coveralls-erl - 4.0

- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_port_request.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
- core/kazoo_number_manager/test/knm_port_request_test.erl
master: https://github.com/2600hz/kazoo/pull/3343
> HELP-28466_4oh: fix state picking when transitioning port request

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/doc/ref/phone_numbers.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/phone_numbers.json
- core/kazoo_number_manager/doc/knm_bandwidth2.md
- core/kazoo_number_manager/doc/knm_rename_carrier.md
- core/kazoo_number_manager/include/knm_phone_number.hrl
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_errors.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_number_manager/src/providers/knm_rename_carrier.erl
- core/kazoo_number_manager/test/knm_number_test.erl
- core/kazoo_number_manager/test/knm_reconcile_test.erl
- core/kazoo_number_manager/test/knm_telnyx_test.erl
master: https://github.com/2600hz/kazoo/pull/3347
> HELP-28353_4oh: schema for e911 region field

- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.tasks.numbers.json
- applications/tasks/src/modules/kt_numbers.erl
master: https://github.com/2600hz/kazoo/pull/3364
> HELP-27871 ~ 4.0

- core/kazoo_data/src/kz_datamgr.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
master: https://github.com/2600hz/kazoo/pull/3370
> qf-datamgr: export kz_datamgr:get_result_keys/2

- applications/crossbar/doc/authentication_configuration.md
- applications/crossbar/doc/multi_factor.md
- applications/crossbar/doc/ref/multi_factor.md
- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/account/auth.json
- applications/crossbar/priv/couchdb/schemas/auth_provider.json
- applications/crossbar/priv/couchdb/schemas/system_config.auth.json
- applications/crossbar/priv/couchdb/schemas/system_config.auth.mfa.json
- applications/crossbar/priv/couchdb/schemas/system_config.crossbar.auth.json
- applications/crossbar/src/crossbar_auth.erl
- applications/crossbar/src/modules/cb_multi_factor.erl
- core/kazoo_auth/doc/multi_factor.md
- core/kazoo_auth/priv/couchdb/providers/duo.json
- core/kazoo_auth/priv/couchdb/providers/google.json
- core/kazoo_auth/priv/couchdb/views/auth.json
- core/kazoo_auth/src/kazoo_auth.hrl
- core/kazoo_auth/src/kz_mfa_auth.erl
- core/kazoo_auth/src/mfa_provider/kz_mfa_duo.erl
- core/kazoo_auth/test/kz_duo_tests.erl
- core/kazoo_modb/priv/couchdb/views/auth.json
~~!! WIP, do not merge yet !!~~
Add support multi-factor authentication to `crossbar_auth` so that new tokens can be conditionally verified by external multi-factor services.
Implemented Duo 2FA as the first multi factor provider.
> KAZOO-5286: Multi factor authentication

- applications/crossbar/src/modules/cb_braintree.erl
- applications/crossbar/src/modules/cb_transactions.erl
- applications/jonny5/src/j5_per_minute.erl
- applications/jonny5/src/j5_util.erl
- applications/jonny5/src/jonny5_maintenance.erl
- applications/tasks/src/kz_account_crawler.erl
- applications/teletype/src/templates/teletype_low_balance.erl
- applications/teletype/src/templates/teletype_topup.erl
- core/kazoo_modb/src/kazoo_modb.erl
- core/kazoo_modb/src/kazoo_modb_maintenance.erl
- core/kazoo_services/src/kz_services.erl
- core/kazoo_services/src/kz_services_modb.erl
- core/kazoo_transactions/src/kazoo_transactions_maintenance.erl
- core/kazoo_transactions/src/kz_topup.erl
- core/kazoo_transactions/src/wht_util.erl
return error tuple back to caller to let them handle error logic
> HELP-27320: handle errors when can't get current balance

- applications/crossbar/src/modules/cb_accounts.erl
Leak correct reseller_id based on the account id on the request path.
> KAZOO-5148: leak correct reseller_id in cb_account

- applications/crossbar/src/modules/cb_accounts.erl
Leak correct reseller_id based on the account id on the request path.
backport of (#3362)
> [4.0] KAZOO-5148: leak correct reseller_id in cb_account

- applications/crossbar/src/modules/cb_braintree.erl
- applications/crossbar/src/modules/cb_transactions.erl
- applications/jonny5/src/j5_per_minute.erl
- applications/jonny5/src/j5_util.erl
- applications/jonny5/src/jonny5_maintenance.erl
- applications/tasks/src/kz_account_crawler.erl
- applications/teletype/src/templates/teletype_low_balance.erl
- applications/teletype/src/templates/teletype_topup.erl
- core/kazoo_modb/src/kazoo_modb.erl
- core/kazoo_modb/src/kazoo_modb_maintenance.erl
- core/kazoo_services/src/kz_services.erl
- core/kazoo_transactions/src/kazoo_transactions_maintenance.erl
- core/kazoo_transactions/src/kz_topup.erl
- core/kazoo_transactions/src/wht_util.erl
return error tuple back to caller to let them handle error logic
backport of (#3346)
> [4.0] HELP-27320: handle errors when can't get current balance (#3346)

- core/kazoo_transactions/src/wht_util.erl
fixes commit
https://github.com/2600hz/kazoo/commit/6b675b056e614baa9abb889b02432358e9d8ec2e
> fix wh_util:modb pattern match 4.0

- core/kazoo/include/kz_types.hrl
- core/kazoo_data/src/kz_data.hrl
- core/kazoo_data/src/kzs_util.erl
Conflicts:
core/kazoo_data/src/kz_data.hrl
> master: add provisioner database type

- core/kazoo_data/src/kzs_doc.erl
- core/kazoo_data/src/kzs_publish.erl
master: https://github.com/2600hz/kazoo/pull/3294
> KAZOO-5351_4oh: flush cache while AMQP publishes change

- applications/tasks/src/knm_number_crawler.erl
- applications/tasks/src/modules/kt_numbers.erl
- core/kazoo_number_manager/doc/carrier_types.md
- core/kazoo_number_manager/include/knm_phone_number.hrl
- core/kazoo_number_manager/src/carriers/knm_carriers.erl
- core/kazoo_number_manager/src/carriers/knm_inventory.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
> Help 27871 master

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.locality.json
- core/kazoo_number_manager/src/knm_config.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_release_number_test.erl
4.0: https://github.com/2600hz/kazoo/pull/3391
> HELP-27871: forward port of #3391 (do NOT save released numbers that resulted in deletion)

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/doc/ref/phone_numbers.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
4.0: https://github.com/2600hz/kazoo/pull/3392
> HELP-28336: forward port of #3392 (add per-number Sync API)

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.locality.json
- core/kazoo_number_manager/src/knm_config.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
Cause https://github.com/2600hz/kazoo/pull/3226 wasn't enough.
> HELP-27871_4oh: do NOT save released numbers that resulted in deletion

- applications/crossbar/src/api_resource.erl
- core/kazoo_csv/src/kz_csv.erl
- core/kazoo_modb/src/kazoo_modb_maintenance.erl
- core/kazoo_transactions/src/kazoo_transactions_maintenance.erl
Conflicts:
applications/crossbar/src/api_resource.erl
> HELP-28561: maintenance functions to audit balances

- core/kazoo_number_manager/priv/fixtures/old_vsn_1.1.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_2.1.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_2.2_in.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_2.2_out.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_2_in.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_3.1.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_3_in.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_4.1.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_4_out.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_5.1.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_6_out.json
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_bandwidth2_test.erl
- core/kazoo_number_manager/test/knm_carriers_find_test.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
- core/kazoo_number_manager/test/knm_move_number_test.erl
- core/kazoo_number_manager/test/knm_number_test.erl
- core/kazoo_number_manager/test/knm_numbers_test.erl
- core/kazoo_number_manager/test/knm_phone_number_test.erl
- core/kazoo_number_manager/test/knm_port_request_test.erl
- core/kazoo_number_manager/test/knm_reconcile_test.erl
- core/kazoo_number_manager/test/knm_release_number_test.erl
- core/kazoo_number_manager/test/knm_telnyx_test.erl
- core/kazoo_number_manager/test/knm_voip_innovations_test.erl
> qf-knm: forward port of #3384 (loads of tests and some fixes to KNM)

- applications/crossbar/src/modules/cb_callflows.erl
master: https://github.com/2600hz/kazoo/pull/3414
> only track assignments for reconcilable numbers (#3414)

- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/test/knm_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3413
> Lazedo patch 1 4oh (only adds tests)

- Makefile
cc https://github.com/2600hz/kazoo/pull/3417
> backport #3417 (use a tag for erlang.mk)

- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_number_manager/test/knm_number_test.erl
4.0 https://github.com/2600hz/kazoo/pull/3429
> qf-extfeat: allow setting external features by default

- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
> [4.0] tests for creating number with rename feature (#3431)

- applications/crossbar/src/modules/cb_pivot.erl
Also set debug_id for each log to fetch the debug details for old logs
> [master] KAZOO-5105: span to multiple modb when fetching pivot debug logs

- core/kazoo_web/src/kz_http.erl
It supported from 18.3 by httpc
> Add PATCH method to kz_http

- applications/crossbar/src/modules/cb_faxes.erl
- applications/fax/src/fax_smtp.erl
> HELP-28743 validate fax to_number is reconcilable

- applications/call_inspector/doc/README.md
- applications/call_inspector/src/call_inspector.hrl
- applications/call_inspector/src/parsers/ci_parser_freeswitch.erl
- applications/call_inspector/src/parsers/ci_parser_hep.erl
- applications/call_inspector/src/parsers/ci_parser_kamailio.erl
- applications/call_inspector/test/ci_parsers_test.erl
- make/kz.mk
master: https://github.com/2600hz/kazoo/pull/3452
> KAZOO-5403_4oh: fix & document call_inspector setup

- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- make/deps.mk
Renamed branch of https://github.com/2600hz/kazoo/pull/3435 cause of me not having my eyes open
> knm-paramig: parallel migration for KNM

- applications/callflow/src/cf_route_req.erl
- applications/doodle/src/doodle_route_req.erl
- core/kazoo_documents/src/kz_account.erl
- core/kazoo_documents/src/kzd_callflow.erl
- scripts/no_raw_json.escript
should close #3462 in favor of this approach
> add prepending of a preflow to a callflow

- core/kazoo_number_manager/priv/fixtures/old_vsn_7.1.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_7_in.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_7_out.json
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_util.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
- core/kazoo_number_manager/test/knm_phone_number_test.erl
- core/kazoo_number_manager/test/knm_telnyx_test.erl
- make/kz.mk
master: https://github.com/2600hz/kazoo/pull/3467
> KAZOO-5429: remove pvt CNAM features if they were manually stripped out

- core/kazoo/src/kz_util.erl
- core/kazoo_number_manager/priv/fixtures/old_vsn_5.1.json
- core/kazoo_number_manager/priv/fixtures/old_vsn_7.1.json
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_phone_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3472
> knm-tests_4oh: some more tests for kpn

- applications/tasks/src/modules/kt_services.erl
master: https://github.com/2600hz/kazoo/pull/3475
> qf-kt_srv-4oh: list descendants + current accounts

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
master: https://github.com/2600hz/kazoo/pull/3490
> KAZOO-5427_4oh: return account_id on identify number edge cases

- core/kazoo_number_manager/src/knm_phone_number.erl
master: https://github.com/2600hz/kazoo/pull/3487
> KAZOO-5431_4oh: expose carrier name in number metadata

- applications/tasks/src/modules/kt_numbers.erl
master: https://github.com/2600hz/kazoo/pull/3494
> KAZOO-5440: use masquerade for some KNM tasks

- applications/crossbar/doc/metaflows.md
https://github.com/2600hz/kazoo/blob/master/applications/konami/src/module/konami_callflow.erl#L36-L37
> looks like a typo

- applications/call_inspector/src/call_inspector_maintenance.erl
- applications/call_inspector/src/ci_datastore.erl
- applications/call_inspector/src/ci_filter_req.erl
- applications/call_inspector/src/ci_lookup_req.erl
- applications/call_inspector/src/parsers/ci_chunk.erl
- applications/crossbar/src/modules/cb_call_inspector.erl
- applications/crossbar/src/modules/cb_cdrs.erl
master: https://github.com/2600hz/kazoo/pull/3510
> dbg-ladder_4oh: use call_collect and fix filtering

- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
master: https://github.com/2600hz/kazoo/pull/3517
> KAZOO-5459_4oh: return e164 on all identify requests

- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/test/knm_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3493
> KAZOO-5439_4oh: have to_reserve(in_service) output reserved numbers

- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.teletype.json
- applications/teletype/src/teletype_util.erl
Parametrize kz_notification:is_enabled/2 default value in teletype_util:is_notice_enabled.
Set it to true by default.
backport of (#3533)
> [4oh] KAZOO-5421: HELP-28880: make is_notice_enabled a system parameter (#3533)

- applications/crossbar/src/modules/cb_services.erl
> [4.0] HELP-29133: fix audit view name, fix audit_logs pagination

- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_errors.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/knm_util.erl
- core/kazoo_number_manager/test/knm_move_number_test.erl
- core/kazoo_number_manager/test/knm_number_test.erl
- core/kazoo_number_manager/test/knm_phone_number_test.erl
- core/kazoo_number_manager/test/knm_port_request_test.erl
- make/kz.mk
> HELP-29314: don't contact external carriers for available nums & allow everyone to buy them

- core/kazoo_voicemail/src/kvm_message.erl
Try save document at 3 times if error is `timeout` or `conflict`.
Also archive the prepend message if merge audio files was unsuccessful, so it can be recovered later by sysadmin.
> HELP-29236: try to save voicemail at least 3 times

- applications/callflow/src/module/cf_park.erl
kamailio will handle this for fast pickup (a-leg=true)
> send parking app name in presence notification

- applications/call_inspector/src/call_inspector.hrl
- applications/call_inspector/src/ci_datastore.erl
- applications/call_inspector/src/parsers/ci_parsers_sup.erl
- applications/call_inspector/src/parsers/ci_parsers_util.erl
- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.call_inspector.json
- core/kazoo_ast/src/kz_ast_util.erl
master: https://github.com/2600hz/kazoo/pull/3566
> KAZOO-5468_4oh: call_inspector listens to configured servers on startup

- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
- core/kazoo_number_manager/src/knm_config.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_options.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/test/knm_release_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3539
> KAZOO-5447_4oh: fix KNM release (rm from prev_account_db + conflicts on deletion)

- applications/crossbar/src/crossbar_services.erl
> [4.0] Add ownerId to service audit log

- core/kazoo_voicemail/src/kvm_message.erl
Try save document at 3 times if error is `timeout` or `conflict`.
Also archive the prepend message if merge audio files was unsuccessful, so it can be recovered later by sysadmin.
backport of (#3534)
> [4.0] HELP-29236: try to save voicemail at least 3 times (#3534)

- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.provisioner.json
- applications/crossbar/src/modules/provisioner_v5.erl
- applications/crossbar/src/modules/provisioner_v5.hrl
master: https://github.com/2600hz/kazoo/pull/3588
> HELP-29207_4oh: send combo_keys to provisioner

- applications/callflow/src/module/cf_resources.erl
master https://github.com/2600hz/kazoo/pull/3599
> support dialplan for refers/redirects 4.0

- applications/ecallmgr/src/ecallmgr_registrar.erl
master https://github.com/2600hz/kazoo/pull/3603
> granular bridge_uri options - 4.0

- applications/ecallmgr/src/ecallmgr_originate.erl
Conflicts:
applications/ecallmgr/src/ecallmgr_originate.erl
> HELP-29668: add some time to allow overhead in originate

- core/kazoo_bindings/src/kazoo_bindings.erl
useful for debugging crashes (e.g. crashes in teletype modules)
> try to catche in kazoo binding for map

- applications/acdc/src/acdc_maintenance.erl
- applications/acdc/src/acdc_stats.erl
- applications/cdr/src/cdr.hrl
- applications/cdr/src/cdr_channel_destroy.erl
- applications/cdr/src/cdr_util.erl
- applications/crossbar/src/modules/cb_cdrs.erl
- applications/crossbar/src/modules/cb_sms.erl
- applications/doodle/src/doodle_util.erl
- applications/fax/src/fax_maintenance.erl
- applications/webhooks/src/webhooks_util.erl
- core/kazoo_bindings/src/kazoo_bindings.erl
- core/kazoo_media/src/kz_media_recording.erl
- core/kazoo_modb/src/kazoo_modb.erl
- core/kazoo_modb/src/kazoo_modb_view.erl
- core/kazoo_services/src/kz_services_modb.erl
- core/kazoo_voicemail/src/kvm_message.erl
- core/kazoo_voicemail/src/kvm_messages.erl
> [4.0] HELP-29570: use kazoo_modb for most modb ops

- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
> r-knm: faster cleaner pushing a collections reserve history

- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/test/knm_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3634
> knm-reserve_4oh: (and reconcile and create) fail if assign_to is not an account id

- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_numbers.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
- core/kazoo_number_manager/test/knm_numbers_test.erl
4.0 version coming up.
Please merge https://github.com/2600hz/kazoo/pull/3634 first!
> KAZOO-5493_master: KNM: no more picking state on account type

- core/kazoo_number_manager/include/knm_phone_number.hrl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_number_manager/src/knm.hrl
- core/kazoo_number_manager/src/knm_phone_number.erl
- core/kazoo_number_manager/src/providers/knm_providers.erl
master: https://github.com/2600hz/kazoo/pull/3646
> KAZOO-5494_4oh: maintenance functions to manage feature permissions

- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/test/knm_create_new_number_test.erl
master: https://github.com/2600hz/kazoo/pull/3642
> KAZOO-5493_4oh: KNM: no more picking state on account type

- make/deps.mk
> [master] KAZOO-5510: temprorary change inet_cidr repo

- applications/crossbar/src/modules/cb_media.erl
- applications/crossbar/src/modules/cb_modules_util.erl
- applications/crossbar/src/modules/cb_vmboxes.erl
- core/kazoo_media/src/kz_media_util.erl
> contain normalization result

- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.kapps_controller.json
- applications/crossbar/src/crossbar_init.erl
- core/kazoo/src/kz_network_utils.erl
- core/kazoo_media/src/kz_media_proxy.erl
> [4.0] use ping to detect ip family is supported or not

- applications/crossbar/priv/api/descriptions.system_config.json
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/system_config.fax.json
- applications/crossbar/priv/couchdb/schemas/system_config.notify.json
- applications/fax/src/fax_request.erl
- applications/fax/src/fax_smtp.erl
- applications/fax/src/fax_xmpp.erl
- applications/teletype/priv/templates/fax_outbound_smtp_error_to_email.html
- applications/teletype/priv/templates/fax_outbound_smtp_error_to_email.txt
- applications/teletype/src/teletype.hrl
- applications/teletype/src/teletype_shared_listener.erl
- applications/teletype/src/teletype_util.erl
- applications/teletype/src/templates/teletype_fax_outbound_smtp_error_to_email.erl
- applications/teletype/src/templates/teletype_topup.erl
- applications/teletype/src/templates/teletype_transaction.erl
- core/kazoo_amqp/src/api/kapi_notifications.erl
- core/kazoo_amqp/src/gen_listener.erl
- core/kazoo_amqp/src/listener_types.hrl
> Opentelecom smtp fax error notifications

- core/kazoo_apps/src/kapps_maintenance.erl
- core/kazoo_bindings/src/kazoo_bindings_sup.erl
- core/sup/priv/sup
- core/sup/rebar.config
- core/sup/src/sup.app.src
- core/sup/src/sup.erl
- rel/ci-sys.config
- scripts/check-release-startup.sh
- scripts/dev/README.md
- scripts/dev/sup.sh
backport of both https://github.com/2600hz/kazoo/pull/3666 and https://github.com/2600hz/kazoo/pull/3672
> rel-migrate_4oh: test release startup better + log sup usage

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/doc/ref/phone_numbers.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/phone_numbers.json
follow-up of https://github.com/2600hz/kazoo/pull/3655
> KAZOO-5500: use an enum instead

- core/kazoo_number_manager/src/knm_number_states.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
No 4.0 equivalent.
This is dangerous: it's possible that not enough test cases are written & so needs cocooning.
Please merge https://github.com/2600hz/kazoo/pull/3641 first!
> knm-auth: streamline knm_number_states auth logic

- applications/crossbar/doc/phone_numbers.md
- applications/crossbar/doc/ref/phone_numbers.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/phone_numbers.json
- applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
- applications/tasks/src/modules/kt_numbers.erl
- core/kazoo_number_manager/include/knm_phone_number.hrl
- core/kazoo_number_manager/src/carriers/knm_carriers.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/test/knm_carriers_find_test.erl
master: https://github.com/2600hz/kazoo/pull/3655
> KAZOO-5500_4oh: allow picking number state on creation

- core/sup/src/sup.erl
master: https://github.com/2600hz/kazoo/pull/3675
> KAZOO-5455_4oh: SUP output error codes

- core/kazoo_bindings/src/kazoo_bindings_sup.erl
- core/kazoo_token_buckets/src/kazoo_token_buckets_sup.erl
- rel/ci-config.ini
> change order of children for proper shutdown

- core/kazoo_number_manager/src/knm_numbers.erl
master: https://github.com/2600hz/kazoo/pull/3694
> qf-free_4oh: skip free-ing an account's numbers if something is wrong

- applications/crossbar/src/modules/cb_notifications.erl
and store the attachment db so no need to attempt to fetch attachment
from wrong db first if template metadata is from account
> read the attachment from system if template comes from system

- .gitignore
- applications/crossbar/src/crossbar_util.erl
- applications/crossbar/src/modules/cb_accounts.erl
- applications/crossbar/src/modules/cb_search.erl
- applications/tasks/src/modules/kt_cleanup.erl
- core/kazoo/include/kz_types.hrl
- core/kazoo_amqp/include/kz_amqp.hrl
- core/kazoo_amqp/src/kz_amqp_assignments.erl
- core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
- core/kazoo_proper/Makefile
- core/kazoo_proper/doc/README.md
- core/kazoo_proper/src/kazoo_proper.app.src
- core/kazoo_proper/src/kazoo_proper.hrl
- core/kazoo_proper/src/pqc_cb_accounts.erl
- core/kazoo_proper/src/pqc_cb_api.erl
- core/kazoo_proper/src/pqc_cb_phone_numbers.erl
- core/kazoo_proper/src/pqc_cb_response.erl
- core/kazoo_proper/src/pqc_cb_search.erl
- core/kazoo_proper/src/pqc_kazoo_model.erl
- core/kazoo_proper/src/pqc_util.erl
- core/kazoo_stdlib/src/props.erl
- core/kazoo_stdlib/test/kz_json_test.erl
- core/kazoo_stdlib/test/props_test.erl
- doc/mkdocs/mkdocs.yml
- make/kz.mk
Creates a framework for building PropEr based testing of Crossbar APIs, with basic testing of `/phone_numbers` as a start.
> PropEr testing

- core/kazoo_voicemail/src/kvm_message.erl
> [4.o] KAZOO-5513: move needs a new msg id

- applications/tasks/src/modules/kt_numbers.erl
- core/kazoo_number_manager/src/providers/knm_rename_carrier.erl
master: https://github.com/2600hz/kazoo/pull/3706
> KAZOO-5515_4oh: some number tasks things

- applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
master: https://github.com/2600hz/kazoo/pull/3718
> qf-knmv1_4oh: fix phone_numbers_v1 handling of collections

- applications/tasks/src/modules/kt_numbers.erl
- core/kazoo_number_manager/src/knm_number.erl
- core/kazoo_number_manager/src/knm_phone_number.erl
master: https://github.com/2600hz/kazoo/pull/3734
> qf-ktn_4oh: allow admins to import numbers as available

- applications/callflow/doc/ref/page_group.md
- applications/callflow/doc/ref/ring_group.md
- applications/callflow/src/module/cf_page_group.erl
- applications/callflow/src/module/cf_ring_group.erl
- applications/crossbar/doc/accounts.md
- applications/crossbar/doc/devices.md
- applications/crossbar/doc/dialplans.md
- applications/crossbar/doc/ref/accounts.md
- applications/crossbar/doc/ref/devices.md
- applications/crossbar/doc/ref/dialplans.md
- applications/crossbar/doc/ref/users.md
- applications/crossbar/doc/users.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.page_group.json
- applications/crossbar/priv/couchdb/schemas/callflows.ring_group.json
- applications/crossbar/priv/couchdb/schemas/dialplans.json
- applications/crossbar/src/modules/cb_presence.erl
- core/kazoo_ast/src/cb_api_endpoints.erl
Follow up on https://github.com/2600hz/kazoo/pull/3728
Side PR: https://github.com/2600hz/kazoo/pull/3736
> qf-swgg: fix last Swagger errors

- core/kazoo_number_manager/src/converters/knm_converters.erl
> Toll us classifier typo

- core/kazoo_config/src/kapps_config_util.erl
Sorry, introduced bug and would like to correct it
> Partial revert 2600hz/kazoo#3732

- applications/callflow/doc/ref/dynamic_cid.md
- applications/crossbar/priv/api/swagger.json
- applications/crossbar/priv/couchdb/schemas/callflows.dynamic_cid.json
Hi!
Looks like cf_dynamic_cid schema missed some action values 
https://github.com/2600hz/kazoo/blob/master/applications/callflow/src/module/cf_dynamic_cid.erl#L64-L76
Regards,
Kirill
> callflows.dynamic_cid.json - missed actions

- applications/crossbar/src/crossbar_app.erl
- applications/ecallmgr/src/ecallmgr_app.erl
master: https://github.com/2600hz/kazoo/pull/3726
> KAZOO-5492_4oh: declare exchange to handle check_sync messages

- applications/callflow/src/module/cf_move.erl
> HELP-29745_4oh: fix MOVEing call to a user's other device

- core/kazoo_data/src/kzs_db.erl
master: https://github.com/2600hz/kazoo/pull/3779
> KAZOO-5539_4oh: use are_equal, obvs

- applications/crossbar/src/cb_context.erl
- applications/crossbar/src/crossbar_doc.erl
- applications/crossbar/src/modules/cb_webhooks.erl
- applications/webhooks/src/webhooks_util.erl
- core/kazoo_ast/include/kz_ast.hrl
- core/kazoo_ast/src/kazoo_ast.erl
- core/kazoo_modb/priv/couchdb/views/webhooks.json
Keep filling up until page size is fulfilled
> HELP-29120: ignore query string filters when paginating

- core/kazoo_attachments/src/aws/kz_aws.erl
- core/kazoo_attachments/src/aws/kz_aws.hrl
- core/kazoo_attachments/src/aws/kz_aws_s3.erl
- core/kazoo_attachments/src/kz_att_s3.erl
. remove credential cache for now, it does not support multiple connections
. support scheme, host, port
. support bucket after host
. support base path
> s3 attachments update

- applications/crossbar/src/modules/cb_modules_util.erl
> quickcall device should merge endpoint properties

- applications/crossbar/src/modules/cb_modules_util.erl
> quickcall device should merge endpoint properties - 4.0

- applications/ecallmgr/src/ecallmgr_fs_event_stream.erl
also add logging to know when the channel_create has been noted in the
channels cache.
> HELP-30600: send channel_destroy to interested processes

- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/crossbar.hrl
Also replace empty json values with empty binary
> [master] HELP-30620: fix to_csv to join as binary

- applications/crossbar/src/api_resource.erl
- applications/crossbar/src/crossbar.hrl
> [4.0] HELP-30620: fix to_csv to join as binary

- applications/ecallmgr/src/ecallmgr_call_command.erl
- applications/ecallmgr/src/ecallmgr_util.erl
- core/kazoo_amqp/src/api/kapi_media.erl
- core/kazoo_media/src/kz_media_cache_sup.erl
- core/kazoo_media/src/kz_media_tts.erl
- core/kazoo_media/src/kz_media_tts_cache.erl
- core/kazoo_media/src/kz_media_url.erl
> [4.0] KAZOO-5469: associate voice and lang in cache key for tts

- core/kazoo_number_manager/src/knm.hrl
@fenollp why was this changed ?
https://github.com/2600hz/kazoo/pull/3801/commits/ac0064f26f707c0f0cc9a0d8d3b54eef8bb0fc39#diff-30bbb193c5dd633435e96e194508ef7aL59
either accept this commit or review make-busy incoming tests
> fix system default number features

- applications/acdc/src/acdc_queue_listener.erl
- applications/acdc/src/acdc_queue_manager.hrl
- applications/acdc/src/acdc_stats_etsmgr.erl
- applications/callflow/src/cf_task.erl
- applications/callflow/src/module/cf_camping_feature.erl
Just a couple dialyzer warnings resolved by updating type specs
> Fix some dialyzer warnings

- applications/callflow/src/module/cf_dynamic_cid.erl
> [4.0] KAZOO-5591: store cid_name in dynamic_cid as well

- applications/ecallmgr/src/ecallmgr_fs_node.erl
(replacing old PRs #3838 for 4.0 and #3834 for master)
> [master] KAZOO-5259: use federate to reload acls/send command
