2600hz/kazoo

applications/crossbar/src/crossbar_maintenance.erl

Must create account before user can be validated.
user validation success depends on the existance of views in an account database - that account database must first exist.

for create_account:

---

applications/cccp/src/cccp_callback_listener.erl
applications/cccp/src/cccp_platform_listener.erl

Small corrections to be able to pass gen_listener:start_link/3,4,5 guards introduced in "KAZOO-3249: added more types for gen_server" (1f642b639f33daa4d09a2e62067f58d3cc981a3e)
Please backport it to 3.19 since gen_listener changes were also backported

CCCP update2

---

applications/callflow/src/module/cf_eavesdrop.erl
applications/ecallmgr/src/ecallmgr_call_command.erl
core/whistle-1.0.0/src/api/wapi_dialplan.hrl
core/whistle_apps-1.0.0/src/whapps_call_command.erl

Hello @jamesaimonetti,
By some unknown reason (UFO invasion probably) our version of eavesdrop callflow modules and one we've contributed differs significantly. We had to fix ecallmgr a bit to make it possible for calls to be routed to some specific FS node.
As always - you feedback is greatly awaited and appreciated.
Thanks!

KAZOO-3293: update eavesdrop to current state

---

applications/crossbar/doc/internationalization/numbers.md
core/whistle_number_manager-1.0.0/src/wnm_util.erl

It appears the defaults stored in whapps_config are automatically updated, so no need to flush the defaults in ETS.

KAZOO-3170: add a master capture group to phone number regexes

---

applications/hangups/doc/index.md
applications/hangups/src/hangups_channel_destroy.erl

2 new fields are added to hangups' system_config:
* `enable_email_alerts` :: `boolean()`: `true` means receiving emails
on hangups alerts (this is the legacy behaviour).
* `subscriber_url` :: `string()`: when non-empty will be used to send
hangups alerts as JSON in a HTTP POST request.
When both alert methods are deactivated, email is used.

KAZOO-3235: POST hangups JSON data to a URI.

---

applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/modules_v1/cb_users_v1.erl
applications/crossbar/src/modules_v2/cb_users_v2.erl
applications/notify/src/notify_account_crawler.erl
applications/teletype/src/teletype_util.erl
core/whistle_couch-1.0.0/src/couch_util.erl
core/whistle_media-1.0.0/src/wh_media_util.erl
core/whistle_services-1.0.0/src/wh_service_sync.erl
core/whistle_services-1.0.0/src/wh_services.erl

During "code roaming" I noticed a function `wh_doc:is_soft_deleted/1` I could have used on my very first PR to this project.
I found out it was only called once, while making code easier to read. (yes, by hiding stuff out…)
So I pulled this together quickly to see what you guys thought.
There are a couple cases left. I'm not patching those lines as I'm getting too tired and not sure I get the logic:
```erlang
applications/crossbar/src/crossbar_doc.erl:910:                   wh_json:is_false(<<"pvt_deleted">>, JObj, 'true')
applications/crossbar/src/crossbar_doc.erl:925:                   wh_json:is_false(<<"pvt_deleted">>, JObj, 'true')
```
Here is how I found what to patch:
```shell
git grep -n '<<"pvt_deleted">>'
```

Refactor: call wh_doc:is_soft_deleted/1

---

applications/callflow/src/cf_util.erl
core/whistle-1.0.0/src/wh_call_response.erl
core/whistle_apps-1.0.0/src/whapps_call_command.erl
core/whistle_apps-1.0.0/src/whapps_maintenance.erl
core/whistle_media-1.0.0/src/wh_media_util.erl

After conversing with @jamesaimonetti I resolved to cleanup `system_media` lines that could be found on older systems [as per this code](https://github.com/2600hz/kazoo/commit/3ca29dbc7a2ac0f806de92949d33c87cf56dd3aa)
After conversing with @k-anderson I made it so `wh_call_response:send*` accepts a `whapps_call` while providing the old interface to `trunkstore` functions.

KAZOO-3377

---

applications/crossbar/src/modules/provisioner_util.erl
applications/crossbar/src/modules/provisioner_v5.erl
applications/crossbar/src/modules_v1/cb_devices_v1.erl
applications/crossbar/src/modules_v2/cb_devices_v2.erl

* If needs be, do a REST request to see to whom a MAC address may belong to
* Check and context modification happens in `cb_devices*`
* REST request is implemented in provisioner_v5
* cb_provisioner_util handles API compatibility
Note: this is paired with https://github.com/2600hz/provisioner/commit/356bf0dc71b982b56404f640b40f91bf2669a21d

KAZOO-3386: push device to provisioner iff its MAC belongs to no one

---

applications/crossbar/src/crossbar_maintenance.erl

Found this while looking for a reason for a bug I had (turned out I needed to refresh the schemas).
These changes follow those I made in https://github.com/2600hz/kazoo/pull/831

Shortcut code: app.json is already known to exist

---

core/whistle_media-1.0.0/src/wh_media_recording.erl
core/whistle_media-1.0.0/src/wh_media_util.erl
core/whistle_media-1.0.0/src/whistle_media.hrl
core/whistle_media-1.0.0/src/whistle_media_maintenance.erl

`WHS_CONFIG_CAT` was set both in `whistle_media.hrl` and `whistle_services.hrl`, to different values.
`WHM_CONFIG_CAT` was not taken.
```
1
```
(hence the *potential*)

Remove potential macro clash in media CONFIG_CAT

---

applications/callflow/src/module/cf_record_call.erl
applications/callflow/src/module/cf_record_caller.erl
applications/ecallmgr/src/ecallmgr_call_events.erl
core/whistle_media-1.0.0/src/wh_media_recording.erl

* Already handled in `ecallmgr_call_events`
* commit 2466cef0ab4c655c0abdd8943a47fab52257a96d
* Now handle it prior in `cf_record_call`
* Log it as an error
* Let callflow execution continue
* Send a system_alert

KAZOO-3385: don't crash when missing url in misconfigured call record

---

applications/callflow/src/module/cf_resources.erl
applications/ecallmgr/src/ecallmgr_fs_authz.erl
core/whistle-1.0.0/src/wh_call_response.erl
core/whistle_apps-1.0.0/src/whapps_call.erl
core/whistle_media-1.0.0/src/wh_media_util.erl

The main issue was already addressed and no longer an issue; however, there was an issue found accessing the prompt when playing failure-to-route prompts. This has been addressed (doesn't allow double-encoding).

Kazoo 3423

---

applications/callflow/src/cf_attributes.erl
applications/crossbar/doc/phone_numbers.md
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar_freeswitch.erl
applications/crossbar/src/modules/cb_api_auth.erl
applications/crossbar/src/modules/cb_port_requests.erl
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
core/whistle_number_manager-1.0.0/doc/number_states.md
core/whistle_number_manager-1.0.0/include/wh_number_manager.hrl
core/whistle_number_manager-1.0.0/src/carriers/wnm_bandwidth.erl
core/whistle_number_manager-1.0.0/src/carriers/wnm_inum.erl
core/whistle_number_manager-1.0.0/src/carriers/wnm_local.erl
core/whistle_number_manager-1.0.0/src/carriers/wnm_managed.erl
core/whistle_number_manager-1.0.0/src/providers/wnm_cnam_notifier.erl
core/whistle_number_manager-1.0.0/src/providers/wnm_dash_e911.erl
core/whistle_number_manager-1.0.0/src/providers/wnm_failover.erl
core/whistle_number_manager-1.0.0/src/providers/wnm_port_notifier.erl
core/whistle_number_manager-1.0.0/src/providers/wnm_prepend.erl
core/whistle_number_manager-1.0.0/src/providers/wnm_vitelity_cnam.erl
core/whistle_number_manager-1.0.0/src/providers/wnm_vitelity_e911.erl
core/whistle_number_manager-1.0.0/src/wh_number_fix.erl
core/whistle_number_manager-1.0.0/src/wh_number_manager.erl
core/whistle_number_manager-1.0.0/src/wnm.hrl
core/whistle_number_manager-1.0.0/src/wnm_number.erl

If the system is configured to do so, instead of moving a number to 'disconnected' move it to 'deleted' for subsequent hard-removal from the system.

Kazoo 3396 - move number to deleted state

---

applications/callflow/src/module/cf_voicemail.erl

This will correctly pronounce count of messages in Russian (and other) language.

Use "messages" as say_type when saying message count

---

applications/crossbar/priv/couchdb/schemas/resources.json
applications/ecallmgr/src/ecallmgr_fs_authn.erl
applications/ecallmgr/src/ecallmgr_fs_route.erl
applications/ecallmgr/src/ecallmgr_registrar.erl
applications/ecallmgr/src/ecallmgr_util.erl
applications/stepswitch/src/stepswitch_resources.erl
core/whistle-1.0.0/src/api/wapi_authn.erl
core/whistle-1.0.0/src/api/wapi_route.erl
core/whistle-1.0.0/src/api/wapi_sms.erl

Added fields "port" and "force_port" in the documents of resources.
At outgoing call field "port" is added to the SIP URI.
At incoming call (if "force_port" = true), the source port is compared with the field of "port".
This allows at one IP-address have multiple gateways separated on different ports.
To work correctly, also requires changes in the configuration file kamailio.
File "default.cfg":
```
route[EXTERNAL_TO_INTERNAL_RELAY]
...
remove_hf_re("^X-.*");
append_hf("X-AUTH-IP: $si\r\n");
append_hf("X-AUTH-PORT: $sp\r\n"); <--- add this!!!
```

Gateway dst/src port

---

applications/acdc/src/acdc_agent_fsm.erl
applications/callflow/src/cf_attributes.erl
applications/callflow/src/cf_util.erl
applications/callflow/src/module/cf_camping_feature.erl
applications/callflow/src/module/cf_eavesdrop.erl
applications/crossbar/src/crossbar_freeswitch.erl
applications/crossbar/src/modules/cb_onboard.erl
applications/crossbar/src/modules/cb_rate_limits.erl
applications/crossbar/src/modules/provisioner_util.erl
applications/crossbar/src/modules/provisioner_v5.erl

Found the culprits with:
$ cd /opt/kazoo/
$ git grep -InE '<<"(username|password)">>' | grep '<<"sip">>'

KAZOO-3532: use a device's getters and setters instead of less clear code

---

applications/crossbar/src/crossbar_maintenance.erl

Modified the context from C1 to C3.

KAZOO-3543: account promotion failing due to invalid context

---

core/whistle_apps-1.0.0/src/whapps_maintenance.erl

When start whistle_apps with empty DB, whapps_maintenance:refresh() hangs on delete_system_media_references()

FIX: unable refresh without system_config/call_response document

---

deps/couchbeam-0.8.0/src/couchbeam_json_stream.erl

After https://github.com/2600hz/kazoo/commit/90b035c8a32065e7197e31be28120ec2a78847c6 broken fetch UTF-data when chnuks not alligned to border of UTF-character.
For example if this UTF-data
**"\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u044f"**
splitted in 2 chunks
**"\u041e\u0441\u04"** and **"3d\u043e\u0432\u043d\u0430\u044f"**
we got error
couch_util:445 (<0.23294.0>) unformatted error: {parse_error,bad_escape}

Fetch more data for incomplete unicode characters

---

applications/callflow/src/module/cf_record_call.erl
core/whistle_media-1.0.0/src/wh_media_recording.erl

1. Store recording file on call stop, only if we started recording early.
2. When store file to 'local' DB dont append filename to Url (its already here).
3. Store to third_party only when enabled store_recordings and set third_party_bigcouch_host

Fix recording

---

applications/acdc/src/acdc_agent_fsm.erl
applications/acdc/src/acdc_agent_listener.erl
applications/acdc/src/acdc_util.erl

Hello,
We are trying to make it possible to transfer ACDC-managed calls (e.g. transfer to another queue). It works but demonstrates wierd behaviour at rare cases: when first transfer to another queue works ok as does the second one, but the third one fails. The agent FSM acts in wrong way and the state is wrong. Probably we are not unsubscribing from AMQP or something like that.... we have a little trouble here due to lack of deep knowledge of ACDC guts. Can you suggest something?
Logs attached to JIRA ticket.

KAZOO-3565: acdc attended transfer

---

applications/crossbar/src/modules/cb_notifications.erl

I know using process dictionary is not the best way but as I dont have access to the context. The only solution would be after loading the view which would mean that I have to re-do the resp breaking the paginations and stuff ...

KAZOO-3504: Not loading skel/system notifications for non system admins

---

applications/crossbar/src/modules_v1/cb_devices_v1.erl

1. ~~I'm not sure I should patch `v2`, but did it anyway (bulk edit is only on kazoo-ui AFAICT, and kazoo-ui uses v1)~~
2. ~~Should I put code shared by `cb_devices_v1` and `cb_devices_v2` in `cb_devices_utils`?~~

KAZOO-2143: load db_doc to fix bulk edit

---

applications/acdc/src/acdc_agent_util.erl
applications/acdc/src/acdc_stats_util.erl

If the agent did not have a status update for the month, stored in the modb, the lookup would return an empty list and the agent would default to "ready" state. Search now includes the previous modb if it exists, fails to old default (ready state)

Check previous modb when determining initial agent status

---

applications/acdc/src/acdc_queue_fsm.erl
applications/acdc/src/acdc_queue_listener.erl

If an agent's ring timer was not timed out but the queue's timeout gets hit, there is a chance that the agent can answer their phone after the queue timed out. This would cause odd bridging issues and stuck calls in the kazoo-ui (stats module)

Resolved issue with agent origination continuing after queue timeout

---

applications/callflow/src/module/cf_collect_dtmf.erl

If DTMF is entered prior to the noop being sent to the cf_tts module, they are put into a collection that is read at the start of cf_collect_dtmf. However, it did not consider that the user may have already entered MaxDigits and that the execution should not go into whapps_call_command:collect_digits. If it did, it would await a noop that would cause the default timeout to be 1 day. Thus, even if MaxDigits was entered, they would still be waiting for DTMF timeout.

Handle DTMF digits properly after TTS module

---

applications/callflow/src/callflow_maintenance.erl
applications/callflow/src/cf_util.erl

When adding feature codes, kazoo-ui would send a too-greedy regex
(See featurecode.js, end of the last line).
If one cannot add feature code `*56` after `*5` is there, one has
to run `sup callflow_maintenance update_feature_codes {Account}`
then re-add `*56`.

KAZOO-3122: maintenance tool to update feature code patterns

---

applications/jonny5/src/j5_authz_req.erl
applications/jonny5/src/j5_request.erl

Currently even with authz_local_resources set to true, calls placed to local number resources do not  consume an inbound trunk.  This commit addresses this issue. With "authz_local_resources" will now be checked,  if true (for individual node or default) AND the number is local, authz will process the call for authorization.
This commit is an enhancement to "https://github.com/2600hz/kazoo/pull/502" since it now validates the configuration parameters on a per node basis.

"authz_local_resources" .. support for node specific configuration

---

applications/callflow/doc/record_call.md
applications/callflow/src/module/cf_record_call.erl
applications/crossbar/priv/couchdb/schemas/callflows.record_call.json
applications/ecallmgr/src/ecallmgr.hrl
applications/ecallmgr/src/ecallmgr_call_command.erl
core/whistle-1.0.0/src/api/wapi_dialplan.hrl
core/whistle_apps-1.0.0/src/whapps_call_command.erl
core/whistle_media-1.0.0/src/wh_media_recording.erl
core/whistle_media-1.0.0/src/whistle_media.hrl

FS by default drop record files shorten than 3 seconds. https://wiki.freeswitch.org/wiki/Variable_record_min_sec.
I add `record_min_sec` option for `record_call` module to set minmum recording time.

Record min sec

---

applications/stepswitch/src/stepswitch_sup.erl

Bind only to "resource".
"Numbers" and "dedicated_ip" not bounded, and not catch changes in this documents.

Incorrect binding declaration.

---

applications/callflow/src/module/cf_disa.erl

Since we always have AccountId that will point to the number owner we should use it to lookup caller id instead of caller_id_number. Old version was trying to find AccountId by caller_id_number, but that number can be anything and not always in our number inventory and assigned to any account.

Fix for DISA setting caller id

---

scripts/sup-build-autocomplete.escript

This needs to be bound to Bash at some point. For now it does not generate a bash completion file.
After some talk with @k-anderson we noted we could also need a way to have documentation hints displayed on tab-completion or when typing `?` then `[enter]`

sup-autocompleter: parse maintenance BEAMs to extract M:F(Args)

---

applications/crossbar/priv/couchdb/schemas/users.json
applications/crossbar/priv/couchdb/schemas/webhook_attempts.json

Add presence_id to users schema. If this value set to integer (monster-ui do it at some circumstances) then `cf_attributes:presence_id/2` is crashed wen try `binary:match(PresenceId, <<"@">>)`.
Add missing coma in webhooks_attemps schema.

Fixes to schema.

---

applications/crossbar/doc/token_restrictions.md
applications/crossbar/priv/couchdb/schemas/token_restrictions.json
applications/crossbar/src/crossbar.hrl
applications/crossbar/src/crossbar_util.erl
applications/crossbar/src/modules/cb_token_auth.erl
applications/crossbar/src/modules/cb_token_restrictions.erl

Each auth type method have own restrictions and one default restriction.
"cb_api_auth_restrictions", "cb_user_auth_restrictions", ... - for each auth method.
"restrictions" - default restrictions if no match auth method.
Macroses {ACCOUNT_ID} and {USER_ID} replaced with <<"account_id">> and <<"owner_id">> from cb_context:doc(Context) when creating auth_token.
Each priv_level have own template for restrictions.
You can create as many priv_level as you wish ("operator" - wich can modify users, but cant modify account).
Example token_restrictions template
system_config / crossbar.token_restrictions
``` JSON
{
"_id": "crossbar.token_restrictions",
"_rev": "5-c4955b161980d140cd49ec60c3e3575d",
"default": {
"restrictions": {
"*": {
"*": [
"#"
]
}
},
"cb_user_auth_restrictions": {
"*": {
"get": …
```

Add systemwide token restrictions.

---

applications/crossbar/priv/couchdb/account/users.json

Setting enabled field to 'false' in user's doc prevents user associated devices from outbound calling which is great :) 
But still user can authenticate through crossbar's user_auth. 
There could be some reasons for such a behavior which I just can't see, but from the very first look web/api access should also be restricted for blocked user. 
Please consider to accept if it make sense
Regards,

KAZOO-3872

---

core/braintree-1.0.0/src/braintree_card.erl
core/braintree-1.0.0/src/braintree_customer.erl
core/braintree-1.0.0/src/braintree_subscription.erl

Also this needs to be cherry picked to 3.20 I beleive

KAZOO-3812: update braintree subscriptions instead of re-creating them

---

applications/callflow/src/module/cf_cidlistmatch.erl
applications/crossbar/doc/lists.md
applications/crossbar/priv/couchdb/account/lists.json
applications/crossbar/priv/couchdb/schemas/list_entries.json
applications/crossbar/priv/couchdb/schemas/lists.json
applications/crossbar/src/crossbar_maintenance.erl
applications/crossbar/src/modules_v1/cb_lists_v1.erl
applications/crossbar/src/modules_v2/cb_lists_v2.erl
core/kazoo_documents-1.0.0/test/kzd_user_test.erl

I added tests for `kzd_users.erl` to this commit.
For using `lists/crossbar_listing` couchdb view (this means "v1 API") you should add
```ini
[query_server_config]
reduce_limit = false
```
to `/etc/kazoo/bigcouch/local.ini`
And this commit brokes v1 API compatibility:
It was allowed to add/update `lists` with `enries` and their IDs in old API.
This ability allowed to have different `entries` with same IDs in different `lists`.
Now `list entry` is separate document, so I wanted prevent ability to rewrite `list entries` when updating `list`.

KAZOO-3774: get list_entries vcard

---

applications/crossbar/src/modules/provisioner_v5.erl

This will need to be backported to 3.19+

KAZOO-3993: if configured include a cluster_id in the request

---

applications/crossbar/src/modules/cb_token_auth.erl

This will need to be backported to 3.19+

KAZOO-3992: fix token_auth DELETE and add GET

---

applications/stepswitch/src/stepswitch_resources.erl

Also, fixes an offnet cache origin issue that inhibited the resource document from flushing when modified (discovered while testing).

KAZOO-3999: update resource gateways with prefix/suffix from classfier

---

core/whistle_media-1.0.0/src/wh_media_recording.erl

If used "record on answer", and call go down without answer, wh_media_recording process is staying alive forever.

Shutown if received 'stop_call' and no recording is started.

---

applications/jonny5/src/j5_channels.erl

After 6b33a8ef1953b28c7e413344761ef6d232399ec2 and 246a91cdfdb9f5092316d9e553bf48e1306a7a6c in authz.resp added Custom-Channel-Vars
Before this commits CCVs was empty and it replaced by JObj. And all data get from CCVs.
After commits in CCVs was only trunk data, and no "Account-Billing", "Reseller-Billing" etc.

Fix j5_channels

---

applications/callflow/src/module/cf_collect_dtmf.erl

We've previously encountered the issue described at:
https://groups.google.com/forum/#!topic/2600hz-dev/IVIk6Rt8Li4
The previous set of code for cf_collect_dtmf would utilize digits entered early, but not purge them so the next cf_collect_dtmf would be clean

Resolved DTMF ending up in default key when entered quickly

---

applications/crossbar/src/modules/cb_cdrs.erl

Recording url is removed from `custom_channel_vars` to root in `cdr_channel_destoy:set_recording_url/3`

KAZOO-4085: crossbar:cb_cdrs fixing recording url

---

applications/callflow/src/cf_route_win.erl

Undo fix b6374a997701f9223b0eed684ae26cc60abe032c
Already fixed in 50fd2d86634200e38ac1534319874b5bc6b03f3e (KAZOO-3439)

Undo fix double prepend cid

---

applications/fax/src/fax_smtp.erl
applications/fax/src/fax_worker.erl

the sup maintenance commands that already exist are.
```
sup fax_maintenance restart_job JobId
sup fax_maintenance update_job JobIs State
sup fax_maintenance account_jobs AccountId
sup fax_maintenance account_jobs AccountId State
sup fax_maintenance faxbox_jobs FaxboxId
sup fax_maintenance faxbox_jobs FaxboxId State
sup fax_maintenance pending_jobs
sup fax_maintenance active_jobs
```
@k-anderson 
@dschreiber what other tools may we need ?

KAZOO-4130: as a fax user i want more control and log of processing faxes

---

applications/omnipresence/src/omnip_subscriptions.erl
applications/omnipresence/src/omnip_sup.erl
applications/omnipresence/src/wapi_omnipresence.erl

load omnipresence modules from configuration so we can disable omnip_presence
KAZOO-4138 - fixes notify exchange
do not publish internal subscribe if there is only one omnipresence server

KAZOO-4137 KAZOO-4138

---

applications/callflow/src/cf_exe.erl

This was originally from https://github.com/2600hz/kazoo/pull/1056.
However, that was issued against 3.20 and we need to target master.  Attempting merge resulted in conflicts so I corrected those and opened a new PR.  This also removes the need for https://github.com/2600hz/kazoo/pull/1258.
@danielfinke made this point way back on May 22 however it was not until PR #1258 that we internally discussed the merits of both approaches.  This resulted in a reversing our prior reluctance on #1056 and this PR was the result!

cf_exe captures CHANNEL_DESTROY to prevent continuing after hangup

---

applications/ecallmgr/src/ecallmgr_fs_xml.erl
core/whistle-1.0.0/src/api/wapi_dialplan.hrl

Freeswitch requires group_* values to be in the global variables of the bridge to work.
Until now, these values were only in CCVS because it was for forwarded calls only. It worked because it uses a loopback.
If we want to be able to do it on regular bridges, this change is needed.

Support for call confirmation on non forwarded calls

---

applications/trunkstore/src/ts_util.erl

#1256 against master
Conflicts:
applications/trunkstore/src/ts_util.erl

Call restriction no longer missing when using ts_from_onnet

---

core/whistle_media-1.0.0/src/wh_media_util.erl

Little fix.
For wh_media_util:prompt_language(<<"system_meida">>) dont try <<"system_meida">> as account ID and always use default_prompt_language() for it.

For "system_media" use default_prompt_language()

---

core/whistle-1.0.0/src/api/wapi_conf.erl
core/whistle-1.0.0/src/wh_cache.erl
core/whistle_amqp-1.0.0/src/amqp_util.erl
core/whistle_couch-1.0.0/src/couch_util.erl

Notification on DB create/delete.
wh_cache binding for database create/delete notififcations.
wh_cache auto-add origins for DB.
Flush cache entry on dtabase create/delete.

wh_cache flush entry on DB create/delete

---

core/whistle_apps-1.0.0/src/whapps_speech.erl

Media conversion had wrong variable - would convert to same type as original type
Badmatch error in attempt_asr_freeform
Moved to rest API for ispeech as the JSON API was always replying incorrectly

Fixed cf_voicemail ASR

---

applications/acdc/src/acdc_agent_fsm.erl

Right now, if an agent pauses during the wrapup state, their acdc_agent_stat gets set to paused, but their acdc_agent_fsm remains in wrapup. This PR fixes the behaviour

Allow agents to pause from wrapup

---

applications/webhooks/src/webhooks_listener.erl

```
Oct  1 19:03:41 dev 2600hz[5506]: |webhooks_listener|webhooks_listener:189 (<0.27433.2>) removing hook 0ee2d697cd6d7698cf9e0a3719fc0df5.700c8b2238fc1d52a53683797623b67a
Oct  1 19:03:41 dev 2600hz[5506]: |webhooks_listener|gen_listener:993 (<0.27433.2>) handle_cast exception: error: function_clause
Oct  1 19:03:41 dev 2600hz[5506]: |webhooks_listener|wh_util:140 (<0.27433.2>) stacktrace:
Oct  1 19:03:41 dev 2600hz[5506]: |webhooks_listener|wh_util:149 (<0.27433.2>) st: webhooks_listener:remove_shared_bindings at 282
Oct  1 19:03:41 dev 2600hz[5506]: |webhooks_listener|wh_util:150 (<0.27433.2>) args: {webhook,<<"0ee2d697cd6d7698cf9e0a3719fc0df5.700c8b2238fc1d52a53683797623b67a">>,<<"http://localhost:8100/test.php">>,get,<<"callflow">>,<<"700c8b2238fc1d52a53683797623b67a">>,1,<<"0ee2d697c …
```

Fix function clause on removing webhooks.

---

applications/acdc/src/acdc.hrl
applications/acdc/src/acdc_queue_fsm.erl
applications/acdc/src/acdc_queue_listener.erl
applications/acdc/src/acdc_queue_manager.erl

If queue has enter_when_empty disabled, queue callers skip entering the queue in cf_acdc_member. However, if the caller enters the queue and all remaining agents subsequently leave the queue, the caller waits, potentially to the queue timeout. This pull request modifies the behaviour of the queue so that with enter_when_empty disabled, queue callers will abort the queue if all its agents log out.

Bump queue callers out of the queue when empty

---

applications/crossbar/doc/notifications.md
applications/crossbar/src/modules/cb_cdrs.erl
applications/crossbar/src/modules/cb_faxes.erl
applications/crossbar/src/modules/cb_jobs_listener.erl
applications/crossbar/src/modules/cb_notifications.erl
applications/crossbar/src/modules/cb_resources.erl
applications/crossbar/src/modules/cb_sms.erl
applications/doodle/src/doodle_doc_handler.erl
applications/doodle/src/doodle_maintenance.erl
applications/doodle/src/doodle_util.erl
applications/fax/src/fax_request.erl
applications/fax/src/fax_smtp.erl
applications/fax/src/fax_util.erl
applications/teletype/src/teletype_util.erl
core/kazoo_modb-1.0.0/priv/couchdb/views/faxes.json
core/kazoo_modb-1.0.0/priv/couchdb/views/notifications.json
core/kazoo_modb-1.0.0/src/kazoo_modb.erl
core/kazoo_modb-1.0.0/src/kazoo_modb_maintenance.erl
core/kazoo_modb-1.0.0/src/kazoo_modb_util.erl
core/whistle-1.0.0/include/wh_types.hrl
core/whistle-1.0.0/src/wh_util.erl
core/whistle_apps-1.0.0/src/whapps_util.erl
core/whistle_couch-1.0.0/src/couch_util.erl

WIP
Also, in `cb_faxes` one can fetch `smtplog`s per-`Id`.
Should I implement the same API in `cb_notifications`?

KAZOO-4108: fetch logs from notifications, consistently to the fax smtplog API

---

applications/crossbar/src/modules/cb_allotments.erl

After 64ac39b01c3a307ce1ebc9da76981ddda6fbac15 always get 500 error on `allotments/consumed`

Restore work allotments/consumed

---

core/whistle_media-1.0.0/src/wh_media_recording.erl

After 629087bcf65ac1c6b962eca7d05e9007b12aa776 `wh_util:format_account_id/2` return encoded Account DB, not Account MODB.

wh_util:format_account_id/2 -> wh_util:format_account_modb/2

---

applications/blackhole/doc/index.md
applications/blackhole/src/blackhole_socket_callback.erl

As a reseller I would like to monitor accounts' calls with blackhole. 
When I am choosing one account after another I need to remove bindings used to listen for previous account's events

KAZOO-4292: blackhole clear_subscriptions event

---

applications/callflow/src/cf_exe.erl
applications/callflow/src/module/cf_park.erl

define children with SlotNumber to allow callflow continuation per slot
or define wildcard "_" to allow for all slots

KAZOO-4224 allow cf_park to continue when callback is not answered

---

applications/jonny5/src/j5_request.erl
applications/stepswitch/src/stepswitch_resources.erl
core/kazoo_documents-1.0.0/src/kzd_freeswitch.erl

E164-Destination precedence for authz/rating
Original-Number is set from Original Request
Add Matched-Number (value taken from former Original-Number)

HELP-19461 clarify usage of stepswitch resource properties

---

applications/crossbar/doc/reverse_proxy.md
applications/crossbar/src/api_resource.erl

Any client can set "X-Forward-For" header, and Crossbar accept this request, and set #context.client_ip to value of this header.
This allow avoiding token buckets and authenticate with cb_ip_auth from any address.

Allow "X-Forward-For" only from allowed proxies

---

core/whistle_services-1.0.0/src/wh_services.erl

Correctly typo in previous pull request.
Should be
Balance - Amount >= 0;
Now the function will return true when deducting the charge from the balance and the resulting balance is greater than or equal to zero

KAZOO-4451 - check_bookkeeper incorrect

---

applications/hotornot/src/hon_util.erl

I believe what was there before was wrong, but I'm not certain - I have a really hard time getting my head around comparison functions.
In rates.json the description field says that lower weights are preferred over higher ones, but this implies otherwise.

Update hon_util.erl to fix priorities

---

applications/omnipresence/src/omnip_subscriptions.erl

when a UA changes the kamailio server between subscriptions but keeps the callid we need to update the stalker and contact

omnipresence : fix subscription updates

---

applications/callflow/src/module/cf_callflow.erl

since 3.22, the module would not be executed if the channel is destroyed, so there's no need to check it status.
to be backported to 3.22

HELP-20384 no need to check channel status

---

core/whistle_services-1.0.0/src/wh_service_plan.erl

prevents wh_service_sync from crashing
`whistle service sync terminating: {function_clause,[{wh_json,get_json_value,[<<"flat_rates">>,undefined,{[]}],[{file,"src/wh_json.erl"},{line,309}]},{wh_service_plan,get_flat_rate,2,[{file,"src/wh_service_plan.erl"},{line,229}]},{wh_service_plan,get_rate_at_quantity,4,[{file,"src/wh_service_plan.erl"},{line,196}]},{wh_service_plan,create_items,5,[{file,"src/wh_service_plan.erl"},{line,76}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{wh_service_plans,create_items,1,[{file,"src/wh_service_plans.erl"},{line,172}]},{wh_service_sync,maybe_sync_services,2,[{file,"src/wh_service_sync.erl"},{line,249}]},{wh_service_sync,handle_info,2,[{file,"src/wh_service_sync.erl"},{line,131}]}]}`

handle undefined ItemPlans

---

.travis.yml
applications/stepswitch/src/stepswitch_bridge.erl
applications/stepswitch/src/stepswitch_formatters.erl
applications/stepswitch/src/stepswitch_local_extension.erl
applications/stepswitch/src/stepswitch_originate.erl
applications/stepswitch/src/stepswitch_outbound.erl
applications/stepswitch/src/stepswitch_request_sup.erl
applications/stepswitch/src/stepswitch_resources.erl
applications/stepswitch/src/stepswitch_sms.erl
applications/stepswitch/src/stepswitch_util.erl
core/whistle-1.0.0/src/wh_json.erl
core/whistle-1.0.0/test/wh_json_test.erl

caller id settings should be applied to the endpoints once calculated,
formatters given a chance to format the caller id, and endpoint-specific
caller id stripped if it doesn't differ from the root bridge's caller id.
KAZOO-4481: fix spec
KAZOO-4481: set caller id per endpoint
KAZOO-4481: add spec and use macros for keys
KAZOO-4481: cleanup usage of offnet req
KAZOO-4481: move formatting to util for reuse
KAZOO-4481: repoint call for default_realm/1
KAZOO-4481: update specs with more descriptive type
use wapi_offnet_resource accessors too
KAZOO-4481: format endpoints when originating
KAZOO-4481: update specs with descriptive types
KAZOO-4481: update spec
KAZOO-4481: typo ;)
Conflicts:
applications/stepswitch/src/stepswitch_resources.erl

KAZOO-4481: move formatting to bridge

---

applications/ecallmgr/src/ecallmgr_util.erl

resolves : if call is put on park it keeps the park number in the final cdr
backport to 3.22

change the variables in get_sip_request

---

core/whistle_apps-1.0.0/src/whistle_apps_init.erl

Was concerned the time check might be weird, but seems pretty reliable. Not sure if we want to make the dns time check configurable (5ms seemed reasonable on my box, as I was getting an occasional outlier around 3ms).
```erlang
19> lists:all(fun(_) -> whistle_apps_init:sanity_checks() end, lists:seq(1,1000)).
true
```
For now, just logs it at critical and continues on its merry way.

KAZOO-4530: sanity checks for dns and timezone

---

applications/acdc/src/acdc_agent_fsm.erl
applications/acdc/src/acdc_agent_listener.erl

acdc_agent_fsm.erl
AMQP Queue was not getting created on time …
bug fix for ACDC Queue, Queue was not getting created on time causing to send undefined queue name (Server-ID), making the response never reach the publishing Agent
acdc_agent_listener.erl
Insted of assigning the value was being compared …
The Value of state was not being initalised and sent but was being compared making the agent crash and giving out: no match of right hand value

Fixed some ACDC Bugs which were making it unusable

---

applications/callflow/src/cf_util.erl
applications/crossbar/doc/internationalization/numbers.md

As stated in internationalization/numbers.md system dialplan looks like this: 
'{"data":{"^(2\\d{6}$":{"prefix":"+7383","name":"Novosibirsk"}}}' 
This obliges each dialplan to have unique regexp/key which is wrong, 
because different dialplans could have same dial patterns. 
So, it is good to make cf_util to be able to also parse multiple dialplans for each key: 
'{"data":{"^(\\d{7})$":[{"prefix":"+7495","name":"Moscow"},{"prefix":"+7812","name":"Saint Petersburg"}]}}'

KAZOO-4543: System dialplan. Multiple dialplans per each regexp.

---

applications/crossbar/src/modules/cb_faxes.erl

faxes api announces the inbox/outbox delete api but does not honor it.
backport to 3.22 please

KAZOO-4567 allow delete if announced

---

.travis.yml
Makefile
README.md
applications/Makefile
core/Makefile
make/kz.mk

Ticket explains a bit what this does.
Tests rely on other apps' code off course, and we've always been running the test suite app by app.
BUT I'm stuck in KNM as stepswitch relies on KNM code, and KNM's calls to whapps_config are replaced at test-time. Thus stepswitch doesn't know about them and directly calls whapps_config…
Now, maybe whapps_config should provide mock functions for when we're running the test suite,
but that would be unreliable until now:
This patch compiles all the code in "test mode" (setting `-DTEST`) before running apps tests app-by-app.
(Providing mock functions and testing against them is probably terrible BTW).
BUT since it's easier for development to not pollute ebin/ we're generating these BEAMs to test/ then `-pa`ing apps with `-pa my/app/test` (instead of `-pa …

KAZOO-4569: set PAs to …/test instead of …/ebin when running test suite

---

applications/crossbar/src/crossbar.erl
applications/crossbar/src/crossbar_doc.erl
applications/ecallmgr/src/ecallmgr_util.erl
core/whistle_couch-1.0.0/src/couch_util.erl
core/whistle_couch-1.0.0/src/wh_doc.erl
core/whistle_media-1.0.0/src/wh_media_map.erl
core/whistle_media-1.0.0/src/wh_media_util.erl

We accomplish several improvements here:
1. Tombstoning of documents is handled in `couch_util`, so we remove the code in `crossbar_doc` as we lost valuable information for the publishing of the doc change AMQP payload.
2. `ecallmgr_util` was failing to set prompt-specific cache bindings to process the doc changes for media. Currently, we remove all account-specific media on changes, as we can't easily reconstruct the prompt name that would be in the doc change routing key.
3. Checks have been added to either directly execute ETS operations or call into the `wh_media_map` process to do the ETS work. This alleviates some deadlock conditions found.
4. Check for undefined when building the prompt path and use `system_media`

Prompt flushing

---

applications/crossbar/src/modules/cb_modules_util.erl

The user/device in the quickcall API URL is the callee. The {NUMBER} in the URL is the caller. Set name and number accordingly.

HELP-21202: set callee/caller id

---

applications/crossbar/src/api_resource.erl

The Content-Length header was incorrect before - though I'm not sure why. This works as intended.
I know this is potentially inefficient, but if the CSV response is expected to be large then it will probably be chunked anyway.

Correct content length for crossbar CSV response

---

core/whistle_apps-1.0.0/src/whapps_call_command.erl

If there is no NoopId, after_timeout should be set to timeout; otherwise
we will wait for one day for events that may never happen.

HELP-21214: set timeout based on noop id

---

applications/crossbar/src/modules/cb_accounts.erl

Call `wh_services:reconcile/1` before creating MODB lead to crash:
> |0000000000|Undefined:Undefined (<0.1771.0>) CRASH REPORT Process <0.1771.0> with 0 neighbours exited with reason: timeout in couchbeam_view_stream:do_init_stream/2 line 120
because `wh_service_ledgers` trying to get data from nonexistent MODB, but `couchbeam_view_stream:do_init_stream/2` is not handle responce with 404 code and died with `timeout` reason.

Crossbar: create MODB before reconciliation when add account

---

applications/notify/src/notify_port_request.erl

Stopped notify_port_request from crashing when trying to join tuples.
I would have preferred to change find_numbers to only return binaries, but this broke template rendering.

Fix crossbar v2 notify_port_request

---

applications/crossbar/src/api_util.erl
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar_types.hrl
applications/crossbar/src/modules/cb_local_provisioner_templates.erl
applications/crossbar/src/modules/cb_signup.erl
applications/crossbar/src/modules/provisioner_v5.erl
applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
core/kazoo_documents/src/kz_device.erl
core/kazoo_documents/src/kzd_apps_store.erl
core/kazoo_documents/src/kzd_schema.erl

Had an issue in training where user sent POST -d '{"real":"stuff"}' and was getting schema validation errors saying "real" is required. That is a confusing because the real error is that the user didn't create the request envelope properly. This PR checks that and returns a more appropriate error payload.

Request envelope requires "data"

---

applications/crossbar/src/api_resource.erl
core/whistle/Makefile
core/whistle/include/wh_types.hrl
core/whistle/src/wh_util.erl
core/whistle/test/wh_util_test.erl
make/deps.mk
make/kz.mk

Tracks memory usage and binary allocations for each request, in addition to time spent.

CB-METRICS: add basic metrics per request

---

core/whistle_number_manager-1.0.0/src/wh_number_manager.erl

@fenollp @k-anderson I think it’s better to rename `KNM_DB`(`WNM_DB`) fields, so when using `wh_json:public_fields` it would return necessary fields(for example rename `pvt_state` to `state`)

KAZOO-4633: return all fields for GET req on a number

---

applications/crossbar/src/modules/cb_callflows.erl
applications/crossbar/src/modules_v2/cb_devices_v2.erl
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
core/kazoo_number_manager/src/converters/knm_converter_regex.erl
core/kazoo_number_manager/src/converters/knm_converters.erl
core/kazoo_number_manager/src/knm_number.erl
core/kazoo_number_manager/src/knm_number_states.erl
core/kazoo_number_manager/src/knm_numbers.erl
core/kazoo_number_manager/src/knm_phone_number.erl

"Cherry pick" of #1693 
**Potential problem**: `reconcile` will actually create/move number to set its state as IN_SERVICE instead of  using `create` with this state parameter (because that is not how `create` is able to be used as).
However, during `reconcile` there will be requests made to phonebook and I am unsure that's the intent of reconcile. Maybe @jamesaimonetti or @k-anderson can tune in?

KAZOO-4595_master: cherry pick PR 1693 from 3.22 to master

---

core/braintree/src/braintree_request.erl

Attempt #2
http:maybe_basic_auth/2 still waits for binaries: 
AuthString = "Basic " ++ base64:encode_to_string(<<Username/binary, ":", Password/binary>>),

KAZOO-4657: braintree_request/kz_http binary to string vars change

---

core/whistle/include/wh_api.hrl
core/whistle/src/wh_util.erl
core/whistle_amqp/src/amqp_util.hrl
core/whistle_amqp/src/wh_amqp_worker.erl

when call-id is an optional header for a wapi message, we are still adding it as part of the payload because of logging in `gen_listener:handle_event/4`.

HELP-21582 use System-Log-ID instead of Call-ID

---

core/whistle-1.0.0/src/wh_json.erl

This was missed by https://github.com/2600hz/kazoo/pull/1668
However, I was able to successfully wh_json:decode the JSON string
logged in the ticket.
Need more data!
(needs cherry picking to master)

KAZOO-4603: handle uncaught exception when decoding JSON

---

Makefile

Note: the `clean-kazoo kazoo` part can be removed iff the deb has already been built: `compile-test` recompiles kazoo with test flags on, meaning you get a whole different kazoo!

for-debian: add `make check`

---

applications/crossbar/src/modules/cb_simple_authz.erl
core/kazoo_bindings/test/kazoo_bindings_test.erl

Found with `git grep -InE 'fun\s*\(([^,]+)\)\s*\->\s*\1\s*end'`
Thinking about adding such a command as a CI check.. Or an elvis rule, if elvis' datastructure wasn't that much of a pain

use-funs: use wh_util:identity/1

---

applications/callflow/src/cf_attributes.erl
applications/trunkstore/src/ts_from_offnet.erl

Introduce a new `anonymizer` field in the `caller_id_options` in the `AccountDB`. 
When a call routed through `trunkstore` if the privacy flags is on and the `anonymizer` option is set to `kazoo` then it make caller id  anonymized. Otherwise if `anonymizer` is set to `sip` privacy flag is forwarded without anonymizing caller id.

KAZOO-4364: honor private flag per account

---

applications/crossbar/src/modules/cb_channels.erl

In log file: `wh_amqp_worker:585 (<0.1016.0>) failed to send request: {badmatch,[]}` beacause `cb_context:doc(Context)` return empty result.

Request to `devices/{DEVICE_ID}/channels` return 500 error.

---

core/whistle-1.0.0/Makefile
core/whistle-1.0.0/src/kz_tracers.erl
core/whistle-1.0.0/src/wh_cache.erl
deps/eflame/.gitignore
deps/eflame/LICENSE
deps/eflame/Makefile
deps/eflame/README-Riak-Example.md
deps/eflame/README.md
deps/eflame/eflame.d
deps/eflame/flamegraph.pl
deps/eflame/flamegraph.riak-color.pl
deps/eflame/src/eflame.app.src
deps/eflame/src/eflame.erl
deps/eflame/src/eflame2.erl
deps/eflame/src/eflame_app.erl
deps/eflame/src/eflame_sup.erl
deps/eflame/stack_to_flame.sh
deps/eflame/stacks_to_flames.sh

Tested thusly:
`kz_tracers:gen_load(N).` will spawn N workers who will create a new database and 1000 documents inside that database, and will perform edit/delete operations against those documents until all are deleted, at which point the database is deleted.
The parent process will track the `whistle_couch_cache` process' largest `message_queue_len` and `current_function`, and will output those values (along with runtime):
```
kz_tracers:gen_load(5).
...processing...
finished test after 531140ms: {23, {lager_format, build2, 3}}
```
In this case, the largest mailbox length found was 23 messages and the whistle_couch_cache process was in `lager_format:build2/3` when that was read.
For perspective, the previous `wh_cache` topped out around 23K messages in the queue, so this PR marks a …

HELP-22210: kz_cache backport to 3.22

---

applications/crossbar/src/modules/cb_sup.erl

validate/{2,3} calls module_name/1 several times and each added "_maintenance" to module name

Fix cb_sup

---

applications/crossbar/priv/couchdb/schemas/user_auth_recovery.json
applications/crossbar/priv/couchdb/schemas/user_auth_recovery_reset.json
applications/crossbar/priv/couchdb/views/user_auth.json
applications/crossbar/src/crossbar.hrl
applications/crossbar/src/modules/cb_google_auth.erl
applications/crossbar/src/modules/cb_user_auth.erl
applications/crossbar/src/modules_v1/cb_users_v1.erl
applications/crossbar/src/modules_v2/cb_users_v2.erl
applications/notify/src/notify_password_recovery.erl
applications/notify/src/notify_templates.hrl
applications/teletype/src/templates/teletype_password_recovery.erl
core/whistle/src/api/wapi_notifications.erl

Notes
* needs testing
* waiting on a UI ticket: ~~[UI-1925](https://2600hz.atlassian.net/browse/UI-1925)~~ [UI-1819](https://2600hz.atlassian.net/browse/UI-1819)
* not sure about the way to `crossbar_cleanup`
* why does my vm not send emailsdammit

KAZOO-3669: replace reset password behaviour

---

applications/konami/src/konami.hrl
applications/konami/src/konami_code_fsm.erl
applications/konami/src/module/konami_transfer.erl

Proposal to load webseq status load from a configurable place as keeping it on everytime crashes konami. i am looking into why there is a crash on some particular call transfers

Proposal to make webseq status configurable

---

core/kazoo_data/src/kz_data.hrl

This PR mostly for pointing to problem, not to fix.
Playing with "system_data" on test server i randomly got error (~50%) on start:
> May  5 07:57:38 dev 2600hz[5385]: |0000000000|Undefined:Undefined (emulator) Error in process <0.3263.0> on node 'kazoo_apps@dev' with exit value:#012{function_clause,[{kzs_doc,open_doc,[#{server => undefined,tag => local},<<"system_config">>,<<"kapps_controller">>,[]],[{file,"src/kzs_doc.erl"},{line,37}]},{timer,tc,1,[{file,"timer.erl"},{line,166}]},{kzs_perf,do_profile,3,[{file,"src/kzs_perf.erl"},{line,81}]},{kzs_cache,open_cache_doc,3,[{file,"src/kzs_cache.erl"},{line,54}]},{kapps_config,get,4,[{file,"src/kapps_config.erl"},{line,239}]},{kapps_controller,initialize_kapps,0,[{file,"src/kapps_controller.erl"},{line,145}]}]}
My `systemd_data/system` …

Add random suffix to key in #data_connection{}

---

core/kazoo_data/src/kz_datamgr.erl
core/kazoo_data/src/kzs_publish.erl
core/kazoo_number_manager/src/knm_phone_number.erl

@lazedo I get a warning every time a number db is created because revise_views tries to convert NumberDb to an account ID (format_account_id fails & returns NumberDb).
Should revise_views really take an account ID? What do you think should be done here?

fix warning of unhandled account ID

---

core/braintree/src/braintree_card.erl
core/braintree/src/braintree_customer.erl

When someone needed to add a customer without having their credit card braintree send an error that make_default(undefined) clause is not defined in braintree_card.erl. now we can add a new customer in braintree by just having using his info and adding a card is not needed.

Fixed an issue with adding a customer

---

applications/crossbar/doc/blacklists.md

The original examples are missing a } causing the server to reply with a "400 Bad Request" error

Fixed missing curly bracket in examples

---

applications/teletype/src/templates/teletype_voicemail_to_email.erl

- voicemail.transcription macro should now work
in the teletype voicemail to email template

KAZOO-4771 Added transcription data to build_voicemail_data()

---

applications/teletype/src/templates/teletype_voicemail_to_email.erl

voicemail.transcription macro should now work
in the teletype voicemail to email template

Added transcription data to build_voicemail_data()

---

core/kazoo/Makefile

prefer mp3 for audio/mpeg
handle audio/mp3 since chrome doesn't follow rfc3003
[CHROMIUM-227004](https://bugs.chromium.org/p/chromium/issues/detail?id=227004)

tweaks on the generated kz_mime.erl

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/doc/ref/vmboxes.md
applications/crossbar/doc/voicemail.md
applications/crossbar/priv/couchdb/schemas/callflows.voicemail.json
applications/crossbar/priv/couchdb/swagger/swagger.json
applications/crossbar/src/modules_v1/cb_vmboxes_v1.erl
applications/crossbar/src/modules_v2/cb_vmboxes_v2.erl
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_voicemail/src/kz_vm_message.erl

* KAZOO-4736: change folder after setting metadata in notify_and_save_meta
* KAZOO-4736: change folder correctly in cb_vmboxes
* KAZOO-4736: add callflow voicemail element schema
* KAZOO-4736: bulk update/delete on voicemail messages
* KAZOO-4736: enhancement in voicemail migration/cleanup
* KAZOO-4736: add missing specs
* KAZOO-4736: return suceeded and failed vm message ids due
to a bulk update/move ops
* KAZOO-4736: pattern match in func header and add specs
* KAZOO-4736: fix dialyzer specs/types warning
* KAZOO-4736: some fixes and cleanup
* KAZOO-4736: iterate just once to do voicemail bulk ops
* KAZOO-4736: fix specs, better naming
* KAZOO-4736: fix spec
* KAZOO-4736: fix specs, use helper modules

KAZOO-4736: add bulk update/delete in vmboxes crossbar module for 4.0 (#1910)

---

make/deps.mk
rel/sys.config
scripts/start-dev.sh

To recompile project's *.erl files (and then reload *.beam) automatically on changes.
Release must be built with symlinks (make build-dev-release).
In erlang shell:
> lager:set_loglevel(lager_console_backend, info).
> sync:go().
Then edit and save a file (actually just save will do):
> 18:26:38.254 [info] ../../core/kazoo_apps/src/kz_nodes.erl:0: Recompiled.

sync support (online re-compile)

---

applications/jonny5/src/j5_per_minute.erl
applications/jonny5/src/j5_request.erl
core/kazoo_transactions/src/wht_util.erl

separated from https://github.com/2600hz/kazoo/pull/1951

KAZOO-4797: set quantity to charged seconds (per-minute-voip ledgers doc: rounded billing seconds)

---

make/deps.mk
rel/sys.config

Specifying src_dir is wrong and works differently (it scans the specified folder for source files, and tries to compile them to specified folder [file:get_cwd() if not specified]. But we need to limit it scope to applications/core modules without altering the destination path. This requires changes to sync, and here they are.

sync: proper config

---

core/kazoo_apps/src/kapps_controller.erl

There are still whapp variable left inside the kazoo_apps and jonny5 should we remove those too ???
the wh_to_kz.sh script does not contain the case when the letters are WhApp

removed whapps reference

---

applications/callflow/src/cf_util.erl

also adds support for inner dialplan
```
"^\\d{7}$": {
"name": "PT-LX",
"description": "Portugal Lisboa",
"prefix": "21",
"dialplan": {
"^\\d{9}$": {
"name": "PT",
"description": "Portugal",
"prefix": "+351"
}
}
}
```

KAZOO-4831 4.0 continue processing dialplans

---

applications/callflow/src/cf_util.erl

also adds support for inner dialplan
```
"^\\d{7}$": {
"name": "PT-LX",
"description": "Portugal Lisboa",
"prefix": "21",
"dialplan": {
"^\\d{9}$": {
"name": "PT",
"description": "Portugal",
"prefix": "+351"
}
}
}
```

KAZOO-4831 continue processing dialplans

---

applications/callflow/src/cf_util.erl

also adds support for inner dialplan
```
"^\\d{7}$": {
"name": "PT-LX",
"description": "Portugal Lisboa",
"prefix": "21",
"dialplan": {
"^\\d{9}$": {
"name": "PT",
"description": "Portugal",
"prefix": "+351"
}
}
}
```

KAZOO-4831 3.22 continue processing dialplans

---

core/kazoo_documents/src/kz_device.erl
core/kazoo_endpoint/src/kz_endpoint.erl

If device configured with `invite_format = e164` (or any other not `username`) we shouldn't add X-KAZOO-AOR header.
If X-KAZOO-AOR header exist, kamailio replace INVITE RURI with stored Contact (from REGISTRATION request).
BTW: kz_device:sip_route/2 and kz_device:set_sip_route/2 must be fixed? Is macro `?IP` should be replaced to something other?

Use correct macros for kz_device:sip_invite_format and kz_device:set_sip_invite_format

---

core/kazoo/include/kz_api.hrl
core/kazoo/src/kz_api.erl
core/kazoo_amqp/src/kz_amqp_worker.erl

Server-ID is optional but if a specific message wants to turn it
mandatory it won't validate
add Queue-ID to default optional list.
when doing a amqp call or call_collect we may still want to send our
queue in the request

KAZOO-4817 filter default headers with message headers

---

core/braintree/src/braintree_card.erl
core/kazoo/src/gen_listener.erl
core/kazoo/src/kz_json.erl
core/kazoo/src/kz_util.erl
core/kazoo_amqp/src/kz_amqp_channel.erl
core/kazoo_amqp/src/kz_amqp_worker.erl
core/kazoo_apps/src/kapps_call.erl
core/kazoo_apps/src/kapps_conference.erl
core/kazoo_apps/src/kapps_speech.erl
core/kazoo_documents/src/kzd_callflow.erl
core/kazoo_services/src/kazoo_services_maintenance.erl

I was asked to whether it's possible to run tidier on kazoo's code base.
This is the result of applying two of the most basic tidier transformations on the `core` dir of `kazoo`.
The transformations are basic code simplifications and they are non-controversial.
PS. If you like them, there will be more...

Apply tidier --cases --straighten to files in core dir

---

applications/crossbar/priv/couchdb/schemas/find_numbers.json
applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
core/kazoo_number_manager/src/knm_util.erl

adds a country to search numbers parameters so we can infer the country
prefix to pass to number search.
used knm_managed to generate +1555 numbers (Hollywood)
simple test in monster-ui 
before patch
search area code 424. it correctly returns 424 US numbers (bandwidth2)
search area code 555. no knm_managed numbers returned
search area code 155. knm_managed numbers returned
after patch
search area code 424. it correctly returns 424 US numbers (bandwidth2)
search area code 555. knm_managed numbers returned

add a country to search numbers parameters

---

core/kazoo_apps/src/kapps_util.erl

Reverts 2600hz/kazoo#2176
kapps_util:get_account_mods(AccountId / AccountDb) only gives back [AccountDb * X] for me
where X = number of modbs for said account

Revert "fix is_matched_account_mod"

---

core/kazoo/src/kz_util.erl
core/kazoo_apps/src/kapps_util.erl

So that, for an existing `AccountId`:
```erlang
kapps_util:get_account_mods(<<"009afc511c97b2ae693c6cc4920988e8">>, raw) =/= [].
kapps_util:get_account_mods(<<"009afc511c97b2ae693c6cc4920988e8">>, encoded) =/= [].
kapps_util:get_account_mods(<<"009afc511c97b2ae693c6cc4920988e8">>, unencoded) =/= [].
```
Possible issue: code that relied on this function returning `[]` (due to wrong encoding) is broken by this change.

get-mods: filter after formatting

---

applications/crossbar/src/crossbar_util.erl
core/kazoo/include/kz_types.hrl
core/kazoo/src/kz_util.erl
core/kazoo_apps/src/kazoo_apps.app.src
core/kazoo_modb/src/kazoo_modb_maintenance.erl
core/kazoo_number_manager/src/kazoo_number_manager.app.src
core/kazoo_number_manager/src/knm_tasks.erl
core/kazoo_services/src/kazoo_services.app.src
core/kazoo_services/src/kazoo_services.hrl
core/kazoo_services/src/kazoo_services_sup.erl
core/kazoo_services/src/kz_services_modb.erl
core/kazoo_services/src/kz_services_tasks.erl
core/kazoo_services/src/kz_services_tasks_listener.erl
core/kazoo_tasks/src/kz_task_noinput_worker.erl
core/kazoo_tasks/src/kz_tasks.erl

Notes:
when either BoM or EoM is not present (but the other is) it will put the value that exists and an empty value:
```
a4349ir30r934ir0349sub_account_idwew2323,201606,number_services,local,,130
```
(note the 2 following commas `,,`).
However, if both documents are not present, no row is generated for this month.
Waiting on https://github.com/2600hz/kazoo/pull/2183 to fix CI issues.

KAZOO-4118

---

make/deps.mk

* more return codes support
* compiles on 19.0

Bump couchbeam from 1.3.0 to 1.3.1

---

applications/acdc/src/acdc_init.erl
applications/callflow/src/callflow_maintenance.erl
applications/callflow/src/module/cf_menu.erl
applications/callflow/src/module/cf_ring_group.erl
applications/callflow/src/module/cf_voicemail.erl
applications/cdr/src/cdr_v3_migrate_lib.erl
applications/crossbar/src/cb_test.erl
applications/crossbar/src/modules/cb_accounts.erl
applications/crossbar/src/modules/cb_modules_util.erl
applications/crossbar/src/modules/cb_signup.erl
applications/crossbar/src/modules/cb_whitelabel.erl
applications/fax/src/fax_util.erl
applications/teletype/src/teletype_renderer.erl
core/kazoo/src/kz_util.erl
core/kazoo/src/perf.erl
core/kazoo_attachments/src/aws/kz_aws_retry.erl
core/kazoo_data/src/kz_dataconnections.erl
core/kazoo_media/src/kz_media_recording.erl
core/kazoo_perf/src/kz_tracers.erl
core/kazoo_services/src/kz_services.erl

In Erlang/OTP 19 the 'random' module is marked deprecated and the 'rand'
module is expected to be used instead.  This module also exists in 18.x.
Also, the compiler issues warnings for crypto:rand_bytes/1 and prompts for
the use of crypto:strong_rand_bytes/1 instead.
This set of changes allows the kazoo code base to be compiled without errors
in 19.0 (because the current compiler options consider warnings as errors)
but most likely disables support for 17.x (because the 'rand' module is not
present there).
It should be merged to 'master' *only* if support for 17.x is not desirable.
However, if support for 17.x is still needed, the code should take out the
compiler option that turns warnings into errors, so that the code can also be
compiled in 19.0.

Modernize calls to random-generating functions

---

applications/blackhole/src/blackhole_listener.erl
core/kazoo_apps/src/kz_hooks.erl
core/kazoo_apps/src/kz_hooks_listener.erl
core/kazoo_apps/src/kz_hooks_shared_listener.erl
core/kazoo_apps/src/kz_hooks_util.erl

add missing the `remove_call_binding` to blackhole and kazoo_hooks.

add unbinding/deregistering to kazoo_hooks and blackhole

---

rel/relx.config.src

Was excluded as part of https://github.com/2600hz/kazoo/pull/2267#discussion_r71717060
However mentioned error cannot be reproduced nor locally nor by CI.

revert excluding sup from release

---

applications/crossbar/src/cb_context.erl
core/kazoo/src/kz_json_schema.erl

from_list/1 wasn't using the key as a path but as an array-as-key.
merge error into errors in cb_context
handle wrong_length validation error

KAZOO-4936: use set_values/2

---

core/kazoo_data/src/kz_datamgr.erl

and that's potentially bad (couchdb adding not-flattened views to db and failing)
so now: pattern matching js code is as minimal as the one in validate-js.sh

qf-views: pattern wasn't minimal enough

---

applications/blackhole/src/blackhole.hrl
applications/blackhole/src/blackhole_listener.erl
applications/blackhole/src/blackhole_socket_callback.erl
applications/blackhole/src/modules/bh_call.erl
applications/blackhole/src/modules/bh_conference.erl
applications/ecallmgr/src/ecallmgr_fs_conference.erl

- keep binding in ws context and insert it into every handled message
- adapt bh_call to ws protocol changes: low-case keys, subscribe/unsubscribe, binding field

KAZOO-4916 (also with KAZOO-4201)

---

applications/crossbar/src/api_util.erl

Cherry pick of https://github.com/2600hz/kazoo/pull/2402
Was supposedly fixed by https://2600hz.atlassian.net/browse/KAZOO-3426

qf-dupes-headers: add only LC headers to ensure no dupes

---

make/deps.mk

- relies on inotifywait
- has fallback to naive filesystem events
- much simplier

better online recompiler/reloader

---

applications/cdr/src/cdr_channel_destroy.erl
applications/ecallmgr/src/ecallmgr.hrl
core/kazoo/include/kz_types.hrl

fixes crashing in cdr_channel_destroy

KAZOO-4983 handle unset interaction-id due to no_route

---

core/kazoo_translator-1.0.0/src/convertors/kzt_kazoo.erl

When a REFER or similar comes in, the To and Request can differ in
meaningful ways. Include both in the Pivot payload so the receiving HTTP
server can decide how to proceed.

HELP-24132: include request field data

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/conferences.json

- enforce in schema conference pin and numbers to be non-empty digit string

KAZOO-5029 conference pins and numbers

---

applications/acdc/src/acdc_agent_listener.erl

This is probably not the most sophisticated solution, but hey it's acdc ;).
In 3.22 the agent listener crashes when an agent has multiple devices or is is hotdesking. This results in the call bouncing back into the queue and ghost calling or channel hijack when another agent answers.
I did a quick fix to just ignore the hangup just as when it is undefined. Again, not the best coding but probably acceptable for a component that is being discontinued but still in use in some places.

Small fix to make ACDC usable on 3.22

---

applications/crossbar/src/modules_v1/cb_phone_numbers_v1.erl
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
core/kazoo_number_manager/include/knm_phone_number.hrl
core/kazoo_number_manager/src/carriers/knm_bandwidth.erl
core/kazoo_number_manager/src/carriers/knm_bandwidth2.erl
core/kazoo_number_manager/src/carriers/knm_carriers.erl
core/kazoo_number_manager/src/carriers/knm_inum.erl
core/kazoo_number_manager/src/carriers/knm_local.erl
core/kazoo_number_manager/src/carriers/knm_managed.erl
core/kazoo_number_manager/src/carriers/knm_mdn.erl
core/kazoo_number_manager/src/carriers/knm_other.erl
core/kazoo_number_manager/src/carriers/knm_reserved.erl
core/kazoo_number_manager/src/carriers/knm_reserved_reseller.erl
core/kazoo_number_manager/src/carriers/knm_simwood.erl
core/kazoo_number_manager/src/carriers/knm_vitelity.erl
core/kazoo_number_manager/src/carriers/knm_voip_innovations.erl
core/kazoo_number_manager/src/knm_gen_carrier.erl
core/kazoo_number_manager/src/knm_util.erl
core/kazoo_number_manager/src/knm_vitelity_util.erl
core/kazoo_number_manager/test/knm_bandwidth2_test.erl
core/kazoo_number_manager/test/knm_bandwidth_find_test.erl
core/kazoo_number_manager/test/knm_carriers_find_test.erl
core/kazoo_number_manager/test/knm_vitelity_find_test.erl
core/kazoo_number_manager/test/knm_voip_innovations_test.erl

Note: for inum & managed offset is only partially supported.
I would argue to split them in inum & inum_reseller and managed & managed_reseller in order to properly handle offset.

KAZOO-4998: support offset in number search

---

applications/stepswitch/src/stepswitch_resources.erl

When setting caller id, gateways were blindly setting outbound caller id
from the JSON payload (which could be the external caller id). When the
endpoints were formatted, the "global" caller id was the emergency CID
while each gateway's CID was the external CID. Since external and
emergency CID didn't match, the gateway CID was not stripped in
stepswitch_util:format_endpoints/4.
This patch sets the gateway CID to the emergency CID if
appropriate. Formatting will then operate on the emergency CID and be
stripped if unchanged (no formatting rules on the resource).

KAZOO-5048 set emergency cid on gateway(s)

---

scripts/validate-js.sh

Script exits with non-zero return code if JS code even mentions `Object.keys`

qf-js: add a check for JS function that caused KAZOO-5012 (#2460)

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
applications/crossbar/priv/couchdb/schemas/system_config.tasks.json
applications/tasks/src/knm_number_crawler.erl
applications/tasks/src/knm_port_request_crawler.erl
applications/tasks/src/kz_account_crawler.erl
core/kazoo_config/src/kapps_config.erl

Should I [move kapps_config categories](https://github.com/2600hz/kazoo/blob/master/core/kazoo_config/src/kapps_config.erl#L662)?
These files in `applications/tasks/src` are concerned:
* knm_number_crawler.erl
* knm_port_request_crawler.erl
* kz_account_crawler.erl

qf-acccra: reinstate cycle_delay_time in account_crawler

---

core/sup/src/sup.erl

As per email: "Additionally, the ability to use the -h argument and connect to machines remotely via SUP has been removed."

Remove -h SUP option

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.trunkstore.json
applications/trunkstore/src/ts_from_onnet.erl
applications/trunkstore/src/ts_util.erl

At the moment, if connected over trunkstore PBX adds diversion field, it is ignored on valid caller ID check. Looks like diversions header also even absent in offnet resource request. Would like to give a try to address this.

trunkstore_honor_diversion by ensure valid cid

---

applications/callflow/src/callflow_app.erl
applications/konami/src/konami_app.erl

Without 'metaflow' exhange konami log error:
` |kz_amqp_assignments|kz_amqp_assignments:751 (<0.124.0>) floating channel <0.20552.0> on amqp://kazoo:xxx@1.2.3.4:5672 went down while still assigned to
consumer <0.22408.0>: {shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'metaflow' in vhost '/'">>}}
`

Create 'metaflow' exchange on start 'callflow' or 'konami' apps

---

core/kazoo_voicemail/src/kvm_message.erl
core/kazoo_voicemail/src/kvm_util.erl

Resolves voicemail messages disappearing into the void

Pass along BoxId to save_metadata so that check_msg_belonging doesn't refuse fetch

---

core/kazoo/src/kazoo.app.src
core/kazoo/src/kazoo_maintenance.erl

simplifies dependency graph for kazoo app by removing kazoo_globals
also include observer in kazoo app deps so etop is available again in
releases.

move_kazoo_globals: move kz_nodes call out of kazoo

---

applications/tasks/src/kz_tasks_trigger.erl

Cleanup timer set in seconds, but `erlang:start_timer/3` wants milliseconds

Fix cleanup timer in tasks

---

applications/ecallmgr/src/ecallmgr_app.erl
core/kazoo_amqp/src/api/kapi_media.erl
core/kazoo_apps/src/kapps_controller.erl
core/kazoo_globals/src/kz_nodes.erl
core/kazoo_globals/src/kz_nodes_bindings.erl

kz_nodes had direct calls to ecallmgr functions. I've moved things around to use kazoo_bindings to retrieve those values. This also paves the way for apps to have custom handlers for providing their own data (this is not explicitly enabled in the PR but the flexibility of kazoo_bindings should allow for expansion).
This is part of the apps_of_app effort to streamline inter-app dependencies.

Kz nodes deps

---

applications/callflow/src/module/cf_voicemail.erl

Doc id can be undefined on L1303. Reusing this undefined instead of the MailboxId acquired by get_mailbox_doc/4 (which may automatically find the vmbox id by caller id or owner id) causes a crash

When vm id not specified (i.e. *97 feature) fix crash in kvm_messages:count/2

---

applications/callflow/src/module/cf_voicemail.erl

When callling *97, we don't know the mailbox_id at first,
mwi should send updates when we found box_id

qf-vm: call send_mwi_update only when mailbox_id is found

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.notify.fax_inbound_error_to_email.json
applications/ecallmgr/src/ecallmgr_call_events.erl
applications/ecallmgr/src/fs_event_filters.hrl
applications/notify/src/notify_voicemail_to_email.erl
applications/teletype/src/templates/teletype_fax_inbound_error_to_email.erl
applications/teletype/src/templates/teletype_fax_inbound_to_email.erl
applications/teletype/src/templates/teletype_voicemail_to_email.erl

- distinguish fax errors by fax error code
- allow system administrator to specify error codes to ignore (e.g. fax wasn't negotiated because of premature call end)

KAZOO-4904 fax notifications

---

core/kazoo/src/kz_util.erl
core/kazoo_amqp/src/api/kapi_offnet_resource.erl

Messages with is_empty To-DID field (<<"0">> as example) should not pass validation.

KAZOO-5063 ensure to-did not being empty

---

applications/crossbar/src/modules/cb_conferences.erl
applications/ecallmgr/src/ecallmgr_fs_conferences.erl
core/kazoo_amqp/src/api/kapi_conference.erl

querying realtime data for conferences was taking too long where each conference obtained from view would make a amqp call to ecallmgr. since the queries are restricted to account, we can send a unique amqp call querying conferences by account_id.

optimize conference query by accountid

---

Makefile

To prevent changes introduced in https://github.com/ninenines/erlang.mk/commit/d5c32474e0690a32371fb8fb0b5d2db2c567269b

temp fix for compilation

---

applications/crossbar/src/api_util.erl

Found during quickchecking of APIs: might be due to spamming APIs too hard too quickly.

qf-pare_ct: handle badarg when cowboy parses for CT

---

applications/acdc/src/acdc.hrl
applications/acdc/src/acdc_agent_fsm.erl
applications/acdc/src/acdc_agent_handler.erl
applications/acdc/src/acdc_agent_listener.erl

Fixes agent falling out of state when answering non-queue calls while in ringing
Allows agent to move to outbound after answered if there happens to be another line up
Pre-requisite to upcoming fixes to transfers
Resolves problems that would occur when conferencing a queue caller with another endpoint
Fixes agent getting into unexpected state if originate_uuid shows up after originate_failed and the caller has picked up the call

acdc: Track multiple outbounds (fixes a number of bugs regarding multiple calls)

---

applications/crossbar/src/crossbar_services.erl
core/kazoo_number_manager/doc/carriers.md
core/kazoo_number_manager/include/knm_phone_number.hrl
core/kazoo_number_manager/src/carriers/knm_bandwidth.erl
core/kazoo_number_manager/src/carriers/knm_bandwidth2.erl
core/kazoo_number_manager/src/carriers/knm_carriers.erl
core/kazoo_number_manager/src/carriers/knm_inum.erl
core/kazoo_number_manager/src/carriers/knm_local.erl
core/kazoo_number_manager/src/carriers/knm_managed.erl
core/kazoo_number_manager/src/carriers/knm_mdn.erl
core/kazoo_number_manager/src/carriers/knm_other.erl
core/kazoo_number_manager/src/carriers/knm_reserved.erl
core/kazoo_number_manager/src/carriers/knm_reserved_reseller.erl
core/kazoo_number_manager/src/carriers/knm_simwood.erl
core/kazoo_number_manager/src/carriers/knm_vitelity.erl
core/kazoo_number_manager/src/carriers/knm_voip_innovations.erl
core/kazoo_number_manager/src/converters/knm_converters.erl
core/kazoo_number_manager/src/knm_gen_carrier.erl
core/kazoo_number_manager/src/knm_phone_number.erl
core/kazoo_number_manager/src/knm_services.erl
core/kazoo_services/src/services/kz_service_phone_numbers.erl

... so that a reduce view can be written (as part of PR 2/2) that would return the cumulated quantities.
I'm far from a services expert so please take a look: is all the data needed to compute quantities now stored on the number document?
Note: classifiers need not be in the number doc. They will be part of the reduce view.
Note: depends on #2700. Will need rebase to please Circle.

Part 1/2 of KAZOO-5093: store enough information in number doc

---

applications/crossbar/src/modules/cb_recordings.erl

When retrieving a recording info using /recordings/Id the api tried to convert the json to binary causing issues.

KAZOO-5120: to_binary bug fix

---

applications/crossbar/src/api_resource.erl
applications/crossbar/src/api_util.erl
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar.hrl
core/kazoo_json/include/kazoo_json.hrl
core/kazoo_json/src/kz_json.erl
core/kazoo_json/src/kz_json.hrl

added pretty printing option for json output
User is able to get the json returned formatted using Header value 'x-pretty-print: true' or inside url or body of the request, 
v1/url?pretty_print=true

Json Pretty Print

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/storage.attachment.aws.json
core/kazoo_attachments/src/kz_att_s3.erl

s3_bucket_after_host is changed to true as while working with s3 some bucket names gives ssl errors as s3 uses wildcard cert for buckets, the commit changes the bucket name to be appended to the back of the host name and it saves us from the invalid cert issue. The other way to get arround the issue is to use http but i guess this is a good way as it does not break anything and is secure. 
The change to hostname is added which will allow user to use any other bucket besides amazon's us-east which is being used as a default.

s3 allow international hosts

---

applications/fax/src/fax_smtp.erl

When an email for fax has nested multipart parts and one of the parts of the parent multipart doesn't have an attachment, fax_smtp will fail because of the error "no valid attachment". It should succeed, as there is a valid attachment in the other part. This patch filters out the "no valid attachment" error upon finding a valid attachment in the other part.
Below is an example of the fax_smtp log lines (with a couple extra) to illustrate the format of the email:
```
Oct 26 21:12:58 hostname 2600hz[22454]: |91e795f2a9515c8b8c7ee9a2dde8ccb4|fax_smtp:177 (<0.10060.2>) Message decoded successfully!
Oct 26 21:12:58 hostname 2600hz[22454]: |91e795f2a9515c8b8c7ee9a2dde8ccb4|fax_smtp:692 (<0.10060.2>) processing multipart/mixed
Oct 26 21:12:58 hostname 2600hz[22454]: …
```

With nested multipart emails, fax_smtp fails if one part doesn't have attachments

---

core/kazoo_voicemail/src/migrate/kvm_migrate_account.erl

Fold was prematurely exited if a single modb did not exist

Check ALL dbs_existence in vm migrate

---

core/kazoo_amqp/src/api/kapi_conference.erl

Minor change. Makes validation via kapi_conference:search_resp_v/1 log a more sensible error (Event-Name error is not search_resp) instead of failing due to missing one of [<<"Conferences">>, <<"Conference-ID">>] keys. This was just confusing because ecallmgr_fs_conferences wanted to publish the error with Conference-ID but it was being stripped out.
tl;dr: log sanity cleanup

Expect Conference-ID on conference error event

---

applications/acdc/src/acdc_agent_fsm.erl
applications/acdc/src/acdc_agent_handler.erl
applications/acdc/src/acdc_agent_listener.erl
applications/acdc/src/acdc_agent_sup.erl
applications/acdc/src/acdc_init.erl

Move logout operation to agent
Validate that logout is permitted in the current state
Better queueing support for agent pause/resume/logout
Clean up agent stats by publishing status less often, only after state fold
Better approach to auto-login of agents after acdc restart
Better agent queue binding

ACDC: Improve state and login/logout management in agent

---

applications/callflow/src/module/cf_menu.erl

The idea here is if the menu has to hunt for a callflow that we then set the cf_capture_group on the call so that the flow we are branching to has access to the captured group(s)
Discussion here. https://groups.google.com/forum/#!topic/2600hz-dev/O1CfULJyqgs
keys should be accesiable with these calls. 
``` erlang
kapps_call:kvs_fetch('cf_capture_group', Call)
kapps_call:kvs_fetch('cf_capture_groups', Call)
```

Adding kvs cf_capture_group to call when we hunt for branch in cf_menu.

---

applications/crossbar/src/modules/cb_cdrs.erl

to be consistent, media_recordings contains a list of recordings and output empty list if no recordings are present and change single binary to a list of recordings

Crossbar cdrs recordings list

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.auth.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.freeswitch.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.json
applications/crossbar/priv/couchdb/schemas/system_config.doodle.json
applications/crossbar/priv/couchdb/schemas/system_config.media.json
core/kazoo_ast/src/kapps_config_usage.erl
core/kazoo_media/src/kazoo_media.hrl
core/kazoo_media/src/kz_media_store_proxy.erl
core/kazoo_media/src/kz_media_util.erl

@fenollp 
https://github.com/2600hz/kazoo/commit/026d2548d2e2718c094efae4c9f6885b11baa6e8 broke some functionality in kazoo_media. we should adapt kapps_config_usage to improve schema/swagger generation. we should not change the core code (kazoo_media in this case) to improve schema/swagger generation.
there's still some work to be done in another PR to address the cases where a `case .. of` is used like `ssl_ca_cert` in crossbar_init

qf-filter out system generated default values

---

core/kazoo_attachments/src/kz_att_s3.erl
core/kazoo_data/src/kzs_attachments.erl

added use case where users att creds could be changed and at that point amazon s3 will disregard old creds and will use newer ones instead. 
While sending a request to get doc, it will check if the docs att handler and the systems att handler are same if not it will use the docs att handler creds, 
if they are same it will use the systems creds and if somehow the creds are messed up it will revert back to att's creds.
Todo:
Needs thorough testing

Update to kzs_attachement

---

core/kazoo_json/src/kz_json.erl
core/kazoo_json/test/kz_json_test.erl

as described on the Erlang ML today by Jesper (for merging maps), this
applies nicely to merging JSON objects as well.
This provides two merge functions, merge_left/2 and merge_right/2,
that will prefer the left or right value (except in cases where the
values are JSON objects themselves - recursively merge them).

json_merge: provides a nice merge function

---

make/deps.mk

Basho just announced they moved lager to https://github.com/erlang-lager/lager

Use erlang-lager repo for lager

---

circle.yml
scripts/circleci-build-erlang.sh

Without "timeout" option kerl build killed with error "took more than 10 minutes since last output".
This happens when erlang build first time (~20 minutes). After this it taken from cache and dont spend so much time.

Fix erlang build timeout for circleci

---

applications/trunkstore/src/ts.hrl
applications/trunkstore/src/ts_callflow.erl
applications/trunkstore/src/ts_from_offnet.erl
applications/trunkstore/src/ts_from_onnet.erl
core/whistle-1.0.0/src/gen_listener.erl
core/whistle_amqp-1.0.0/src/wh_amqp_worker.erl

Checks out a worker, sets the worker to relay any messages received to the trunkstore process.

Use AMQP worker for Trunkstore

---

core/kazoo_number_manager/src/knm_maintenance.erl

Extracted from https://github.com/2600hz/kazoo/pull/2748

KAZOO-5133: log & continue on crashing migration

---

applications/trunkstore/src/ts_callflow.erl
applications/trunkstore/src/ts_from_offnet.erl
applications/trunkstore/src/ts_from_onnet.erl

There doesn't seem to be a need for the trunkstore process to stay
alive once the bridge has started (CHANNEL_BRIDGE received). If
received, the process will cleanup and terminate.

Stop trunkstore process on bridge

---

applications/fax/src/fax_request.erl
core/kazoo_call/src/kapps_call_command.erl
core/kazoo_media/src/kz_media_recording.erl
core/kazoo_voicemail/src/kvm_message.erl

bigcouch may return error when storing attachments and when retried it can be a 409

qf-attachments allow url as a function

---

applications/ecallmgr/src/ecallmgr_originate.erl

Prior to this patch the originate_uuid event is not fired for uuids generated as part of an originate_req. However, they are used in existing applications and, in particular, event control queues exist for the missed uuids. Without this patch, commands such as hangup on those calls cannot reach FS.

Missing originate_uuid event breaks existing apps (noticed on acdc)

---

core/kazoo_translator/src/convertors/kzt_twiml.erl
core/kazoo_translator/src/convertors/kzt_twiml_dial.erl
core/kazoo_translator/src/kzt.hrl
core/kazoo_xml/src/kz_xml.erl

Use xmerl's {space, normalize} to reduce #xmlText{} with just
whitespace to " ". Added function to remove those #xmlText{} elements.
Additionally, there was an unintentional pattern match when matching a
single <Number> element. The attributes of the Dial and Number
elements were being bound with the same name. Differentiated those to
make sure the single Number clause is used.

HELP-26680: filter empty text elements

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.record_call.json

when adding a "stop" action, time_limit can/should be unset from the
client to avoid validation errors. If we include a default, time_limit
will be set and, if the schema changes, the value could become invalid
through no fault of the user.

HELP-26661: remove default time_limit

---

applications/callflow/src/module/cf_disa.erl
applications/callflow/src/module/cf_prepend_cid.erl
core/kazoo_endpoint/src/kz_attributes.erl
core/kazoo_endpoint/src/kz_endpoint.erl

* keep the origrinal caller id in disa & add some log lines
* move get account cid to kz_attributes to keep cid hunting in sync
* log correct number that is about to set
* HELP-26318 preserve already set CID in endpoint, and keep the CID in prepend in from PR #2857

keep the original caller id for DISA and preserve CID for prepend

---

core/kazoo_number_manager/src/carriers/knm_bandwidth2.erl

It could be that I'm not calling `knm_bandwidth2:sites()` incorrectly, but when I call it with `account_id`, `api_username`, and `api_password` set in `system_config/number_manager.bandwidth2`, I get an error:
`** exception error: no match of right hand side value {error,<<"Number not found">>}`
After adding the lines for verifying the response for the sites and peer id requests, the methods return successfully.

Bandwidth sites and peers results have an xpath that is different from the rest

---

applications/konami/src/konami_listener.erl

(HT Paolo Consolaro)
In commit ab0e0e6b1b275a58ad65dee8a5b31e243bac588d Luis Azedo introduced the
"metaflow" exchange in AMQP. But a typo prevents konami to properly react to
this exchange bindings as published, I think, by:
grep METAFLOW_BIND_ROUTING_KEY ./core/kazoo/src/api/kapi_metaflow.erl
...
-define(METAFLOW_BIND_ROUTING_KEY(AccountId, CallId), <<"metaflow.bind.", ...

konami listener typo for metaflow exchange

---

core/whistle_number_manager-1.0.0/src/carriers/wnm_bandwidth2.erl

Backport of PR #2897 
Error when calling `wnm_bandwidth2:sites/0` and `wnm_bandwidth2:peers/1` with `account_id`, `api_username`, and `api_password` set in `system_config/number_manager.bandwidth2`

Account for reponses for sites and peer ids requests with wnm_bandwidth2

---

applications/fax/src/fax_smtp.erl

Backport of the commit ca6a32bc99d83ba3a57a77d50455633c03123a16 (#2742) to 3.22

[3.22] fix fax_smtp if one part doesn't have attachments in nested multipart emails

---

core/kazoo_attachments/src/kz_att_ftp.erl
core/kazoo_attachments/src/kz_att_http.erl

Fix `kz_att_http:fetch_attachment/1`
Fix `default_format/0` in kz_att_http & kz_att_ftp
Fix parsing `field_list` from storage_plan in kz_att_http & kz_att_ftp

qf kz_att_http & kz_att_ftp

---

core/kazoo_bindings/src/kazoo_bindings.erl
core/kazoo_bindings/test/kazoo_bindings_test.erl

The long and short of it is that when you have a # and repeated
segments, the code was being too greedy with the # matching.
In matching <<"*.u.*.7.7.#">> against <<"i.u.e.7.7.7.a">>, the code
would match away 'a' and '7' but would also strip a '7' from the
routing key.
Uncomment dbg_test and run it with the above binding and routing keys
to see it in action.

binding_fix: add needed clause to handle found failure

---

core/kazoo_endpoint/src/kz_endpoint.erl

If only call is on-net and "Keep Caller ID" is enabled set retain caller.

KAZOO-5107: only retain cid if on-net call and keep_caller_id is enable

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/src/modules/cb_media.erl
core/kazoo/src/kz_util.erl
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_media/src/kz_media_util.erl
core/kazoo_voicemail/src/kazoo_voicemail_maintenance.erl
core/kazoo_voicemail/src/kvm_message.erl
core/kazoo_voicemail/src/kvm_messages.erl
core/kazoo_voicemail/src/kvm_util.erl

~~DO NOT MERGE THIS YET!~~ It's ready
with ability to prepend a message
* add an option to message_menu for forwarding a message
* present a forwarding menu to user if they wish to prepend a message
* if forwarding without a prepend, just call `copy_to_vmboxes` and if it was successful, send mwi update for both vmboxes/owners
* if forwarding with a prepend message, try to record and join the desire message and save it as new message to destination vmbox then send mwi update to both vmboxes/owners
* depends on https://github.com/2600hz/kazoo-sounds/pull/4 for prompts necessary for forwarding
~~DO NOT MERGE THIS YET!~~ It's ready

KAZOO-5212: forward a vm message to another vmbox from callflow

---

applications/stepswitch/src/stepswitch_bridge.erl

The stepswitch_formatters are determining that the caller id name/number is different if the caller id is corrected for an emergency call.  They they set per-leg the 'formatted' caller id based on the original, overriding the correction.  To correct, if the emergency cid is utilized copy it to the endpoints (if necessary) so that the formatters use the corrected caller id.

HELP-27113: update endpoint cid when emergency

---

core/kazoo_services/src/kz_services.erl

It seems we're applying cascade quantities twice during
calculating services charges.
Currently in `kz_services:calclute_services_charges/2` gets current
quantities, apply cascade quantities and then set the result (which
is current quanitties + updates + Cascade quantities) into the service jobj which
looks okay at the first sight.
But in the line below that, when the items are created for the updated
service jobj, `kz_service_plans:create_items/2` is calling `kz_service_plans:create_items/1`
which by default is calculating cascade quantities.
This results to adding cascade quatinties to updated service twice.
In this patch I remove the call to `apply_cascade_quantities/2`, because
in the end when creating service from json, it will calculate anyway.
This still needs to be tested though.

HELP-26829: do not compute cascade quantities twice

---

applications/trunkstore/src/ts_from_offnet.erl
applications/trunkstore/src/ts_util.erl
core/kazoo_endpoint/src/kz_attributes.erl
core/kazoo_endpoint/src/kz_endpoint.erl

Making sure caller id format from caller_id_options works again in both Callflow and Trunktore.

KAZOO-4009: make cid format from caller_id_options works again

---

applications/callflow/src/module/cf_disa.erl
applications/callflow/src/module/cf_dynamic_cid.erl
applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.dynamic_cid.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.dynamic_cid.json

* Add a new mode to cf_dynamic which allows users to set a static caller id.
* Inform user if the cid would be set to the default:
Better response to user if the caller id number are missing and is about to
set to default value, instead of hanging up.
* Read manual mode options from callflow data, default to system_config
* Handle channel hungup during collect digits in disa and dynamic cid

[4.0] HELP-26637: add static mode to cf_dynamic

---

applications/callflow/src/module/cf_disa.erl
applications/callflow/src/module/cf_dynamic_cid.erl
applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.dynamic_cid.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.dynamic_cid.json

* This is adding a static mode to cf_dynamic module. Users can set a static caller id in the callflow. This should works with/without CaptureGroup.
* Make min, max digits and regex for manual mode configurable in the callflow data.
* for static, list and lists mode, if one the caller id name or number or both is missing inform user that we're going to set them to default value(play reject dynamic cid prompt).

HELP-26637: add static mode to cf_dynamic

---

applications/blackhole/src/blackhole_bindings.erl

the typo didnt let modules started with blachole in front of the names to be validated

Typo fix for blackhole binding validation

---

applications/crossbar/src/crossbar_bindings.erl

Typo which didn't validate any module as crossbar module when crossbar appended in front of the module name

Validation of crossbar module typo fix

---

core/kazoo_number_manager/src/carriers/knm_carriers.erl
core/kazoo_number_manager/src/knm.hrl
core/kazoo_number_manager/src/knm_phone_number.erl
core/kazoo_number_manager/test/knm_release_number_test.erl

Note: the catch-all was added so that binary_to_existing_atom failure is caught.

KAZOO-5260_4oh: fix number release of unknown carrier

---

core/kazoo_number_manager/src/knm_search.erl

I'm testing Telnyx as a number provider atm.
Sometimes Telnyx processes its number lookup slightly longer than 5 seconds.
Because of 5000 number search hardcoded timeout, Kazoo provides empty result...

KAZOO-5262: Make number search timeout configurable

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json

@onnet Hey would you happen to know why CircleCI does not run your PRs?
Examples: https://github.com/2600hz/kazoo/pull/3078 https://github.com/2600hz/kazoo/pull/3081

qfm: add missing description on system_config entry

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.json
applications/crossbar/src/crossbar_init.erl

Check IP address for IPv6, if it failed check for IPv4.
Default to `::` if IPv6 is enabled, otherwise to bind to `0.0.0.0`.

KAZOO-5270: read crossbar ip from system_config

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.json
applications/crossbar/src/crossbar_init.erl

Check IP address for IPv6, if it failed check for IPv4.
Default to `::` if IPv6 is enabled, otherwise to bind to `0.0.0.0`.

[4.0] KAZOO-5270: read crossbar ip from system_config

---

applications/fax/src/fax_util.erl

Handle a case when number is empty during validating caller _id in fax_util
(backport of #3111)

[4.0] KAZOO-5273: return false if number is empty in fax_util

---

applications/fax/src/fax_util.erl

Handle a case when number is empty during validating caller _id in fax_util

KAZOO-5273: return false if number is empty in fax_util

---

applications/crossbar/src/cb_apps_util.erl

If the account does not have a service plan with apps defined then it lists all apps of the reseller, unless the reseller doesn't have apps defined in which case it list all system apps.
If the service plan defines the available apps then it gets the list from the service plan, regardless of the published state.
> NOTE: currently there is no logic for checking the `published` status, and **NONE** of the Monster apps have `published` set in their `metadata/app.json` file!

[4.0] HELP-26987: check service plan for ui_apps recursively to top reseller

---

core/kazoo_number_manager/src/providers/knm_telnyx_e911.erl

Telnyx config "sandbox_provisioning" flag doesn't influences 911 provisioning behaviour.
Detailed conversation could be found over here: https://github.com/2600hz/kazoo/pull/3081

Telnyx E911 sandbox provisioning

---

applications/stepswitch/src/stepswitch_inbound.erl

check conditions for call to be anonymous:
- caller_id_number is set to two or more zeroes, maybe with plus sign
- caller_privacy_number is set to true
- caller_privacy_name is set to true
tests: https://github.com/2600hz/make-busy-callflow/commit/148a37c51dd196cc2dc15deed3cc588bfd8a9873

KAZOO-4791: block anonymous calls

---

applications/callflow/src/module/cf_directory.erl

Adding a few check maximum loop to avoid infinite loop in some of the functions in cf_directory.

KAZOO-5217: set a maximum loop during collecting digits cf_dicrectory

---

applications/callflow/src/module/cf_directory.erl

Adding a few check maximum loop to avoid infinite loop in some of the functions in cf_directory.
(backport of #3121)

[4.0] KAZOO-5217: set a maximum loop during collecting digits cf_dicrectory

---

applications/crossbar/src/modules_v2/cb_devices_v2.erl
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
core/kazoo_number_manager/src/knm.hrl
core/kazoo_number_manager/src/knm_number.erl
core/kazoo_number_manager/src/knm_number_options.erl
core/kazoo_number_manager/src/knm_phone_number.erl
core/kazoo_number_manager/src/knm_search.erl
core/kazoo_number_manager/test/knm_create_new_number_test.erl
core/kazoo_number_manager/test/knm_move_number_test.erl

create number in func add_mobile_mdn in cb_devices
(backport of #3127)

[4.0] KAZOO-5278: create the number when adding a mobile device

---

applications/crossbar/src/modules/cb_vmboxes.erl

Fix issue during testing VM delete method, when there is no query string but message id is member of list of messages that should be deleted
(backport of #3136 )

[4.0] fix issue in delete method when there is no qs

---

applications/crossbar/src/modules/cb_vmboxes.erl

Fix issue during testing VM delete method, when there is no query string but message id is member of list of messages that should be deleted

fix issue in delete method when there is no qs

---

core/kazoo/src/kz_util.erl
core/kazoo/test/kz_util_test.erl
core/kazoo_number_manager/src/knm_number_options.erl

cc https://github.com/2600hz/kazoo/pull/3149

KAZOO-5293_4oh: ensure KNM options precendence is meaningful

---

applications/crossbar/src/modules/cb_accounts.erl

'trial_time_left' is the flag one can use to assume the account is in trial/evaluation state.
Posting this flag to the account doc allows to keep it and pretend the account is trial despite it is not...

fake_trial_time_left

---

applications/callflow/doc/cf_branch_variable.md
applications/callflow/doc/cf_dynamic_cid.md
applications/callflow/src/module/cf_branch_variable.erl
applications/callflow/src/module/cf_dynamic_cid.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.branch_variable.json
applications/crossbar/priv/couchdb/schemas/callflows.dynamic_cid.json

Re-work of PR #1732
Change the current cf_branch_variable module to add more places that a variable can be look up. Use case is if someone wants to branch based on value of a specific variable in users/device/account documents.
Default location to define the name of the variable is in "custom_channel_vars" which is because of preserving the current behavior if the scope is not defined.
(backport of #3077 and #3120 )

[4.0] KAZOO-4601: branch on a variable's value

---

applications/trunkstore/src/ts_from_onnet.erl

@k-anderson fixed. I guess I named the variable in `ts_callflow` `Done` and matched on `{done, _}` instead of the actual tagged tuple `{bridged, _}`.

ts_bridged: handle return when channel is bridged

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
core/kazoo_number_manager/src/knm_port_request.erl

This is disabled by default. Can be enabled by setting "allow_port_transition_from_submitted_to_scheduled" in system_config/number_manager to true.

Allow number port transition from submitted to scheduled

---

applications/crossbar/src/api_resource.erl
core/kazoo_json/src/kz_json.erl
core/kazoo_json/test/kz_json_test.erl

- calculate difference between json objects
- new api for flatten (second argument determines the way to join keys)
- new function expand to convert from flatten representation

kz_json:diff, expand, flatten/2

---

core/kazoo_endpoint/src/kz_endpoint.erl

The change to andalso in KAZOO-5107 actually causes the caller ID to never appear for forwarded external callers. We just ran into this after a recent merge and reverting the change fixes the issue. Not directly reverting commit so as to keep lager line english update ;)

Revert KAZOO-5107 change as that actually /broke/ it in the way the ticket describes

---

applications/stepswitch/src/stepswitch_local_extension.erl
core/kazoo_endpoint/src/kz_privacy.erl

Fix backward caller id for loopback calls introduce by previous privacy PR.
Plus better log line why ignoring caller privacy hide name/number and actually hide configured cid part

KAZOO-5268: fix backward cid in loopback

---

applications/callflow/src/module/cf_voicemail.erl

Some customers want the ability for a caller to have the option to contact a secretary or to leave a message. Currently the only way to achieve that is to put a menu in front of the voicemail which means the caller hears two messages. This change allows a button to be pressed to skip the voicemail element (# by default).

Allow escape from voicemail to next callflow element

---

applications/crossbar/priv/couchdb/views/port_requests.json
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl

Conflicts:
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl

HELP-28312: include active port in numbers by default

---

core/kazoo_ast/src/cf_data_usage.erl

cf_data_usage looks for kz_json:get_value(K,V) pattern,
in case K is a function call (e.g. kz_json:get_value(fun(), V) it fails because of missing clause,
and here is a fix for this clause.

skip keys that are function calls

---

applications/crossbar/doc/notifications.md
applications/crossbar/src/modules/cb_notifications.erl
applications/teletype/src/templates/teletype_customer_update.erl
core/kazoo_amqp/src/api/kapi_notifications.erl

As a kapp developer I would like to be able to send different updates form my app to customer(s) with the information generated in my kapp.
In order to do that I need to be able to:
- manage multiple templates for notification emails of customer_update type, e.g. "new billing period approaching", "Happy New Year", etc;
- provide these templates with data generated by my kapp during template compilation;
- use existing customer_update mechanism in order to not to create teletype modules again and again

KAZOO-5335: Teletype customer_update enhancement

---

applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/modules/cb_vmboxes.erl

prefix filter props in query strings with `metadata.`, so filtering messages are possible in vmboxes.

HELP-28524: prepare qs filter props for filtering in vmbox

---

applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/modules/cb_vmboxes.erl

prefix filter props in query strings with metadata., so filtering messages are possible in vmboxes.
backport of (#3349)

[4.0] HELP-28524: prepare qs filter props for filtering in vmbox (#3349)

---

applications/crossbar/src/modules/cb_accounts.erl

When account creation failed, we don't return an error to UI, so UI doesn't know that account has not created, which result in UI continues to make other request to put limits, callflow an etc to the non-existent account.
backport of (#3388)

[4.0] properly return an error when exception raised in account creation

---

applications/crossbar/src/modules/cb_accounts.erl

When account creation failed, we don't return an error to UI, so UI doesn't know that account has not created, which result in UI continues to make other request to put limits, callflow an etc to the non-existent account.

[master] properly return an error when exception raised in account creation

---

core/kazoo_number_manager/src/knm_phone_number.erl
core/kazoo_number_manager/src/providers/knm_providers.erl
core/kazoo_number_manager/test/knm_number_test.erl

qf-extfeat_4oh: allow setting external features by default

---

applications/crossbar/src/modules/cb_pivot.erl

Also set debug_id for each log to fetch the debug details for old logs
backport of (#3433)

[4.0] KAZOO-5105: span to multiple modb when fetching pivot debug logs

---

applications/crossbar/src/api_resource.erl
core/kazoo/src/kz_network_utils.erl

Fix kz_network_utils:verify_cidr/2 (it never match)
Display IPv4 addres when it is mapped in IPv6 (0:0:0:0:0:ffff:0:0/96 [RFC](https://tools.ietf.org/html/rfc4038#section-4.2))

QF Crossbar log & kz_network_utils:verify_cidr/2

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.hotornot.json
applications/hotornot/src/hon_trie.erl
applications/hotornot/src/hon_trie_lru.erl
applications/hotornot/src/hon_util.erl
applications/hotornot/src/hotornot.hrl
applications/hotornot/src/hotornot_config.erl
applications/hotornot/test/hon_trie_lru_pqc.erl

This allows you to progressively load rates instead of loading the
whole ratedeck in one shot. Minimizes memory usage as rarely-used
rates aren't kept in memory while oft-used rates stay in-memory for
fast matching.

KAZOO-5396: hon_trie_lru - progressively load rates

---

applications/crossbar/priv/couchdb/schemas/metaflow.callflow.json

Hi! 
Since we've got an option to look for a callflow based on captures, it seems "id" field shouldn't be strictly demanded...
https://github.com/2600hz/kazoo/blob/master/applications/konami/src/module/konami_callflow.erl#L32-L38
Regards,

metaflow.callflow: should "id" field be the mandatory one?

---

applications/crossbar/priv/couchdb/schemas/metaflow.callflow.json

Revert "metaflow.callflow: should "id" field be the mandatory one?"

---

rel/args

master: https://github.com/2600hz/kazoo/pull/3499

qf-vmargs_4oh: remove ERL option that disables writting crash dumps

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.teletype.json
applications/teletype/src/teletype_util.erl

Parametrize  `kz_notification:is_enabled/2` default value in `teletype_util:is_notice_enabled`.
Set it to `true` by default.

KAZOO-5421: HELP-28880: make is_notice_enabled a system parameter

---

applications/crossbar/doc/ref/system_configs.md
applications/crossbar/doc/system_configs.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/src/crossbar_init.erl
applications/crossbar/src/modules/cb_system_configs.erl
core/kazoo_apps/src/kapps_maintenance.erl
core/kazoo_config/src/kapps_config_doc.erl
core/kazoo_config/src/kapps_config_util.erl
core/kazoo_json/include/kazoo_json.hrl

A system configuration document is a JSON document of certain
syntetic type (each node value must be a JSON object of type
system_config.$config_name). REST API allows to address both
documents and and docuemnt nodes. Default node of the
configuration document is treated specially, see below.
In order to avoid confusion configuration document nodes
we call document sections, each such section is a JSON
object representing a configuration object for Kazoo
node or zone.
General idea is to return (with with_defaults=true URI
option) the effective values for configuration, therefore
a complex mergedown is performed: document values are
merged with document default section, and then merged
with schema defaults.
Therefore on save actions (PUT/POST/PATCH) a reverse
operation is performed: a …

cb_system_configs with defaults

---

applications/crossbar/src/modules/cb_notifications.erl

Walk up in account up to the first reseller and then system_config for getting templates in crossbar notifications. same logic as how templates are fetching in teletype.
Advantage is users see the same teletype that they're getting from teletype.

HELP-29219: walk to reseller then system_config in cb_notification

---

core/kazoo_config/src/kapps_config_util.erl

The merge fails when trying to load the system config. This corrects that.

Fix error when merging configs in kapps_config

---

applications/callflow/src/cf_exe.erl

giving time for other actions in ecallmgr execution queue to complete

move hangup to tail of ecallmgr execution queue

---

core/kazoo_services/src/kz_services.erl

The {'error', 'no_change'} return value of maybe_save isn't used, but causes an error such as in https://github.com/2600hz/kazoo/blob/master/core/kazoo_number_manager/src/knm_services.erl#L135. The return value is used as if it were a services record. Making the change in kz_services:maybe_save/1 because nothing uses the error tuple.

Repeat service reconciles: Remove unused/bad return type

---

applications/crossbar/src/modules/cb_parked_calls.erl

makes sure crossbar returns the freshest parked calls object available

cf_park doesn't use cache; neither should parked_calls

---

applications/callflow/src/cf_exe.erl

* move hangup to tail of ecallmgr execution queue giving time for other actions in ecallmgr execution queue to complete

move hangup to tail of ecallmgr execution queue - 4.0

---

applications/conference/src/conf_participant.erl
applications/conference/src/conf_route_req.erl

If a conference caller has to bridge to another media server because their original call was not on the media server running the mod_conference instance, name announcements will not work. The necessary FS channel vars (conference_enter_sound & conference_exit_sound) that mod_conference looks for will not be present on the channel on the new media server (to be expected, as FS instances can't share channel vars). So, when bridging, send some SIP headers that can be unwrapped in conf_route_req that will set the name announcements on the new channel.
Also removed the bridged_conference/1 function as it is no longer relevant since Kazoo 4 conferences use mod_conference's built-in media features.

PISTON-422: fix name announcements in conferences when crossing media servers

---

applications/acdc/src/acdc_maintenance.erl
applications/acdc/src/acdc_stats.erl
applications/cdr/src/cdr.hrl
applications/cdr/src/cdr_channel_destroy.erl
applications/cdr/src/cdr_util.erl
applications/crossbar/src/modules/cb_cdrs.erl
applications/crossbar/src/modules/cb_sms.erl
applications/doodle/src/doodle_util.erl
applications/fax/src/fax_maintenance.erl
applications/webhooks/src/webhooks_util.erl
core/kazoo_bindings/src/kazoo_bindings.erl
core/kazoo_media/src/kz_media_recording.erl
core/kazoo_modb/src/kazoo_modb.erl
core/kazoo_modb/src/kazoo_modb_view.erl
core/kazoo_services/src/kz_services_modb.erl
core/kazoo_voicemail/src/kvm_message.erl
core/kazoo_voicemail/src/kvm_messages.erl

* make sure we use `kazoo_modb` function for `get_results`, `save_doc`, `copy_doc`, `move_doc` every place that we operate on MODB. This cause if modb is not created yet, creates it and properly refresh modb views
* add functions for move and copy doc to kazoo_modb

[master] HELP-29570: use kazoo_modb for most modb ops

---

applications/crossbar/src/modules/cb_account.erl
applications/crossbar/src/modules/cb_me.erl

It would be useful to be able to use /me instead of /accounts/{AUTH_ACCOUNT_ID}. This mimics many other APIs, and would make it easier to integrate Crossbar with other services. It also increases the usability of Crossbar as this is what most uses want for every API request.
This currently doesn't work with the autogenerated API documentation as it calls methods in cb_accounts as part of allowed_methods. Would you prefer I hardcoded the values obtained from cb_accounts, or kept it as it is and manually wrote the documentation?

Added cb_me endpoint to alias /accounts/{AUTH_ACCOUNT_ID}

---

core/kazoo_number_manager/src/knm_numbers.erl
core/kazoo_number_manager/test/knm_numbers_test.erl

knm-reserve: (and reconcile and create) fail if assign_to is not an account id

---

core/kazoo_documents/src/kzd_rate.erl

Restores setting ID as before in [cb_rates](https://github.com/2600hz/kazoo/blob/master/applications/crossbar/src/modules/cb_rates.erl#L435)

Set Rate ID to {ISO}-{Prefix} as before

---

applications/crossbar/src/modules/cb_notifications.erl
applications/teletype/src/teletype_templates.erl

It seems useful to allow accounts to modify the notification docs for a teletype notification while using the system level template. This allows us to make a change to the template in system_config and have it apply to any accounts that have overridden fields such as "from" in the notification doc but not provided their own template. (That's our use case)
This is currently possible by doing a POST to /v[12]/accounts/<account_id>/notifications/<notification_id> with just the metadata fields and no attachment. Without the modifications in this PR, the notification doesn't work when a POST is done this way. With them, if a notification doc doesn't have attachments going up the tree, it will fall back to the system_config template attachments.

PISTON-421: allow teletype to use system-level templates as fallback

---

applications/crossbar/src/modules/cb_accounts.erl

reduces channel creation/destruction for this one-off process

use worker to publish new account notification

---

core/kazoo_apps/src/kapps_maintenance.erl

4.0: https://github.com/2600hz/kazoo/pull/3665

remove maintenance code duplicating notify's maintenance code (master)

---

core/kazoo_apps/src/kapps_maintenance.erl

Reported by @swysor  after crash:
```
<9847.5234.0> (21/21) refreshing database 'system_config'
archiving to /tmp/system_config.json
archived 83 docs
<9847.5234.0> (20/21) refreshing database 'system_data'
<9847.5234.0> (19/21) refreshing database 'offnet'
<9847.5234.0> (18/21) refreshing database 'accounts'
Stderr Command failed: {'EXIT',{badarg,[{erlang,list_to_binary,[[{error,bad_name},"/couchdb/",<<"views/notify.json">>]],[]},{kapps_util,get_view_json,2,[{file,"src/kapps_util.erl"},{line,530}]},{kapps_maintenance,refresh,1,[{file,"src/kapps_maintenance.erl"},{line,315}]},{kapps_maintenance,refresh,3,[{file,"src/kapps_maintenance.erl"},{line,244}]},{kapps_maintenance,migrate,2,[{file,"src/kapps_maintenance.erl"},{line,141}]},{kapps_maintenance,migrate,1,[{file,"src/kapps_maintenance.erl …
```

remove maintenance code duplicating notify's maintenance code

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.notifications.json
applications/crossbar/src/modules/cb_notifications.erl

As an extension to https://github.com/2600hz/kazoo/pull/3618, we are finding it useful to allow POST updates to .../notifications/<notification_id> to omit a couple of the required fields (subject/to) and merge them in from the notification inherited from up the account tree. They are still required as per the schema - retains compatibility with teletype logic.
We use this to provide control of the "from" of a notification, but automatically fill in "subject" (without having to explain the macros) and avoid potentially unwanted configuration of the "to".

PISTON-425: use parent teletype config subject/to as defaults

---

applications/crossbar/src/modules/cb_callflows.erl
applications/crossbar/src/modules/cb_connectivity.erl
applications/crossbar/src/modules/cb_modules_util.erl
core/kazoo_number_manager/src/knm_number_states.erl

Ensure that number docs can't be modified by cb_callflows or cb_connectivity if the authorizing account does have rights to do so.
We noticed that it was possible to update fields in a numbers document that shouldn't be allowed simply by permitting the update of in_service numbers by setting assign_to to an account that /would/ allow those doc updates. This is handled in the knm_number_states change.
cb_callflows and cb_connectivity have validation functions to prevent the callflow from saving if the additional functions (track_assignment and reconciliation) shouldn't be allowed.

PISTON-351: validate did ownership before saving callflows/trunks

---

core/kazoo_number_manager/src/knm_numbers.erl

Found during failed creation of the master account

qf-free: skip free-ing an account's numbers if something is wrong

---

applications/teletype/src/templates/teletype_system_alert.erl

when there is no post url or when there's an error in the post request than the email is sent twice, so this change will send email as default as well as send post to a url but when the email is turned off and the post request fails only than send email as a backup option.

Teletype dual email fix

---

applications/crossbar/doc/ledgers.md
applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/modules/cb_ledgers.erl
applications/crossbar/src/modules/cb_modules_util.erl
core/kazoo_ledgers/src/kz_ledger.erl
core/kazoo_ledgers/src/kz_ledgers.erl
core/kazoo_modb/priv/couchdb/views/ledgers.json
core/kazoo_modb/priv/couchdb/views/transactions.json
core/kazoo_stdlib/src/kz_json.erl
core/kazoo_stdlib/test/kz_json_test.erl

1. Accumulates total credits/debits for any ledger on /ledger, within the given or default time range (changes to kz_ledgers)
1. Fixes multi-databases modb crossbar view queries (see crossbar_doc's introduction of the should_paginate boolean)

KAZOO-5426 & KAZOO-5352: support ranges in ledgers + better data accumulation

---

applications/crossbar/priv/api/swagger.json
core/kazoo_ast/src/cb_api_endpoints.erl

Removes a lot of Swagger validation issues, leaving only errors (and lots of warnings):
```
#/definitions/callflows.page_group/properties/endpoints/default: Array is too short (0), minimum 1
#/definitions/callflows.ring_group/properties/endpoints/default: Array is too short (0), minimum 1
#/definitions/dialplans/properties/system: Missing required property: items
#/paths/~1google_auth/put/parameters/0/schema/$ref: Definition could not be resolved: #/definitions/google_auth
#/paths/~1ip_auth/put/parameters/0/schema/$ref: Definition could not be resolved: #/definitions/ip_auth
#/paths/~1accounts~1{ACCOUNT_ID}~1presence~1report-{REPORT_ID}/get: API requires path parameter but it is not defined: REPORT_ID
```
To reproduce:
```shell
npm install swagger-tools …
```

qf-swagpaths: fix up $ref's

---

Makefile

Cause previous tag randomly disappeared!
c.f. https://github.com/ninenines/erlang.mk/issues/703
master: https://github.com/2600hz/kazoo/pull/3729

bump erlang.mk to 2017.05.18 from 2016.01.12

---

applications/cdr/src/cdr_util.erl

Ignore the confict if the cdr is tried to be saved again, 
If the cdr is tried to save again the conflict error is ignored and the value is given as retries error which causes a error log to be generated in cdr_util

Ignore the cdr conflict

---

core/kazoo_couch/src/kz_couch_db.erl
core/kazoo_modb/src/kazoo_modb.erl

CouchDB returns and HTTP error 500 with payload
`{"error":"error","reason":"conflict"}`
This seems and internal error when couchdb tries to create the shard
files, but due to race condition on creating db at same time those files
are already created, so couchdb returns an undocumented error.
The `kazoo_modb:create` falsely thinks that database creation failed and
won't referesh views.
This patches `kz_couch_db` to handle that error.
Also it patches the `kazoo_modb` to retry the operation due db creation
failure.

[master] HELP-30444: check for conflict when creating db

---

core/kazoo_couch/src/kz_couch_db.erl
core/kazoo_modb/src/kazoo_modb.erl

CouchDB returns and HTTP error 500 with payload
`{"error":"error","reason":"conflict"}`
This seems and internal error when couchdb tries to create the shard
files, but due to race condition on creating db at same time those files
are already created, so couchdb returns an undocumented error.
The `kazoo_modb:create` falsely thinks that database creation failed and
won't refresh views.
This patches `kz_couch_db` to handle that error.
Also it patches the `kazoo_modb` to retry the operation due db creation
failure.
backport of (#3783 )

[4.0] HELP-30444: check for conflict when creating db

---

core/kazoo_transactions/src/kz_transaction.erl

@fenollp (#3782) Hi! 
IMHO we should expect modb according to this line: https://github.com/2600hz/kazoo/blob/master/core/kazoo_transactions/src/kz_transaction.erl#L753
Sorry in advance if I'm wrong :)

db type mismatch

---

applications/crossbar/doc/ref/token_restrictions.md
applications/crossbar/doc/token_restrictions.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/token_restrictions.json
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar_auth.erl
applications/crossbar/src/crossbar_util.erl
applications/crossbar/src/modules/cb_token_restrictions.erl
applications/crossbar/test/cb_token_restrictions_test.erl
core/kazoo_schemas/src/kz_json_schema.erl
make/kz.mk
scripts/export_auth_token.bash

The new auth doc in crossbar_auth didn't add "restrictions" to the
auth doc (as was done in other auth work in crossbar_util). This
meant token restrictions were never processed during the authorize
phase.

amend auth doc with restrictions

---

applications/crossbar/src/crossbar_auth.erl
applications/crossbar/src/crossbar_util.erl
applications/crossbar/src/modules/cb_token_restrictions.erl

Instead of loading the restrictions into the auth doc (and ballooning the size on large restriction rule sets), load them from the restrictions doc on each request and compare.

Load token restrictions per request

---

core/kazoo_amqp/include/kz_amqp.hrl
core/kazoo_amqp/src/amqp_util.erl
core/kazoo_amqp/src/kz_amqp_channel.erl

When AMQP methods have fields that violate their constraints (like a routing key over 255 characters, for instance), the connection is taken down which is obviously disruptive to the system and a bit of overkill. Before we send the method to the amqp_client code, let's assert that it can be encoded properly for sending to the broker (via the amqp_client library).

AMQP framing check

---

applications/crossbar/src/modules/cb_callflows.erl

During collecting additional info about objects referenced in a callflow, when matching if the key has `_id` in it, also checks if the value is actually a binary. (e.g. do not consider it as id if the value is a json object, for example `{"caller_id": {"number":"123", "name": "alaki"}}`)

check the id actually is a binary in ids_in_flow

---

core/kazoo_number_manager/src/knm_telnyx_util.erl

Just a temporary correction while guys thinking: https://groups.google.com/forum/#!topic/2600hz-dev/UaIqtL_OVGY

KAZOO-5473: Why limit numbers lookup to Zero?

---

core/kazoo_number_manager/src/knm_telnyx_util.erl

master: https://github.com/2600hz/kazoo/pull/3890

KAZOO-5473: Why limit numbers lookup to Zero? (#3890)

---

applications/crossbar/priv/couchdb/account/vmboxes.json
applications/fax/src/fax_maintenance.erl
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_modb/src/kazoo_modb.erl
core/kazoo_modb/src/kazoo_modb_migrate_maintenance.erl
core/kazoo_modb/src/kazoo_modb_util.erl
core/kazoo_voicemail/src/kvm_message.erl
core/kazoo_voicemail/src/kvm_util.erl
core/kazoo_voicemail/src/kz_voicemail.hrl
core/kazoo_voicemail/src/migrate/kvm_migrate_account.erl

Add maintenance command to migrate cdrs and voicemail from AccountDB to MODB.
Useful for cleaning Account DBs purposes in which it would create old modb if they're not present.

HELP-27660: migrate cdrs and voicemail to modb

---

applications/acdc/src/acdc_agent_listener.erl
applications/acdc/src/acdc_util.erl

Fix compatibility with changes made to kapi_presence:update_routing_key/1

PISTON-442: use PresenceId for default CallId in acdc_util:presence_update/3

---

core/braintree/src/braintree_descriptor.erl

while creating a new subscription braintree descriptor is undefined which crashes, bookkeeper sync

Braintree Descriptor crash fix

---

applications/omnipresence/src/omnip_subscriptions.erl

`omnip_util:request_probe(Package, Username, Realm)`  was being called with value `user` instead of `username` which contains `username@realm` so the function was changed to `omnip_util:request_probe(Package, User)`

MWI function fix

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.services.json
core/kazoo_services/include/kz_service.hrl
core/kazoo_services/src/kz_services.erl

Hi,
At the moment only kz_bookkeeper_local could be used to bill non master reseller's children.
This reduces the benefit of reseller tree feature.
I would like to propose a little step forward in order subresellers could also have fully featured billing solution within their Kazoo platform tenant  
Regards,
Kirill

reseller_bookkeeper_lookup

---

applications/crossbar/doc/port_requests.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/port_requests.to_scheduled.json.src
applications/crossbar/priv/couchdb/views/port_requests.json
applications/crossbar/priv/port-request-scheduled-schema.escript
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/crossbar_maintenance.erl
applications/crossbar/src/modules/cb_accounts.erl
applications/crossbar/src/modules/cb_port_requests.erl
applications/crossbar/src/modules_v1/cb_users_v1.erl
applications/crossbar/src/modules_v2/cb_users_v2.erl
applications/teletype/src/teletype_port_utils.erl
core/kazoo_ast/src/cb_api_endpoints.erl
core/kazoo_number_manager/include/knm_port_request.hrl
core/kazoo_number_manager/src/knm_port_request.erl

Fixes and issue where, after validating a scheduled port request, the PATCH would forget about the port request JSON and only continue with the req data.
`crossbar_doc:patch_and_validate` was not used here because `cb_port_requests` loads then checks/modifies its documents its own way and I do not want to deal with that mess.

qf-portreq: introduce and use validate_request_data_only/2,3,4

---

core/kazoo_number_manager/src/knm_number.erl

Creating a number authorised by system currently crashes with the following stacktrace:
```
02:23:28.322 warning kzs_util.86 unknown type for database account%2Fsy%2Fst%2Fem
02:23:28.322 error kz_util.108 stacktrace:
02:23:28.323 error kz_util.120 st: kzs_util:db_classification/1 at (87)
02:23:28.323 error kz_util.120 st: kzs_plan:get_dataplan/1 at (70)
02:23:28.323 error kz_util.120 st: kzs_plan:plan/2 at (47)
02:23:28.323 error kz_util.120 st: kz_datamgr:open_doc/3 at (631)
02:23:28.323 error kz_util.120 st: kzs_cache:open_cache_doc/3 at (52)
02:23:28.323 error kz_util.120 st: knm_number:allow_number_additions/2 at (253)
02:23:28.323 error kz_util.120 st: knm_number:allowed_creation_states/2 at (171)
02:23:28.326 error kazoo_bindings.692 excepted: error: {badmatch,{error,not_found}} …
```

Fix create number with auth_by system

---

core/kazoo_ast/README.org
core/kazoo_ast/src/code_usage.erl

For now, just counts literal usage of the M:F/A (no dynamic M or F). Could be nice to add more functions that analyze the counts, or unwrap Kazoo M:F/A until an Erlang/OTP module is encountered. Could also look at other code analysis tooling to see what they look for and adapt here.

Count M:F/A across the project or within an application

---

applications/crossbar/src/crossbar_util.erl

Can't see why it wasn't doing this already

fallback to user_id in crossbar_util:response_auth

---

applications/crossbar/doc/basics.md
applications/crossbar/src/api_resource.erl
applications/crossbar/test/api_resource_test.erl

This allows seeking of streamed media in HTML5, and will show the correct media length in Safari.

Allow HTTP partial response

---

make/kz.mk

With this change, `compile-test` now mirrors the behavior of `compile`.

also format jsons when compiling tests

---

Makefile
rel/relx.config.src

This was intended to find inter-kapps dependencies. Turns out Relx does not verify that all modules bundled in a release are reachable.
I thought this could be useful in the future so here it is.

and-you-get-a-rel: decare a release per kapp

---

core/kazoo_schemas/src/kz_json_schema.erl
core/kazoo_schemas/test/kz_json_schema_test.erl
make/deps.mk

With the 2600Hz branch of jesse, the supplied test would fail. Pointing to the 1.5 rc2 in the for-GET repo causes the test to pass successfully.

Add previously failing test and update jesse dep location

---

applications/ecallmgr/src/ecallmgr_fs_bridge.erl

Previous version of this function would only enable bypass_media if there was a single endpoint and Bypass-Media was enabled on it. New version enables bypass_media as long as _all_ endpoints have Bypass-Media set to true.

PISTON-459: if all resources have Bypass-Media, still set bypass_media=true

---

applications/crossbar/src/crossbar_maintenance.erl

With changes to how PATCH worked, the _rev from the account creation step would be set on the admin user doc. This clears out the 'doc' portion of the context so the user's doc doesn't pick up account-related pvt fields.

Create admin user

---

core/kazoo/src/kz_doc.erl

* found during testing, if passing a list of `JObjs`, `private_fields` filter is returning public fields instead
* add `IncludeId` for `public_fields` to control adding the `id`

after 6 years, lets filter private fields

---

applications/callflow/src/module/cf_collect_dtmf.erl

Add unit test as requested by @fenollp in https://github.com/2600hz/kazoo/pull/3998.

PISTON-460: add unit test for truncate_after_terminator/2

---

applications/callflow/doc/flush_dtmf.md
applications/callflow/doc/ref/flush_dtmf.md
applications/callflow/src/module/cf_flush_dtmf.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.flush_dtmf.json

When a callflow looks like:
- cf_play
- cf_play
- cf_collect_dtmf
If a caller presses a digit during the first cf_play, it cancels playback and gets added to the kapps_call dtmf_collection. Then the next media file starts playing.
There isn't a way to allow a caller to just skip the first cf_play without accumulating that DTMF. The solution is this:
- cf_play
- cf_flush_dtmf
- cf_play
- cf_collect_dtmf

PISTON-461: Callflow module for flushing early DTMF collection

---

core/kazoo_apps/src/kazoo_apps.app.src
rel/args

Thought it was weird.
https://github.com/2600hz/kazoo/commit/40b5f524fea944bfd536077dd74ad64ef863cd37 does not say why it was introduced. Maybe things are different now, @lazedo ?

vmargs-lager: no need to mention lager in vm.args

---

applications/teletype/src/teletype.hrl
applications/teletype/src/teletype_util.erl
applications/teletype/test/teletype_util_test.erl

If the address for a key is not defined in the JObj, but the key's value is not empty either (has a JObj value like `{"type", "specific"}`) fallback to the next key and/or next JObj.
(fixes the preview issue in crossbar)
backport of #4061

[4.1] fix find_addresses when emails are not defined in desired jobj

---

applications/teletype/src/teletype.hrl
applications/teletype/src/teletype_util.erl
applications/teletype/test/teletype_util_test.erl

If the address for a key is not defined in the JObj, but the key's value is not empty either (has a JObj value like `{"type", "specific"}`) fallback to the next key and/or next JObj.
(fixes the preview issue in crossbar)

[master] fix find_addresses when emails are not defined in desired jobj

---

applications/registrar/src/reg_authn_req.erl
applications/registrar/src/reg_route_req.erl
applications/registrar/src/registrar_maintenance.erl
applications/trunkstore/src/ts_callflow.erl
core/kazoo_apps/src/kapps_maintenance.erl
core/kazoo_apps/src/kapps_util.erl

[4.0] HELP-31826 (#4085)
* HELP-31826: better logging of CCVs for debugging
* add flush for getby cache
* move lookup by ip to route_req handler
* HELP-31826: normalize checking if things are enabled
* HELP-31826: functions to help figure out what's being checked
* HELP-31826: ensure account id is present
* HELP-31826: finer return type, formatting
* spel much gud

HELP-31826: forward-port from 4.0

---

applications/acdc/src/acdc.hrl
applications/acdc/src/acdc_announcements.erl
applications/acdc/src/acdc_announcements_sup.erl
applications/acdc/src/acdc_queue_manager.erl
applications/acdc/src/acdc_queue_manager.hrl
applications/acdc/src/acdc_sup.erl
applications/crossbar/doc/queues.md
applications/crossbar/doc/ref/queues.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/queues.json
core/kazoo_call/src/kapps_call_command.erl

Add support for periodic position and estimated wait time announcements while waiting for call to be answered in ACDc queue.
Either can be enabled independently, time interval and media files are customizable.
Relevant media files at: https://github.com/2600hz/kazoo-sounds/pull/6

PISTON-470: ACDc position/wait time announcements

---

applications/tasks/priv/list_task_modules.py
applications/tasks/src/kz_tasks_scheduler.erl
applications/tasks/src/modules/kt_compactor_worker.erl
core/kazoo_config/src/kapps_config.erl
core/kazoo_couch/src/kazoo_couch.erl
core/kazoo_couch/src/kz_couch_db.erl
core/kazoo_couch/src/kz_couch_util.erl
core/kazoo_couch/src/kz_couch_view.erl
core/kazoo_data/src/kz_datamgr.erl
core/kazoo_data/src/kzs_util.erl
make/deps.mk

Fix various problem in `kt_compactor`.
**Note:** `couchbeam` needs to patch to have `Content-type` header when doing `view_cleanup` otherwise BigCouch is returning an error
master: #4109

[4.1] Resurrect kt compactor

---

applications/callflow/src/module/cf_group.erl
applications/crossbar/doc/ips.md
applications/crossbar/doc/ref/ips.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/src/cb_context.erl
applications/crossbar/src/modules/cb_ips.erl
applications/crossbar/src/modules/cb_simple_authz.erl
core/kazoo/Makefile
core/kazoo/src/kz_doc.erl
core/kazoo/test/kz_doc_tests.erl
core/kazoo_bindings/src/kazoo_bindings.erl
core/kazoo_ips/src/kazoo_ips_maintenance.erl
core/kazoo_ips/src/kz_ip.erl
core/kazoo_proper/doc/README.md
core/kazoo_proper/src/pqc_cb_accounts.erl
core/kazoo_proper/src/pqc_cb_api.erl
core/kazoo_proper/src/pqc_cb_ips.erl
core/kazoo_proper/src/pqc_kazoo_model.erl
core/kazoo_proper/src/pqc_util.erl
core/kazoo_stdlib/src/kz_json.erl

To avoid a circular dependency between kazoo_ips and kazoo_services (and to be more inline with what most charge-able crossbar endpoints do), move reconciliation to the endpoint code and out of the core kz_ip module.
Also added a PropEr quickcheck suite of the IPs API

Reconcile IPs

---

applications/crossbar/src/modules/cb_user_auth.erl
applications/teletype/src/templates/teletype_password_recovery.erl
core/kazoo_amqp/src/api/kapi_notifications.erl
core/kazoo_documents/src/kzd_user.erl

if `Email` is not present in payload and it's previewing use `to` email
addresses

[master] fix pass recovery template when previewing

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.notifications.password_recovery.json
applications/crossbar/src/modules/cb_user_auth.erl
applications/teletype/src/templates/teletype_password_recovery.erl
core/kazoo_amqp/src/api/kapi_notifications.erl
core/kazoo_documents/src/kzd_user.erl

if `Email` is not present in payload and it's previewing use `to` email
addresses
master: #4192

[4.1] fix pass recovery template when previewing

---

core/kazoo_endpoint/src/kz_endpoint.erl

inbound sip headers are not set when there's no authorizing endpoint

HELP-32352 fix endpoint inbound sip headers - 4.1

---

core/kazoo_endpoint/src/kz_endpoint.erl

inbound sip headers are not set when there's no authorizing endpoint

HELP-32352 fix endpoint inbound sip headers

---

applications/callflow/src/module/cf_resources.erl
applications/crossbar/doc/ref/resources.md
applications/crossbar/doc/resources.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.dialplan.bridge.json
applications/crossbar/priv/couchdb/schemas/kapi.dialplan.bridge_endpoint.json
applications/crossbar/priv/couchdb/schemas/kapi.dialplan.bridge_endpoint_headers.json
applications/crossbar/priv/couchdb/schemas/kapi.offnet_resource.req.json
applications/crossbar/priv/couchdb/schemas/kapi.resource.eavesdrop_req.json
applications/crossbar/priv/couchdb/schemas/kapi.resource.originate_req.json
applications/crossbar/priv/couchdb/schemas/kapi.resource.originate_req_endpoint_headers.json
applications/crossbar/priv/couchdb/schemas/kapi.sms.message.json
applications/crossbar/priv/couchdb/schemas/kapi.sms.message_endpoint_headers.json
applications/crossbar/priv/couchdb/schemas/resources.json
applications/ecallmgr/src/ecallmgr_fs_xml.erl
applications/stepswitch/src/stepswitch_resources.erl
applications/trunkstore/src/ts_from_onnet.erl
core/kazoo_amqp/include/kapi_offnet_resource.hrl
core/kazoo_amqp/src/api/kapi_dialplan.hrl
core/kazoo_amqp/src/api/kapi_offnet_resource.erl

This allows you to add the following to a resource gateway:
```
"invite_parameters": {
"dynamic": [
"custom_channel_vars.pass-through",
{
"tag": "id",
"key": "custom_channel_vars.account_id"
}
],
"static": [
"npid"
]
}
```
Assuming the inbound call has pass-through (with value "pass-through=0288") and account_id (with value "XXXX") CCVs it will result in an INVITE request such as:
```
INVITE sip:+14158867900@10.26.0.88;npid;id=XXXX;pass-through=0288 SIP/2.0
```

Prod 154 master

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.json
applications/crossbar/src/api_resource.erl
applications/crossbar/src/api_util.erl
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/crossbar_modb_view.erl
applications/crossbar/src/crossbar_view.erl
applications/crossbar/src/modules/cb_accounts.erl
applications/crossbar/src/modules/cb_acdc_call_stats.erl
applications/crossbar/src/modules/cb_allotments.erl
applications/crossbar/src/modules/cb_call_inspector.erl
applications/crossbar/src/modules/cb_cdrs.erl
applications/crossbar/src/modules/cb_faxes.erl
applications/crossbar/src/modules/cb_ledgers.erl
applications/crossbar/src/modules/cb_modules_util.erl
applications/crossbar/src/modules/cb_multi_factor.erl
applications/crossbar/src/modules/cb_notifications.erl
applications/crossbar/src/modules/cb_pivot.erl
applications/crossbar/src/modules/cb_recordings.erl
applications/crossbar/src/modules/cb_resources.erl
applications/crossbar/src/modules/cb_search.erl
applications/crossbar/src/modules/cb_security.erl
applications/crossbar/src/modules/cb_sms.erl
core/kazoo_stdlib/src/kz_date.erl
core/kazoo_stdlib/src/kz_time.erl

We usually normalizing `start_key` and `next_start_key` to be a timestamp, and for every db request we construct the `startkey` and `endkey` based on that, but in some situation like CDRs this is not helping. View's key in cdrs is a list and to have accurate view result we need at least two element in view's key list.
This PR is base64 encoding (url safe) erlang term binary representation of `start_key` and `next_start_key`, so for the next request we can decode it to erlang term again use that as the `startkey` as is.  
For example if `next_start_key` is `[63660927599, <<"abc123">>]` will encoded to `"g2wAAAACbgUAb6p80g5tAAAABmFiYzEyM2o"` and the client can set it as `start_key` value, and in crossbar we can decode it as erlang term again to use as `startkey` for CouchDB query.
Also this …

encode start_keys in request and response

---

applications/fax/src/fax_worker.erl
applications/notify/src/notify_fax_inbound_to_email.erl
applications/notify/src/notify_fax_outbound_to_email.erl
applications/teletype/src/teletype_bindings.erl
applications/teletype/src/teletype_fax_util.erl
applications/teletype/src/teletype_util.erl
applications/teletype/src/templates/teletype_fax_inbound_error_to_email.erl
applications/teletype/src/templates/teletype_fax_inbound_to_email.erl
applications/teletype/src/templates/teletype_fax_outbound_error_to_email.erl
applications/teletype/src/templates/teletype_fax_outbound_smtp_error_to_email.erl
applications/teletype/src/templates/teletype_fax_outbound_to_email.erl
applications/teletype/src/templates/teletype_voicemail_full.erl
applications/teletype/src/templates/teletype_voicemail_to_email.erl
core/kazoo_amqp/src/api/kapi_notifications.erl
core/kazoo_apps/src/kapps_notify_publisher.erl

* Don't send fax notifications to reseller if could not find owner email address
* fix issue with finding account_db (found during debugging fax notification)
master: #4211

[4.1] don't send fax to reseller, fix user email lookup

---

scripts/dev/kazoo.sh

When KAZOO_ROOT is set, release path isn't correctly determined.

set release root to _rel/kazoo

---

core/sup/priv/sup

when `KAZOO_ROOT` is set, `DEFAULT_ROOT` isn't found properly

find release path fix

---

core/kazoo_documents/src/kzd_rate.erl
core/kazoo_proper/src/pqc_cb_rates.erl

When specifying a direction on a rate doc, it would default to both directions (since binary() is not list()). Add conversion code in from_map/1 to ensure direction is a list of one when specified in the CSV.

Rate direction fixes

---

applications/crossbar/src/crossbar_util.erl
applications/crossbar/src/modules/cb_braintree.erl
applications/crossbar/src/modules/cb_service_plans.erl
applications/tasks/src/kz_service_sync.erl
core/kazoo_amqp/src/api/kapi_maintenance.erl
core/kazoo_services/src/bookkeepers/kz_bookkeeper_braintree.erl
core/kazoo_services/src/bookkeepers/kz_bookkeeper_local.erl
core/kazoo_services/src/kazoo_services_maintenance.erl
core/kazoo_services/src/kz_gen_bookkeeper.erl
core/kazoo_services/src/kz_service_items.erl
core/kazoo_services/src/kz_services.erl

kz_service_sync is the gen_listener that both receives AMQP maintenance payloads to initiate a service clean as well as a timer-manager to periodically sync dirty service plans. However, other apps had been calling into it to do explicit sync/clean/mark_dirty actions. When kz_service_sync moved to tasks, this created an inter-app dependency.
This PR moves the core functionality back to kz_services so other apps can call directly to the functionality without a dependency on the tasks app. The PR also adds a maintenance AMQP for cleaning services. This also removes a circular dep between kz_service_sync (tasks) and kz_services (kazoo_services).

Service sync via amqp

---

core/kazoo/src/kz_doc.erl
core/kazoo_data/src/kazoo_data.app.src
core/kazoo_data/src/kazoo_data_config.erl
core/kazoo_data/src/kz_datamgr.erl
core/kazoo_data/src/kzs_cache.erl
core/kazoo_data/src/kzs_perf.erl
core/kazoo_data/src/kzs_plan.erl
core/kazoo_data/src/kzs_publish.erl

Remove circular dependency between kazoo_data and kazoo_config (specifically kapps_config usage in kazoo_data).

Config as app vars

---

applications/crossbar/priv/couchdb/schemas/callflows.record_caller.json

Allow schema to accept up to 3 hours or recording time.

Update schema for longer time limit

---

core/kazoo_ast/src/kapps_config_usage.erl
core/kazoo_ast/src/kazoo_ast.erl
core/kazoo_ast/src/kz_ast_util.erl

Not all apps want their detected schemas in the default location. This allows apps to override the default with an app-specific location.

Schemas config dir

---

applications/crossbar/doc/channels.md
applications/crossbar/src/modules/cb_channels.erl
applications/ecallmgr/src/ecallmgr_call_command.erl
core/kazoo_call/src/kapps_call_command.erl

also fixes searching for the envelope first when doing metaflows

KAZOO-5758: tts can be uninterrupted

---

Makefile
doc/mkdocs/Makefile
scripts/setup_docs.bash

Please do not use `readlink -f`, macOS is lame and doesn't support GNU commands.

do not use 'readlink -f' to support macOS

---

applications/crossbar/src/modules/cb_registrations.erl

Got two registrations from FreePBX host.
One registration is a device.
Another one a trunkstore registration. 
Contact appears to be the same and dict:store/3 overwrites one another.

cb_registrations loses endpoints

---

applications/ecallmgr/src/ecallmgr.hrl

It seems "t38_passthrough" should be "t38_passthru" or fax should be just enabled "fax_enable_t38"
Sorry if I'm wrong, but just offending to the eye..

looks like a typo, but not sure

---

applications/doodle/src/doodle_app.erl
applications/doodle/src/doodle_maintenance.erl
applications/tasks/src/kz_account_crawler.erl
applications/tasks/src/kz_tasks_trigger.erl
applications/tasks/src/modules/kt_initial_occurrence.erl
applications/tasks/src/modules/kt_low_balance.erl
applications/tasks/src/tasks_bindings.erl

- Trigger this new tasks checks along doodle checks
- Fix dialyzer warnings

 [Fix #kazoo-5636] Split kz_account_crawler tasks into task modules

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.json
core/kazoo_config/src/kapps_config.erl

* fix spelling
* update system config
* update swagger
* remove old config from swagger
* set the enum properties up
* revert description
* migrate setting

Check spelling of forward in config

---

core/kazoo_services/doc/bookkeepers.md

Http bookkeeper does not attempt to contact remote bookkeeper if the account does not have an active service plan.

Add HTTP bookkeeper note

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.notifications.port_comment.json
applications/crossbar/src/modules/cb_comments.erl
applications/crossbar/src/modules/cb_global_provisioner_templates.erl
applications/crossbar/src/modules/cb_local_provisioner_templates.erl
applications/crossbar/src/modules/cb_port_requests.erl
applications/crossbar/src/modules/cb_vmboxes.erl
applications/teletype/priv/templates/port_comment.html
applications/teletype/priv/templates/port_comment.text
applications/teletype/src/teletype.hrl
applications/teletype/src/teletype_port_utils.erl
applications/teletype/src/templates/teletype_port_cancel.erl
applications/teletype/src/templates/teletype_port_comment.erl
applications/teletype/src/templates/teletype_port_pending.erl
applications/teletype/src/templates/teletype_port_rejected.erl
applications/teletype/src/templates/teletype_port_request.erl
applications/teletype/src/templates/teletype_port_request_admin.erl
applications/teletype/src/templates/teletype_port_scheduled.erl
applications/teletype/src/templates/teletype_port_unconfirmed.erl
applications/teletype/src/templates/teletype_ported.erl
core/kazoo_amqp/src/api/kapi_notifications.erl

Also fixes port dates macros (just referencing KAZOO-5668 here since old dates macro was used for template metadata. Actual problem with the ticket was either the template was not using `date` filter or was using wrong macro)

[4.1] KAZOO-5718: send notification on direct port comment

---

core/kazoo_call/src/kapps_call_command.erl

https://freeswitch.org/confluence/display/FREESWITCH/T.38 says: 
As of FS v1.6, t38_passthru=true can *NOT* be used if fax_enable_t38 is not also true.

t38_passthru fax_enable_t38 requirement

---

core/kazoo_number_manager/src/carriers/knm_voip_innovations.erl

The Voip-Innovations carrier module is broken because of TLS issues.
For us, compiling with erlang 19.2, this prevents the voip-innovations module from functioning at all.
Forcing TLS v1.2 in HTTPOptions fixes this issue.

Fix broken voip-innovations module by forcing TLS v1.2

---

Makefile
applications/tasks/src/kz_tasks_scheduler.erl
applications/tasks/src/modules/kt_numbers.erl
core/kazoo_number_manager/src/knm_numbers.erl
core/kazoo_number_manager/src/knm_phone_number.erl
core/kazoo_number_manager/test/knm_numbers_test.erl

Also:
-  Mark job as partial when listing or dumping numbers and some of those numbers cannot be obtained
- Fix typo within kazoo/Makefile

[Fix #kazoo-5748] Fix send worker update check

---

Makefile

`make -j` allows `make` to spawn as many parallel jobs as it needs when
building a large number of modules. The problem with this is that it
can, and does, overwhelm systems with restricted memory, CPU power, or
`ulimit` settings, and it can (and does) cause builds on such systems to
fail, which consumes an enormous amount of time when doing multiple test
runs during development or maintenance.
This commit adds the `make` variable `MAKEFLAGS`, which defaults to `-j`.
This variable can be overridden on a case-to-case basis, to limit or
eliminate parallel jobs.
The change made is backwards-compatible with existing build invocations.
`make all MAKEFLAGS=""     # Eliminate parallel jobs`
`make all MAKEFLAGS="-j8"  # Limit parallel jobs to a max of 8`

Enable override of the 'make -j' flag (#4420)

---

Makefile
applications/Makefile
circle.yml
core/Makefile
make/kz.mk

Orders the core/application folders for compiling. 
Changes to use `JOBS` in top level Makefile instead of setting/overriding `MAKEFLAGS` as the `-j` was problematic. 
Quieter compiling too.

Make ordering

---

applications/crossbar/doc/port_requests.md
applications/crossbar/doc/ref/port_requests.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/port_requests.json

A new `bill.carrier` field was added to save the losing carrier's name.
I assume the schema should be updated accordingly.

Document new `bill.carrier` property in port request schema

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/voicemail_keys.json

on further discussion, it was deemed good to not have defaults because
accounts overriding individual keys would get the defaults from the
schema added on validation. if the global values were to be changed,
these accounts would no longer use the global values of keys they
didn't override.
Without defaults, the account config doc will reflect only the keys
overridden by the account and all other keys will be pulled from the
reseller/global configs.

remove defaults from voicemail key schema

---

scripts/README.md
scripts/list-ext-deps.escript

This escript gathers information from all `.beam` files in the filesystem tree specified by a list of directories provided to it on the command line, determines which external calls these files collectively make, and compares these calls with the applications provided by the Erlang runtime under which the script is running.
The end result is a list of OTP applications that this set of `.beam` files collectively make calls to (i.e. depend on).
* NOTE: The `.beam` files *must* be compiled with debug information for this script to be useful.
In this example, we find the names of all the Erlang applications which the `.beam` files in `applications/`, `core/`, and `deps` depend on.
```
$ scripts/list-ext-deps.escript core applications deps 2> /tmp/errors.log
common_test
compiler
crypto
erts …
```

Add escript to list OTP dependencies of a set of .beam files

---

core/kazoo_fixturedb/doc/README.md
core/kazoo_fixturedb/src/kz_fixturedb_server.erl
core/kazoo_fixturedb/src/kz_fixturedb_util.erl
core/kazoo_fixturedb/src/kz_fixturedb_view.erl

Allow to call fixturedb functions utility without starting without need
to start kazoo_data and config.
Also enhance add attachment to fixturedb by creating sym linking att
file to the media_files/* if you're using files from media_files
(I need to update the document, maybe tomorrow :)

make easy to add attachment to fixturedb

---

core/kazoo_call/src/kzc_recording.erl

allows receivers to directly interact with the recording via API

add API id to recording query params

---

scripts/evil_specs_remover.escript

ag is not a good choice for scripting, so don't expect to much from it (try to pipe its result in your script and enjoy debugging it)
But it fast! so usually you want to run `evil_specs_remover` with `-k` (short for `--kazoo-dirs`) option.

evil_spec_script: try to not crash if no filename is there

---

core/kazoo_media/src/kz_media_map.erl

Account-level overridden prompts have the format lang/prompt_id. Support this in extract_prompt_id/1 in kz_media_map. Then deletions of those prompts will be properly removed from the map

PISTON-524: extract_prompt_id/1 to support "/" as per Kazoo 4 prompt id format

---

applications/callflow/doc/dynamic_cid.md
applications/callflow/src/module/cf_cidlistmatch.erl
applications/callflow/src/module/cf_dynamic_cid.erl
applications/callflow/src/module/cf_lookupcidname.erl
applications/crossbar/priv/couchdb/account/lists.json
applications/crossbar/src/modules_v2/cb_lists_v2.erl
scripts/misspellings.txt

Updating Callflow Dynamic CID module to use `list/entries` for both `list` and `lists` action.
For doing this, `lists/entries` view has been updated to emit both monolithic `list` entries and `lists_entry` documents. The migration command in `cb_list_v2` has been updated too rename and set some especial property like `name/cid_name`, `number/cid_number`  and `length/capture_group_length`.
Be aware that these changes expect that at least the view has been updated. Otherwise dynamic cid will not work properly.

[master] HELP-34270: using list entries for both list/lists dynamic_cid actions

---

core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
core/kazoo_number_manager/src/knm_numbers.erl

Add a maintenance command to kazoo number manager to sync/create account db numbers to number dbs.
This is for cases which the account was migrated to another separate
server and it needs to create account's numbers in correct number dbs.
4.1: #4529

[master] KAZOO-5801: add a maintenance command to sync numbers from account db to number dbs

---

applications/tasks/src/kz_notify_resend.erl
applications/teletype/src/teletype_util.erl
applications/teletype/src/templates/teletype_voicemail_to_email.erl
core/kazoo_amqp/src/api/kapi_notifications.erl
core/kazoo_apps/src/kapps_notify_publisher.erl
core/kazoo_voicemail/src/kvm_message.erl
core/kazoo_voicemail/src/kvm_util.erl

Check for any completed in the notification response and if it wasn't successful don't do nothing.
This for the case when the user don't have any email address set or doesn't want to receive notification or the template is disabled in account but `delete_after_notify` or `save_after_notify` is set on voicemail box, so kazoo_voicemail would do that action regardless of the reality that it wasn't successful.
master: https://github.com/2600hz/kazoo/pull/4520

[4.1] HELP-34519: don't do after-notify action if notify was not successful

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.notifications.notify_update.json
applications/tasks/src/kz_notify_resend.erl
applications/teletype/src/teletype_bindings.erl
applications/teletype/src/templates/teletype_voicemail_to_email.erl
core/kazoo_amqp/src/api/kapi_notifications.erl
core/kazoo_apps/src/kapps_notify_publisher.erl
core/kazoo_voicemail/src/kvm_message.erl
core/kazoo_voicemail/src/kvm_util.erl

Check for any completed in the notification response and if it wasn't successful don't do nothing.
This for the case when the user don't have any email address set or doesn't want to receive notification or the template is disabled in account but `delete_after_notify` or `save_after_notify` is set on voicemail box, so kazoo_voicemail would do that action regardless of the reality that it wasn't successful.
4.1: https://github.com/2600hz/kazoo/pull/4519

[master] HELP-34519: don't do after-notify action if notify was not successful

---

core/kazoo_media/src/kz_media_file.erl
core/kazoo_media/src/kz_media_map.erl

Prompts overridden by cb_media right now cannot be found by kz_media_file (kz_media_file:get_uri/2 returns <<>>).
Fixed by this PR. Tested various other calls to get_uri and they all still work.

PISTON-523: handle Lang when using account db, not just system_media

---

applications/acdc/src/acdc_agent_fsm.erl

kz_http expects Content-Type in Headers, not in req opts (which was the old ibrowse behaviour)

PISTON-529: put Content-Type in headers, not req opts

---

applications/Makefile
applications/callflow/doc/audio_macro.md
applications/callflow/doc/play.md
applications/callflow/doc/ref/audio_macro.md
applications/callflow/doc/ref/play.md
applications/callflow/src/module/cf_play.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.play.json
applications/crossbar/priv/couchdb/schemas/kapi.conference.say.json
applications/crossbar/priv/couchdb/schemas/kapi.dialplan.play.json
applications/crossbar/priv/couchdb/schemas/kapi.dialplan.tts.json
applications/ecallmgr/src/ecallmgr_call_command.erl
core/Makefile
core/kazoo_amqp/src/api/kapi_dialplan.hrl
core/kazoo_ast/src/kapi_schemas.erl
core/kazoo_call/src/kapps_call_command.erl
core/kazoo_number_manager/Makefile
core/kazoo_stdlib/src/kz_term.erl
make/kz.mk

Since endless_playback is not easily interruptible (going into a conference appears to work), allow setting a loop counter on the media to be played.

KAZOO-5808: add loop count param to tts/play

---

applications/blackhole/src/blackhole_listener.erl

Being a cluster's superadmin, I would like to monitor all the calls passing though my cluster.
Since we've already got cb_channels able to provide all cluster's current calls, the only thing we need for live monitoring is ability to subscribe to call events of all the cluster over  Websockets

subscribe to all accounts' calls

---

applications/acdc/src/acdc_agent_stats.erl
applications/acdc/src/acdc_stats.erl
applications/acdc/src/acdc_stats.hrl
applications/acdc/src/acdc_stats_util.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.acdc.json

Conflicts:
applications/acdc/src/acdc_agent_stats.erl
applications/acdc/src/acdc_stats.erl
applications/acdc/src/acdc_stats_util.erl

PISTON-535: allow agents/status queries with no limit

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/doc/media.md
applications/crossbar/doc/ref/media.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/media.json
applications/crossbar/src/modules/cb_media.erl

Set `media_source` to `recording` for greetings, name, and temp greeting in voicemail callflow module.
Also enforcing `media_source` in schema for Media API and only handling TTS based on it.
4.1: #4560

[master] HELP-34868: enforce media_source when recording in cf_voicemail

---

core/kazoo_documents/test/kzd_callflow_test.erl
core/kazoo_schemas/src/kz_json_schema.erl
core/kazoo_schemas/test/fixtures/schemav3_sub_defaults_array.json
core/kazoo_schemas/test/kz_json_schema_test.erl
make/deps.mk
scripts/README.md
scripts/check-whitespace.sh

fix callflow tests
data object has a default
add check-whitespace description to README

use defaults from jesse (#4561) - 4.1

---

applications/callflow/src/cf_util.erl
applications/callflow/src/module/cf_privacy.erl
applications/callflow/src/module/cf_resources.erl
applications/crossbar/doc/accounts.md
applications/crossbar/doc/devices.md
applications/crossbar/doc/ref/accounts.md
applications/crossbar/doc/ref/devices.md
applications/crossbar/doc/ref/users.md
applications/crossbar/doc/users.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/accounts.json
applications/crossbar/priv/couchdb/schemas/devices.json
applications/crossbar/priv/couchdb/schemas/users.json
core/kazoo_documents/src/kzd_accounts.erl.src
core/kazoo_documents/src/kzd_devices.erl.src
core/kazoo_documents/src/kzd_users.erl.src
core/kazoo_endpoint/src/kz_endpoint.erl

Caller id privacy settings can be controlled through the User, Device and Account docs. Configuration works similarly to how it does in cf_privacy; common code has been refactored into cf_util.

Implement withholding of caller id for offnet outbound calls via property on user, device and account doc.

---

applications/crossbar/doc/basic_auth.md

A missing '-' in the parameters options broke this example. The following commit works on curl 7.19.7 and above

basic_auth.md updated with correct param options

---

applications/crossbar/src/crossbar_filter.erl
applications/crossbar/src/crossbar_view.erl
applications/crossbar/src/modules/cb_cdrs.erl

The 'time-only' filter check wasn't differentiating between filter keys and non-filter keys on the query string. So you'd get `paginate` being compared with `created_to` and `created_from`, not matching, and returning `false` when `true` was the appropriate return (as seen when omitting `paginate=false` from the query string).

Ignore non-filter keys when checking if filters are defined

---

applications/crossbar/src/modules/cb_storage.erl
core/kazoo_attachments/src/kz_att_error.erl
core/kazoo_attachments/test/kz_att_error_test.erl
core/kazoo_data/src/kzs_attachments.erl
core/kazoo_data/src/kzs_plan.erl

Also:
-  Include the att handler id within the stored error

KAZOO-5693: Remove attachment content from stored error

---

applications/conference/src/conf_discovery_req.erl
applications/ecallmgr/src/ecallmgr_fs_conferences.erl
core/kazoo_call/src/kapps_conference.erl

Prior to the dynamic conference profile work, conference names were
used when interacting with FreeSWITCH. The field used was shifted to
the 'id' in the kapps_conference record but the 'name' was not used as
a backup if id was missing when building the kapps_conference record.
What would happen is, a callflow with a dynamic conference doc in the
action (defining "name" but not "id") would get "id" set to
rand_hex(8) instead of the value of "name". Conference dial API would
put another caller in the "name" conference and an API command to put
the original caller in would fail as the rand_hex was used instead.
If "id" isn't defined, we now default to using the "name".

HELP-35856: use conference name as ID if ID is missing

---

applications/conference/src/conf_discovery_req.erl
applications/ecallmgr/src/ecallmgr_fs_conferences.erl
core/kazoo_call/src/kapps_conference.erl

Prior to the dynamic conference profile work, conference names were
used when interacting with FreeSWITCH. The field used was shifted to
the 'id' in the kapps_conference record but the 'name' was not used as
a backup if id was missing when building the kapps_conference record.
What would happen is, a callflow with a dynamic conference doc in the
action (defining "name" but not "id") would get "id" set to
rand_hex(8) instead of the value of "name". Conference dial API would
put another caller in the "name" conference and an API command to put
the original caller in would fail as the rand_hex was used instead.
If "id" isn't defined, we now default to using the "name".

HELP-35856-4.2: use conference name as ID if ID is missing

---

applications/konami/src/module/konami_record_call.erl

Rewrite of handle function for "Stop" Action to fix Action not stopping recording where using different media name than "CallID.Format" as it invokes a hardcoded "CallID.Format" stop.
Used same functions as in Callflow app and launch function kapps_call:stop_recording() to invoke Stop command through kapps_call module instead of calling kapps_call_command:record_call directly. This to be able to stop the recording by name as saved in the custom_channel_variable for the media file name instead of invoking a stop on hardcoded CallID.Format.

Rewrite handle function for "Stop" Action (#4581) (Backport to 4.1)

---

applications/conference/src/conf_config_req.erl
applications/ecallmgr/src/ecallmgr_call_command.erl
applications/ecallmgr/src/ecallmgr_fs_config.erl
applications/ecallmgr/src/fs_event_filters.hrl
core/kazoo_call/src/kapps_conference.erl
core/kazoo_call/src/kapps_conference.hrl

when a config handler crashes, no fetch response is sent until the
timeout (3s typically). This causes lots of issues on
FreeSWITCH (missed audio when joining a conference, for instance).
Catch exceptions and return the empty config XML quickly. Also removes
some lower-level defensive programming that can be handled at the
higher level try/catch
refactor page app building
get the profile name from fs data

[4.2] HELP-36162: don't let crashes block config responses

---

applications/conference/src/conf_config_req.erl
applications/ecallmgr/src/ecallmgr_call_command.erl
applications/ecallmgr/src/ecallmgr_fs_config.erl
applications/ecallmgr/src/fs_event_filters.hrl
core/kazoo_call/src/kapps_conference.erl
core/kazoo_call/src/kapps_conference.hrl

when a config handler crashes, no fetch response is sent until the
timeout (3s typically). This causes lots of issues on
FreeSWITCH (missed audio when joining a conference, for instance).
Catch exceptions and return the empty config XML quickly. Also removes
some lower-level defensive programming that can be handled at the
higher level try/catch
refactor page app building
get the profile name from fs data

[master] HELP-36162: don't let crashes block config responses

---

applications/fax/src/fax_worker.erl

On Alpine options must goes before input file

Fixed tiff2pdf call on Alpine dist

---

applications/crossbar/src/crossbar_types.hrl
core/kazoo_ast/src/cb_api_endpoints.erl
core/kazoo_web/include/kazoo_web.hrl

Some includes were picked up from `crossbar.hrl`. With the breakening, `crossbar` won't necessarily exist; this decouples kazoo_ast from crossbar to build properly.

decouple cb_api_endpoints from crossbar

---

applications/callflow/src/module/cf_webhook.erl

This only for 4.1. It is fixed in 4.2 and master already.

[4.1] KAZOO-5819:convert props to json to avoid crash publishing webhooks

---

core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
scripts/dev/kazoo.sh

Also removes the timer between accounts, since most of the time the account doesn't have any numbers in the current processing number db., it's just wasting too much time.
~DO NOT MERGE THIS YET!~
4.2: #4801

[master] give more time for fix/sync account numbers

---

applications/tasks/src/modules/kt_compactor.erl
applications/tasks/src/modules/kt_compactor_worker.erl
core/kazoo_couch/src/kz_couch_db.erl
core/kazoo_couch/src/kz_couch_util.erl
core/kazoo_couch/src/kz_couch_view.erl

output rows for node compaction
use db name not shard
update log

[4.2] fixes when manually compacting a db

---

applications/crossbar/src/api_resource.erl

Revert "Update terminate/2 and rest_terminate/3 callbacks to terminate/3 after cowboy 2.2 update"
This reverts commit 3fa5bd5d8d9654fb629969d97c6138f17ea8ca0c.
Remove legacy cowboy terminate/2 callback and add expected terminate/3 for updated cowboy dep.
add specs
(cherry picked from commit 39413fef82e2dd805ab2fce584de4214f2a61710)

[4.2] - rest terminate fix-up #4827

---

core/kazoo_endpoint/src/kz_endpoint.erl

Instead of using "Invite-Format" of "route" and "Route" of
"loopback/DID", this change will use "Invite-Format" of "loopback" and
"Route" of "DID".
The conference dial command needs the "loopback" in "Invite-Format" to
track the loopback legs properly

HELP-36935: build call-forwarded endpoint as a loopback channel

---

scripts/README.md
scripts/export_auth_token.bash

This script did not work for me when I used it like this:
```
eval $(export_auth_token.bash -c "$CREDENTIALS" -a '2600Hz Ed' -s 'ui.zswitch.net')
```
It turns out that it was expecting the server to always be listening on http port 8000. I changed this parameter to take a base URL, so now the invocation looks like
```
eval $(export_auth_token.bash -c "$CREDENTIALS "-a '2600Hz Ed' -s 'https://ui.zswitch.net')
```
In addition, it was not quoting some parameters, making things like space-containing account names  (IIRC) not work, so this fixes that, too.
I took the liberty of adding better error checking and reporting, added a `-v` (verbose) option for debugging, and did a few other things that I think improved the script, but YMMV.

Make scripts/export_auth_token.bash work in more general cases

---

applications/ecallmgr/src/ecallmgr_call_control.erl
applications/ecallmgr/src/ecallmgr_fs_channel.erl
applications/ecallmgr/src/ecallmgr_fs_conferences_shared.erl

When using conference dial and DIDs, the loopback will cause a
dialplan fetch request to come back around into Kazoo. With multiple
ecallmgrs connected, it is possible that the control process will be
on a separate VM from the conference dial process.
The conference dial code must start a control process on the
initiating node to supply the conference participant process with an
AMQP control queue. Since there's no route_win to publish as well (no
controller queue), this commit conditionally publishes the route_win
if the controller queue is defined but opts to always publish the
usurp (which should teardown the control process started by the
loopback).
log the ecallmgr node
use kz_api
try to set fetch-id on the originate

HELP-37054-4.2: always publish usurp; conditionally publish route_win

---

applications/ecallmgr/src/ecallmgr_call_control.erl
applications/ecallmgr/src/ecallmgr_fs_channel.erl
applications/ecallmgr/src/ecallmgr_fs_conferences_shared.erl

When using conference dial and DIDs, the loopback will cause a
dialplan fetch request to come back around into Kazoo. With multiple
ecallmgrs connected, it is possible that the control process will be
on a separate VM from the conference dial process.
The conference dial code must start a control process on the
initiating node to supply the conference participant process with an
AMQP control queue. Since there's no route_win to publish as well (no
controller queue), this commit conditionally publishes the route_win
if the controller queue is defined but opts to always publish the
usurp (which should teardown the control process started by the
loopback).
log the ecallmgr node
use kz_api
try to set fetch-id on the originate

HELP-37054: always publish usurp; conditionally publish route_win

---

applications/ecallmgr/src/ecallmgr_call_control.erl
applications/ecallmgr/src/ecallmgr_fs_channel.erl
applications/ecallmgr/src/ecallmgr_fs_conferences_shared.erl
core/kazoo_amqp/src/api/kapi_call.erl
core/kazoo_amqp/src/api/kapi_metaflow.erl
core/kazoo_amqp/src/api/kapi_route.erl

When there are multiple ecallmgrs connected to a FreeSWITCH server, it
is possible that the conference dial occurs on ecallmgr1 and the fetch
request for the loopback-b channel comes in on ecallmgr2. This results
in the legs associated with the loopback (a and b) and the final
b-leg, are all considered "local" to ecallmgr2.
However, the conference dial needs to start a call control process on
ecallmgr1 to get a control queue for the add_participant API (used to
start a conf_participant process to manage the now-dialed
participant).
This means both ecallmgr1 and ecallmgr2 consider the b-leg to be
"local". Metaflows checks the local ecallmgr's channel cache to
determine if it should repond to channel API actions - since both
ecallmgrs consider the channel local, both metaflow listeners …

HELP-37054-4.2: address ownership of conference dial channels

---

applications/ecallmgr/src/ecallmgr_call_control.erl
applications/ecallmgr/src/ecallmgr_fs_channel.erl
applications/ecallmgr/src/ecallmgr_fs_conferences_shared.erl
core/kazoo_amqp/src/api/kapi_call.erl
core/kazoo_amqp/src/api/kapi_metaflow.erl
core/kazoo_amqp/src/api/kapi_route.erl

When there are multiple ecallmgrs connected to a FreeSWITCH server, it
is possible that the conference dial occurs on ecallmgr1 and the fetch
request for the loopback-b channel comes in on ecallmgr2. This results
in the legs associated with the loopback (a and b) and the final
b-leg, are all considered "local" to ecallmgr2.
However, the conference dial needs to start a call control process on
ecallmgr1 to get a control queue for the add_participant API (used to
start a conf_participant process to manage the now-dialed
participant).
This means both ecallmgr1 and ecallmgr2 consider the b-leg to be
"local". Metaflows checks the local ecallmgr's channel cache to
determine if it should repond to channel API actions - since both
ecallmgrs consider the channel local, both metaflow listeners …

HELP-37054: address ownership of conference dial channels

---

applications/conference/src/conf_discovery_req.erl

Because clients can provide custom conference config docs for ad-hoc
conferencing, we need to ensure no pvt fields are included before
converting the config to the conference record.

KAZOO-5906-4.2: strip pvt fields before processing

---

applications/conference/src/conf_discovery_req.erl

Because clients can provide custom conference config docs for ad-hoc
conferencing, we need to ensure no pvt fields are included before
converting the config to the conference record.

KAZOO-5906: strip pvt fields before processing

---

core/kazoo_amqp/src/api/kapi_callflow.erl
core/kazoo_amqp/src/api/kz_api.erl

Especially since tts/play commands consider [] different from
'undefined' for terminators. It is getting hard to know which API
commands might have a callflow payload (or a terminators attribute in
general); easier to permit a key with [] when it make no difference
than stripping keys with [] when there is a difference.

HELP-37225: don't consider [] as empty

---

core/kazoo_amqp/src/api/kapi_callflow.erl
core/kazoo_amqp/src/api/kz_api.erl

Especially since tts/play commands consider [] different from
'undefined' for terminators. It is getting hard to know which API
commands might have a callflow payload (or a terminators attribute in
general); easier to permit a key with [] when it make no difference
than stripping keys with [] when there is a difference.

HELP-37225-4.2: don't consider [] as empty

---

make/kz.mk
scripts/README.md
scripts/eunit_run.escript

Filter test modules which has the same name as their normal module (e.g. kz_date and kz_date_tests) to avoid running tests in kz_date_tests twice.
When running EUnit to test the module kz_date, it will also look for the module kz_date_tests and run those tests as well.
4.2: https://github.com/2600hz/kazoo/pull/4883

[master] filter same name test modules

---

make/kz.mk
scripts/README.md
scripts/eunit_run.escript

Filter test modules which has the same name as their normal module (e.g. `kz_date` and `kz_date_tests`) to avoid running tests in `kz_date_tests` twice.
When running EUnit to test the module `kz_date`, it will also look for the module `kz_date_tests` and run those tests as well.

[4.2] filter same name test modules

---

core/kazoo_media/Makefile
core/kazoo_media/src/kz_media_util.erl
core/kazoo_media/test/kz_media_util_tests.erl

When overriding prompts with other forms of media, like tone_stream or
HTTP URLs, normalization still occurs as it would for prompts like
"/{ACCOUNT_ID}/{PROMPT}" or "/system_media/{PROMPT}" or
"{PROMPT}". This results in invalid "prompt://" URLs and FreeSWITCH
being unable to play the appropriate media back to the call leg.
Introduce a function that looks for media that isn't
prompt-normalizable and returns a boolean indicating such.

HELP-37171-4.2: check if media is convertible to prompt://

---

core/kazoo_media/Makefile
core/kazoo_media/src/kz_media_util.erl
core/kazoo_media/test/kz_media_util_tests.erl

When overriding prompts with other forms of media, like tone_stream or
HTTP URLs, normalization still occurs as it would for prompts like
"/{ACCOUNT_ID}/{PROMPT}" or "/system_media/{PROMPT}" or
"{PROMPT}". This results in invalid "prompt://" URLs and FreeSWITCH
being unable to play the appropriate media back to the call leg.
Introduce a function that looks for media that isn't
prompt-normalizable and returns a boolean indicating such.

HELP-37171: check if media is convertible to prompt://

---

applications/ecallmgr/src/ecallmgr_maintenance.erl
core/kazoo/src/kz_network_utils.erl

Add CIDR checks when resolving an address to an IP/CIDR.
Also refactors ecallmgr_maintenance ACL functions to remove
duplication and resolve the supplied address in one place.
Also provides some useful feedback is resolution fails.

KAZOO-5907-4.2: check for CIDR or IP, or resolve hostnames

---

applications/ecallmgr/src/ecallmgr_maintenance.erl
core/kazoo/src/kz_network_utils.erl

Add CIDR checks when resolving an address to an IP/CIDR.
Also refactors ecallmgr_maintenance ACL functions to remove
duplication and resolve the supplied address in one place.
Also provides some useful feedback is resolution fails.

KAZOO-5907: check for CIDR or IP, or resolve hostnames

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.fax.start_job.json
applications/fax/src/fax.hrl
applications/fax/src/fax_global_shared_listener.erl
applications/fax/src/fax_jobs.erl
applications/fax/src/fax_shared_listener.erl
applications/fax/src/fax_sup.erl
applications/fax/src/fax_worker.erl
core/kazoo_amqp/src/amqp_util.erl
core/kazoo_amqp/src/api/kapi_fax.erl
core/kazoo_amqp/src/gen_listener.erl

when using federation on shared queues
we create queuename-zone by default on the federated connection
this adds the option to listen on original queue name
this allows for round-robin distribution of events across zones
add split_routing_key to amqp utils
add control queue to fax status
handle fax start with global queue name
rename fax exchange name to faxes so restarts don't break
Renamed exchange to faxes to change from fanout to topic
moved some loglines around
Conflicts:
applications/fax/src/fax_jobs.erl
applications/fax/src/fax_worker.erl
core/kazoo_amqp/src/api/kapi_fax.erl
core/kazoo_amqp/src/gen_listener.erl

[4.1] Help-36418: Address issues with disabling serialization by outbound number in faxing

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.kazoo_convert.json
applications/crossbar/src/modules/cb_ledgers.erl
applications/crossbar/src/modules_v2/cb_phone_numbers_v2.erl
core/kazoo_couch/src/kz_couch.hrl
core/kazoo_couch/src/kz_couch_util.erl
core/kazoo_couch/src/kz_couch_view.erl
core/kazoo_ledgers/src/kz_ledgers.erl
core/kazoo_modb/priv/couchdb/views/ledgers.json
make/deps.mk

Ledgers summary was not honoring page size, and timestamp correctly, so it was loading all ledgers in a MODB database causing slowness and pressure on CouchDb and kazoo.
This PR changes ledgers API (`/ledger`) to use use crossbar_view for handling multi database load and time range query (default to 50). Currently I'm not sure how set the page size and next start key in response. This is the summary API, meaning it is returning all categories sums, so if you have 2 service category it returns two object. Since behind scene it limits the db result to 50, and we returning two object there is ambiguity between request page size (default to 50) and response  page size (in this example 2).
Also fixing KAZOO-5191 . There are times that view result is big, and couchdb dropping the connection …

[master] HELP-37319: handle huge load view better

---

applications/teletype/src/teletype_util.erl
applications/teletype/test/teletype_util_tests.erl

Checks list of emails to see if they're really an email address. For example in teletype fax utils one of the places ti search for email address is username in user document, and it possible the username is not an email address.
4.2: #4973

[master] KAZOO-5926: check in teletype that the found addresses are really email addresses

---

applications/tasks/src/kz_task_worker.erl
applications/tasks/src/kz_tasks_scheduler.erl
applications/tasks/src/modules/kt_rates.erl

Prior to this PR, tasks would execute each row in the CSV using the provided task module, mark the task as complete, and then run the task's `cleanup` if provided.
The `kt_rates` used `cleanup` to do the actual uploading of rates into the ratedecks. Due to the tight testing in `pqc_cb_rates:seq/0`, the test would query for the rate before the task's cleanup function had finished uploading, resulting in a failed test (subject to race conditions).
This PR introduces a `finish` callback for tasks to run after all CSV rows are processed but before the task is marked as complete.

Fix rate import race condition

---

.travis.yml
doc/engineering/ci.md
doc/mkdocs/mkdocs.yml

We want to make sure Kazoo tracks newer Erlang versions even if we're not ready to build packages using those versions.
Deprecation in 21 of `erlang:get_stacktrace/0` (primarily) will require a lot of work in Kazoo and its deps to get working builds and isn't currently prioritized. We'll probably need to vendor all our deps and patch for 21 when we move to it as the official version.

Add more Erlang versions and note issues with 21

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.ecallmgr.json
applications/ecallmgr/src/ecallmgr_config.erl
applications/ecallmgr/src/ecallmgr_util.erl

Also  default default multivar separator set to `"~"`

[4.2] Fixed UK ringback and made configurable multivar separator

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.number_manager.vitelity.json
core/kazoo_number_manager/src/carriers/knm_vitelity.erl

should_lookup_cnam() does a check to see if use_stepswitch_cnam() is set to true in the couchdoc. If so, then incoming cnam requests are done against the stepswitch cnam service.

KAZOO-5938 - 4.2

---

applications/teletype/src/teletype_fax_util.erl
core/kazoo_documents/src/kzd_fax.erl

- Teletype was adding an extra . in the extension. 
- Teletype was not handling the case where the extension was using the original fax_file_format in kazoo_convert config. 
- fetch_original_attachment had an invalid pattern match, should have been a binary not a tuple. 
- Updated search for legacy attachment to exclude the reserved file types. 
- maybe_store_url_attachment should have been using save_fax_doc not save_outbound_fax. 
- Added some debug log lines to the chained cases so the logic is apparent in the logs 
- Switch the cases in save_outbound_fax for the url fax case to avoid unnecessary lookup of document in cases where store_url_document is false on receipt of api call.

QF: fixed a few bugs in teletype_fax_util and kzd_fax

---

applications/teletype/src/teletype_fax_util.erl
core/kazoo_documents/src/kzd_fax.erl

* Fixed a bug in fax notification attachment filename ..pdf instead of .pdf
* streamlined search logic for finding attachments
* Fixed case where original attachment is format

[4.2] QF: fixed a few bugs in teletype_fax_util and kzd_fax

---

applications/crossbar/src/api_util.erl

Handling uploading big file properly in Crossbar.
master: https://github.com/2600hz/kazoo/pull/5020

[4.0] KAZOO-5943: read next body content properly in crossbar

---

core/kazoo_globals/src/kz_nodes.erl

new format will adjusat to max size of address
``` 
Node          : kamailio@dev-01.lx.labs.2600hz.com
Version       : 5.2.0-dev6
Memory Usage  : 26.72MB
Zone          : lx1 (local)
Broker        : amqp://rabbitmq:5676/lx1
WhApps        : kamailio(3h54m38s)       
Roles         : Dispatcher Presence Proxy Registrar 
Dispatcher 1  : sip:192.168.16.125:11000 (AX)   
Dispatcher 51 : sip:192.168.16.125:12000 (AX)   
Subscribers   : message-summary (4)  dialog (4)  
Subscriptions : message-summary (5)  dialog (30)  
Presentities  : presence (0)  dialog (2)  message-summary (2)  
Listening on  : 192.168.16.125 tcp (5060 7000 7070) tls (5061 7001) udp (5060 7000) ws (5064) wss (5065) 
192.168.25.125 udp (7000) 
XX.XXX.XX.XX   tcp (7005) udp (7005) 
Registrations : 6
Node          : …
```

kz_nodes proxy display alignment to left with size

---

applications/crossbar/src/crossbar_filter.erl
applications/crossbar/src/crossbar_view.erl
applications/crossbar/src/modules/cb_call_inspector.erl
applications/crossbar/src/modules/cb_cdrs.erl

In CDRs API, because we query view to get list of cdrs first then going to fetch the documents, qs filter won't work on the view, so no view result is passing the filter and an empty result will be returned instead.
CDRs API now pass an option to crossbar view to no_filter during querying the view and then when fetching the documents it filters documents.
4.2: #5027

[master] HELP-38399: handle qs filtering for cdrs properly

---

applications/crossbar/src/crossbar_filter.erl
applications/crossbar/src/crossbar_view.erl
applications/crossbar/src/modules/cb_call_inspector.erl
applications/crossbar/src/modules/cb_cdrs.erl

In CDRs API, because we query view to get list of cdrs first then going to fetch the documents, qs filter won't work on the view, so no view result is passing the filter and an empty result will be returned instead.
CDRs API now pass an option to crossbar view to no_filter during querying the view and then when fetching the documents it filters documents.
master: https://github.com/2600hz/kazoo/pull/5028

[4.2] HELP-38399: handle qs filtering for cdrs properly

---

applications/callflow/src/module/cf_resources.erl

Master is already fixed by https://github.com/2600hz/kazoo/pull/4897.

[4.2] KAZOO-5947: default to false if override privacy is not defined

---

core/kazoo/src/kz_network_utils.erl

[4.2] KAZOO-5948: avoid crash when cidr is invalid

---

core/kazoo_stdlib/src/kz_network_utils.erl

[master] KAZOO-5948: avoid crash when cidr is invalid

---

applications/callflow/src/cf_util.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.json
applications/crossbar/src/modules/cb_modules_util.erl
applications/crossbar/src/modules/cb_token_auth.erl
applications/ecallmgr/src/ecallmgr_call_control.erl

- don't crash ecallmgr_call_control on dialplan errors
- allow callflows to dry-run blocking calls via token bucket

[4.2] Call control updates

---

applications/callflow/src/cf_util.erl
applications/callflow/src/module/cf_park.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.json
applications/crossbar/src/modules/cb_modules_util.erl
applications/crossbar/src/modules/cb_token_auth.erl
applications/ecallmgr/src/ecallmgr_call_control.erl
applications/ecallmgr/src/ecallmgr_fs_channel.erl

* ignore error events
* add dry-run to token restrictions on callflows
* update log lines to match
* made apis
unmatched returns

Call control updates

---

applications/stepswitch/src/stepswitch_bridge.erl
core/kazoo_documents/src/kz_call_event.erl

```
Aug 22 13:30:40 apps001 2600hz[28410]: |CALL_ID|gen_listener:929 (<0.23921.80>) CRASH in handle_event {{badmatch,<<"ring">>},[{stepswitch_bridge,handle_event,2,[{file,"src/stepswitch_bridge.erl"},{line,196}]},{gen_listener,callback_handle_event,4,[{file,"src/gen_listener.erl"},{line,943}]},{gen_listener,callback_handle_event,3,[{file,"src/gen_listener.erl"},{line,907}]},{gen_listener,distribute_event,3,[{file,"src/gen_listener.erl"},{line,825}]},{gen_listener,handle_info,2,[{file,"src/gen_listener.erl"},{line,645}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```

[4.2] ignore non-bridge channel_execute_complete events

---

applications/ecallmgr/src/ecallmgr.hrl
applications/ecallmgr/src/ecallmgr_call_command.erl
applications/ecallmgr/src/ecallmgr_call_events.erl
applications/ecallmgr/src/ecallmgr_registrar.erl
applications/ecallmgr/src/ecallmgr_util.erl
core/kazoo_documents/src/kzd_freeswitch.erl

The default realm config is accessed on nearly every call event
processed in ecallmgr before publishing to the wider kazoo
ecosystem. When the cache is cold, several things happen:
1. Each event for any active calls will request the default realm
2. Since the cache is cold, a kz_amqp_worker will be checked out to
fetch the value from sysconf
3. Each worker will return at about the same time and attempt to cache
the value.
Under load, this causes:
1. If enough call events happen before the value can be retrieved from
sysconf, the worker pool will be exhausted, crashing the event
process.
2. When the amqp workers that did get used to fetch the value return,
they will inundate the cache process' mailbox, causing timeouts
waiting for the cache to respond.
This patch does two things to help: …

[master] Avoid asking for cached value when possible

---

applications/ecallmgr/src/ecallmgr.hrl
applications/ecallmgr/src/ecallmgr_call_command.erl
applications/ecallmgr/src/ecallmgr_call_events.erl
applications/ecallmgr/src/ecallmgr_config.erl
applications/ecallmgr/src/ecallmgr_registrar.erl
applications/ecallmgr/src/ecallmgr_util.erl
core/kazoo_caches/src/kz_cache.erl
core/kazoo_documents/src/kzd_freeswitch.erl

The default realm config is accessed on nearly every call event
processed in ecallmgr before publishing to the wider kazoo
ecosystem. When the cache is cold, several things happen:
1. Each event for any active calls will request the default realm
2. Since the cache is cold, a kz_amqp_worker will be checked out to
fetch the value from sysconf
3. Each worker will return at about the same time and attempt to cache
the value.
Under load, this causes:
1. If enough call events happen before the value can be retrieved from
sysconf, the worker pool will be exhausted, crashing the event
process.
2. When the amqp workers that did get used to fetch the value return,
they will inundate the cache process' mailbox, causing timeouts
waiting for the cache to respond.
This patch does two things to help: …

[4.2] Avoid asking for cached value when possible

---

applications/crossbar/src/modules/cb_cdrs.erl

It seems both Excel and LibreOffice consider two continuance double quotes as a single double quotes.
Since just one double quotes is working fine in these applications, I'm removing the extra quote.
master: #5091

[4.2] KAZOO-5963: remove extra quotes from rfc_1036 in cdrs

---

applications/crossbar/src/modules/cb_cdrs.erl

It seems both Excel and LibreOffice consider two continuance double quotes as a single double quotes.
Since just one double quotes is working fine in these applications, I'm removing the extra quote.
4.2: #5092

[master] KAZOO-5963: remove extra quotes from rfc_1036 in cdrs

---

core/kazoo_endpoint/src/kz_attributes.erl
core/kazoo_endpoint/src/kz_endpoint.erl

When privacy is enabled the prepend gets overwritten after anonymization. This fixes it by applying the prepend again afterwards.

Prepend after privacy

---

make/deps.mk

Patched syslog to properly encode unicode characters before sending via `port_command`.

reference 2600hz fork of syslog driver

---

core/kazoo_call/src/kapps_call.erl
core/kazoo_call/src/kz_call_response.erl
core/kazoo_media/src/kz_media_util.erl

When `Media` is not defined for a hangup cause, `kz_media_util` would crash since `is_not_prompt` didn't handle `'undefined`.

handle undefined prompts

---

applications/callflow/src/module/cf_resources.erl
applications/stepswitch/src/stepswitch_bridge.erl
core/kazoo_endpoint/src/kz_endpoint.erl

call forwarding configured to require key press needs to exit
from the originate loop if the user rejects the call
using Fail-On-Single-Reject is not enough because it will add
the variable to the a-leg of the loopback channel, and we want to
add it as part of the bridge dial string of the b-leg

HELP-37255 - add Require-Fail-On-Single-Reject - 4.2

---

applications/callflow/src/module/cf_temporal_route.erl
applications/callflow/test/cf_temporal_route_test.erl

change weekly from using prevdate to today to avoid lots of edge cases.

[4.2] HELP-39593: Fixed bug in weekly TOD logic

---

.circleci/config.yml

A recent CI pass for the `build-plt dialyze` step took ~117s to build
the PLT. Since this is done for every CI pass, saving 2 minutes per
pass is an obvious boon.

cache the PLT based on the checksum of the deps.mk

---

applications/fax/src/fax_smtp.erl

…sions list and from email
from email is always lowercase on receipt of a message, but the permissions list could have upper case characters making the comparison fail. 
https://github.com/2600hz/kazoo/blob/master/applications/fax/src/fax_smtp.erl#L111

HELP-39529: ensure comparisons of FROM to permissions list is ensuring lower case 

---

applications/callflow/doc/conference.md
applications/callflow/doc/ref/conference.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.conference.json

Since callflow always wins over conference config when merging settings, remove the default values which would supersede the values in the conference so new conference callflows that are created will use the conference settings, not the callflow settings.

KAZOO-5952: do not default settings in conference callflow

---

applications/ecallmgr/src/ecallmgr_call_events.erl

i still feel that this ringing seconds should be
```
if ( answered_time == 0 ) then
length_of_phone_ringing = hangup_time - created_time
else   
length_of_phone_ringing = answered_time - created_time
end
```

add defaults to billing & ringing seconds

---

core/kazoo_caches/src/kz_cache_callbacks.erl

If the cache hasn't been started and a `flush` is attempted, a crash
will occur when performing the ETS operation. This can happen when the
Kazoo application hasn't yet started and an operator attempts to flush
its cache.
Instead, check that the cache is running and log if not, avoiding a
crash.

don't flush a missing ETS table

---

core/kazoo_stdlib/include/kazoo_json.hrl
core/kazoo_stdlib/src/kz_json.erl
core/kazoo_stdlib/test/kz_json_generators.erl
core/kazoo_stdlib/test/kz_json_tests.erl

Add a property check that reports the object depth generation
Use symbolic calls to kz_json:set_value/3 to construct the object
Use resize/2 to control the max depth of the object
Update tests to use the new deep_object/0 generator

Improve JSON object generation for testing

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.kazoo_convert.convertapi.json
core/kazoo_convert/doc/fax_converter_convertapi.md
core/kazoo_convert/src/kz_fax_converter.erl
core/kazoo_convert/src/providers/kz_fax_converter_convertapi.erl
doc/mkdocs/mkdocs.yml

* Fixed typo
* Fixed typo
* Added passing options as map
* Added convertapi support
* Updated swagger.json adn added system_config.kazoo_convert.json
* Added md file for convertapi
* Renamed "for_open_office_files_only" value to "for_openoffice_files_only"
* Fixed typo
* Documentation clarification
* Added missed behaviour declaration
(cherry picked from commit 5df065656cca7ef827d3e3de03825ee9c3650813)

[4.2] Added convertapi support (#5102)

---

core/kazoo_number_manager/src/carriers/knm_voip_innovations.erl

Reverting incorrectly modified endpoint ID variable. Please push to the rpm as soon as possible, much appreciated, thanks.

Revert endpoint ID

---

applications/crossbar/src/modules/cb_cdrs.erl

This is a follow up of https://github.com/2600hz/kazoo/pull/5183 to add ISO 8601 date time (combined) format to CDRs.

adding iso8601 combined datetime format to cdrs

---

core/kazoo_amqp/src/kz_amqp_sup.erl
core/kazoo_amqp/src/kz_amqp_worker.erl

also handles event without spawning process as it was noticed that this may lead to out of order message handling.
the spawned process only does a cast and the erlang scheduler may run the process out of order of received message.
the use case is presence detail queries where proxy servers send 1+ messages with details and a final message to indicate completion. the completion message may be processed before one of the intermediary detail messages and the result will be the absence of details in `monster-ui-debug`

add publisher confirms to amqp_worker

---

applications/acdc/src/acdc_agent_listener.erl
applications/callflow/doc/dynamic_cid.md
applications/callflow/src/cf_util.erl
applications/callflow/src/module/cf_call_forward.erl
applications/callflow/src/module/cf_dynamic_cid.erl
applications/callflow/src/module/cf_park.erl
applications/callflow/src/module/cf_voicemail.erl
applications/ecallmgr/src/ecallmgr_call_command.erl
applications/ecallmgr/src/ecallmgr_fs_channel.erl
applications/ecallmgr/src/ecallmgr_fs_channels.erl
applications/konami/src/module/konami_intercept.erl
applications/konami/src/module/konami_move.erl
core/kazoo/src/kz_doc.erl
core/kazoo_amqp/src/api/kapi_call.erl
core/kazoo_amqp/src/api/kapi_switch.erl
core/kazoo_amqp/src/kz_amqp_worker.erl
core/kazoo_apps/src/kapps_account_config.erl
core/kazoo_apps/src/kapps_config.erl
core/kazoo_apps/src/kapps_util.erl
core/kazoo_call/src/kapps_call.erl
core/kazoo_call/src/kapps_call_command.erl
core/kazoo_documents/src/kz_call_event.erl
core/kazoo_number_manager/src/converters/knm_converters.erl
core/kazoo_stdlib/include/kazoo_json.hrl
core/kazoo_stdlib/src/kz_json.erl
core/kazoo_stdlib/src/kz_time.erl
core/kazoo_voicemail/src/kvm_message.erl

* update kazoo json type usages
* don't bind unless necessary
* will filter undefined while setting
* fix some more json specs/types, use kz_datamgr:update_doc/3
* fix type for config_key()
* more type updates
* a few more dialyzer-related updates
* refactor out the try/catch
* more refactoring to appease the dialyzer
* cleanup docs for dynamic CID
* more dialyzer updates
* clean up spec for kz_json:from_list
* update specs
* revert to from_list/1
Conflicts:
core/kazoo_amqp/src/kz_amqp_worker.erl

Dialyzing hard of callflows (#5182) - 4.3

---

applications/callflow/src/module/cf_directory.erl

master: https://github.com/2600hz/kazoo/pull/5264

[4.3] HELP-40391: fix passing terminators instead of lang in cf_directory

---

applications/crossbar/doc/port_requests.md
applications/crossbar/doc/ref/port_requests.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/src/cb_context.erl
applications/crossbar/src/modules/cb_port_requests.erl
applications/crossbar/src/modules/phonebook.erl

QF: moved the port_request push to phonebook to inside state change to pending
make fmt
fixed docs
make apis
added example to docs
fix return value
bad args for cb_context:load()
there is already a loader funciton here
there is already a loader funciton here
fixed global listing by number
removed restriction on superduper admin user to support api_keys

[4.3] Phonebook: allow patching of port documents and move push to phonebook to staging state change 

---

core/kazoo_number_manager/src/providers/knm_providers.erl

4.3: https://github.com/2600hz/kazoo/pull/5280
4.2: https://github.com/2600hz/kazoo/pull/5279

[master] KAZOO-6004: ensure account has min 3 characters length when e911 caller_name is missing

---

core/kazoo_number_manager/src/providers/knm_providers.erl

master: https://github.com/2600hz/kazoo/pull/5278
4.2: https://github.com/2600hz/kazoo/pull/5279

[4.3] KAZOO-6004: ensure account has min 3 characters length when e911 caller_name is missing

---

core/kazoo_number_manager/src/providers/knm_providers.erl

master: https://github.com/2600hz/kazoo/pull/5278
4.3: https://github.com/2600hz/kazoo/pull/5280

[4.2] KAZOO-6004: ensure account has min 3 characters length when e911 caller_name is missing

---

applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar.hrl
applications/crossbar/src/modules/cb_templates.erl
applications/crossbar/src/modules/cb_token_auth.erl

Since multiple modules are checking for superduper admin and account admin, this PR is adding those keys to `cb_context` record after Auth token validation so it is accessible in all modules.

storing superduper and account admin in context

---

applications/crossbar/src/modules_v2/cb_devices_v2.erl

When a device is dry-run'd with a 402 accept charges, the
'maybe_add_mobile_mdn/1' call would still add the number to the
account. On the subsequent PUT to accept charges, since the number now
exists, the PUT will fail and the device will not be created.
Instead, we check that the save was successful (since 402 is an
'error') before handling the new device. This is more in line with how
it used to work when crossbar_services:maybe_dry_run/2 took a callback
function if not dry-running.

Handle new device only on successful save

---

applications/crossbar/doc/ref/devices.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/devices.combo_key.json
applications/crossbar/priv/couchdb/schemas/devices.json
core/kazoo_documents/src/kzd_devices.erl.src
core/kazoo_provisioner/src/provisioner_v5.erl
core/kazoo_provisioner/src/provisioner_v5.hrl

* Fix `devices` schema for `provision` field. Now it allows only integer 1..10 for parking or string 1..10 or object label, value. The rest of features code only allows arbitrary string or an object with label and value keys.
* Add ability to set a custom label for BLF keys if the value is an JSON object (with label and value keys)

SSSU-68: add ability to set a custom label for BLF keys

---

applications/acdc/src/cb_agents.erl
applications/acdc/src/cb_queues.erl

Make sure that current status and stats requests for agents and queues, with a specified time range, falls within the ACDC clean up window.
If clean up window is greater than a day, ensure to fetch current stats for only the last 24 hours. If clean up window is less than a day, ensure we are not looking for a longer time range than the window.

Ensure acdc request time range is within configured cleanup window

---

applications/acdc/src/acdc_stats.erl
applications/acdc/src/acdc_stats.hrl

A call can enter more than one queue, for example in the case where all agents reject the call in the first queue and the callflow routes to a second queue. In this case, the find_call/1 function needs to account for multiple stats returned for a call, and should return the most recent stat, based on when the queue was entered.

Ensure most recent queue stat is returned for call

---

core/kazoo_endpoint/src/kz_endpoint.erl

The Endpoint object at this point is a couch JObj, not a parsed endpoint, so look for the doc fields, not the props

PISTON-632: wrong field check for T38 on endpoint doc in kz_endpoint

---

applications/callflow/doc/record_call.md
applications/callflow/doc/ref/record_call.md
applications/callflow/src/cf_route_win.erl
applications/callflow/src/module/cf_record_call.erl
applications/callflow/src/module/cf_record_caller.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.record_call.json
core/kazoo_call/src/kapps_call.erl

When the caller is an authorized endpoint, prior to this change the
flag to have recordings follow transfers was always set, regardless of
whether the endpoint had recordings configured to be started
implicitly.
However, when the recording isn't started by config but is started via
callflow action (`cf_record_call`), the resulting recording will not
follow transfers which is unexpected behaviour.
This change now only sets the follow flag to false if the
recording-by-config is happening.
When starting recordings-by-action, always follow transfers.

HELP-40948: disable transfer follows when starting recording by config

---

applications/callflow/doc/record_call.md
applications/callflow/doc/ref/record_call.md
applications/callflow/src/cf_route_win.erl
applications/callflow/src/module/cf_record_call.erl
applications/callflow/src/module/cf_record_caller.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.record_call.json
core/kazoo_call/src/kapps_call.erl

When the caller is an authorized endpoint, prior to this change the
flag to have recordings follow transfers was always set, regardless of
whether the endpoint had recordings configured to be started
implicitly.
However, when the recording isn't started by config but is started via
callflow action (`cf_record_call`), the resulting recording will not
follow transfers which is unexpected behaviour.
This change now only sets the follow flag to false if the
recording-by-config is happening.
When starting recordings-by-action, always follow transfers.

[4.3] HELP-40948: disable transfer follows when starting recording by config

---

applications/callflow/doc/record_call.md
applications/callflow/doc/ref/record_call.md
applications/callflow/src/cf_route_win.erl
applications/callflow/src/module/cf_record_call.erl
applications/callflow/src/module/cf_record_caller.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.record_call.json
core/kazoo_call/src/kapps_call.erl

When the caller is an authorized endpoint, prior to this change the
flag to have recordings follow transfers was always set, regardless of
whether the endpoint had recordings configured to be started
implicitly.
However, when the recording isn't started by config but is started via
callflow action (`cf_record_call`), the resulting recording will not
follow transfers which is unexpected behaviour.
This change now only sets the follow flag to false if the
recording-by-config is happening.
When starting recordings-by-action, always follow transfers.

[4.2] HELP-40948: disable transfer follows when starting recording by config

---

.gitignore
Makefile
make/deps.mk

Especially when switching version branches, outdated deps can hang around and cause issues to arise later (because a feature was developed using the old "cached" dep but the real dep had API changes that render the feature broken).

Rebuild deps when the deps.mk changes

---

applications/crossbar/src/modules/cb_alerts.erl
applications/crossbar/test/cb_alerts_tests.erl
core/kazoo_documents/src/kzd_accounts.erl
core/kazoo_number_manager/src/knm_port_request.erl

Master's branch PR:  https://github.com/2600hz/kazoo/pull/5318/
for when:
- [SSSU-40] Balance is below threshold
- [SSSU-42] Port request's last comment has waiting_for_reply property set to true
- [SSSU-43] Port request's state is scheduled or rejected
* SSSU-21: peer programing refactor, enjoy!
* SSSU-21: Update tests to match new notification triggers implementation
* SSSU-21,SSSU-40: Improve low_balance check
* SSSU-21,SSSU-41: Add payment_token check/-notification trigger-
* SSSU-21: Set context.resp_status to success after all checks are performed
* SSSU-21: Fix minor tab issue
* SSSU-21: Fix function spec and improve payment_token alert's metadata

SSSU-21: Add notification triggers

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.media.json
core/kazoo_media/src/kz_media_file.erl
core/kazoo_media/src/kz_media_util.erl

allows haproxy configuration of media proxy (maybe with ssl termination).
ex: https://media-proxy.mydomain.com => 
{ apps001.prod.kazoo.local:24517 , apps002.prod.kazoo.local:24517 }

allow configuration for a distributed proxy

---

applications/crossbar/doc/storage.http.md
applications/crossbar/doc/storage.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.system_data.json
applications/crossbar/src/modules/cb_storage.erl
core/kazoo_data/src/kzs_plan.erl
core/kazoo_proper/src/pqc_cb_storage.erl
doc/engineering/make.md

When creating a storage plan, Kazoo checks the settings by storing a
small text file with the attachment's settings and then reading it
back. This typically works fine for "dumb" storage backends.
However, it could be a hinderance when the storage backend is "smart"
but only for the specific files it expects to receive. Adding code to
handle the writing and reading of the test file is burdensome to the
storage backend. Presumably once the backend is receiving files
properly, executing more validation checks (for new account storage
plans) could be a waste of time.
This change allows the skipping of the validation of the attachment's
settings during the API request; only JSON and internal KAZOO
validation will be performed.

HELP-40835: allow client to opt-out of validation checks

---

Makefile
core/kazoo_documents/Makefile
core/kazoo_documents/test/kzd_test_fixtures.erl
core/kazoo_fixturedb/src/kz_fixturedb_util.erl
make/kz.mk

Speeds up most targets that operate over the core/applications code (like clean, eunit, etc).

Update targets to properly handle -j

---

applications/crossbar/doc/storage.http.md
applications/crossbar/doc/storage.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.system_data.json
applications/crossbar/src/modules/cb_storage.erl
core/kazoo_data/src/kzs_plan.erl
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_proper/src/pqc_cb_storage.erl
doc/engineering/make.md

Also backport the skipping of validation settings when creating a storage plan via API.

[4.3] HELP-40835: add metadata to mailbox message

---

Makefile
applications/callflow/src/module/cf_audio_macro.erl
core/amqp_leader/src/amqp_leader_proc.erl
core/kazoo_ast/src/kazoo_ast.erl
core/kazoo_call/src/kapps_call.erl
core/kazoo_call/src/kapps_conference.erl
core/kazoo_convert/src/kz_fax_converter.erl
core/kazoo_convert/src/providers/kz_fax_converter_convertapi.erl
core/kazoo_endpoint/test/kz_formatters_tests.erl
core/kazoo_modb/src/kazoo_modb_migrate_maintenance.erl
core/kazoo_number_manager/src/converters/knm_converter_regex.erl
core/kazoo_number_manager/src/knm_number_options.erl
core/kazoo_number_manager/src/knm_phone_number.erl
core/kazoo_number_manager/test/knm_converters_tests.erl
core/kazoo_schemas/src/kz_json_schema.erl
core/kazoo_services/src/kz_services.erl
core/kazoo_services/src/kz_services_item.erl
core/kazoo_services/src/kz_services_items.erl
core/kazoo_services/src/kz_services_plan.erl
core/kazoo_services/src/modules/kz_services_payment_tokens.erl
core/kazoo_speech/src/tts/kazoo_tts_google_utils.erl
core/kazoo_stdlib/src/kz_json.erl
core/kazoo_transactions/src/kz_transaction.erl
make/emacs/erlang-start.el
make/emacs/erlang.el
make/fmt.mk
make/kz.mk

erlang.el has a bug where it stops execution during formatting due to an ['unbalanced parenthesis'](https://bugs.erlang.org/browse/ERL-228). With a little adjustment, at least for Kazoo's purposes, we can address the cause of stoppage so the formatter continues processing the Erlang file.
For now, we track the erlang.el we want to use separate from the erlang-formatter repo until such time the official erlang.el is fixed to address the issue itself.

Address a bug in erlang.el formatter

---

core/kazoo_stdlib/src/kz_module.erl

When calling an API that has long path tokens (e.g. GET /v1/user_auth/<jwt>) a crash introduced in 2f35988 prevents the API req from completing. The prior catch all catch clause handled the 'system_limit' error. Adding the specific catch for that error in this PR.

PISTON-668: handle system_limit for to_atom on long path tokens

---

applications/stepswitch/src/stepswitch_inbound.erl

e164_destination is missing from CDR's for offnet origination calls

PISTON-656: Added e164_dest to offnet org cdrs

---

applications/teletype/priv/templates/port_request_admin.html
applications/teletype/priv/templates/port_request_admin.text
applications/teletype/src/teletype_port_utils.erl
applications/teletype/src/templates/teletype_port_cancel.erl
applications/teletype/src/templates/teletype_port_comment.erl
applications/teletype/src/templates/teletype_port_pending.erl
applications/teletype/src/templates/teletype_port_rejected.erl
applications/teletype/src/templates/teletype_port_request.erl
applications/teletype/src/templates/teletype_port_request_admin.erl
applications/teletype/src/templates/teletype_port_scheduled.erl
applications/teletype/src/templates/teletype_port_unconfirmed.erl
applications/teletype/src/templates/teletype_ported.erl
core/kazoo_documents/src/kzd_port_requests.erl

~~DON'T MERGE THIS YET!~~
Some fixes found during port request templates testing:
* fix/update: try to send templates: port cancel, port comment, port rejected, port request, port request admin in two passes:
1. Pass 1: add only submitter to data only if it is not comment template with private comment). If user made a customization to template by changing email type to specify or admins, it will process accordingly otherwise it will b sent to submitter as default type is original. The result of this sending will be ignored.
2. Pass 2: Will try to send another email to port authority, if it failed the whole process will be assumed failed. 
* fix: use correct key name for reference number
* update: add pre/post direction billing address
* reorganize bill object in macros
* show more field …

[master] send to port authority and submitter in two passes, fix fields

---

applications/crossbar/src/modules/cb_notifications.erl
applications/teletype/src/teletype_util.erl

* When notification is preview, only check inside data object to get `to` addresses
* When getting SMTP log from API in debug app with non-superduper logged in, if template is port_comment and its comment is private, remove the comment and rendered template to hide the private comment.

[master] check only data for preview, remove private comment if not superduper

---

applications/stepswitch/src/stepswitch_bridge.erl

* this will need better handling. right now we wait for the
channel_bridge event which may take some time even when the the call
progresses.

HELP-41788 use same timeout as originate

---

applications/crossbar/src/api_resource.erl
applications/crossbar/src/api_util.erl
applications/crossbar/src/crossbar_types.hrl

If an endpoint (like cb_channels) uses crossbar_util:response_202/3
during validation, api_util will consider validation unsuccessful and
not continue to the 'execute' phase.

consider accepted and success as "successful" resp_status

---

applications/crossbar/src/api_resource.erl
applications/crossbar/src/api_util.erl
applications/crossbar/src/crossbar_types.hrl

If an endpoint (like cb_channels) uses crossbar_util:response_202/3
during validation, api_util will consider validation unsuccessful and
not continue to the 'execute' phase.

[4.3] consider accepted and success as "successful" resp_status

---

applications/crossbar/src/api_util.erl

Don't log JSON response from crossbar, if the text has unicode or something that shell/log cannot show/print it breaks the shell.

[master] don't log json response, it breaks log and shell

---

applications/callflow/src/module/cf_directory.erl

Master counterpart: #5528
- Remove apostrophes around the users full_name when listing directories

[4.3] HELP-41859: Remove apostrophes when converting users full_name to audio (TTS)

---

make/deps.mk

it is git version 2.11.0, it is silly.

[master]  git is being silly about trailing slash

---

core/kazoo_speech/src/asr/kazoo_asr_google.erl
core/kazoo_voicemail/src/kvm_util.erl

kazoo_voicemail: Fixed crash when ASR recognition is failed
kazoo_speech: Removed from logs  Google API key exposing
(cherry picked from commit 0d058db5b228ec32e26919523a144b1e78db597b)

[4.3] kazoo_speech: Added support for empty ASR responce. (#5538)

---

applications/crossbar/src/modules/cb_media.erl

Fixing 500 error returned from prompts API when loading an single existing prompt

Use value from prompt results to determine attachments

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.epmd.json
core/kazoo_apps/src/kazoo_apps_app.erl
core/kazoo_apps/src/kazoo_apps_sup.erl
core/kazoo_apps/src/kz_epmd.erl

Currently no nice way to ensure EPMD is started but this at least lets a node reconnect and re-register when EPMD has gone down and returned.

Check that an EPMD registration exists

---

applications/crossbar/src/modules_v2/cb_devices_v2.erl

This is only for 4.3, master is fine.

KAZOO-6074: fix argument to provisioner is_unique_mac

---

applications/tasks/src/kz_tasks_trigger.erl
applications/tasks/src/modules/kt_compaction_reporter.erl
applications/tasks/src/modules/kt_compactor.erl
applications/tasks/src/modules/kt_compactor.hrl
applications/tasks/src/modules/kt_compactor_worker.erl
applications/tasks/src/tasks_bindings.erl
applications/tasks/src/tasks_maintenance.erl
applications/tasks/src/tasks_sup.erl
applications/tasks/test/kt_compactor_tests.erl
core/kazoo_modb/priv/couchdb/views/compaction_jobs.json
core/kazoo_tasks/src/kz_tasks.erl

By:
- Sorting databases by `disk_size` from bigger to smaller before being sent to the compactor worker
- Using `ratio` as the heuristic by default
Also:
- Improve progress logging
- Track all kt_compactor compaction jobs (compact_db, compact_all, compact_node) stats as well as auto_compaction job triggered by kz_tasks_trigger module for progress and history reports via sup commands.

Improve execution time for automatic compaction job

---

applications/registrar/src/reg_authn_req.erl

Master counterpart:  #5600
HELP-41363: Rename ccv HotDesk-Current-ID to Hotdesk-Current-ID
HELP-41363: Improve code according to PR review comments
HELP-41363: Improve code according to PR review comments
just pattern-match the list

HELP-41363: Add HotDesk-Current-ID CCV when device is hotdesked (#5600)

---

core/kazoo_amqp/include/kz_amqp.hrl
core/kazoo_amqp/src/gen_listener.erl
core/kazoo_amqp/src/kz_amqp_util.erl
core/kazoo_number_manager/src/knm_search.erl

When a "random" queue name is used to consume events for a specific process (vs a "named" queue which generally is for sharing events among consumers), set the prefetch value to what's in the config.ini. This setting increases the number of messages in-flight between the broker and the consumer and speeds up throughput.

Set prefetch to config's value if unnamed queue is used

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.rate.resp.json
applications/crossbar/src/modules/cb_rates.erl
core/kazoo_amqp/src/api/kapi_rate.erl

It is good to have rate_id in search result in order to able to edit/delete found rate.

add Rate-ID to cb_rates by number search result

---

applications/ecallmgr/src/ecallmgr_call_events.erl

duration_seconds in a cdr doc is stored as a string value when billing_seconds is stored as an int. 
As a result every time a cdr is loaded through CB, the string value must be converted to an int. 
Converting it to a int before saving also helps follow consistency.

PISTON-731: Changed duration_seconds in cdr to int from string to match all other 'seconds' value types

---

applications/crossbar/src/modules/cb_storage.erl

If a storage object is created through CB without a 'attachment' the request will crash
I have added a case to handle wen no 'attachment' is supplied and skip validation of the attachment settings

PISTON-724: Handled crossbar 'storage' validation when no 'attachment' is supplied in the request body

---

applications/callflow/src/module/cf_ring_group.erl
core/kazoo_endpoint/src/kz_endpoint.erl

Process the endpoints specified in the ring group's Data config in
reverse order (using foldr); when the builders return their endpoints,
they are prepended to the accumulator and return to the configured
order of members.

HELP-43123: build ring group members in order

---

applications/callflow/src/module/cf_ring_group.erl
core/kazoo_endpoint/src/kz_endpoint.erl

Process the endpoints specified in the ring group's Data config in
reverse order (using foldr); when the builders return their endpoints,
they are prepended to the accumulator and return to the configured
order of members.

[4.3] HELP-43123: build ring group members in order

---

applications/ecallmgr/src/ecallmgr_util.erl

Because we want to de-dup failover endpoints with same destination
it is important to pass bridge strings in intial order to {@link failover_if_all_unregistered/1}
function so only the first duplicated endpoint will ne used.
e.g:
```
[^^!ecallmgr_Authorizing_ID='forward_1']loopback/forward_1/context_2
[^^!ecallmgr_Authorizing_ID='forward_2']loopback/forward_1/context_2
[^^!ecallmgr_Authorizing_ID='forward_3']loopback/another_forward_destination/context_2
```
would be translate to:
```
[^^!ecallmgr_Authorizing_ID='forward_1']loopback/forward_1/context_2
[^^!ecallmgr_Authorizing_ID='forward_3']loopback/another_forward_destination/context_2
```
master: this commit is included in https://github.com/2600hz/kazoo/pull/5675

HELP-43124: [4.3]pass endpoints in intial order

---

applications/acdc/src/acdc_agent_fsm.erl
applications/acdc/src/acdc_agent_handler.erl
applications/acdc/src/acdc_agent_listener.erl
applications/acdc/src/acdc_agent_maintenance.erl
applications/acdc/src/acdc_agent_sup.erl
applications/acdc/src/acdc_agents_sup.erl
core/kazoo_stdlib/src/kz_types.erl

Prevent multiple acdc_agent_sup procs from being spawned for a single agent unless they are thief procs.

PISTON-709: serialize all agent spawns thru acdc_queues_sup 

---

applications/crossbar/doc/port_requests.md
applications/crossbar/doc/ref/port_requests.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/port_requests.json

Removing enum from post/pre street direction. Old port docs still has empty post/pre and it causing issue for updating the port request.
master: https://github.com/2600hz/kazoo/pull/5702

PORT-21: [4.3] remove enum from post/pre street direction

---

applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.pusher.json
core/kazoo_endpoint/src/kz_endpoint.erl

`extra_headers` and `X-KAZOO-PUSHER-INVITE-FORMAT` were used in a prior version of the Kamailio configs but are no longer used

PISTON-680: remove unused X-KAZOO-PUSHER-Invite-Format, extra_headers

---

applications/ecallmgr/src/ecallmgr_fs_transfer.erl
applications/ecallmgr/src/ecallmgr_util.erl

Set a high timeout for att_xfer. By default the FS implementation of att_xfer will perform an originate that uses the current timeout channel vars on the call making the transfer. This can backfire if that timeout is lower than the desired timeout on the other side of the att_xfer loopback. So here we set it to a high value and rely on the bridges on the other side of the loopback to control the ringing timeout.

PISTON-698: set originate timeout for ecallmgr_fs_transfer:attended/3

---

core/kazoo_amqp/src/kz_amqp_bootstrap.erl

```
> kz_config:zone().                        
lx1
> kz_config:get_section(<<"amqp">>).
[{<<"generic">>,
[{<<"zone">>,lx3},
{<<"uri">>,<<"amqp://guest:guest@rabbitmq:5676/lx3">>},
{<<"pool_size">>,50}]},
{<<"generic">>,
[{<<"zone">>,lx2},
{<<"uri">>,<<"amqp://guest:guest@rabbitmq:5676/lx2">>},
{<<"pool_size">>,50}]},
{<<"generic">>,
[{<<"uri">>,<<"amqp://guest:guest@rabbitmq:5676/lx1">>},
{<<"pool_size">>,50},
{<<"zone">>,lx1}]}]
```
produces
```
[{lx2,[<<"amqp://guest:guest@rabbitmq:5676/lx2">>]},
{lx3,[<<"amqp://guest:guest@rabbitmq:5676/lx3">>]},
{local,[<<"amqp://guest:guest@rabbitmq:5676/lx1">>]}]
```

amqp zones from config are atoms

---

applications/crossbar/doc/ref/users.md
applications/crossbar/doc/users.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/users.json
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar_util.erl
applications/crossbar/src/modules_v2/cb_users_v2.erl
core/kazoo_proper/src/kazoo_proper.hrl
core/kazoo_proper/src/pqc_cb_accounts.erl
core/kazoo_proper/src/pqc_cb_api.erl
core/kazoo_proper/src/pqc_cb_cdrs.erl
core/kazoo_proper/src/pqc_cb_ips.erl
core/kazoo_proper/src/pqc_cb_ledgers.erl
core/kazoo_proper/src/pqc_cb_phone_numbers.erl
core/kazoo_proper/src/pqc_cb_port_requests.erl
core/kazoo_proper/src/pqc_cb_rates.erl
core/kazoo_proper/src/pqc_cb_recordings.erl
core/kazoo_proper/src/pqc_cb_search.erl
core/kazoo_proper/src/pqc_cb_services.erl
core/kazoo_proper/src/pqc_cb_storage.erl
core/kazoo_proper/src/pqc_cb_system_configs.erl
core/kazoo_proper/src/pqc_cb_tasks.erl
core/kazoo_proper/src/pqc_cb_users.erl
core/kazoo_proper/src/pqc_cb_vmboxes.erl
core/kazoo_proper/src/pqc_cb_whitelabel.erl
core/kazoo_proper/src/pqc_kazoo_model.erl
core/kazoo_schemas/src/kz_json_schema.erl
core/kazoo_stdlib/src/kz_json.erl
core/kazoo_web/src/kz_http.erl
core/kazoo_web/src/kz_http_util.erl

In this case, a user was created with an empty (`""`) email address. It failed both the `minLength` and `format` requirements but kz_json_schema was not ready to handle the `wrong_format` error from jesse and the API request crashed.
This PR adds wrong_format handling as well as introduces user API CRUD testing in kazoo_proper. Also increases minLength for emails to 3 (1 makes no sense).
Additionally, crashes occurred during user validation if schema validation failed. The functions that tried to modify the user doc (loaded after successful validation) failed because failed validation did not set a doc in cb_context and thus kz_json operations occurred against `'undefined'`. This PR sets those apart and checks that validation of the request was successful before running the updates. …

API crash when 'format' JSON schema is triggered

---

applications/crossbar/src/api_util.erl
applications/crossbar/src/modules/cb_modules_util.erl
core/kazoo_token_buckets/src/kz_buckets.erl

Adds new fields to crossbar response envelope fields for debugging:
`crossbar_tokens_consumed`: the token cost of the request
`crossbar_tokens_remaining`: remaining tokens for this client

add tokens consumed and remaining stats to crossbar response

---

applications/crossbar/src/modules_v1/cb_devices_v1.erl

4.3: https://github.com/2600hz/kazoo/pull/5830

HELP-44059: [master] flush registration when device is deleted using api_v1

---

applications/crossbar/src/modules/cb_port_requests.erl
applications/teletype/priv/templates/port_cancel.html
applications/teletype/priv/templates/port_cancel.text
applications/teletype/priv/templates/port_pending.html
applications/teletype/priv/templates/port_pending.text
applications/teletype/priv/templates/port_rejected.html
applications/teletype/priv/templates/port_rejected.text
applications/teletype/priv/templates/port_request.html
applications/teletype/priv/templates/port_request.text
applications/teletype/priv/templates/port_request_admin.html
applications/teletype/priv/templates/port_request_admin.text
core/kazoo_fixturedb/priv/dbs/system_config/docs/665e92549b63fdd67036380d3e68d1ca.att
core/kazoo_fixturedb/priv/dbs/system_config/docs/b36216106de3f70f4a034f078c75928d.att

When transitioning from rejected state to submitted, empty comments from phonebook response was replacing the comment already in port's document during merging the docs.
Also removing time info from port's templates since the user can't choose the time of desired port date anyway.
master: https://github.com/2600hz/kazoo/pull/5851

[4.3] fix removing comments when rejected->submitted

---

applications/crossbar/src/modules/cb_port_requests.erl
applications/teletype/priv/templates/port_cancel.html
applications/teletype/priv/templates/port_cancel.text
applications/teletype/priv/templates/port_pending.html
applications/teletype/priv/templates/port_pending.text
applications/teletype/priv/templates/port_rejected.html
applications/teletype/priv/templates/port_rejected.text
applications/teletype/priv/templates/port_request.html
applications/teletype/priv/templates/port_request.text
applications/teletype/priv/templates/port_request_admin.html
applications/teletype/priv/templates/port_request_admin.text
core/kazoo_fixturedb/priv/dbs/system_config/docs/665e92549b63fdd67036380d3e68d1ca.att
core/kazoo_fixturedb/priv/dbs/system_config/docs/b36216106de3f70f4a034f078c75928d.att

When transitioning from `rejected` state to `submitted`, empty comments from phonebook response was replacing the comment already in port's document during merging the docs.
Also removing time info from port's templates since the user can't choose the time of desired port date anyway.

[master] fix removing comments when rejected->submitted

---

applications/callflow/src/module/cf_temporal_route.erl
applications/crossbar/priv/oas3/oas3-schemas.yml
doc/mkdocs/commercial.yml

Previously, actions of `menu`, `enable`, `disable`, and `reset` would
terminate the call after processing. Upon discussion, there wasn't a
compelling reason to continue doing this (and restricting the ability
to chain more actions off the action).
The usecase is that when there is an "emergency" a callflow can be
dialed to disable the main temporal route rules and enable the
particular "emergency" temporal route rule.

HELP-44744: allow chaining children off temporal route actions

---

core/kazoo_endpoint/src/kz_endpoint.erl

My recent change resulted in account information missing on some calls! 
Bug introduced here: https://github.com/2600hz/kazoo/pull/5695

Fix missing account info from parent call restrictions merge. 

---

applications/ecallmgr/src/ecallmgr_fs_channels.erl

To avoid blocking the calling process when the gen_server is overly
busy, move the channel updates to a cast instead of a call. In
particular, we've observed the authz worker (during route req/resp for
dialplan) getting blocked for 2s while waiting for this update to
occur.
Since the authz worker and dialplan response don't depend on the
channel cache, no sense blocking for the ETS write.

[4.3] KZ00-5: move call to cast

---

applications/ecallmgr/src/ecallmgr_fs_channels.erl
applications/ecallmgr/src/fetch/ecallmgr_fs_fetch_dialplan.erl

To avoid blocking the calling process when the gen_server is overly
busy, move the channel updates to a cast instead of a call. In
particular, we've observed the authz worker (during route req/resp for
dialplan) getting blocked for 2s while waiting for this update to
occur.
Since the authz worker and dialplan response don't depend on the
channel cache, no sense blocking for the ETS write.

KZ00-5: move call to cast

---

core/kazoo_data/src/kzs_attachments.erl

Reported here:
https://github.com/2600hz/kazoo/pull/5890/files#r300826699

PISTON-847: fix double fire of publish for external attachments

---

applications/crossbar/doc/voicemail.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/mailbox_message.json
applications/crossbar/priv/oas3/oas3-schemas.yml
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_documents/src/kzd_mailbox_message.erl
core/kazoo_documents/src/kzd_mailbox_message.erl.src
core/kazoo_modb/priv/couchdb/views/mailbox_messages.json

Transcriptions are being saved outside of the metadata key which is what is returned when information about a voicemail is pulled from crossbar. I had originally considered changing the way transcriptions are saved to move them into metadata but decided on the approach of adding it to the return data upon request so that this will work with pre-existing transcriptions. I’ve updated the crossbar api doc also because now this data will be returned when applicable.

PISTON-837: Added transcription to metadata & updated docs

---

applications/callflow/src/module/cf_voicemail.erl

This PR allow make callback to `caller_id_number` of voicemail message.
By default is used key `8` for callback.
PR is created to callback from offnet also as voicemail box owner. If `authorizing_id` or `owner_id` is `undefined`, then callback is initiated with account permissions.
Designed to use/apply dialplans (device/user/account) - please check implementation.
Now no new announcements is create/used. Please look currently defined, may be you can suggest other announcements that will be more appropriate.

Voicemail callback

---

applications/jonny5/src/j5_authz_req.erl
applications/jonny5/src/j5_channels.erl
applications/jonny5/src/j5_hard_limit.erl
applications/jonny5/src/j5_limits.erl
applications/jonny5/src/j5_request.erl
core/kazoo_documents/src/kzd_accounts.erl
core/kazoo_proper/src/pqc_cb_limits.erl
core/kazoo_proper/src/pqc_j5_channels.erl
core/kazoo_services/src/kz_services_bookkeeper.erl

Processing the authz request can take longer than processing the
subsequent CHANNEL_DESTROY. This causes the flushing in j5_channels to
occur before the storing of the authorization payload. Since the
channel is gone, the authorization payload isn't flushed and counts
against the account/reseller limits.
Instead, check the j5_channels ETS table for the authorization
payload on CHANNEL_DESTROY; if none, store an entry with a
destroyed:true flag. If a subsequent authz response is attempted
to be stored, this check will keep it from happening.
Introduce a test for sending CHANNEL_DESTROY followed by authz_req and
ensuring totals remain 0 and no authz_resp is generated.

[4.3] HELP-44667: don't send authz resp on quick hangup

---

Makefile
applications/callflow/src/callflow.app.src
applications/callflow/src/module/cf_temporal_route.erl
applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/doc/rates.md
applications/crossbar/doc/ref/rates.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/oas3/paths/rates.yml
applications/crossbar/src/crossbar.app.src
applications/crossbar/src/crossbar_view.erl
applications/crossbar/src/modules/cb_rates.erl
applications/crossbar/src/modules/cb_vmboxes.erl
applications/notify/src/notify_fax_inbound_error_to_email.erl
applications/notify/src/notify_fax_outbound_error_to_email.erl
applications/notify/src/notify_fax_outbound_to_email.erl
applications/notify/src/notify_util.erl
applications/notify/src/notify_voicemail_to_email.erl
applications/teletype/src/teletype_util.erl
core/kazoo_caches/test/kz_cache_pqc.erl
core/kazoo_convert/doc/README.md
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_stdlib/src/kz_date.erl
core/kazoo_stdlib/src/kz_time.erl
core/kazoo_stdlib/test/kz_time_tests.erl
make/deps.mk

Moved all fetched dependencies under the 2600Hz orginazation. There
are probably some transitive dependencies that need sorting out but
for a first pass, this should be fine.
Also formally removed the rates CSV upload from the rates API, which
rid us of the ecsv dep.

Vendor all 3rd party dependencies under github/2600hz

---

applications/blackhole/src/blackhole.hrl
applications/blackhole/src/modules/bh_presence.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.blackhole.json
applications/crossbar/priv/oas3/oas3-schemas.yml

This adds a new blackhole module, `bh_presence`, which emits presence events via blackhole for the following bindings:
- `dialog.*.*`
- `mwi_updates.*.*`
- `update.*.*`

Bh presence master

---

core/kazoo_data/src/kzs_plan.erl
core/kazoo_data/test/kzs_plan_tests.erl
core/kazoo_fixturedb/priv/dbs/system_data/docs/account0000000000000000000000005.json
core/kazoo_fixturedb/priv/dbs/system_data/views/storage+accounts.json
core/kazoo_proper/src/pqc_cb_storage.erl

Given a storage plan with "plan".Classification."types".Type:
If Type."connection" is defined, check that the value (the connection
ID) is also defined on the root level's "connections" object. If not,
remove the connection from the Type.
Adds tests for crossbar rejection of undefined connections and checks
that kzs_plan:plan/1 returns an appropriately filtered plan.

[4.3] KAZOO-6118: strip missing connections off storage plan settings

---

core/kazoo_data/src/kzs_plan.erl
core/kazoo_data/test/kzs_plan_tests.erl
core/kazoo_fixturedb/priv/dbs/system_data/docs/account0000000000000000000000005.json
core/kazoo_fixturedb/priv/dbs/system_data/views/storage+accounts.json
core/kazoo_proper/src/pqc_cb_storage.erl

Given a storage plan with "plan".Classification."types".Type:
If Type."connection" is defined, check that the value (the connection
ID) is also defined on the root level's "connections" object. If not,
remove the connection from the Type.
Adds tests for crossbar rejection of undefined connections and checks
that kzs_plan:plan/1 returns an appropriately filtered plan.

KAZOO-6118: strip missing connections off storage plan settings

---

core/kazoo_apps/priv/couchdb/account/groups.json
core/kazoo_documents/src/kzd_accounts.erl
core/kazoo_documents/src/kzd_blacklists.erl
core/kazoo_documents/src/kzd_callflows.erl
core/kazoo_documents/src/kzd_conferences.erl
core/kazoo_documents/src/kzd_devices.erl
core/kazoo_documents/src/kzd_directories.erl
core/kazoo_documents/src/kzd_faxbox.erl
core/kazoo_documents/src/kzd_groups.erl
core/kazoo_documents/src/kzd_menus.erl
core/kazoo_documents/src/kzd_temporal_rules.erl
core/kazoo_documents/src/kzd_temporal_rules_sets.erl
core/kazoo_documents/src/kzd_users.erl
core/kazoo_documents/src/kzd_vmboxes.erl

The local branch I have which I used to open the previous PR adding the flags list to the views has some differences with what was actually merged, not sure how that happened yet.  However, here are the missing changes (minus the devices.json update that Luis already issued).
I will also double check the master updates to see if it had a similar issue.

[4.3] issues with the previous PR left syntax issues in some updated views

---

core/kazoo_couch/src/kz_couch_util.erl

currently when using creds to access couch, the library creates a {basic_auth, User, Pass} to pass as options to couchbeam. couchbeam doesn't do anything with this and pass it along to hackney request.
hackney adds the authorization header to the request.
the problem with this comes when freeswitch tries to access media files (attachments) directly from couch. the attachment url does not contain the credentials because kazoo_couch defers the server_url to couchbeam which knows nothing (or adds) the credentials.
creating the Host with User:Pass@Host seems to fix it, according to mkbusy which now runs couch with creds

couch creds - 4.3

---

applications/crossbar/doc/media.md
applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/modules/cb_media.erl
core/kazoo_proper/src/kazoo_proper.hrl
core/kazoo_proper/src/pqc_cb_api.erl
core/kazoo_proper/src/pqc_cb_media.erl
core/kazoo_proper/src/pqc_cb_users.erl
core/kazoo_proper/src/pqc_media_mgr.erl

Testing the CRUDy parts of the media API endpoint, including
uploading/fetching the media binary data.
Removes the need to use /raw to specify the binary data vs JSON
metadata.
Adds a test to query media_mgr for the streaming URL and fetching the
media via AMQP query.

FORUM-10598: testing of the media api

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/port_requests.to_scheduled.json.src

If a port request was schedule we use port_requests.to_schedule" schema to validate and on save we convert the date in "schedule_on" to UTC and save it in "schedule_date".
If for some reason the port want to transit to schedule state once again, because the both "schedule_on" and "scheduled_date" are present the above schema won't validate with error `not_one_schema_valid`
master: https://github.com/2600hz/kazoo/pull/5952

[4.3] don't panic when both schedule date keys are present

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/port_requests.to_scheduled.json.src
applications/crossbar/priv/oas3/oas3-schemas.yml

If a port request was schedule we use port_requests.to_schedule" schema to validate and on save we convert the date in "schedule_on" to UTC and save it in "schedule_date".
If for some reason the port want to transit to schedule state once again, because the both "schedule_on" and "scheduled_date" are present the above schema won't validate with error `not_one_schema_valid`

[master] don't panic when both schedule date keys are present

---

applications/acdc/src/acdc_agent_fsm.erl
applications/acdc/src/acdc_agent_listener.erl

When the parent supervisor is shutting down the supervisor of this process with supervisor:terminate_child/2 during a restart, the reason will be 'shutdown'. acdc_agents_sup:stop_agent/2 should not be called as it will try to delete the supervisor child before it is restarted and the restart will do nothing, leaving the agent stopped

PISTON-892: avoid race condition btwn agent sup delete/restart child

---

applications/acdc/src/acdc_agent_fsm.erl
applications/acdc/src/acdc_agent_listener.erl

Every single acdc_agent_listener AMQP queue is bound to `route.req.*.*` - completely unnecessary overhead, it's not used at all

PISTON-893: acdc_agent_listener doesn't need route.req, don't bind it

---

applications/acdc/src/acdc_agent_util.erl

`kz_amqp_worker:call_collect/4` can return `{'timeout', Resps}` if not all nodes in the "until" (acdc) respond before the timeout

PISTON-889: also accept {'timeout', Resps} for most_recent_ets_statuses

---

applications/crossbar/src/modules/cb_services.erl
core/kazoo_modb/priv/couchdb/views/services.json
core/kazoo_services/src/kz_services_plan.erl

* ~Increasing max allowed date range for service change summary per account~
* Reverting changes made by https://github.com/2600hz/kazoo/pull/5822 . It seems https://github.com/2600hz/kazoo/commit/4d131905639052bbad9e6dc13dba64940881fd42 removes override and contract defaults values from assign.
* Using composite key in for per request in https://github.com/2600hz/kazoo/pull/5822#discussion_r300799463

[master] service changes summary per account followup

---

applications/crossbar/src/api_resource.erl
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar.hrl
applications/crossbar/src/modules/cb_comments.erl
applications/crossbar/src/modules/cb_port_requests.erl
applications/crossbar/src/modules/phonebook.erl
core/kazoo_documents/src/kzd_port_requests.erl
core/kazoo_number_manager/src/knm_port_request.erl

* Rejecting the port if the external service (port automation) is failing to submit the port
* Also saving the port automation failure as a private comment and as a field inside port's document.
* Adding master account id to `cb_context` to easy access to master id in crossbar modules.

SPHBK-12: [master] rejecting port if port submission is failed due to an external service

---

applications/ecallmgr/src/ecallmgr_call_events.erl

ecallmgr_call_events is now a gen_server, using kapi_call directly assigns a channel which is not properly closed on terminate

call events getting unnecessary channel

---

core/kazoo_amqp/src/gen_listener.erl
core/kazoo_amqp/src/kz_amqp_assignments.erl

if there's an error before the start consume
we can potentially have initial Params
set to empty array and therefore loose the bindings

preserve initial params - 4.3

---

core/kazoo_amqp/src/gen_listener.erl
core/kazoo_amqp/src/kz_amqp_assignments.erl

if there's an error before the start consume
we can potentially have initial Params
set to empty array and therefore loose the bindings
also, since we're folding the Params into bindings
the return is the list of bindings that we preserve in state,
so we still need to add the existing binding to the acumulator.
we need to set the broker when assigning existing to consumer
we need to send 'channel_lost' if we're moving the channel
to the primary broker

preserve bindings (#5986)

---

core/kazoo_amqp/src/gen_listener.erl

callback terminate
- allows the callback to still do amqp things in the terminate method

[master] fix gen_listener terminate to not release channel until after

---

core/kazoo_amqp/src/gen_listener.erl

callback terminate
- allows the callback to still do amqp things in the terminate method

[4.3] fix gen_listener terminate to not release channel until after

---

applications/crossbar/src/modules/cb_menus.erl
applications/ecallmgr/src/ecallmgr_util.erl
core/kazoo_documents/src/kzd_menus.erl
core/kazoo_proper/src/pqc_cb_media.erl
core/kazoo_proper/src/pqc_cb_menus.erl
core/kazoo_proper/src/pqc_forum_10598.erl

Specifically the ask was to use a parent account's media in a child
account's menu greeting. pqc_forum_10598.erl effectively follows the
path of creating a media file in a parent account, creating a menu in
a child account, and following the path of that
media path (/parent_account/media_id) until it is resolved to a couch
URL by ecallmgr via media_mgr.
Also added a CRUD seq test for the menu API.

FORUM-10598: validate using parent account's media in sub accounts

---

core/kazoo_amqp/src/gen_listener.erl

- when the queue_name is requested before it is actually done setting
up it will return 'undefined' instead of the to-be-used name, check for
that condition and return the queue_name that is configured instead

[4.3] fix returning queue_name from gen_listener

---

core/kazoo_amqp/src/gen_listener.erl

* ecallmgr node sup which is a supervisor under a supervisor (fs_sup)
is terminated with shutdown.
if we find a way to properly shutdown the supervisor with a reason
we can re-add the shutdown shortcut
(cherry picked from commit 509a03ebac5527e280f81c6af6221d9eafc958af)

add logging in gen_listener and don't shortcut shutdown - 4.3

---

applications/ecallmgr/Makefile
core/kazoo/src/kz_dist.erl
rel/kazoo

* change fs_dist to accept connections because of sup & remote_console
* we need to ensure that node only connects outbound thru amqp
or in the case of ecallmgr to freeswitch with inet_tcp

move fs_dist to core and enable it in kazoo script

---

applications/callflow/src/cf_exe.erl
applications/callflow/src/module/cf_missed_call_alert.erl
core/kazoo_apps/src/kapps_util.erl
core/kazoo_documents/src/kz_call_event.erl

**This depends on https://github.com/2600hz/kazoo/pull/6022.**
This is fixing the issue with missed call alert or other termination handlers when they are get executed.
4.3: https://github.com/2600hz/kazoo/pull/5980
There is race condition between callflow action modules, if one of the action (usually voicemail) takes a bit more to process and going down than when cf_exe is receiving and processing `channel_destory` event this cause the termination handlers run before voicemail module can update the the call record in cf_exe causing the missed call alert always being sent even though the caller left a message.
For resolving this we decided to move handlers runner to when cf_exe is stopping so at that point we're sure every other callflow modules has been already terminated or being …

HELP-45446: [master] move when termination handlers are running to cf_exe termination

---

Makefile
applications/callflow/src/cf_route_win.erl
core/kazoo_apps/src/kapps_config.erl
core/kazoo_ast/src/raw_json_usage.erl
core/kazoo_call/src/kapps_call.erl
core/kazoo_endpoint/src/kazoo_endpoint.hrl
core/kazoo_endpoint/src/kz_account_recording.erl
core/kazoo_endpoint/src/kz_endpoint.erl
core/kazoo_endpoint/src/kz_endpoint_recording.erl
core/kazoo_endpoint/test/kz_endpoint_tests.erl
doc/user_guides/call_recording.md
scripts/no_raw_json.escript

Added tests for kz_endpoint when merging call recording settings to
clarify the behaviour.
Updated documentation to clarify precedence and the duality of account
and endpoint call recording settings.

[4.3] HELP-10237: refactor decision-making for call recording

---

applications/pusher/src/pusher_listener.erl

Master https://github.com/2600hz/kazoo/pull/6021

[4.3] HELP-10194: Add utc_unix_timestamp_ms key to pushed objects via pusher

---

applications/callflow/doc/branch_bnumber.md
applications/callflow/doc/ref/branch_bnumber.md
applications/callflow/src/cf_route_req.erl
applications/callflow/src/cf_util.erl
applications/callflow/src/module/cf_branch_bnumber.erl
applications/callflow/src/module/cf_menu.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.branch_bnumber.json
applications/crossbar/priv/oas3/oas3-schemas.yml

Most callflow actions that include a feature code option have a
separate module for handling the capture group portion, and a main
action module for the feature.
Rather than require all actions wanting to be feature-code-able to
create a corresponding feature code module, when the action only wants
to use the capture group to re-hunt and branch to the found callflow,
this callflow action branch_bnumber can be put at the end to perform
the hunt.

Allow generic branching of callflow based on capture group

---

applications/callflow/doc/branch_bnumber.md
applications/callflow/doc/ref/branch_bnumber.md
applications/callflow/src/cf_route_req.erl
applications/callflow/src/cf_util.erl
applications/callflow/src/module/cf_branch_bnumber.erl
applications/callflow/src/module/cf_menu.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.branch_bnumber.json

Most callflow actions that include a feature code option have a
separate module for handling the capture group portion, and a main
action module for the feature.
Rather than require all actions wanting to be feature-code-able to
create a corresponding feature code module, when the action only wants
to use the capture group to re-hunt and branch to the found callflow,
this callflow action branch_bnumber can be put at the end to perform
the hunt.

[4.3] Allow generic branching of callflow based on capture group

---

core/kazoo_stdlib/src/props.erl
core/kazoo_web/test/kz_http_util_tests.erl

also test encoding/decoding query strings more thoroughly

[4.3] correct get_values_and_keys return when duplicate keys exist

---

core/kazoo_stdlib/src/props.erl
core/kazoo_web/test/kz_http_util_tests.erl

also test encoding/decoding query strings more thoroughly

correct get_values_and_keys return when duplicate keys exist

---

.gitignore
Makefile
applications/blackhole/deps.mk
applications/call_inspector/deps.mk
applications/callflow/deps.mk
applications/crossbar/deps.mk
applications/ecallmgr/deps.mk
applications/fax/deps.mk
applications/hangups/deps.mk
applications/hotornot/deps.mk
applications/media_mgr/deps.mk
applications/pusher/deps.mk
applications/stepswitch/deps.mk
applications/tasks/deps.mk
applications/teletype/deps.mk
make/Makefile.deps
make/deps.mk
make/kz.mk

Rather than maintain the list of all 3rd party dependencies used,
allow per-application dependency lists as well. Ideally make/deps.mk
will reflect core's dependencies while each KAZOO app will list the
specific 3rd party applications it depends on.
The one major caveat is that, while an apps' deps.mk will override the
DEPS variable (used by erlang.mk), the make/deps.mk `dep_{NAME}`
setting will be used if both the app and core define the same
dependency.
Future enhancements:
- check each app's deps.mk and put common ones into make/deps.mk
- check the app.src for 3rd party deps and make sure they're listed in
deps.mk or make/deps.mk.

Allow KAZOO applications to have their own 3rd party dependencies

---

applications/callflow/doc/answer.md
applications/callflow/doc/noop.md
applications/callflow/doc/wait_for_hangup.md
scripts/calculate-dep-targets.escript

Since KAZOO apps list their dependent apps in the .app.src file, it is
imperitive that we search deps/ core/ and applications/ to find the
dependent app.

Find where an application's dependencies are stored

---

Makefile
make/kz.mk

If for some reason the deps/ is cached (as in CI builds), there will
be no attending .erlang.mk for per-application deps to use to fetch
their deps.
This adds a target to kz.mk to ensure that .erlang.mk is available
before building deps.

Ensure erlang.mk exists for building deps

---

Makefile
scripts/README.md
scripts/make-prerequisite.sh

Introduce pre-check for make dependency like git version. This is motivated by a recent change in mk and erlang.mk upversion that require to parse git output. The older version of git (lower than major version 2) does not match with the output parsing.

[master] check prerequisites for make

---

core/kazoo_events/src/kz_hooks_util.erl

same behaviour as CHANNEL_CREATE in case account ID must be determined by inbound destination

add account id lookup for kz_hooks_util CHANNEL_DESTROY

---

core/kazoo_number_manager/src/knm_port_request.erl

1. Remove used_by json object under a port_in number when the associated callflow is deleted.

[master] remove used_by under port_in number when its callflow is deleted

---

applications/crossbar/src/modules/cb_services.erl

Adds an optional parameter to the services available API  which when true will include the full plan in the listing.
{{api_server}}/accounts/{{account_id}}/services/available?details=true

KCRO-1: support a request parameter details on the available service plans

---

core/kazoo_call/src/kzc_recording.erl

- the code used to send the AMQP message to store the recording uses
the switch_nodename to target that message, set it correctly to fix the
issue of recordings not storing properly when it is not set

KZOO-8: correctly set switch_nodename for kapps_call on record_stop

---

applications/pusher/src/modules/pm_google.erl

unlike firebase that accepts map

gcm accepts kz_json object not map

---

applications/callflow/doc/group_pickup_feature.md
applications/callflow/doc/ref/group_pickup_feature.md
applications/callflow/src/module/cf_group_pickup_feature.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.group_pickup_feature.json
applications/crossbar/priv/oas3/oas3-schemas.yml

To facility legacy documents that still miss `type` for pickup_group_feature callflow doc. This introduces a fallback default value `extension`.

[master] fallback a default value for pickup_group_feature

---

scripts/check-dialyzer.escript

For kazoo apps repo, we use the full path as changed file, and pass that to check_dialyzer script. But that script is not properly converting the erl file path (full path) to correct ebin file (dropping the leading "/" from the beginning) causing to not dialyze anything at all.

[master] fix check-dialyzer script to properly fix full path

---

scripts/check-dialyzer.escript

For kazoo apps repo, we use the full path as changed file, and pass that to check_dialyzer script. But that script is not properly converting the erl file path (full path) to correct ebin file (dropping the leading "/" from the beginning) causing to not dialyze anything at all.
master: https://github.com/2600hz/kazoo/pull/6102

[4.3] fix check-dialyzer script to properly fix full path

---

applications/callflow/doc/group_pickup_feature.md
applications/callflow/doc/ref/group_pickup_feature.md
applications/callflow/src/module/cf_group_pickup_feature.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.group_pickup_feature.json

Previously `type` was not required; if not included the action would
essentially be skipped. The schema was then updated to require `type`
but existing feature code callflows still had empty `data` objects
with no `type` defined - thus still "not working".
Default the `type` to `extension` as that is the common `type` used by
SmartPBX-configured feature codes.

HELP-10397 [4.3] Use default value for `type` in group pickup 

---

.circleci/config.yml
make/deps.mk
scripts/cover.escript

This is the latest fixes for application's CircleCI config file:
We found out the `CHANGED` variable are not passed to some of the targets, so they won't actually runs against the the app report and no won't report any error/warnings at all.
* fix check_unstaged step show it shows the changes in the app folder
* fix dialyzer so it actually dialyzes the *changed* files in the app folder
* fix code_checks so it runs on changed files in the app folder
* fix fmt
* add coverage report step (I think it needs per repo activation in coveralls.com site)
* **UPDATE:** disabling coverage report. It seems we need to set a token when using a CI other than than Travis-CI. Also it is crashing right now which we need to investigate it later. And we need to find out what to do with other repos too.
* fix …

[4.3] More circleci updates

---

applications/crossbar/src/modules/cb_modules_util.erl
applications/crossbar/src/modules/cb_port_requests.erl
core/kazoo_number_manager/src/knm_port_request.erl

1. use 'phone_numbers_listing' view to get port in number assignment
2. the change applies to cb_callflow/cb_connectivity via cb_module_utils:apply_assigment_updates
3. Reconcile legacy used_by in the port-in document and trunkstore/callflow usage
4. Update portin database with the correct used_by when port is completed
5. Preserve used_by value in the new number database when a port in is completed.

[master] KZOO-20 and 21: allow assign rejected portin number and used_by check after completed portin

---

applications/crossbar/src/modules/cb_modules_util.erl
applications/crossbar/src/modules/cb_port_requests.erl
core/kazoo_number_manager/src/knm_port_request.erl

There are a few bugs addressed in this PR.
Remove used_by json object under a port_in number when the associated callflow is deleted.
An earlier bug caused `used_by` not set when a port_in number is
in `rejected` state. Although this has been fix in this PR,
the ramification of earlier numbers without this fix still exists.
Therefore, this commit checks if `used_by` is not set properly when
the port_in transitions to `completed` state.
It also fixes another bug that a newly created phone_number as a result of
port_in completed will preserve `used_by` app. That has been missing.

[4.3] KZOO-20/21: fix app used_by for port_in number

---

core/kazoo_call/src/kapps_call_command.erl

- queueing this will cause it to not take effect immediately

MCCP-206-master: insert recv_dtmf immediately

---

core/kazoo_call/src/kapps_call_command.erl

- queueing this will cause it to not take effect immediately

MCCP-206: insert recv_dtmf immediately

---

applications/crossbar/src/modules/cb_ledgers.erl

Fix normalizer for ledgers summary API so it extract account ID from view's key correctly.
In previous [PR](https://github.com/2600hz/kazoo/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+PROD-30) for PRDO-30 the ledgers account summary was change to have account_id, timestamp and doc._id as view's compound key, but the normalizer in crossbar module didn't updated accordingly.
master: https://github.com/2600hz/kazoo/pull/6127

[4.3] update ledger summary normalizer

---

applications/crossbar/src/modules/cb_ledgers.erl

Fix normalizer for ledgers summary API so it extract account ID from view's key correctly.
In previous [PR](https://github.com/2600hz/kazoo/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+PROD-30) for PRDO-30 the ledgers account summary was change to have account_id, timestamp and doc._id as view's compound key, but the normalizer in crossbar module didn't updated accordingly.

[master] update ledger summary normalizer

---

applications/callflow/src/callflow_maintenance.erl
core/kazoo_endpoint/src/kz_endpoint.erl

Flush should only flush the endpoint cache and callers of the fun do not need to do so as they are performing a doc update anyway. Recent changes to kazoo_caches remove this need.
This also resolves an infinite loop where a listener might act on a doc_{created,deleted,edited} event and request a flush of the endpoint cache before requesting the endpoint via kz_endpoint:get

PISTON-953: no need to flush endpoint cache after doc updates

---

applications/acdc/src/acdc_agent_handler.erl

* PISTON-954: use kz_endpoint:flush_local/2 to flush endpoint cache

PISTON-954: acdc_agent_handler: flush endpoint before handling changes

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.media.json
applications/pivot/doc/kazoo/recording.md
core/kazoo/src/kz_doc.erl
core/kazoo_media/src/kazoo_media_maintenance.erl
core/kazoo_media/src/kz_media_util.erl

max_recording_time_limit can be reset by values from system_config/callflow by kazoo_media_maintenance:migrate(). To prevent reset again, the original callflow (or any originals) data shall be removed after the migration.
It's also required that the system-config default should be 10800, as seconds in 3 hours.

[4.3] KZOO-15: Ensure min value of max_recording_time_limit

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.media.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/pivot/doc/kazoo/recording.md
core/kazoo/src/kz_doc.erl
core/kazoo_media/src/kazoo_media_maintenance.erl
core/kazoo_media/src/kz_media_util.erl

max_recording_time_limit can be reset by values from system_config/callflow by kazoo_media_maintenance:migrate(). To prevent reset again, the original callflow (or any originals) data shall be removed after the migration.
It's also required that the system-config default should be 10800, as seconds in 3 hours.

[master] KZOO-15: ensure min value of max_recording_time_limit

---

applications/crossbar/src/modules/cb_conferences.erl
applications/ecallmgr/src/ecallmgr_conference_control.erl
applications/ecallmgr/src/ecallmgr_fs_conference.erl
core/kazoo_amqp/src/listener_federator.erl

If ecallmgrs don't respond, conference API requests could crash due to unhandled timeout clause.
Improve logging around federated listeners.

[4.3] Conference related updates

---

applications/crossbar/src/modules/cb_conferences.erl
applications/ecallmgr/src/conference/ecallmgr_conference_control.erl
core/kazoo_amqp/src/listener_federator.erl

note when collection times out
bring the parent's call-id along
when a federated listener is spun up, it defaulted to all 0s for the
log ID, making it hard to correlate the listener to the parent
gen_listener.
Add the zone tag to the call-id of the parent to help associate the
listener but also differentiate it from other federated listeners.

Conference related updates

---

applications/crossbar/src/crossbar_view.erl
core/kazoo_proper/src/pqc_cb_cdrs.erl

Add tests for 4 scenarios from "big data" fetches:
1. paginated and chunked
2. paginated and unchunked
3. unpaginated and chunked
4. unpaginated and unchunked
Wonderfully, 3 does not trip the memory limit while 4 does, so
chunking is a nice benefit for unpaginated requests. Might consider
defaulting to `is_chunked=true` when `paginate=false`...

Adjust page size based on chunked/pagination settings

---

applications/crossbar/src/crossbar_view.erl
core/kazoo_proper/src/pqc_cb_cdrs.erl

Add tests for 4 scenarios from "big data" fetches:
1. paginated and chunked
2. paginated and unchunked
3. unpaginated and chunked
4. unpaginated and unchunked
Wonderfully, 3 does not trip the memory limit while 4 does, so
chunking is a nice benefit for unpaginated requests. Might consider
defaulting to `is_chunked=true` when `paginate=false`...

[4.3] Adjust page size based on chunked/pagination settings

---

applications/callflow/src/cf_route_req.erl
applications/callflow/test/cf_route_req_tests.erl
applications/stepswitch/src/stepswitch_bridge.erl
applications/stepswitch/test/stepswitch_bridge_tests.erl
core/kazoo_amqp/include/kapi_offnet_resource.hrl

If a user dials to an emergency number and the device, user, account, or carrier has `Caller-ID Privacy` enabled and/or the user uses `*67` feature code to perform the emergency call, disregard the privacy settings and use the configured caller-id for emergency calls.

Do not honor privacy settings for emergency calls

---

applications/callflow/src/cf_route_req.erl
applications/stepswitch/src/stepswitch_bridge.erl
applications/stepswitch/test/stepswitch_bridge_tests.erl
core/kazoo_amqp/include/kapi_offnet_resource.hrl

Master https://github.com/2600hz/kazoo/pull/6139/
If a user dials to an emergency number and the device, user, account,
or carrier has Caller-ID Privacy enabled and/or the user uses *67
feature code to perform the emergency call, disregard the privacy
settings and use the configured caller-id for emergency calls.

[4.3] Do not honor privacy settings for emergency calls (#6139)

---

applications/callflow/src/cf_exe.erl
applications/callflow/src/cf_listener.erl
applications/callflow/src/cf_remote_action.erl
core/kazoo_amqp/src/api/kapi.erl
core/kazoo_amqp/src/api/kapi_callflow.erl
core/kazoo_amqp/test/kz_api_tests.erl
core/kazoo_call/src/kapps_call_command.erl

* early fail with amqp
* returned value to allow continuation
* cf_module can call cf_remote_action explicitly or `remote_execution: true` can be defined as a peer or `module` in `Flow`

Remote callflow actions

---

applications/teletype/src/templates/teletype_transaction.erl
applications/teletype/src/templates/teletype_transaction_failed.erl

Mark the notification as `ignored` when transaction templates (for successful transaction) or transaction failed template is not being processed.
Binding for these two notifications is same, and the templates are checking `success` in DataJObj to see if the notification is for them to process or the other module. Previously if the notification is for example for failed transaction, the successful template mark itself as disabled which is miss leading, because the template is not disabled it is simply is being process as this notification is irrelevant to the template. With current implementation in teletype these multiple templates can mark them as ignore when they don't want to process the notification so notification publisher consider it as done.

[master] make clear that the template is ignored, not disabled

---

applications/teletype/src/templates/teletype_transaction.erl
applications/teletype/src/templates/teletype_transaction_failed.erl

Mark the notification as `ignored` when transaction templates (for successful transaction) or transaction failed template is not being processed.
Binding for these two notifications is same, and the templates are checking `success` in DataJObj to see if the notification is for them to process or the other module. Previously if the notification is for example for failed transaction, the successful template mark itself as disabled which is miss leading, because the template is not disabled it is simply is being process as this notification is irrelevant to the template. With current implementation in teletype these multiple templates can mark them as ignore when they don't want to process the notification so notification publisher consider it as done.
master pr: …

[4.3] make clear that the template is ignored, not disabled

---

core/kazoo_translator/src/converters/kzt_kazoo.erl

When the INVITE arrives with custom SIP headers, include those in the Pivot request so the receiving web service can make appropriate decisions.

[4.3] Include custom SIP headers in Pivot request

---

applications/crossbar/src/modules/cb_notifications.erl

Notification template fields such as to, from, cc, bcc were being lost as only the `kz_notification:base_properties` were being written to the account-local notification doc during migration. This was being missed on the API req that performed the migration as it would succeed because the missing properties had been inherited from the parent/system during the validate step. But then subsequent requests would be missing the properties because the notification template exists in the account and inheritance is therefore not performed.

PISTON-979: fix migrating templates from system into accounts

---

core/kazoo_media/src/kz_media_tts_cache.erl

Fixed removing tts cache records from ecallmgr_util_cache after
kz_media_tts_cache is terminated.
Forward-port of #6169

Remove TTS cache objects

---

applications/crossbar/src/modules/cb_webhooks.erl
applications/webhooks/src/modules/webhooks_notifications.erl
applications/webhooks/src/webhooks.hrl
applications/webhooks/src/webhooks_listener.erl
applications/webhooks/src/webhooks_sup.erl
applications/webhooks/src/webhooks_util.erl
core/kazoo_documents/src/kzd_webhooks.erl
core/kazoo_proper/src/pqc_cb_webhooks.erl

- listen for and remove account hooks when account is deleted
- allow 'all' modifier for hook types and event types
- test put/post for webhooks

Allow webhooks to be sent using PUT

---

core/kazoo_amqp/src/gen_listener.erl

in master the return is correct, 4.3 expects `State`

fix return in distribute_event

---

core/kazoo/Makefile

apache.org sometimes goes down when we need it.
this is backport from master

change mime types url to github

---

applications/crossbar/doc/voicemail.md
applications/crossbar/src/modules/cb_alerts.erl
applications/crossbar/src/modules/cb_port_requests.erl
applications/crossbar/test/cb_alerts_tests.erl
core/kazoo_numbers/src/knm_port_request.erl
core/kazoo_schemas/src/kz_json_schema.erl

In the UI, a sub-account of a whitelabel domain where the domain admin has selected "
I will request ports on behalf of customers" should not see port alerts in the UI.  Those should be shown to the account managing the ports.
In addition, port requests' comments should only honor action_required on comments that are from the port authority AND public.

[master] KZOO-16: don't show port request alerts to managed sub-accounts

---

applications/callflow/doc/pivot.md
applications/callflow/doc/ref/pivot.md
applications/callflow/src/module/cf_pivot.erl
applications/crossbar/doc/pivot.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/call_recording.parameters.json
applications/crossbar/priv/couchdb/schemas/callflows.pivot.json
applications/crossbar/priv/couchdb/schemas/callflows.record_call.json
applications/crossbar/priv/couchdb/schemas/callflows.record_caller.json
applications/crossbar/priv/couchdb/schemas/callflows.webhook.json
applications/crossbar/priv/couchdb/schemas/faxbox.json
applications/crossbar/priv/couchdb/schemas/kapi.pivot.req.json
applications/crossbar/priv/couchdb/schemas/metaflows.pivot.json
applications/crossbar/priv/couchdb/schemas/metaflows.record_call.json
applications/crossbar/priv/couchdb/schemas/storage.attachment.http.json
applications/crossbar/priv/couchdb/schemas/system_config.kazoo_web.json
applications/crossbar/priv/couchdb/schemas/system_config.pivot.json
applications/crossbar/priv/couchdb/schemas/webhooks.json
applications/pivot/src/pivot_call.erl
core/kazoo_amqp/src/api/kapi_pivot.erl
core/kazoo_proper/src/pqc_cb_api.erl
core/kazoo_proper/src/pqc_cb_callflows.erl
core/kazoo_proper/src/pqc_cb_storage.erl
core/kazoo_proper/src/pqc_cb_webhooks.erl
core/kazoo_schemas/src/kz_json_schema.erl
core/kazoo_schemas/src/kz_json_schema_extensions.erl
core/kazoo_web/src/kazoo_web_maintenance.erl
core/kazoo_web/src/kz_http.erl
core/kazoo_web/src/kz_http_util.erl
core/kazoo_web/test/kz_http_util_tests.erl

It can be advantageous to timeout the Pivot request and allow the
callflow to progress to the failure branch.
Validated client-supplied URLs

[4.3] Configurable timeout on Pivot requests

---

applications/pusher/src/modules/pm_apple.erl
applications/pusher/src/modules/pm_firebase.erl

* applications with same id for fcm/apns
would only work for the first to be triggered
because fcm/apns register the apps with {local', Name}

pusher unique pm apps

---

applications/pusher/src/modules/pm_apple.erl
applications/pusher/src/modules/pm_firebase.erl

* applications with same id for fcm/apns
would only work for the first to be triggered
because fcm/apns register the apps with {local', Name}

pusher unique pm apps - 4.3

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.alerts.json
applications/crossbar/src/modules/cb_alerts.erl

Create the following parameters on the crossbar.alerts document in system config, each is a boolean value that when false suppresses that alert category or specific type:
- check_financials
- check_low_balance
- check_payment_token
- check_port_requests
- check_port_action_required
- check_port_suspended
- check_system_alerts
For example, setting "check_financials" to false will disable both low balance and payment token alerts.  To disable low balance alerts only, leave "check_financials" and set "check_low_balance" to false.

[4.3] Kazoo 6127: Added configuration parameters to control cluster alerts

---

core/kazoo_apps/src/kapps_config.erl
core/sup/src/sup.erl

* in sup commands for kapps_config, the key can be specified like A.B.C.D
to access just D
* adds is_sup_call to process dictionary

allow sup to access inner keys for kapps_config

---

applications/crossbar/doc/connectivity.md
applications/crossbar/doc/ref/connectivity.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/connectivity.json
applications/crossbar/src/modules/cb_connectivity.erl
applications/trunkstore/src/ts_util.erl
core/kazoo_documents/src/kzd_connectivity.erl.src
core/kazoo_proper/src/pqc_cb_connectivity.erl

Connectivity docs should not include an auth_realm as it leads users
to confusion thinking they can set an realm separate from the
account's - this is not the case!
Ensure connectivity docs have the account's realm (just in case) and
ensure Trunkstore sets the account's realm when processing calls.

[4.3] Ensure trunkstore uses account doc's realm

---

applications/crossbar/doc/connectivity.md
applications/crossbar/doc/ref/connectivity.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/connectivity.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/crossbar/src/modules/cb_connectivity.erl
applications/trunkstore/src/ts_util.erl
core/kazoo_documents/src/kzd_connectivity.erl.src
core/kazoo_proper/src/pqc_cb_connectivity.erl

Connectivity docs should not include an auth_realm as it leads users
to confusion thinking they can set an realm separate from the
account's - this is not the case!
Ensure connectivity docs have the account's realm (just in case) and
ensure Trunkstore sets the account's realm when processing calls.

Ensure trunkstore uses account doc's realm

---

applications/crossbar/src/modules/cb_directories.erl
core/kazoo_apps/priv/couchdb/account/directories.json
core/kazoo_apps/src/kapps_notify_publisher.erl
core/kazoo_proper/src/pqc_cb_directories.erl
core/kazoo_proper/src/pqc_cb_users.erl
core/kazoo_stdlib/src/kz_term.erl

Prior, the view only indexed by the directory IDs on a user's
doc. When `paginate=false` was included on a fetch of the directory,
the directory/users_listing view did not interact nicely with the
internal pagination protections added.
The view arguments used `[{key, DirectoryId}, {limit, 50}]`; the first page would
be returned and since the next `startkey` would be `DirectoryId`
again, crossbar_doc gets stuck in a loop as there was no way to
"increment" the startkey.
Instead, the view now emits `[DirectoryId, UserId]` to allow
differentiation between rows, and view options are now passed in as
`[{startkey, [DirectoryId]}]`. This plays much nicer with pagination
regardless of whether pagination has been disabled or not.

[4.3] HELP-12897: properly paginate directory's users

---

applications/crossbar/src/modules/cb_directories.erl
core/kazoo_apps/priv/couchdb/account/directories.json
core/kazoo_apps/src/kapps_notify_publisher.erl
core/kazoo_proper/src/pqc_cb_directories.erl

Prior, the view only indexed by the directory IDs on a user's
doc. When `paginate=false` was included on a fetch of the directory,
the directory/users_listing view did not interact nicely with the
internal pagination protections added.
The view arguments used `[{key, DirectoryId}, {limit, 50}]`; the first page would
be returned and since the next `startkey` would be `DirectoryId`
again, crossbar_doc gets stuck in a loop as there was no way to
"increment" the startkey.
Instead, the view now emits `[DirectoryId, UserId]` to allow
differentiation between rows, and view options are now passed in as
`[{startkey, [DirectoryId]}]`. This plays much nicer with pagination
regardless of whether pagination has been disabled or not.

HELP-12897: properly paginate directory's users

---

applications/crossbar/src/api_util.erl
applications/crossbar/src/cb_context.erl
applications/crossbar/src/crossbar.hrl
applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/crossbar_types.hrl
applications/crossbar/src/modules/cb_token_auth.erl
applications/crossbar/src/modules/cb_users.erl
core/kazoo_auth/src/kz_auth_bearer.erl
core/kazoo_auth/src/kz_auth_keys.erl
core/kazoo_stdlib/include/kazoo_json.hrl

- Kazoo Bearer Tokens
* Sometimes JWT Tokens can be excessive in size.
for long running integrations, we need to provide
Bearer Tokens that can be scoped and invalidated
at any time.
* this is not a replacement for user auth
- Crossbar Bindings
* modules should be allowed to fetch
the request data to avoid normalizing
the payload.
- Other minor fixes

more crossbar bindings

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.pusher.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/pusher/src/pusher_listener.erl

Simple flag to enable/disable push notifications for an app as a whole, without having to remove/lose app configuration including token/cert/private key

PISTON-1021: enabled toggle for pusher apps

---

applications/pusher/doc/pusher.md

Documentation for generating a cert file of the expected format for `pusher_maintenance:add_apple_app`

PISTON-1021: documentation for Certfile for pusher apple apps

---

applications/crossbar/doc/filters.md
applications/crossbar/doc/ref/filters.md
applications/crossbar/src/crossbar_filter.erl
applications/crossbar/src/modules/cb_vmboxes.erl

If you want to find a document by missing a value for a parameter the only way currently is to use the filter for a missing key.  However, this filter does not emit the document if the key is present but the value is empty/null.  There is a has_value filter but no inverse of that.  This adds a new query filter `missing_value` that will return a document if the key is missing OR the value is empty.

[master] KCRO-7: new filter to find missing keys OR keys with empty values

---

applications/crossbar/doc/filters.md
applications/crossbar/doc/ref/filters.md
applications/crossbar/src/crossbar_filter.erl
applications/crossbar/src/modules/cb_vmboxes.erl

If you want to find a document by missing a value for a parameter the only way currently is to use the filter for a missing key. However, this filter does not emit the document if the key is present but the value is empty/null. There is a has_value filter but no inverse of that. This adds a new query filter missing_value that will return a document if the key is missing OR the value is empty.

[4.3] KCRO-7: new filter to find missing keys OR keys with empty values

---

core/kazoo_data/src/kzs_doc.erl
core/kazoo_number_manager/src/knm_locality.erl
core/kazoo_number_manager/src/knm_phone_number.erl
core/kazoo_number_manager/test/knm_create_new_number_tests.erl
core/kazoo_proper/src/pqc_cb_accounts.erl
core/kazoo_proper/src/pqc_cb_phone_numbers.erl

Previously, when deleting the number document from the account
database, a conflict almost always occurred on the first delete
attempt as the number doc from the number database was used (which
contained a different _rev).
However, `knm_phone_number:retry_conflicts/4` only had code for saving
to the target database (the account). The result is that the number
doc (now in the "available" state) would be `ensure_saved` to the
account database, resulting in number listings for the account to both
show the number belonging to the account *and* show it as "available",
an internal state that clients should not see.
This changeset provides additional context to handle_bulk_change about
what type of change, 'delete' or 'save', and informs retry_conflicts
of how to proceed.
Secondly, the …

[4.3] KZ00-41: handle number delete conflicts

---

core/kazoo_data/src/kzs_doc.erl
core/kazoo_numbers/src/knm_locality.erl
core/kazoo_numbers/src/knm_phone_number.erl
core/kazoo_proper/src/pqc_cb_phone_numbers.erl

This is a forward port of the 4.3 version that corrects an error where
retrying deletes caused a save operation instead. This bug is
corrected in current master; this commit serves to forward-port the
pqc test recreation of the 4.3 issue.

KZOO-41: handle number delete conflicts

---

applications/notify/src/notify_maintenance.erl
applications/notify/src/notify_util.erl
applications/teletype/src/teletype_util.erl
core/kazoo_ast/src/kapps_config_usage.erl
make/deps.mk

`gen_smtp_client` has been changed to accept more `relay` as a list. But it has a bug to use list comprehensive to convert a list to string, which also cause a genuine string to be converted to string char by char.
This is trying to pass the `relay` option as a binary so it would be properly converted to string by `gen_smtp_client`.
commit that changed the the `deps.mk`: https://github.com/2600hz/kazoo/commit/4aab964987de4bd1e3233aba94c2e119cc5eefeb
commit that changed the gen_smtp: https://github.com/2600hz/erlang-gen_smtp/commit/033f2d133e733304d591fef4b05ea58e8c220e92

pass relay setting as binary

---

applications/crossbar/src/modules/cb_directories.erl
core/kazoo_proper/src/pqc_cb_directories.erl

With just `startkey`, any directories sorted after the requested
directory would also appear in the results. Include `endkey` to ensure
only the requested directory's users are listed.
Update pqc to test that only a directory's users are returned.

Add endkey to avoid pulling in other directory listings

---

applications/crossbar/src/modules/cb_directories.erl
core/kazoo_proper/src/pqc_cb_directories.erl

With just `startkey`, any directories sorted after the requested
directory would also appear in the results. Include `endkey` to ensure
only the requested directory's users are listed.
Update pqc to test that only a directory's users are returned.

[4.3] Add endkey to avoid pulling in other directory listings

---

core/kazoo_amqp/src/gen_listener.erl
core/kazoo_amqp/src/kz_amqp_federated_listeners_sup.erl
core/kazoo_amqp/src/kz_amqp_sup.erl
core/kazoo_amqp/src/listener_federator.erl
core/kazoo_apps/src/kapps_maintenance.erl
core/kazoo_proper/src/kazoo_proper_maintenance.erl
core/kazoo_services/src/kz_services.erl

Prior, when a gen_listener needed to federate its queue and bindings
to other zones, it would start_link the listener_federator (and trap
exits). However, should a listener_federator process actually exit,
the parent gen_listener would receive the EXIT message but failed to
have a handle_info clause to restart the process.
Introduce a sofo supervisor for starting listener_federator processes
and restart them if they die unexpectedly (non-normal exits).
Secondly, introduce memory consumption checks and GC gen_listeners
when they exceed 100K in total_heap_size. In addition, copy the binary
payloads as they arrive off the AMQP channel has shown to decelerate
the memory growth as the original binary can be garbage collected
sooner and not count against the gen_listener's "old" heap.
All told, …

[4.3] Listener federators and memory improvements

---

core/kazoo_amqp/src/gen_listener.erl
core/kazoo_amqp/src/kz_amqp_federated_listeners_sup.erl
core/kazoo_amqp/src/kz_amqp_sup.erl
core/kazoo_amqp/src/listener_federator.erl
core/kazoo_apps/src/kapps_maintenance.erl
core/kazoo_globals/src/kz_nodes.erl
core/kazoo_proper/src/kazoo_proper_maintenance.erl

Prior, when a gen_listener needed to federate its queue and bindings
to other zones, it would start_link the listener_federator (and trap
exits). However, should a listener_federator process actually exit,
the parent gen_listener would receive the EXIT message but failed to
have a handle_info clause to restart the process.
Introduce a sofo supervisor for starting listener_federator processes
and restart them if they die unexpectedly (non-normal exits).
Secondly, introduce memory consumption checks and GC gen_listeners
when they exceed 100K in total_heap_size. In addition, copy the binary
payloads as they arrive off the AMQP channel has shown to decelerate
the memory growth as the original binary can be garbage collected
sooner and not count against the gen_listener's "old" heap.
All told, …

Listener federators and memory improvements

---

applications/crossbar/doc/devices.md
core/kazoo_endpoint/src/kz_endpoint.erl
core/kazoo_endpoint/src/kz_endpoint_v4.erl
core/kazoo_endpoint/src/kz_endpoint_v5.erl

The `call_forward` object handles configuration for both call
forwarding and for failover. In its current implementation, only one
of those features can be "active".
Prior to this change, if `call_forward.failover` was `true` it would
be included on the endpoint object and ecallmgr would treat the
`call_forward` settings as a failover endpoint, regardless of the
`call_forward.enabled` flag's setting.
This change clarifies that if `call_forward.enabled` is `true`, the
settings should only be considered for call forwarding. If the setting
is `false` *and* `call_forward.failover` is `true` then consider the
settings as a failover endpoint.

HELP-11566: clarify precedence of call forward vs failover

---

applications/crossbar/doc/devices.md
core/kazoo_endpoint/src/kz_endpoint.erl

The `call_forward` object handles configuration for both call
forwarding and for failover. In its current implementation, only one
of those features can be "active".
Prior to this change, if `call_forward.failover` was `true` it would
be included on the endpoint object and ecallmgr would treat the
`call_forward` settings as a failover endpoint, regardless of the
`call_forward.enabled` flag's setting.
This change clarifies that if `call_forward.enabled` is `true`, the
settings should only be considered for call forwarding. If the setting
is `false` *and* `call_forward.failover` is `true` then consider the
settings as a failover endpoint.

[4.3] HELP-11566: clarify precedence of call forward vs failover

---

applications/crossbar/src/modules/cb_alerts.erl

When deciding to how to show port alerts for reseller account, we should check and use **authenticated** account ID (as it was describ in the comments).

[4.3] HELP-13256: show correct port alerts based on authenticated account id

---

applications/crossbar/src/modules/cb_vmboxes.erl

When listing the voicemail boxes this adds a new object to each called "folders" if the vmbox has messages.  The object contains two properties that represent the quantity of messages in the 'new' and 'saved' folders.

[4.3] KCRO-10: expose the message counts per folder when listing vmboxes

---

applications/crossbar/src/modules/cb_vmboxes.erl

When listing the voicemail boxes this adds a new object to each called "folders" if the vmbox has messages.  The object contains two properties that represent the quantity of messages in the 'new' and 'saved' folders.

[master] KCRO-10: expose the message counts per folder when listing vmboxes

---

applications/crossbar/src/api_util.erl
core/kazoo_documents/src/kzd_accounts.erl
core/kazoo_proper/src/pqc_cb_cdrs.erl

When using sendfile in Crossbar, there can exist a race condition
where the filename has been passed to Cowboy for sending, Cowboy
handles streaming the file asynchronously, and calls Crossbar's
finish_request callback.
Because the streaming and finish_request callback are happening in
parallel, it is possible for the file to be deleted from the local
disk before streaming has completed.
pqc_cb_ledgers will occassionally provoke this race condition.
Since deleting the file occurs in a spawned process itself, use the
rounded natural log of the file's size * 10 to calculate a small sleep
timeout before deleting the file.

Stagger deleting a file based on filesize

---

applications/teletype/priv/templates/voicemail_to_email.html
applications/teletype/priv/templates/voicemail_to_email.text
applications/teletype/src/templates/teletype_voicemail_to_email.erl

Add configuration parameter to VM documents to decide whether or not to
include attachments when sending the voicemail_to_email notification.

HELP-13212: Exclude attachments from being included if present

---

.gitignore
Makefile
doc/engineering/make.md
make/pest.mk

From the project's description: "Do a basic scan of Erlang source code
and report any function calls that may cause Erlang source code to be
insecure."
As PEST reports lots of "maybe" issues, this is more intended for
specific PEST-related coding. Mostly validating input before calling
os:cmd for instance.
Two targets:
- `make pest`: will run PEST on changed Erlang files (if any)
- `make pest-all`: will run PEST on all deps, core, and app BEAM files

Add Primitive Erlang Security Tool ('PEST') to Makefile

---

.gitignore
applications/fax/.gitignore
applications/fax/Makefile
applications/fax/src/fax_smtp.erl
applications/fax/test/fax_smtp_tests.erl
applications/fax/test/pdf.pdf
core/kazoo_proper/Makefile
make/deps.mk

On some email attachments (seemingly PDFs) the `iconv` program used to
convert between character encodings (via gen_smtp/mimemail) will fail,
causing the email to be thrown away as invalid. These emails and their
attachments are, in fact, valid and should be processed.
The gen_smtp commit hash is updated to change mimemail to consider
matching `From`/`To` encodings as a no-op and avoid the call to
`iconv` entirely. This allows the PDF to be processed out of the email
for use by fax_smtp.

HELP-13433: noop email conversions to avoid errors

---

.gitignore
applications/fax/Makefile
applications/fax/src/fax_smtp.erl
applications/fax/test/fax_smtp_tests.erl
make/deps.mk

On some email attachments (seemingly PDFs) the `iconv` program used to
convert between character encodings (via gen_smtp/mimemail) will fail,
causing the email to be thrown away as invalid. These emails and their
attachments are, in fact, valid and should be processed.
The gen_smtp commit hash is updated to change mimemail to consider
matching `From`/`To` encodings as a no-op and avoid the call to
`iconv` entirely. This allows the PDF to be processed out of the email
for use by fax_smtp.

[4.3] HELP-13433: noop email conversions to avoid errors

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.blackhole.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.json
applications/crossbar/priv/couchdb/schemas/system_config.cluster_manager.json
applications/crossbar/priv/couchdb/schemas/system_config.mobile.json
applications/crossbar/priv/couchdb/schemas/system_config.phonebook.json
applications/crossbar/priv/couchdb/schemas/system_config.webrtc.json
applications/crossbar/src/crossbar_util.erl
applications/crossbar/src/modules/cb_vmboxes.erl
core/kazoo_speech/src/asr/kazoo_asr_google.erl
core/kazoo_speech/src/asr/kazoo_asr_ispeech.erl
core/kazoo_speech/src/gen_asr_provider.erl
core/kazoo_speech/src/kazoo_asr.erl
core/kazoo_voicemail/src/kvm_util.erl

When generating a new JWT for Crossbar the response now includes the cluster id as well as a new object 'capabilities'.  The capabilities object conveys services and settings of the cluster so the UI can modify the user experience to match.  At this time the only parameters that are exposed are voicemail.transcription.supported if a transcription service is configured with an API key and voicemail.transcription.default to inform the UI transcriptions are created by default.

[4.3] KCRO-15: expose transcription capabilities in the crossbar authentication response

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.blackhole.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.json
applications/crossbar/priv/couchdb/schemas/system_config.cluster_manager.json
applications/crossbar/priv/couchdb/schemas/system_config.mobile.json
applications/crossbar/priv/couchdb/schemas/system_config.phonebook.json
applications/crossbar/priv/couchdb/schemas/system_config.webrtc.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/crossbar/src/crossbar_util.erl
applications/crossbar/src/modules/cb_vmboxes.erl
core/kazoo_speech/src/asr/kazoo_asr_google.erl
core/kazoo_speech/src/asr/kazoo_asr_ispeech.erl
core/kazoo_speech/src/gen_asr_provider.erl
core/kazoo_speech/src/kazoo_asr.erl
core/kazoo_voicemail/src/kvm_util.erl

When generating a new JWT for Crossbar the response now includes the cluster id as well as a new object 'capabilities'. The capabilities object conveys services and settings of the cluster so the UI can modify the user experience to match. At this time the only parameters that are exposed are voicemail.transcription.supported if a transcription service is configured with an API key and voicemail.transcription.default to inform the UI transcriptions are created by default.

[master] KCRO-15: expose transcription capabilities in the crossbar authentication response

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.cdrs.json
applications/crossbar/src/modules/cb_cdrs.erl
core/kazoo_proper/src/pqc_cb_cdrs.erl
core/kazoo_stdlib/src/props.erl
core/kazoo_stdlib/test/props_tests.erl

An addition to filter_empty fields from the CDR summary response is
causing expected fields like `cost` to be stripped when they are
0. The intent of the change was to filter keys with empty strings ("")
to reduce payload size.
Instead, let's add a `filter_empty_strings` to narrow down what is
removed from the payload.

[4.3] KZOO-45: Filter just empty strings when normalizing CDRs

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.crossbar.cdrs.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/crossbar/src/modules/cb_cdrs.erl
core/kazoo_proper/src/pqc_cb_cdrs.erl
core/kazoo_stdlib/src/props.erl
core/kazoo_stdlib/test/props_tests.erl

An addition to filter_empty fields from the CDR summary response is
causing expected fields like `cost` to be stripped when they are
0. The intent of the change was to filter keys with empty strings ("")
to reduce payload size.
Instead, let's add a `filter_empty_strings` to narrow down what is
removed from the payload.

KZOO-45: Filter just empty strings when normalizing CDRs

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/doc/ref/vmboxes.md
applications/crossbar/doc/voicemail.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/vmboxes.json
applications/crossbar/priv/oas3/oas3-schemas.yml
core/kazoo_documents/src/kzd_vmboxes.erl.src
core/kazoo_documents/src/kzd_voicemail_box.erl
doc/announcements.md

This PR adds new functionality to a voicemail box, enabling a mailbox to only play the greeting and advance to the next node of the current callflow.
Announcement only mode can be controlled with the `announcement_only` boolean in the vmbox schema or by the mailbox owner via the voicemail config menu.  This default setting for this feature's is disabled or `false`.
Mailbox owners will now hear new options in the voicemail configuration menu as two new prompts have been added to [Kazoo Core Media](https://github.com/2600hz/kazoo-sounds/tree/master/kazoo-core#importing-prompts-for-a-language).
Two new en-US prompts have been added to handle this feature and should be imported in conjunction with the upgrade of KAZOO.
* vm-settings\_menu
* vm-settings\_menu\_announcement_on
For instructions …

[PROD-170]: Announcement Only Mode for vmboxes - Master

---

applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/doc/ref/vmboxes.md
applications/crossbar/doc/voicemail.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/vmboxes.json
core/kazoo_documents/src/kzd_vmboxes.erl.src
core/kazoo_documents/src/kzd_voicemail_box.erl
doc/announcements.md

This PR adds new functionality to a voicemail box, enabling a mailbox to only play the greeting and advance to the next node of the current callflow.
Announcement only mode can be controlled with the `announcement_only` boolean in the vmbox schema or by the mailbox owner via the voicemail config menu.  This default setting for this feature's is disabled or `false`.
Mailbox owners will now hear new options in the voicemail configuration menu as two new prompts have been added to [Kazoo Core Media](https://github.com/2600hz/kazoo-sounds/tree/master/kazoo-core#importing-prompts-for-a-language).
Two new en-US prompts have been added to handle this feature and should be imported in conjunction with the upgrade of KAZOO.
* vm-settings\_menu
* vm-settings\_menu\_announcement_on
For instructions …

[PROD-170]:  Announcement Only Mode for vmboxes - 4.3

---

core/kazoo_modb/priv/couchdb/views/interactions.json

The reduce view for user interactions uses the billing seconds but it is not emitted from the map function.

[4.3] KCRO-14: emit the billing_seconds for the reduce

---

core/kazoo_modb/priv/couchdb/views/interactions.json

The reduce view for user interactions uses the billing seconds but it is not emitted from the map function.

[master] KCRO-14: emit the billing_seconds for the reduce

---

applications/crossbar/src/modules/cb_users.erl

Addresses payloads that fail validation but continue to execute routines that expected valid data:
01:00:29.333 error kazoo_bindings.690 unable to find function clause for kz_json:no_prune([<<"pvt_sha1_auth">>], undefined) in src/kz_json.erl:1369
01:00:29.334 error kazoo_bindings.696 as part of cb_users_v2:validate/2
01:00:29.334 error kazoo_bindings.697 st: {lists,foldr,3,[{file,"lists.erl"},{line,1276}]}
01:00:29.334 error kazoo_bindings.697 st: {cb_users_v2,remove_creds,1,[{file,"src/modules_v2/cb_users_v2.erl"},{line,770}]}
01:00:29.334 error kazoo_bindings.697 st: {lists,foldl,3,[{file,"lists.erl"},{line,1263}]}
01:00:29.334 error kazoo_bindings.697 st: {kazoo_bindings,fold_bind_results,5,[{file,"src/kazoo_bindings.erl"},{line,632}]}
01:00:29.334 error kazoo_bindings.697 st: …

[master] KCRO-17: skip some routines during user creation if there were errors

---

applications/crossbar/src/modules/cb_vmboxes.erl
core/kazoo_proper/src/pqc_cb_vmboxes.erl

When a voicemail box is empty and deleted via API, an error would be
thrown during deletion when deciding to publish deleted
messages. kvm_messages:fetch/4 strips empty values from the results,
`succeeded` would be `[]` and thus stripped, so `get_list_value/2`
returned `undefined`. This caused the call to `lists:foreach/2` to
crash.
Instead, fetch `succeeded` with `[]` as a default and only process if
the result is a non-empty list.

KZOO-52: use a default empty list for messages

---

applications/crossbar/src/modules/cb_vmboxes.erl
core/kazoo_proper/src/pqc_cb_vmboxes.erl

When a voicemail box is empty and deleted via API, an error would be
thrown during deletion when deciding to publish deleted
messages. kvm_messages:fetch/4 strips empty values from the results,
`succeeded` would be `[]` and thus stripped, so `get_list_value/2`
returned `undefined`. This caused the call to `lists:foreach/2` to
crash.
Instead, fetch `succeeded` with `[]` as a default and only process if
the result is a non-empty list.

[4.3] KZOO-52: use a default empty list for messages

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.privacy.json
applications/ecallmgr/src/ecallmgr_call_command.erl
applications/ecallmgr/src/ecallmgr_fs_xml.erl
core/kazoo_endpoint/src/kz_privacy.erl

This adds the `Privacy: id` SIP header on the endpoints string if only some of carriers/endpoints have the privacy flags during building the bridge string.
If there is only one carrier or the only some of the carriers have privacy settings, the `P-Asserted-Identity` tend to not be lifted in bridge object and `ecallmgr_fs_xml` during creating bridge string won't add `Privacy: id` header because the `Privacy-Hide-Name` or `Privacy-Hide-Number` are set on the endpoint Prop.
Also when adding `P-Asserted-Identity`, its value in the bridge string should be single quoted.
If this PR causes issues with your devices you can opt-out of the feature by setting use_sip_privacy_header to false on that system_config privacy document.

[4.3] KZOO-31: add privacy headers for carrier endpoints in bridge string

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.privacy.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/ecallmgr/src/call_cmd/ecallmgr_call_command.erl
applications/ecallmgr/src/ecallmgr_fs_xml.erl
core/kazoo_endpoint/src/kz_privacy.erl

This adds the Privacy: id SIP header on the endpoints string if only some of carriers/endpoints have the privacy flags during building the bridge string.
If there is only one carrier or the only some of the carriers have privacy settings, the P-Asserted-Identity tend to not be lifted in bridge object and ecallmgr_fs_xml during creating bridge string won't add Privacy: id header because the Privacy-Hide-Name or Privacy-Hide-Number are set on the endpoint Prop.
Also when adding P-Asserted-Identity, its value in the bridge string should be single quoted.
If this PR causes issues with your devices you can opt-out of the feature by setting use_sip_privacy_header to false on that system_config privacy document.

[master] KZOO-31: add privacy headers for carrier endpoints in bridge string

---

core/kazoo_endpoint/src/kz_endpoint.erl
core/kazoo_endpoint/test/kz_endpoint_tests.erl

Make sure that account and endpoint settings are properly populated
when device/user settings are empty objects instead of undefined.
Part of HELP-13159

[4.3] KZOO-53: test when endpoint settings are empty objects

---

core/kazoo_endpoint/src/kz_endpoint_v4.erl
core/kazoo_endpoint/test/kz_endpoint_tests.erl

Make sure that account and endpoint settings are properly populated
when device/user settings are empty objects instead of undefined.
Part of HELP-13159

KZOO-53: test when endpoint settings are empty objects

---

applications/crossbar/src/modules/cb_accounts.erl
core/kazoo_databases/src/kzdb_account.erl
core/kazoo_proper/src/pqc_cb_accounts.erl

If `realm` is included on the request, ensure created account reports
the custom `realm` after creation.
If `realm` is not included, ensure created account reports the `realm`
as a string containing the system-configured realm suffix.
Part of HELP-13467

KZOO-54: ensure accounts are created with the realm specified

---

core/kazoo_proper/src/pqc_cb_accounts.erl

If `realm` is included on the request, ensure created account reports
the custom `realm` after creation.
If `realm` is not included, ensure created account reports the `realm`
as a string containing the system-configured realm suffix.
Part of HELP-13467

[4.3] KZOO-54: ensure accounts are created with the realm specified

---

core/kazoo_stdlib/src/kz_date.erl
core/kazoo_stdlib/test/kz_date_tests.erl

kz_date:previous_day/1 will correctly handle month/year boundries
when calculating the previous day

[4.3] Add previous_day method to kz_date

---

core/kazoo_stdlib/src/kz_date.erl
core/kazoo_stdlib/test/kz_date_tests.erl

kz_date:previous_day/1 will correctly handle month/year boundries
when calculating the previous day

Add previous_day method to kz_date

---

applications/ecallmgr/src/ecallmgr_fs_xml.erl
applications/ecallmgr/src/ecallmgr_util.erl

kz_moh was added to freeswitch so that
hold media position is preserved
between HOLD/UNHOLD
this is opt-in and for now is global

allow use of kz_moh - 4.3

---

applications/fax/src/fax_jobs.erl
applications/fax/src/fax_worker.erl
core/kazoo/src/kz_doc.erl
core/kazoo_data/src/kzs_doc.erl
core/kazoo_proper/src/pqc_kz_datamgr.erl

The faxes DB fills up when the `move_doc` fails with a conflict when
inserting the doc into the MODB. Handle the error by checking that the
document exists in the MODB and forcing deletion of the doc in the
faxes database.

[4.3] KZOO-56: handle conflict when moving faxes to MODB

---

applications/fax/src/fax_worker.erl
core/kazoo_data/src/kzs_doc.erl
core/kazoo_documents/src/kz_doc.erl
core/kazoo_proper/src/pqc_kz_datamgr.erl

The faxes DB fills up when the `move_doc` fails with a conflict when
inserting the doc into the MODB. Handle the error by checking that the
document exists in the MODB and forcing deletion of the doc in the
faxes database.

KZOO-56: handle conflict when moving faxes to MODB

---

core/sup/src/sup.erl

Allow a user to pass any data type to a function call through the sup command
EG.  
sup kz_time to_gregorian_seconds "{{2020, 01, 01}, {01, 20, 30}}" "<<\"Etc/UTC\">>"

PISTON-1032: Allow SUP to handle any argument type as long as the argument is surrounded by double quotes.

---

.circleci/config.yml
applications/callflow/src/cf_route_req.erl
applications/callflow/src/cf_route_win.erl
applications/ecallmgr/src/ecallmgr_fs_xml.erl
applications/registrar/src/reg_authn_req.erl
core/kazoo_call/src/kapps_call.erl
core/kazoo_data/src/kz_data.hrl
core/kazoo_documents/src/kzd_devices.erl
core/kazoo_documents/test/kzd_device_tests.erl
core/kazoo_endpoint/src/kz_attributes.erl
core/kazoo_number_manager/src/kazoo_number_manager_maintenance.erl
core/kazoo_proper/src/pqc_kz_datamgr.erl

When a device registers, the calculated presence_id is cached and
passed along on subsequent INVITEs. If a user hotdesks into the
device, the cached presence_id (likely the SIP username of the device)
will continue to be used on call events related to that device.
This causes issues with applications (like Qubicle) that track a
user's calls based on the user's presence_id being present on dialog
update events (confirmed and terminated).
Instead, provide a uniform way to calculate a device's presence_id and
use it for setting CCVs on the route response in callflow and in
registrar for authn responses.

[4.3] KZOO-57: calculate presence id for route requests

---

core/kazoo_proper/src/pqc_kz_datamgr.erl

Listeners for db config change payloads try to load views into a
database which is going away quite fast. No need, we don't use views
in this test.

Don't publish AMQP updates during testing

---

Makefile
applications/callflow/doc/conference_feature.md
applications/callflow/doc/ref/conference_feature.md
applications/callflow/src/module/cf_conference.erl
applications/callflow/src/module/cf_conference_feature.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.conference_feature.json
applications/crossbar/priv/oas3/oas3-schemas.yml
core/kazoo_ast/src/cf_data_usage.erl
core/kazoo_ast/src/kapps_config_usage.erl
doc/mkdocs/mkdocs.yml
scripts/generate-schemas.escript

Rather than needing to know the extension to dial for a conference,
allow a feature code to capture the conference ID from the dialed
number. Useful for clients that are provisioned dynamically (like
WebRTC devices) that have full control over the dialed number (as
opposed to typical desk phones which only dial digits).

KZOO-60: permit conference feature code

---

applications/callflow/src/cf_flow.erl
applications/callflow/src/cf_route_req.erl
applications/callflow/src/cf_route_win.erl
applications/crossbar/doc/callflows.md
applications/crossbar/doc/ref/callflows.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/callflows.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/ecallmgr/src/ecallmgr_discovery.erl
applications/ecallmgr/src/ecallmgr_fs_xml.erl
applications/ecallmgr/src/ecallmgr_util.erl
applications/registrar/src/reg_authn_req.erl
core/kazoo_amqp/src/api/kapi_authn.erl
core/kazoo_amqp/src/api/kapi_self.erl
core/kazoo_data/src/kz_data.hrl
core/kazoo_directory/src/kz_directory_endpoint.erl
core/kazoo_directory/src/kz_directory_user.erl
core/kazoo_documents/src/kzd_callflows.erl
core/kazoo_documents/src/kzd_callflows.erl.src
core/kazoo_documents/src/kzd_devices.erl
core/kazoo_documents/test/kzd_device_tests.erl
core/kazoo_endpoint/src/kz_attributes.erl
core/kazoo_endpoint/src/kz_endpoint.erl
core/kazoo_numbers/src/kazoo_numbers_maintenance.erl
core/kazoo_proper/src/pqc_kz_datamgr.erl

When a device registers, the calculated presence_id is cached and
passed along on subsequent INVITEs. If a user hotdesks into the
device, the cached presence_id (likely the SIP username of the device)
will continue to be used on call events related to that device.
This causes issues with applications (like Qubicle) that track a
user's calls based on the user's presence_id being present on dialog
update events (confirmed and terminated).
Instead, provide a uniform way to calculate a device's presence_id and
use it for setting CCVs on the route response in callflow and in
registrar for authn responses.

KZOO-57: calculate presence id for route requests

---

applications/ecallmgr/src/ecallmgr_fs_xml.erl

send acls with ports - 4.3

---

applications/cdr/src/cdr_channel_destroy.erl
core/kazoo_proper/src/pqc_cb_accounts.erl

Verify required schema fields and other expected fields are on the
response (including leaked pvt fields)

KZOO-61: ensure reseller_id on account response

---

applications/cdr/src/cdr_channel_destroy.erl
core/kazoo_proper/src/pqc_cb_accounts.erl

Verify required schema fields and other expected fields are on the
response (including leaked pvt fields)

[4.3] KZOO-61: ensure reseller_id on account response

---

core/kazoo_apps/src/kapps_config.erl
core/kazoo_apps/src/kapps_config_maintenance.erl
core/kazoo_data/src/kazoo_data_maintenance.erl

Optional _pp suffix if you want the returned term pretty-printed.

[4.3] Add maintenance module for kapps_config interactions

---

core/kazoo_apps/src/kapps_config.erl
core/sup/src/sup.erl

* in sup commands for kapps_config, the key can be specified like A.B.C.D
to access just D
* adds is_sup_call to process dictionary

allow sup to access inner keys for kapps_config (#6253)

---

applications/crossbar/doc/devices.md
applications/crossbar/doc/ref/devices.md
applications/crossbar/doc/ref/resources.md
applications/crossbar/doc/resources.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/devices.json
applications/crossbar/priv/couchdb/schemas/kapi.acdc_agent.end_wrapup.json
applications/crossbar/priv/couchdb/schemas/kapi.acdc_agent.pause.json
applications/crossbar/priv/couchdb/schemas/kapi.acdc_agent.resume.json
applications/crossbar/priv/couchdb/schemas/resources.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/crossbar/src/modules/cb_resources.erl
applications/stepswitch/src/stepswitch_resources.erl
core/kazoo_apps/src/kapps_maintenance.erl
core/kazoo_ast/src/kapi_schemas.erl
core/kazoo_directory/src/kz_directory_resource.erl
core/kazoo_documents/src/kzd_devices.erl
core/kazoo_documents/src/kzd_devices.erl.src
core/kazoo_documents/src/kzd_resources.erl
core/kazoo_documents/src/kzd_resources.erl.src
core/kazoo_endpoint/src/kz_endpoint_v4.erl
core/kazoo_schemas/src/kz_json_schema.erl
doc/mkdocs/mkdocs.yml

Stepswitch makes use of a number of fields that aren't defined on the
resources schema. Add them and use the accessor module when possible.

Add missing fields from resources schema

---

applications/crossbar/src/crossbar_util.erl

Fallback to en-US label of UI app when user, account and system default language is not en-US.

[4.3] fallback to en-US if i18n label is missing

---

applications/crossbar/src/crossbar_util.erl

Fallback to en-US label of UI app when user, account and system default language is not en-US.
4.3: https://github.com/2600hz/kazoo/pull/6407

[master] fallback to en-US if i18n label is missing

---

applications/ecallmgr/src/ecallmgr_fs_node_sup.erl

module names are taken from env which may be changed at startup
by changing sys.config.
this makes sure that deprecated modules
are removed from the list in cae a sys.config was changed
or not chagned and still has reference to missing module
a better way would be to ensure that the module exists
but i was out of time :)

add deprecated modules - 4.3

---

applications/teletype/priv/templates/voicemail_to_email.html

This PR addresses a small formatting issue with the template where the if block for media file attachment was not wrapping to a new line in the template preview.
- adds a missing <tr> opening tag
- wrap voicemail media file condition in a pre tag to wrap to a new line in branding app template viewer

[MBRA-1] - Fix formatting issue with voicemail to email HTML template - 4.3

---

applications/teletype/priv/templates/voicemail_to_email.html

This PR addresses a small formatting issue with the template where the if block for media file attachment was not wrapping to a new line in the template preview.
- adds a missing <tr> opening tag
- wrap voicemail media file condition in a pre tag to wrap to a new line in branding app template viewer

[MBRA-1] - Fix formatting issue with voicemail to email HTML template - Master

---

applications/teletype/priv/templates/voicemail_to_email.html
applications/teletype/priv/templates/voicemail_to_email.text
applications/teletype/src/templates/teletype_voicemail_to_email.erl

It seems `voicemail.file_name` is also set when `transcribe` is enabled so I added a new parameter to the template data object to take an accurate decision on whether or not to include the attachment's referral information.

[4.3] HELP-13212: Improve check to include attachment referral information

---

applications/teletype/priv/templates/voicemail_to_email.html
applications/teletype/priv/templates/voicemail_to_email.text
applications/teletype/src/templates/teletype_voicemail_to_email.erl

It seems `voicemail.file_name` is also set when `transcribe` is enabled so I added a new parameter to the template data object to take an accurate decision on whether or not to include the attachment's referral information.
[4.3 PR](https://github.com/2600hz/kazoo/pull/6476)

HELP-13212: Improve check to include attachment referral information

---

.circleci/config.yml
applications/tasks/src/modules/kt_compactor.erl
core/kazoo_couch/src/kazoo_couch.erl
core/kazoo_couch/src/kz_couch.hrl
core/kazoo_couch/src/kz_couch_util.erl
rel/ci.config.ini

* Adding support for CouchDB version 3
* Not starting `kt_compactor` if couchdb version is 3
Note: this PR doesn't address deprecation of `list` and `show` functions.

adding CouchDB 3 support

---

applications/crossbar/src/api_util.erl
core/kazoo_proper/src/pqc_cb_api.erl
core/kazoo_proper/src/pqc_cb_webhooks.erl
core/kazoo_stdlib/src/kz_json.erl

Only include backend "version" when responding to an authenticated
request.

Conditionally include "version" on response payloads

---

applications/stepswitch/src/stepswitch_bridge.erl
applications/stepswitch/src/stepswitch_local_extension.erl
core/kazoo/src/kz_util.erl
core/kazoo_amqp/include/kz_api.hrl
core/kazoo_numbers/src/knm_options.erl

When using local_extension (when hairpinning calls to stay on-net) in
stepswitch, the local_extension bridge command was missing some key
values - specifically setting `Bridge-Actions` with the offnet
request's `Outbound-Actions` (which sets up recording on answer for
instance).

KSTE-1: Include additional parameters on local ext bridge request

---

applications/stepswitch/src/stepswitch_bridge.erl
applications/stepswitch/src/stepswitch_local_extension.erl
core/kazoo/src/kz_util.erl
core/kazoo_number_manager/src/knm_number_options.erl
core/kazoo_number_manager/src/knm_numbers.erl

When using local_extension (when hairpinning calls to stay on-net) in
stepswitch, the local_extension bridge command was missing some key
values - specifically setting `Bridge-Actions` with the offnet
request's `Outbound-Actions` (which sets up recording on answer for
instance).

[4.3] KSTE-1: Include additional parameters on local ext bridge request

---

applications/crossbar/doc/connectivity.md
applications/crossbar/doc/devices.md
applications/crossbar/doc/ref/connectivity.md
applications/crossbar/doc/ref/devices.md
applications/crossbar/doc/ref/resources.md
applications/crossbar/doc/resources.md
applications/crossbar/priv/api/descriptions.system_config.json
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/connectivity.json
applications/crossbar/priv/couchdb/schemas/devices.json
applications/crossbar/priv/couchdb/schemas/kapi.dialplan.bridge_endpoint.json
applications/crossbar/priv/couchdb/schemas/kapi.route.resp_route.json
applications/crossbar/priv/couchdb/schemas/resources.json
applications/crossbar/priv/couchdb/schemas/system_config.number_manager.json
applications/crossbar/priv/couchdb/schemas/trunkstore.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/ecallmgr/src/ecallmgr_util.erl
applications/trunkstore/src/ts_util.erl
core/kazoo_amqp/src/api/kapi_dialplan.hrl
core/kazoo_call/src/kapps_call_command.erl
core/kazoo_directory/src/kz_directory_endpoint.erl
core/kazoo_endpoint/src/kz_formatters.erl
core/kazoo_numbers/doc/knm_converter_migrate_maintenance.md
core/kazoo_numbers/doc/ref/knm_converter_migrate_maintenance.md
core/kazoo_numbers/src/converters/knm_converter_migrate_maintenance.erl
core/kazoo_numbers/src/converters/knm_converter_regex.erl
core/kazoo_numbers/src/converters/knm_converters.erl
core/kazoo_schemas/test/fixtures/schemav3_sub_defaults_array.json
doc/mkdocs/mkdocs.yml

This PR adds a new `knm_converter` and schema to allow an INVITE format to the prefixed `+` plus stripped.
This PR adds and exports new converter `strip_plus` and `is_strip_plus` functions from the converter abstraction.
Implements the `to_strip_plus` function for use by `knm_converters` abstraction.
Creates a maintenance command to migrate existing devices, resources, and trunks configured for a given invite format to another.
The **default** for migrate/0 converts from `npan` to `strip_plus`.
- [[Master] monster-ui-pbxs](https://github.com/2600hz/monster-ui-pbxs/pull/14) 
- [[Master]monster-ui-callflows](https://github.com/2600hz/monster-ui-callflows/pull/98)

[Master] - PROD-210: Add INVITE format to strip +

---

applications/crossbar/src/crossbar_maintenance.erl

Corresponding back port PR for: https://github.com/2600hz/kazoo/pull/6495
This is an extension of the SUP command to create the initial master account. We wanted to be able to add optional parameters for the uuid's of the account and user. This is so we can set the UUIDs ahead of time for functional testing.

Sup UUID 43

---

applications/callflow/src/module/cf_voicemail.erl
core/kazoo_call/src/kapps_call_command.erl

When `play_greeting_intro`, `play_greeting`, or `play_instructions` play media, a noop is enqueued. `kapps_call_command:wait_for_application_or_dtmf` may continue on the noop from one of these play commands, rather than as expected due to `kapps_call_command:noop`. This means, for example, the user is unable to press a key to connect to the operator during instructions, if the greeting has already been played.
I introduced the 8-arity `collect_digits` for this purpose, too, as it allows a long initial timeout (`kapps_call_command:default_application_timeout`) but continues immediately after the expecting noop (the second argument set to 0).

PISTON-1002: use collect_digits for DTMF during vm greeting/instructions

---

core/kazoo_stdlib/doc/kz_json.md
core/kazoo_stdlib/src/kz_json.erl
core/kazoo_stdlib/test/kz_json_tests.erl

Deprecate `kz_json:merge_recursive` in favor of `kz_json:merge/2` with the `Options` map containing 'recursive' => 'true'.
Previously discussed here: https://github.com/2600hz/kazoo/pull/6242#issuecomment-572760221

PISTON-1005: make kz_json:merge_recursive an option of kz_json:merge

---

scripts/validate-js.py

We use CouchDB `couchjs` to validate that view are a valid Javascript code
and has no syntax error. Start with CouchDB 3, `couchjs` is changed now
it really require that we pass it a valid function statement with name.
This adds a name to function before writing it to file for validation.

when validating couchdb view, give the function a name

---

applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/crossbar_view.erl
applications/crossbar/src/modules/cb_vmboxes.erl
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_proper/src/pqc_cb_api.erl
core/kazoo_proper/src/pqc_cb_vmboxes.erl
core/kazoo_web/src/kz_http.erl

Prior, when page_size and filters are in play with a query, the
next_db clause would not match (since PageSize wasn't
'infinity'). This would lead to results being missed in the intial
query and subsequent queries would skip over to the next group of
results.
Instead, consider if there is a next last key only for whether to
query the current DB again.

[4.3] KCRO-24: address pagination issue when querying MODBs

---

applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/crossbar_view.erl
applications/crossbar/src/modules/cb_vmboxes.erl
core/kazoo_documents/src/kzd_box_message.erl
core/kazoo_proper/src/pqc_cb_api.erl
core/kazoo_proper/src/pqc_cb_vmboxes.erl
core/kazoo_web/src/kz_http.erl

Prior, when page_size and filters are in play with a query, the
next_db clause would not match (since PageSize wasn't
'infinity'). This would lead to results being missed in the intial
query and subsequent queries would skip over to the next group of
results.
Instead, consider if there is a next last key only for whether to
query the current DB again.

KCRO-24: address pagination issue when querying MODBs

---

applications/crossbar/doc/phone_numbers.md
applications/crossbar/doc/ref/phone_numbers.md
applications/crossbar/doc/ref/resources.md
applications/crossbar/doc/resources.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.notifications.emergency_bridge.json
applications/crossbar/priv/couchdb/schemas/phone_numbers.json
applications/crossbar/priv/couchdb/schemas/resources.json
applications/crossbar/priv/oas3/oas3-schemas.yml
applications/crossbar/src/modules/cb_notifications.erl
applications/stepswitch/doc/emergency.md
applications/stepswitch/doc/rules.md
applications/stepswitch/src/stepswitch_bridge.erl
applications/stepswitch/src/stepswitch_resources.erl
applications/teletype/doc/README.md
applications/teletype/priv/templates/emergency_bridge.html
applications/teletype/priv/templates/emergency_bridge.text
applications/teletype/src/templates/teletype_emergency_bridge.erl
applications/teletype/test/teletype_render_tests.erl
core/kazoo_amqp/src/api/kapi_dialplan.erl
core/kazoo_amqp/src/api/kapi_notifications.erl
core/kazoo_amqp/src/api/kz_api.erl
core/kazoo_apps/src/kz_amqp_worker.erl
core/kazoo_call/src/kz_call_response.erl
core/kazoo_documents/src/kzd_phone_numbers.erl
core/kazoo_documents/src/kzd_phone_numbers.erl.src
core/kazoo_documents/src/kzd_resources.erl
core/kazoo_documents/src/kzd_resources.erl.src
core/kazoo_stdlib/src/props.erl
doc/mkdocs/mkdocs.yml

This PR adds new functionality to help facilitate compliance with Kari's Law and notification for when an emergency call is placed.
An email contact list can now be set on a phone numbers emergency metadata.
Notification can now be achieved one of several ways:
* A new amqp event, `emergency_bridge` has been added to `kapi_notifications` to trigger a teletype notification email when an emergency call is placed.
* A new dedicated emergency bridge webhook can be configured
* Adds new text and html teletype templates
* Adds new teletype module to render template
* Template will distinguish between Emergency and test calls
* Creates a new amqp definition ing `kapi_notifications` for usage when an emergency call is attempted.
* Publish callback as been added to `cb_notifications`
* Set …

[Master] - KZOO-46: Add Emergency Notification for E911 Compliance

---

Makefile
TODO.org
rel/ci.relx.config.script
rel/dev.relx.config.script
rel/relx.config.script

- Put a safety check on `make sparkly-clean` to avoid losing work
- Update file references to match make targets
- Filter out .circleci directories

Updates to account for changes in the breakening

---

make/deps.mk

This is updating gen_smtp to have a our fix to the multiple occuring `to`
headers by properly encoding addresses in a comma separared fashion.

[master] HELP-14436: update gen_smtp to fix multiple to header lines

---

applications/teletype/src/teletype_util.erl
make/deps.mk

This is updating gen_smtp to have a our fix to the multiple occuring `to`
headers by properly encoding addresses in a comma separared fashion.
Also adding X-Teletype-Log-ID headers to identify and debug tickets about email easy.
master: https://github.com/2600hz/kazoo/pull/6527

[4.3] HELP-14436: update gen_smtp to fix multiple to header lines

---

applications/blackhole/src/modules/bh_conference.erl
applications/ecallmgr/src/ecallmgr_fs_conference.erl
core/kazoo_amqp/src/api/kapi_conference.erl

- export published conference events
- move published conference events to `kapi_conference`
- update `bh_conferences` event bindings to take an event argument
- refactor `bh_conferences` to pass * as event binding for backwards compatibility
- [4.3] [kazoo](https://github.com/2600hz/kazoo/pull/6532)
- [Master] [kazoo-core](https://github.com/2600hz/kazoo-core/pull/5)
- [Master] [kazoo-ecallmgr](https://github.com/2600hz/kazoo-ecallmgr/pull/2)
- [Master] [kazoo-blackhole](https://github.com/2600hz/kazoo-blackhole/pull/2)

[4.3] - DUPT-193: Granularize conference blackhole event bindings

---

applications/ecallmgr/src/ecallmgr_call_events.erl

`duration`, `billsec`, `progresssec` and their ilk should always be
non-negative.
A scenario occurred where a call leg was queued to originate in
FreeSWITCH while an immediate hangup API call was made over
mod_kazoo. The channel was still in `CS_NEW` and went from `DOWN` ->
`HANGUP` without ever being in `UP`.
The result was `variable_duration` being a negative UNIX timestamp and
throwing off all the other calculations (like Ringing-Seconds) in the
CDR that rely on `duration`.
This commit ensures that the variables with relative time are never
negative.

[4.3] HELP-14697: correct erroneous data in CDR

---

applications/crossbar/doc/conference.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/kapi.conference.search_resp.json
applications/crossbar/src/modules/cb_conferences.erl
applications/ecallmgr/src/ecallmgr_fs_conferences.erl
core/kazoo_amqp/src/api/kapi_conference.erl
core/kazoo_call/src/kapps_conference_command.erl
scripts/validate_mkdocs.py

If no target call-id is supplied, use the conference ID to search for
the conference focus to make sure the dial command is sent to the
right zone (otherwise the conference could be started in the local
zone while the existing conference is in another zone).

[4.3] KCON-1: search for conference focus before origination

---

core/kazoo_services/src/modules/kz_services_im.erl

when a plan is `not found` or `im is not set` we take a policy setting and apply it as default.
this commit uses differentiated settings for regular accounts and resellers

split no_plan policy for im - 4.3

---

core/sup/priv/sup
rel/kazoo

ensures proper expansion of arguments
example:
sup kapps_config set_json cat a.b.c '{"fsxxx.fqdn": {"foo" : "bar"}}'

argument expansion in sup - 4.3

---

core/kazoo_attachments/src/kz_att_azure.erl
core/kazoo_attachments/src/kz_att_http.erl
core/kazoo_data/src/kz_datamgr.erl
core/kazoo_data/src/kzs_attachments.erl
core/kazoo_media/src/kz_media_url.erl
core/kazoo_proper/src/pqc_cb_storage.erl

fetch_/put_attachment functions updated Options args with the doc's
_rev and doc type, necessary for selecting the proper dataplan before
doing the operation. stream_attachment was not updated and was
selecting the wrong (read: default) plan for the attachment.

[4.3] HELP-14818: update stream_attachment options

---

applications/crossbar/src/crossbar_maintenance.erl
applications/crossbar/src/modules/cb_auth.erl
core/kazoo_auth/doc/example/index.html
core/kazoo_auth/priv/couchdb/providers/generic.oauth.json
core/kazoo_auth/src/kz_auth_profile.erl
core/kazoo_auth/src/kz_auth_util.erl

Only the path of the provider's profile_url should be searched for
dynamic URL updates. Also provide a convenience function to generate
an auth token for API usage.

[4.3] HELP-15032: OAuth fixes for FusionAuth

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.stepswitch.json
applications/stepswitch/src/stepswitch_util.erl
applications/stepswitch/test/stepswitch_util_tests.erl

And also refactor short-dial correction code in order to be able to add
unit tests for that functionality per @jamesaimonetti request.
Master PRs:
- https://github.com/2600hz/kazoo-stepswitch/pull/4
- https://github.com/2600hz/kazoo-crossbar/pull/21

[4.3] HELP-14771: Add stepswitch.min_shortdial_destination parameter

---

core/kazoo_number_manager/src/converters/knm_converters.erl
core/kazoo_number_manager/test/knm_converters_tests.erl

System classifiers missing 'friendly_name' would be "corrected" into
the accumulator object instead of the classifier settings.
Add classifier name as "friendly_name" into the classifier's settings
object and set that updated object into the accumulator.

[4.3] HELP-15556: correct classifiers before setting into accumulator

---

applications/blackhole/src/blackhole_data_emitter.erl
applications/blackhole/src/blackhole_maintenance.erl
core/kazoo_events/include/kz_hooks.hrl
core/kazoo_events/src/kazoo_events.app.src
core/kazoo_events/src/kz_hooks_util.erl
core/kazoo_proper/src/pqc_blackhole.erl

When blackhole runs stand-alone, it relies on kazoo_events for the
kz_hooks when subscriptions for channel events are made. When the
event is a CHANNEL_CREATE from offnet, and no account ID is
associated, kz_hooks_util uses knm_number to lookup the account
associated with the destination.
kazoo_events.app did not list kazoo_number_manager as a dependency;
thus knm was not started and number lookups failed since the knm cache
wasn't started.
Updating kazoo_events.app to its proper dependencies resolves the issue.

[4.3] HELP-15749: start kazoo_number_manager before kazoo_events

---

applications/crossbar/src/modules/cb_accounts.erl

When trying to disable an account via the Account Manager app, the account is not disabled.
This bug was introduce when account creation/deletion was moved to core.
Before that move, we properly load and merge the request document with doc from database
so we had the `pvt_tree` field when we were checking ig the requestor is in
account's tree.
But this got moved into after validation and in `post/1,2` function and so we
don't set enabled anymore.

SUPP-8: read exisiting account document to get tree when importing enabled field

---

applications/fax/src/fax_worker.erl
core/kazoo_amqp/src/api/kapi_call.erl

When sending fax, fax_worker sets `Origination-Call-ID` but will be discarded by `kapi_call` on the loopback. This will take care of fax events to honor this field.
Also it puts job_id in fax_worker handle_event as call_id so we can grab logs by job_id for all stages in fax_workers.
Increasing timeouts for fax_worker stages to give it a more relax time if something taking more times to finish like sending the page.

SUPP-14: fix losing origination-call-id when faing account to account

---

core/kazoo_media/src/kz_media_util.erl

Before this change if you set `conference.profile.moh-sound=media-id` you get dead air when you join the conference.
Master: https://github.com/2600hz/kazoo-core/pull/41

HELP-15121: Fix moh-sound conference setting to work with media-id

---

core/kazoo_speech/src/asr/kazoo_asr_google.erl

Currently the anonymous match pattern for `handle_response/1` assumes a JSON content-type and attempts to decode the response body.  This will cause a crash on 502 responses, for example, as they return an HTML response body.
This PR removes the JSON decode call in favor of passing up the raw response body for error propagation.

[4.3] - KZOO-72: Crash handling 502 error in Google ASR Provider

---

applications/crossbar/doc/faxes.md
applications/crossbar/doc/ref/faxes.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/faxes.json
applications/fax/src/fax_smtp.erl
applications/teletype/priv/templates/fax_outbound_error_to_email.html
applications/teletype/priv/templates/fax_outbound_error_to_email.text
applications/teletype/priv/templates/fax_outbound_smtp_error_to_email.html
applications/teletype/priv/templates/fax_outbound_smtp_error_to_email.txt
applications/teletype/priv/templates/fax_outbound_to_email.html
applications/teletype/priv/templates/fax_outbound_to_email.text
applications/teletype/src/teletype.hrl
applications/teletype/src/templates/teletype_fax_outbound_error_to_email.erl
applications/teletype/src/templates/teletype_fax_outbound_smtp_error_to_email.erl
applications/teletype/src/templates/teletype_fax_outbound_to_email.erl
core/kazoo_documents/src/kzd_fax.erl
core/kazoo_documents/src/kzd_faxes.erl.src

After an upgrade to a release containing this enhancement,  from one server running the `teletype` app by running the command:
`sup teletype_maintenance restore_system_templates` 
This command will add the {{ subject }} macro used in templates and update the default templates in the database.

[4.3] PROD-167: capture the subject line in inbound email to fax for use in notifications

---

core/kazoo_globals/src/kz_nodes.erl
core/kazoo_stdlib/include/kz_records.hrl
core/kazoo_telemetry/include/kazoo_telemetry.hrl
core/kazoo_telemetry/src/extractors/kztm_nodes_extractor.erl
core/kazoo_telemetry/src/kazoo_telemetry_app.erl
core/kazoo_telemetry/src/kazoo_telemetry_leader.erl
core/kazoo_telemetry/src/kazoo_telemetry_sup.erl
core/kazoo_telemetry/src/reducers/waveguide_reducer.erl

This PR modifies how kazoo_telemetry determines its leader and removes functionality from `kz_nodes`.
- backports change to `kz_nodes` to use node_info binding to retrieve metadata for node_info status
- consensus logic moved to `kazoo_telemetry_leader`
- `kazoo_telemetry_leader` now uses node_info binding to publish leader data
- fixes bug where registration metadata wasn't being from registrar role in #kz_node{} record

[4.3] PROD-157: Seperate telemetry consensus logic

---

applications/callflow/doc/voicemail.md
applications/callflow/src/module/cf_park.erl
applications/callflow/src/module/cf_voicemail.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.callflow.json

Prior to this change, an malicious caller could leave a voicemail with
a bogus Caller ID number (typically an international number for
fraud) to a compromised voicemail box. Calling back into the voicemail
box, the malicious caller could select the callback option and place a
call to the fraudulent number.
If the account or owner of the voicemail box allowed international
calling, the fraud would progress.
This PR introduces two toggles to give system administrators more
control over callback functionality.
The first global config `should_disable_callback` can toggle whether
to allow the caller to select the callback option in general. If set
to `true`, the callback feature will be disable cluster-wide.
The second global config `should_disable_offnet_callback` requires the
caller to be …

[4.3] HELP-17551: allow disabling voicemail callback

---

applications/trunkstore/src/ts_callflow.erl
applications/trunkstore/src/ts_from_offnet.erl
applications/trunkstore/src/ts_from_onnet.erl

Prior to this change, if the receiving PBX refused the call and no
failover was configured, Trunkstore would exit and the A-leg would
continue ringing until the caller hungup.
This change sends a hangup to the A-leg before exiting.

[4.3] HELP-16882: hangup call if no failover

---

core/kazoo_schemas/src/kz_json_schema_extensions.erl

This commit allows to add ftp urls inside user call recording option.

 [4.3] KZOO-75: Added ftp url for call recording

---

core/kazoo_schemas/src/kz_json_schema_extensions.erl

fixed use case when ftp url is entered anything else than ftp, such as ftps will return a error 500.

[4.3] KZOO-75: ftp url fixes

---

applications/fax/src/fax_worker.erl
core/kazoo_data/src/kzs_doc.erl

At the completion of a fax it uses the move_doc (which uses copy_doc) to move the fax document with its attachments to the MODB from the faxes database.  However, bigcouch can return conflict despite being successful when moving attachments.  Since fax documents have so many attachments the move fails frequently causing the faxes db to grow significantly.

4.3 fax fixes

---

core/kazoo_media/src/kz_media_util.erl

changed log line for better readability as right now it was confusing and it was considered as an error while debugging an issue.

[4.3] prompt log readability change

---

core/kazoo_speech/src/asr/kazoo_asr_ibm.erl
core/kazoo_speech/src/kazoo_asr_util.erl

Added wav supported and removed unnecessary code which was creating confusion, we already have the preferred audio codec not sure why we are looking for it again.

[4.3] add wav support and remove unnecessary code

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.tasks.cleanup.json
applications/tasks/src/modules/kt_cleanup.erl
core/kazoo_apps/priv/couchdb/views/maintenance.json

We should remove soft deleted docs from all configured dbs. To this we also need
to add maintenance view to all dbs.
Also `maintenance/soft_deletes` is update to have id and rev so deleting won't
required lookup_rev one by one.

[4.3] SUPP-33: add maintenance view to all dbs, clean soft deleted from all dbs

---

applications/crossbar/src/crossbar_doc.erl
applications/crossbar/src/modules/cb_rates.erl
applications/tasks/src/modules/kt_rates.erl
core/kazoo_data/src/kz_datamgr.erl
core/kazoo_documents/src/kzd_rates.erl

Fix import/delete rates in tasks app and cb_rates.
* fix import where ratedeck database was incorrectly formatted (like `ratedeck/`) because of
`ratedeck_id` being an empty binary from CSV
* fix delete returning result which causing crashes in `kt_task_worker`
* in delete, group objects by db, also add better logging
* convert import state to map
* make a clean json to save to db: CSV missing fields are empty binary. Together with changes in kzd_rates make
sure we are generating a clean JSON to be saved to db.
* try to update rate doc on conflict: When a user deletes the rates from ratedeck db, it is soft deleted by default. This commit will try to update and ensure save the doc even if it is deleted.
* fix kzd_rates accessors return empty binary: Tasks app CSV has empty binary for all …

[4.3] SUPP-33: fix import/delete rates

---

README.md

Tickets URL was pointing to **.org** domain and wasn't redirecting to Jira page.

Fix tickets URL in README

---

applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/phone_numbers.json

when invalid email is entered into email section it crashes 911 notifications.

[4.3] KZOO-154: make sure e911 email format is email

---

applications/crossbar/doc/accounts.md
applications/crossbar/doc/ref/accounts.md
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/accounts.json
applications/stepswitch/src/stepswitch_inbound.erl
core/kazoo_documents/src/kzd_accounts.erl
core/kazoo_documents/src/kzd_accounts.erl.src

Kazoo 5 prs: 
https://github.com/2600hz/kazoo-crossbar/pull/139
https://github.com/2600hz/kazoo-ecallmgr/pull/71
https://github.com/2600hz/kazoo-core/pull/208

[4.3] Upstream 4.3 added missing blacklist list to accounts schema updated relevant calls

---

applications/tasks/src/tasks_listener.erl

After the removal of kz_globals from the tasks app the tasks app was creating N number of copies of an object where N was the number of tasks applications in the cluster.
Kazoo 5.x PR https://github.com/2600hz/kazoo-tasks/pull/13

PISTON-1191 Add Queue name and options to tasks_listener

---

applications/callflow/src/cf_util.erl
applications/crossbar/priv/api/swagger.json
applications/crossbar/priv/couchdb/schemas/system_config.call_command.json
core/kazoo_call/src/kapps_call_command.erl

There is potential for a callflow executor leak when sending a default error response.  In the field we found inbound calls that were forwarded to a number which canceled the request almost immediately.  When this happens callflows gets a message back from stepswitch that the bridge was unsuccessful then looks up the children in the callflow to see if any handle that specific hangup cause.  In this case (and most configurations) there are no special branches so it performs a default action which is to send back a SIP error message.  However, while that process is happening FreeSWITCH has already forwarded the cancel from the B leg back to the A leg and out to the carrier.  The particular carrier in this incident then immediately retries the same call in another zone.  When that call gets …

HELP-19729: handle rapid carrier retry that leaves cf_exe processes

---

core/kazoo_auth/test/kz_duo_tests.erl

Because the test sig_auth is expired, disabling the test until we find another valid one.

[4.3] disable a test in duo that verifies valid sig_auth because it is expired now

---

core/kazoo_telemetry/src/responders/waveguide_responder.erl

fix crash when alerts are disabled and we still try to create new alerts.

Make sure alerts are enabled before processing

---

core/kazoo_stdlib/src/kz_network_utils.erl

when a number is passed through ip check it results in saying valid ip when its just a number, strict checking of ipv4 will make sure when an ip is properly formatted with dots is accepted as a valid IP.

[4.3] KZOO-173: Strict check ipv4 addresses

---

core/kazoo_call/src/kzc_recording.erl

It has been observed the timer for expiration timer while waiting to receive
`RECORD_STOP` event could timed out sooner than receiving that event. Increasing
this timer to allow more time for the event to arrive so the recording can
properly stored.

[4.3] KZOO-185: increase stop recording expiration timer

---

applications/callflow/src/cf_route_req.erl

When transferring a call, don't prepend a preflow.
Previously, preflows were prepended to all callflows when present. If
a preflow defined a TTS like "Welcome to Company X", the caller would
hear the TTS on call connection and, if transferred to a parking slot
via *31 (for instance), would hear the preflow TTS again before
hearing hold music.
Backport of https://github.com/2600hz/kazoo-callflow/pull/77

Skip adding preflow on transfers

---

applications/teletype/src/teletype_fax_util.erl

5.x: https://github.com/2600hz/kazoo-teletype/pull/22
When teletype sends a fax attachment, its name includes a time format that includes colons. Colons are not allowed characters for filenames in Windows and so many SMTP relays and mail servers will auto-correct the colon to a dash or underscore character. However, if the end user's server does not correct this, the resulting attachment is unopenable on Windows.

KTEL-10: Replace colons by dashes on fax attachments names

---

core/kazoo_number_manager/src/carriers/knm_bandwidth2.erl

Old bandwidth API URL is shutting down. Using the new URL.

[4.3] KZOO-212: change bandwidth api url

---

applications/callflow/doc/resources.md

Just to let people know that CCVs that we set and use in our apps may change across versions, and to make sure that if you are using our CCVs as opposed to your own, make sure to test to make sure nothing is broken on an upgrade or downgrade before deploying that KAZOO version to your own production cluster or a customer's cluster, as we don't guarantee consistency of those variables across versions.

Add a disclaimer about CCVs used in 2600hz apps

---

applications/crossbar/doc/how_to_authenticate.md

Since it is a little bit confusing the wording of "usernames are always in lower case", did change to a more descriptive version.

Update how to created MD5 hash

---

applications/callflow/src/module/cf_flush_dtmf.erl
applications/callflow/test/cf_flush_dtmf_tests.erl

Backport of 2600hz/kazoo-callflow#238
Make sure to persist the cleared DTMF collection on the call using `cf_exe:set_call/1`

[4.3] KCAL-60: fix `cf_flush_dtmf`
